# Landscape Data Commons LPI — Protocol-aware canonical code dictionary

This notebook resolves the national LPI `code` universe while preserving the fact that LDC harmonizes observations from multiple monitoring implementations.

Three observation scopes are retained:

1. **Top canopy** — `TopCanopy` only.
2. **Canopy multilayer** — `TopCanopy + Lower1...Lower7`.
3. **Raw/all contacts** — every recorded layer, including `SoilSurface`.

> **Important:** Top + Lower is a canopy-contact scope, **not complete vegetation any-hit**. Basal plant hits can occur at `SoilSurface`; true vegetation any-hit must be constructed later from the raw tall LPI table after code identity is resolved.

The raw observed code is never overwritten.

## Resolution precedence

1. Protocol/domain definitions (AIM / NRI / NWERN lineage), with context restrictions where needed.
2. Existing curated `Species_List` from prior NCA/SamplePoint work.
3. USDA PLANTS accepted-symbol match.
4. USDA PLANTS synonym-symbol match.
5. Recognized generic / unknown plant-code families.
6. Unresolved/manual-review queue.

A central design rule is that some codes are **context dependent**. Therefore the notebook does not force every code into a universal `code → meaning` mapping. Ambiguous codes such as `W` and `AG` are retained as context-dependent in the master dictionary and exported with explicit layer-specific protocol rules for later row-level resolution.

# LDC LPI Code Dictionary — Taxonomic and USDA Attribute Resolution

This notebook resolves the observed LDC/LPI code universe through:

1. preservation and canonicalization of raw observed codes,
2. protocol-aware classification of nonplant and no-canopy codes,
3. curated project species metadata,
4. USDA PLANTS accepted-symbol and synonym resolution,
5. cached USDA ecological attributes.

The notebook intentionally stops **before functional-group derivation**.

Functional-group assignment is treated as a separate ecological decision stage.

In [2]:
# =========================================================================
# 1. IMPORTS AND PATHS
# =========================================================================

from pathlib import Path
import pandas as pd
import numpy as np
import json

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)

BASE_DIR = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present"
)

LPI_CODE_FILE = (
    BASE_DIR
    / "LDC_LPI_observed_code_unique.csv"
)

USDA_PLANTS_SOURCE = (
    BASE_DIR
    / "plantlst.txt"
)

OUTPUT_DIR = (
    BASE_DIR
    / "species_dictionary_outputs"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

USDA_ATTRIBUTE_CACHE = (
    OUTPUT_DIR
    / "USDA_PLANTS_ecological_attributes.csv"
)

DICT_PREFG_FILE = (
    OUTPUT_DIR
    / "LDC_LPI_species_dictionary_pre_functional_group.csv"
)

USDA_ATTR_FINAL_FILE = (
    OUTPUT_DIR
    / "USDA_PLANTS_ecological_attributes_final.csv"
)

CHECKPOINT_METADATA_FILE = (
    OUTPUT_DIR
    / "LDC_LPI_species_dictionary_pre_functional_group_metadata.json"
)

print("LPI code file:")
print(LPI_CODE_FILE)

print("\nUSDA PLANTS file:")
print(USDA_PLANTS_SOURCE)

print("\nUSDA attribute cache:")
print(USDA_ATTRIBUTE_CACHE)

LPI code file:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\LDC_LPI_observed_code_unique.csv

USDA PLANTS file:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\plantlst.txt

USDA attribute cache:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\USDA_PLANTS_ecological_attributes.csv

In [3]:
# =========================================================================
# 2. LOAD AND CANONICALIZE OBSERVED LPI CODE UNIVERSE
# =========================================================================

codes = pd.read_csv(
    LPI_CODE_FILE,
    dtype={"code": "string"},
    low_memory=False
)

print("Input rows:", f"{len(codes):,}")


# -------------------------------------------------------------------------
# Preserve the original source code
# -------------------------------------------------------------------------

codes["observed_code_raw"] = codes["code"]


# -------------------------------------------------------------------------
# Identify true source blanks BEFORE canonicalization
# -------------------------------------------------------------------------

codes["source_code_was_blank"] = (
    codes["observed_code_raw"].isna()
    | codes["observed_code_raw"].str.strip().eq("")
)


# -------------------------------------------------------------------------
# Canonical observed code
#
# IMPORTANT:
# "__NO_CANOPY__" = blank source TopCanopy observation
# "NONE"          = legitimate literal USDA plant symbol
# -------------------------------------------------------------------------

codes["observed_code"] = (
    codes["observed_code_raw"]
    .astype("string")
    .str.strip()
)

codes.loc[
    codes["source_code_was_blank"],
    "observed_code"
] = "__NO_CANOPY__"


# -------------------------------------------------------------------------
# Basic QA
# -------------------------------------------------------------------------

print(
    "Canonical observed codes:",
    f"{codes['observed_code'].nunique(dropna=False):,}"
)

print(
    "Source-blank rows:",
    f"{codes['source_code_was_blank'].sum():,}"
)

print(
    "Literal NONE rows:",
    f"{codes['observed_code'].eq('NONE').sum():,}"
)

display(
    codes[
        codes["observed_code"].isin(
            ["__NO_CANOPY__", "NONE"]
        )
    ][
        [
            "observed_code",
            "observed_code_raw",
            "source_code_was_blank",
            "n_records",
            "n_top",
            "n_lower",
            "n_soil_surface",
        ]
    ]
)

Input rows: 10,960
Canonical observed codes: 10,960
Source-blank rows: 1
Literal NONE rows: 1

,observed_code,observed_code_raw,source_code_was_blank,n_records,n_top,n_lower,n_soil_surface
15,__NO_CANOPY__,<NA>,True,442612,442612,0,0
2527,NONE,NONE,False,398,394,4,0

In [4]:
# =========================================================================
# 3. CONSERVATIVE PROTOCOL-AWARE RULES
# =========================================================================

protocol_rules = pd.DataFrame(
    [
        ("__NO_CANOPY__", "No top-canopy contact", "NoCanopy"),

        ("S",  "Soil", "NonPlant"),
        ("R",  "Rock", "NonPlant"),
        ("BR", "Bedrock", "NonPlant"),
        ("GR", "Gravel", "NonPlant"),
        ("CB", "Cobble", "NonPlant"),
        ("ST", "Stone", "NonPlant"),
        ("BY", "Boulder", "NonPlant"),

        ("HL", "Herbaceous litter", "NonPlant"),
        ("WL", "Woody litter", "NonPlant"),
        ("NL", "Other litter", "NonPlant"),

        ("L",  "Lichen", "NonPlant"),
        ("LC", "Lichen / biotic crust", "NonPlant"),
        ("VL", "Vagrant lichen", "NonPlant"),
        ("M",  "Moss", "NonPlant"),

        ("EL", "Embedded litter", "NonPlant"),
        ("D",  "Duff", "NonPlant"),
        ("WA", "Water", "NonPlant"),

        # Source/protocol-dependent meanings
        ("W",  "Context-dependent W", "ContextDependent"),
        ("AG", "Context-dependent AG", "ContextDependent"),
        ("PC", "Context-dependent PC", "ContextDependent"),

        # Not safely interpreted yet
        ("O",  "Unresolved protocol code O", "ProtocolUnresolved"),
        ("PT", "Unresolved protocol code PT", "ProtocolUnresolved"),
    ],
    columns=[
        "observed_code",
        "protocol_label",
        "protocol_code_class",
    ]
)

print("Protocol rules:", len(protocol_rules))

display(protocol_rules)

Protocol rules: 23

    observed_code               protocol_label protocol_code_class
0   __NO_CANOPY__        No top-canopy contact            NoCanopy
1               S                         Soil            NonPlant
2               R                         Rock            NonPlant
3              BR                      Bedrock            NonPlant
4              GR                       Gravel            NonPlant
5              CB                       Cobble            NonPlant
6              ST                        Stone            NonPlant
7              BY                      Boulder            NonPlant
8              HL            Herbaceous litter            NonPlant
9              WL                 Woody litter            NonPlant
10             NL                 Other litter            NonPlant
11              L                       Lichen            NonPlant
12             LC        Lichen / biotic crust            NonPlant
13             VL               Vagrant lichen            NonPlant
14              M                         Moss            NonPlant
15             EL              Embedded litter            NonPlant
16              D                         Duff            NonPlant
17             WA                        Water            NonPlant
18              W          Context-dependent W    ContextDependent
19             AG         Context-dependent AG    ContextDependent
20             PC         Context-dependent PC    ContextDependent
21              O   Unresolved protocol code O  ProtocolUnresolved
22             PT  Unresolved protocol code PT  ProtocolUnresolved

In [5]:
# =========================================================================
# 4. CONSTRUCT FRESH MASTER DICTIONARY
# =========================================================================

dictionary = codes.copy()

dictionary = dictionary.merge(
    protocol_rules,
    on="observed_code",
    how="left",
    validate="many_to_one",
)

dictionary["code_class"] = (
    dictionary["protocol_code_class"]
    .astype("string")
)

dictionary["resolved_label"] = (
    dictionary["protocol_label"]
    .astype("string")
)


# -------------------------------------------------------------------------
# QA
# -------------------------------------------------------------------------

print(
    "Dictionary rows:",
    f"{len(dictionary):,}"
)

print(
    "Unique observed codes:",
    f"{dictionary['observed_code'].nunique(dropna=False):,}"
)

print("\nCurrent classification:")

display(
    dictionary["code_class"]
    .value_counts(dropna=False)
    .rename_axis("code_class")
    .reset_index(name="n_codes")
)

Dictionary rows: 10,960
Unique observed codes: 10,960

Current classification:

           code_class  n_codes
0                <NA>    10937
1            NonPlant       17
2    ContextDependent        3
3  ProtocolUnresolved        2
4            NoCanopy        1

In [6]:
# =========================================================================
# 5. LOAD USDA PLANTS TAXONOMIC REFERENCE — DEFENSIVE PARSER
# =========================================================================

print("USDA source:")
print(USDA_PLANTS_SOURCE)


# -------------------------------------------------------------------------
# Inspect raw header first
# -------------------------------------------------------------------------

with open(
    USDA_PLANTS_SOURCE,
    "r",
    encoding="utf-8-sig",
    errors="replace"
) as f:
    raw_header = f.readline()

print("\nRaw file header:")
print(repr(raw_header))


# -------------------------------------------------------------------------
# Expected USDA PLANTS fields
# -------------------------------------------------------------------------

required_usda_cols = [
    "Symbol",
    "Synonym Symbol",
    "Scientific Name with Author",
    "Common Name",
    "Family",
]


# -------------------------------------------------------------------------
# Try likely delimiters and keep the parse that recovers the expected schema
# -------------------------------------------------------------------------

candidate_separators = [
    "\t",
    "|",
    ",",
]

usda_raw = None
separator_used = None

for sep in candidate_separators:

    try:
        test = pd.read_csv(
            USDA_PLANTS_SOURCE,
            sep=sep,
            dtype="string",
            low_memory=False,
            encoding="utf-8-sig",
        )

        # Normalize column names
        test.columns = (
            test.columns
            .astype(str)
            .str.replace("\ufeff", "", regex=False)
            .str.strip()
            .str.strip('"')
            .str.strip("'")
        )

        n_required_found = sum(
            c in test.columns
            for c in required_usda_cols
        )

        print(
            f"Separator {repr(sep)}:"
            f" {len(test.columns)} columns,"
            f" {n_required_found}/{len(required_usda_cols)}"
            " required fields found"
        )

        if n_required_found == len(required_usda_cols):
            usda_raw = test
            separator_used = sep
            break

    except Exception as e:
        print(
            f"Separator {repr(sep)} failed:"
            f" {type(e).__name__}: {e}"
        )


# -------------------------------------------------------------------------
# Fallback: Python delimiter inference
# -------------------------------------------------------------------------

if usda_raw is None:

    print("\nTrying automatic delimiter inference...")

    test = pd.read_csv(
        USDA_PLANTS_SOURCE,
        sep=None,
        engine="python",
        dtype="string",
        encoding="utf-8-sig",
    )

    test.columns = (
        test.columns
        .astype(str)
        .str.replace("\ufeff", "", regex=False)
        .str.strip()
        .str.strip('"')
        .str.strip("'")
    )

    missing = [
        c for c in required_usda_cols
        if c not in test.columns
    ]

    if not missing:
        usda_raw = test
        separator_used = "auto"


# -------------------------------------------------------------------------
# Fail informatively only if no parser recovered the schema
# -------------------------------------------------------------------------

if usda_raw is None:

    raise ValueError(
        "Could not recover the expected USDA PLANTS schema.\n"
        "Inspect the raw header printed above before proceeding."
    )


print("\nUSDA file parsed successfully.")
print("Separator used:", repr(separator_used))
print("Rows:", f"{len(usda_raw):,}")
print("Columns:", len(usda_raw.columns))

print("\nParsed columns:")
for col in usda_raw.columns:
    print(f"  {repr(col)}")


# -------------------------------------------------------------------------
# Final schema check
# -------------------------------------------------------------------------

missing_usda_cols = [
    c for c in required_usda_cols
    if c not in usda_raw.columns
]

assert not missing_usda_cols, (
    "USDA schema still missing: "
    + ", ".join(missing_usda_cols)
)


# -------------------------------------------------------------------------
# Normalize USDA symbol fields
# -------------------------------------------------------------------------

for col in [
    "Symbol",
    "Synonym Symbol",
]:
    usda_raw[col] = (
        usda_raw[col]
        .astype("string")
        .str.strip()
    )

    usda_raw.loc[
        usda_raw[col].eq(""),
        col
    ] = pd.NA


# -------------------------------------------------------------------------
# Separate accepted taxa and synonym records
# -------------------------------------------------------------------------

accepted_rows = usda_raw[
    usda_raw["Synonym Symbol"].isna()
].copy()

synonym_rows = usda_raw[
    usda_raw["Synonym Symbol"].notna()
].copy()


print(
    "\nAccepted-record rows:",
    f"{len(accepted_rows):,}"
)

print(
    "Synonym-record rows:",
    f"{len(synonym_rows):,}"
)

USDA source:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\plantlst.txt

Raw file header:
'"Symbol","Synonym Symbol","Scientific Name with Author","Common Name","Family"\n'
Separator '\t': 1 columns, 0/5 required fields found
Separator '|': 1 columns, 0/5 required fields found
Separator ',': 5 columns, 5/5 required fields found

USDA file parsed successfully.
Separator used: ','
Rows: 93,157
Columns: 5

Parsed columns:
  'Symbol'
  'Synonym Symbol'
  'Scientific Name with Author'
  'Common Name'
  'Family'

Accepted-record rows: 48,994
Synonym-record rows: 44,163

In [7]:
# =========================================================================
# 6. BUILD USDA ACCEPTED-TAXON TABLE
# =========================================================================

usda_accepted = (
    accepted_rows[
        [
            "Symbol",
            "Scientific Name with Author",
            "Common Name",
            "Family",
        ]
    ]
    .dropna(subset=["Symbol"])
    .drop_duplicates()
    .copy()
)


# -------------------------------------------------------------------------
# Check whether any accepted symbol has genuinely conflicting taxonomy
# -------------------------------------------------------------------------

accepted_symbol_counts = (
    usda_accepted
    .groupby("Symbol", dropna=False)
    .size()
)

accepted_conflicts = (
    accepted_symbol_counts[
        accepted_symbol_counts > 1
    ]
)

print(
    "Accepted USDA symbols:",
    f"{usda_accepted['Symbol'].nunique():,}"
)

print(
    "Accepted symbols with >1 distinct metadata row:",
    f"{len(accepted_conflicts):,}"
)

if len(accepted_conflicts) > 0:
    display(
        usda_accepted[
            usda_accepted["Symbol"].isin(
                accepted_conflicts.index
            )
        ]
        .sort_values("Symbol")
        .head(100)
    )


# -------------------------------------------------------------------------
# For lookup purposes, retain one metadata row per accepted symbol.
#
# We are not changing taxonomy here; duplicate identical rows have already
# been removed above. Any remaining conflict is preserved in the diagnostic.
# -------------------------------------------------------------------------

usda_accepted_lookup = (
    usda_accepted
    .drop_duplicates(
        subset="Symbol",
        keep="first"
    )
    .rename(
        columns={
            "Symbol":
                "USDA_accepted_symbol",

            "Scientific Name with Author":
                "USDA_scientific_name",

            "Common Name":
                "USDA_common_name",

            "Family":
                "USDA_family",
        }
    )
    .copy()
)

print(
    "\nAccepted lookup rows:",
    f"{len(usda_accepted_lookup):,}"
)

Accepted USDA symbols: 48,994
Accepted symbols with >1 distinct metadata row: 0

Accepted lookup rows: 48,994

In [8]:
# =========================================================================
# 7. BUILD USDA SYNONYM → ACCEPTED SYMBOL MAP
# =========================================================================

usda_synonym_pairs = (
    synonym_rows[
        [
            "Synonym Symbol",
            "Symbol",
        ]
    ]
    .dropna(
        subset=[
            "Synonym Symbol",
            "Symbol",
        ]
    )
    .drop_duplicates()
    .rename(
        columns={
            "Synonym Symbol":
                "USDA_synonym_symbol",

            "Symbol":
                "USDA_accepted_symbol",
        }
    )
    .copy()
)


# -------------------------------------------------------------------------
# Detect synonym symbols pointing to >1 accepted symbol
# -------------------------------------------------------------------------

synonym_target_counts = (
    usda_synonym_pairs
    .groupby("USDA_synonym_symbol")[
        "USDA_accepted_symbol"
    ]
    .nunique()
)

ambiguous_synonyms = (
    synonym_target_counts[
        synonym_target_counts > 1
    ]
)

print(
    "Unique USDA synonym symbols:",
    f"{usda_synonym_pairs['USDA_synonym_symbol'].nunique():,}"
)

print(
    "Ambiguous synonym symbols:",
    f"{len(ambiguous_synonyms):,}"
)


# -------------------------------------------------------------------------
# Exclude only genuinely ambiguous synonym mappings
# -------------------------------------------------------------------------

unambiguous_synonym_pairs = (
    usda_synonym_pairs[
        ~usda_synonym_pairs[
            "USDA_synonym_symbol"
        ].isin(
            ambiguous_synonyms.index
        )
    ]
    .drop_duplicates(
        subset="USDA_synonym_symbol",
        keep="first"
    )
    .copy()
)

print(
    "Usable synonym mappings:",
    f"{len(unambiguous_synonym_pairs):,}"
)

Unique USDA synonym symbols: 44,163
Ambiguous synonym symbols: 0
Usable synonym mappings: 44,163

In [9]:
# =========================================================================
# 8. RESOLVE OBSERVED CODES TO USDA TAXONOMY
# =========================================================================

# -------------------------------------------------------------------------
# Taxonomy eligibility
#
# Only codes not already identified as protocol/nonplant are eligible.
# Literal NONE is eligible.
# __NO_CANOPY__ is not.
# -------------------------------------------------------------------------

taxonomy_eligible = (
    ~dictionary["source_code_was_blank"]
    & ~dictionary["code_class"].isin(
        [
            "NoCanopy",
            "NonPlant",
            "ContextDependent",
            "ProtocolUnresolved",
        ]
    )
)

print(
    "Taxonomy-eligible codes:",
    f"{taxonomy_eligible.sum():,}"
)


# -------------------------------------------------------------------------
# Build fast lookup structures
# -------------------------------------------------------------------------

accepted_symbols = set(
    usda_accepted_lookup[
        "USDA_accepted_symbol"
    ]
    .dropna()
)

synonym_to_accepted = dict(
    zip(
        unambiguous_synonym_pairs[
            "USDA_synonym_symbol"
        ],
        unambiguous_synonym_pairs[
            "USDA_accepted_symbol"
        ],
    )
)


# -------------------------------------------------------------------------
# Initialize resolution columns
# -------------------------------------------------------------------------

dictionary["USDA_accepted_symbol"] = pd.NA
dictionary["USDA_match_method"] = pd.NA


# -------------------------------------------------------------------------
# 1. Exact accepted-symbol matches
# -------------------------------------------------------------------------

exact_mask = (
    taxonomy_eligible
    & dictionary["observed_code"].isin(
        accepted_symbols
    )
)

dictionary.loc[
    exact_mask,
    "USDA_accepted_symbol"
] = dictionary.loc[
    exact_mask,
    "observed_code"
]

dictionary.loc[
    exact_mask,
    "USDA_match_method"
] = "accepted_symbol"


# -------------------------------------------------------------------------
# 2. Synonym matches among codes still unresolved
# -------------------------------------------------------------------------

synonym_mask = (
    taxonomy_eligible
    & dictionary["USDA_accepted_symbol"].isna()
    & dictionary["observed_code"].isin(
        synonym_to_accepted
    )
)

dictionary.loc[
    synonym_mask,
    "USDA_accepted_symbol"
] = (
    dictionary.loc[
        synonym_mask,
        "observed_code"
    ]
    .map(synonym_to_accepted)
)

dictionary.loc[
    synonym_mask,
    "USDA_match_method"
] = "synonym_symbol"


# -------------------------------------------------------------------------
# Summary before metadata join
# -------------------------------------------------------------------------

print(
    "\nExact accepted-symbol matches:",
    f"{exact_mask.sum():,}"
)

print(
    "Synonym-symbol matches:",
    f"{synonym_mask.sum():,}"
)

print(
    "Total USDA-resolved rows:",
    f"{dictionary['USDA_accepted_symbol'].notna().sum():,}"
)

print(
    "Unique accepted USDA taxa represented:",
    f"{dictionary['USDA_accepted_symbol'].nunique():,}"
)

Taxonomy-eligible codes: 10,937

Exact accepted-symbol matches: 7,160
Synonym-symbol matches: 415
Total USDA-resolved rows: 7,575
Unique accepted USDA taxa represented: 7,264

In [10]:
# =========================================================================
# 9. ATTACH USDA TAXONOMIC METADATA
# =========================================================================

dictionary = dictionary.merge(
    usda_accepted_lookup,
    on="USDA_accepted_symbol",
    how="left",
    validate="many_to_one",
)


# -------------------------------------------------------------------------
# Any successful USDA taxonomic resolution is a plant
# -------------------------------------------------------------------------

usda_plant_mask = (
    dictionary["USDA_accepted_symbol"].notna()
    & dictionary["code_class"].isna()
)

dictionary.loc[
    usda_plant_mask,
    "code_class"
] = "Plant"


# -------------------------------------------------------------------------
# USDA scientific name becomes label where protocol label is absent
# -------------------------------------------------------------------------

dictionary["resolved_label"] = (
    dictionary["resolved_label"]
    .combine_first(
        dictionary["USDA_scientific_name"]
    )
)


# -------------------------------------------------------------------------
# Summary
# -------------------------------------------------------------------------

display(
    dictionary["code_class"]
    .value_counts(dropna=False)
    .rename_axis("code_class")
    .reset_index(name="n_codes")
)

           code_class  n_codes
0               Plant     7575
1                <NA>     3362
2            NonPlant       17
3    ContextDependent        3
4  ProtocolUnresolved        2
5            NoCanopy        1

In [11]:
# =========================================================================
# 10. CRITICAL SENTINEL / USDA NONE QA
# =========================================================================

critical = dictionary[
    dictionary["observed_code"].isin(
        [
            "__NO_CANOPY__",
            "NONE",
        ]
    )
].copy()

display(
    critical[
        [
            "observed_code",
            "observed_code_raw",
            "source_code_was_blank",
            "code_class",
            "resolved_label",
            "USDA_match_method",
            "USDA_accepted_symbol",
            "USDA_scientific_name",
            "USDA_common_name",
            "USDA_family",
            "n_records",
            "n_top",
            "n_lower",
            "n_soil_surface",
        ]
    ]
)


no_canopy = dictionary[
    dictionary["observed_code"].eq(
        "__NO_CANOPY__"
    )
]

literal_none = dictionary[
    dictionary["observed_code"].eq(
        "NONE"
    )
]


# -------------------------------------------------------------------------
# These are now legitimate hard invariants
# -------------------------------------------------------------------------

assert len(no_canopy) == 1

assert (
    no_canopy[
        "source_code_was_blank"
    ]
    .all()
)

assert (
    no_canopy[
        "code_class"
    ]
    .eq("NoCanopy")
    .all()
)

assert (
    no_canopy[
        "USDA_accepted_symbol"
    ]
    .isna()
    .all()
)


assert len(literal_none) == 1

assert (
    ~literal_none[
        "source_code_was_blank"
    ]
    .all()
)

assert (
    literal_none[
        "USDA_accepted_symbol"
    ]
    .eq("NONE")
    .all()
)

assert (
    literal_none[
        "code_class"
    ]
    .eq("Plant")
    .all()
)


print(
    "\nCritical QA passed:"
    "\n  __NO_CANOPY__ is excluded from USDA taxonomy"
    "\n  literal NONE is retained as a USDA plant"
)

,observed_code,observed_code_raw,source_code_was_blank,code_class,resolved_label,USDA_match_method,USDA_accepted_symbol,USDA_scientific_name,USDA_common_name,USDA_family,n_records,n_top,n_lower,n_soil_surface
15,__NO_CANOPY__,<NA>,True,NoCanopy,No top-canopy contact,<NA>,<NA>,<NA>,<NA>,<NA>,442612,442612,0,0
2527,NONE,NONE,False,Plant,Notholaena neglecta Maxon,accepted_symbol,NONE,Notholaena neglecta Maxon,Maxon's cloak fern,Pteridaceae,398,394,4,0

Critical QA passed:
  __NO_CANOPY__ is excluded from USDA taxonomy
  literal NONE is retained as a USDA plant

C:\Users\scottfordham\AppData\Local\Temp\ipykernel_40900\2614387556.py:82: DeprecationWarning: Bitwise inversion '~' on bool is deprecated and will be removed in Python 3.16. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
  ~literal_none[

In [12]:
# =========================================================================
# 11. INSPECT USDA-UNRESOLVED CODES
# =========================================================================

unresolved = dictionary[
    dictionary["code_class"].isna()
].copy()

print("Unresolved codes:", f"{len(unresolved):,}")

print(
    "Records represented by unresolved codes:",
    f"{unresolved['n_records'].sum():,}"
)

print("\nHighest-frequency unresolved codes:")

display(
    unresolved[
        [
            "observed_code",
            "n_records",
            "n_plot_visits",
            "n_top",
            "n_lower",
            "n_soil_surface",
            "first_year",
            "last_year",
        ]
    ]
    .sort_values(
        "n_records",
        ascending=False
    )
    .head(100)
)

Unresolved codes: 3,362
Records represented by unresolved codes: 529,463

Highest-frequency unresolved codes:

,observed_code,n_records,n_plot_visits,n_top,n_lower,n_soil_surface,first_year,last_year
14,RF,177392,9091,0,0,177392,2018,2024
494,LM,68581,157,0,0,68581,2018,2023
75,Perennial grasses,61012,1814,47784,13228,0,2018,2024
42,CY,56462,2957,0,0,56462,2018,2025
83,Annual plants,35750,1507,23705,12045,0,2018,2024
101,Shrubs,21122,1221,16657,4465,0,2018,2024
96,Sub-shrubs and perennial forbs,20140,1330,13449,6691,0,2018,2024
111,Plant base,17980,1105,0,0,17980,2018,2024
138,Trees,14631,841,13379,1252,0,2018,2024
128,SH00,4187,903,3145,691,351,2018,2023
156,AF00,2058,661,1266,786,6,2018,2023
509,GUTCFSAR,1894,149,1659,193,42,2019,2021
214,PF00,1268,454,825,435,8,2018,2023
724,TR00,972,94,878,67,27,2018,2023
1980,PPGG,853,21,420,61,372,2019,2023
340,2FA1,849,250,524,276,49,2018,2024
1266,FG,751,43,0,1,750,2018,2023
678,CHJUMG,711,102,530,177,4,2018,2019
459,PG00,687,173,408,173,106,2018,2023
762,AG04001,567,88,546,21,0,2022,2023
2184,ER,536,17,0,536,0,2018,2020
532,AF01000,528,142,386,141,1,2020,2023
579,AF02000,498,125,347,149,2,2020,2023
1759,AAFF,482,25,286,190,6,2018,2023
963,BOETRII,476,64,377,99,0,2018,2023
791,PG01,456,85,269,98,89,2018,2025
417,2FP1,450,192,252,175,23,2018,2024
1865,PINSCO,441,23,436,2,3,2018,2020
464,SU00,440,171,407,19,14,2018,2023
1155,PHYGOR,365,50,271,89,5,2018,2023
555,DS,351,135,49,302,0,2018,2023
1011,2GP1,338,59,230,87,21,2018,2024
631,DN,323,112,0,323,0,2018,2025
661,SH03000,319,105,254,40,25,2020,2023
916,CHJUR,313,68,174,135,4,2018,2019
2230,AG60001,309,16,221,88,0,2021,2021
676,SH01000,308,103,252,47,9,2020,2023
2919,AAGG,292,9,203,85,4,2018,2020
948,PHYFEN,290,66,193,90,7,2018,2023
523,AM,269,145,0,257,12,2018,2023
2814,ELELLA,267,10,180,87,0,2019,2019
685,SH07000,265,101,240,18,7,2020,2023
716,AF07000,254,95,183,70,1,2020,2023
1790,SIDTEN,246,25,227,17,2,2018,2024
915,AG00,243,68,174,67,2,2018,2023
677,AF03000,242,102,169,70,3,2019,2023
2034,PG02,238,20,151,78,9,2018,2022
1210,2SHRUB1,225,46,175,39,11,2018,2024
1392,SPOCFCRY,220,38,173,29,18,2018,2021
781,SH05000,215,86,178,25,12,2021,2023
1039,PF01,196,58,114,70,12,2018,2025
1224,Unk,195,46,195,0,0,2018,2018
970,CHJUMT,194,63,103,91,0,2018,2019
991,AF10000,194,61,129,65,0,2020,2023
2761,AG01001,192,10,172,20,0,2019,2022
1277,AF20000,185,42,135,50,0,2022,2023
2472,AG04002,177,13,143,33,1,2020,2021
961,SH10000,159,65,127,14,18,2020,2023
813,SH09000,157,82,124,24,9,2019,2023
1187,PG03000,157,48,99,27,31,2020,2023
1963,GUTcfSAR,155,21,122,33,0,2020,2023
2256,CM,154,16,0,0,154,2018,2022
831,SH02000,153,79,116,22,15,2020,2023
1501,AG01,152,33,107,44,1,2018,2025
1041,SH04000,148,58,112,21,15,2020,2023
1319,SH20000,145,41,126,16,3,2022,2023
937,AF09000,145,66,119,26,0,2020,2023
2866,PG04001,143,10,95,39,9,2020,2023
2102,AF01001,143,18,57,84,2,2019,2023
1762,AF50000,138,25,97,41,0,2021,2022
3758,AG01002,137,5,115,22,0,2019,2022
952,AF04000,137,65,88,48,1,2020,2024
1991,2LICHN,128,20,52,76,0,2021,2021
3203,PF05002,127,8,115,10,2,2019,2023
1341,AG07000,127,39,83,42,2,2020,2023
914,AF05000,126,68,99,26,1,2020,2023
2281,LIVR86,124,16,11,113,0,2019,2019
1140,AF04001,123,50,113,10,0,2019,2022
5555,AG05008,122,2,13,108,1,2019,2019
5348,TR01,121,3,111,7,3,2019,2019
4454,PG01003,120,4,44,74,2,2019,2023
3390,PG09010,117,7,74,15,28,2021,2023
3041,PG09990,117,9,108,8,1,2023,2023
1752,SH666,116,26,100,9,7,2018,2018
3717,TR08000,114,6,112,0,2,2022,2023
8140,Duff,114,1,0,0,114,2020,2020
5563,AG1806,111,2,85,26,0,2019,2019
1063,SH08000,111,56,84,12,15,2020,2023
1716,AG03000,110,26,67,43,0,2019,2023
1179,AF08000,110,48,77,33,0,2020,2023
1649,SH50000,108,29,86,16,6,2021,2022
2925,AF03001,106,9,80,26,0,2020,2020
1530,2FA2,104,32,43,59,2,2018,2024
4465,PG09014,103,4,80,3,20,2020,2023
1974,PG00000,102,21,58,39,5,2019,2021
5350,TR09003,102,3,72,28,2,2023,2023
2400,ALCOC,100,14,98,1,1,2020,2023
2221,SHRUB,99,17,50,4,45,2019,2023
1026,AF06000,97,58,74,21,2,2019,2023
1318,SH00000,96,41,78,14,4,2019,2021

In [13]:
# =========================================================================
# 11. RESOLVE GENERIC NUMBERED VEGETATION CODES
# =========================================================================

generic_rules = {
    "AF": ("Annual forb", "AnnualForb"),
    "PF": ("Perennial forb", "PerennialForb"),
    "AG": ("Annual graminoid", "AnnualGraminoid"),
    "PG": ("Perennial graminoid", "PerennialGraminoid"),
    "SH": ("Shrub", "Shrub"),
    "TR": ("Tree", "Tree"),
}

dictionary["protocol_plant_group"] = pd.Series(
    pd.NA,
    index=dictionary.index,
    dtype="string"
)

dictionary["generic_code_prefix"] = pd.Series(
    pd.NA,
    index=dictionary.index,
    dtype="string"
)

for prefix, (label, group) in generic_rules.items():

    # Must have at least one digit after the prefix.
    # Therefore bare "AG" is NOT captured.
    pattern = rf"^{prefix}\d+$"

    mask = (
        dictionary["code_class"].isna()
        & dictionary["observed_code"].str.match(
            pattern,
            na=False
        )
    )

    dictionary.loc[mask, "code_class"] = "Plant"
    dictionary.loc[mask, "resolved_label"] = label
    dictionary.loc[mask, "protocol_plant_group"] = group
    dictionary.loc[mask, "generic_code_prefix"] = prefix


generic_resolved = dictionary[
    dictionary["generic_code_prefix"].notna()
].copy()

print(
    "Generic numbered plant codes resolved:",
    f"{len(generic_resolved):,}"
)

print(
    "Records represented:",
    f"{generic_resolved['n_records'].sum():,}"
)

display(
    generic_resolved[
        [
            "observed_code",
            "resolved_label",
            "protocol_plant_group",
            "n_records",
            "n_top",
            "n_lower",
            "n_soil_surface",
        ]
    ]
    .sort_values("n_records", ascending=False)
    .head(100)
)

Generic numbered plant codes resolved: 2,954
Records represented: 40,570

,observed_code,resolved_label,protocol_plant_group,n_records,n_top,n_lower,n_soil_surface
128,SH00,Shrub,Shrub,4187,3145,691,351
156,AF00,Annual forb,AnnualForb,2058,1266,786,6
214,PF00,Perennial forb,PerennialForb,1268,825,435,8
724,TR00,Tree,Tree,972,878,67,27
459,PG00,Perennial graminoid,PerennialGraminoid,687,408,173,106
762,AG04001,Annual graminoid,AnnualGraminoid,567,546,21,0
532,AF01000,Annual forb,AnnualForb,528,386,141,1
579,AF02000,Annual forb,AnnualForb,498,347,149,2
791,PG01,Perennial graminoid,PerennialGraminoid,456,269,98,89
661,SH03000,Shrub,Shrub,319,254,40,25
2230,AG60001,Annual graminoid,AnnualGraminoid,309,221,88,0
676,SH01000,Shrub,Shrub,308,252,47,9
685,SH07000,Shrub,Shrub,265,240,18,7
716,AF07000,Annual forb,AnnualForb,254,183,70,1
915,AG00,Annual graminoid,AnnualGraminoid,243,174,67,2
677,AF03000,Annual forb,AnnualForb,242,169,70,3
2034,PG02,Perennial graminoid,PerennialGraminoid,238,151,78,9
781,SH05000,Shrub,Shrub,215,178,25,12
1039,PF01,Perennial forb,PerennialForb,196,114,70,12
991,AF10000,Annual forb,AnnualForb,194,129,65,0
2761,AG01001,Annual graminoid,AnnualGraminoid,192,172,20,0
1277,AF20000,Annual forb,AnnualForb,185,135,50,0
2472,AG04002,Annual graminoid,AnnualGraminoid,177,143,33,1
961,SH10000,Shrub,Shrub,159,127,14,18
1187,PG03000,Perennial graminoid,PerennialGraminoid,157,99,27,31
813,SH09000,Shrub,Shrub,157,124,24,9
831,SH02000,Shrub,Shrub,153,116,22,15
1501,AG01,Annual graminoid,AnnualGraminoid,152,107,44,1
1041,SH04000,Shrub,Shrub,148,112,21,15
937,AF09000,Annual forb,AnnualForb,145,119,26,0
1319,SH20000,Shrub,Shrub,145,126,16,3
2866,PG04001,Perennial graminoid,PerennialGraminoid,143,95,39,9
2102,AF01001,Annual forb,AnnualForb,143,57,84,2
1762,AF50000,Annual forb,AnnualForb,138,97,41,0
3758,AG01002,Annual graminoid,AnnualGraminoid,137,115,22,0
952,AF04000,Annual forb,AnnualForb,137,88,48,1
3203,PF05002,Perennial forb,PerennialForb,127,115,10,2
1341,AG07000,Annual graminoid,AnnualGraminoid,127,83,42,2
914,AF05000,Annual forb,AnnualForb,126,99,26,1
1140,AF04001,Annual forb,AnnualForb,123,113,10,0
5555,AG05008,Annual graminoid,AnnualGraminoid,122,13,108,1
5348,TR01,Tree,Tree,121,111,7,3
4454,PG01003,Perennial graminoid,PerennialGraminoid,120,44,74,2
3041,PG09990,Perennial graminoid,PerennialGraminoid,117,108,8,1
3390,PG09010,Perennial graminoid,PerennialGraminoid,117,74,15,28
1752,SH666,Shrub,Shrub,116,100,9,7
3717,TR08000,Tree,Tree,114,112,0,2
5563,AG1806,Annual graminoid,AnnualGraminoid,111,85,26,0
1063,SH08000,Shrub,Shrub,111,84,12,15
1179,AF08000,Annual forb,AnnualForb,110,77,33,0
1716,AG03000,Annual graminoid,AnnualGraminoid,110,67,43,0
1649,SH50000,Shrub,Shrub,108,86,16,6
2925,AF03001,Annual forb,AnnualForb,106,80,26,0
4465,PG09014,Perennial graminoid,PerennialGraminoid,103,80,3,20
5350,TR09003,Tree,Tree,102,72,28,2
1974,PG00000,Perennial graminoid,PerennialGraminoid,102,58,39,5
1026,AF06000,Annual forb,AnnualForb,97,74,21,2
1318,SH00000,Shrub,Shrub,96,78,14,4
1746,PG000,Perennial graminoid,PerennialGraminoid,94,41,13,40
2446,PG09015,Perennial graminoid,PerennialGraminoid,94,48,43,3
2471,AF21000,Annual forb,AnnualForb,94,65,28,1
6725,TR04002,Tree,Tree,93,91,0,2
2161,AG10001,Annual graminoid,AnnualGraminoid,91,56,35,0
1533,AF01,Annual forb,AnnualForb,91,61,30,0
2399,AF40000,Annual forb,AnnualForb,88,41,47,0
1789,PF03,Perennial forb,PerennialForb,88,47,37,4
3636,PG01005,Perennial graminoid,PerennialGraminoid,86,20,62,4
1933,AF02,Annual forb,AnnualForb,86,46,40,0
1747,PG08000,Perennial graminoid,PerennialGraminoid,85,45,26,14
3646,PG222,Perennial graminoid,PerennialGraminoid,84,27,57,0
3389,PG04,Perennial graminoid,PerennialGraminoid,84,49,27,8
6413,PG09029,Perennial graminoid,PerennialGraminoid,84,42,42,0
1861,PG02000,Perennial graminoid,PerennialGraminoid,83,39,42,2
1585,SH000,Shrub,Shrub,83,65,10,8
1441,SH11000,Shrub,Shrub,82,66,9,7
1797,AF15000,Annual forb,AnnualForb,80,51,27,2
1830,SH21000,Shrub,Shrub,80,62,17,1
6419,PG09052,Perennial graminoid,PerennialGraminoid,80,26,53,1
3211,PG10003,Perennial graminoid,PerennialGraminoid,80,68,7,5
2290,PG10002,Perennial graminoid,PerennialGraminoid,79,60,16,3
9926,PG2001,Perennial graminoid,PerennialGraminoid,79,60,19,0
4471,PG13006,Perennial graminoid,PerennialGraminoid,78,24,53,1
9790,PG07026,Perennial graminoid,PerennialGraminoid,77,62,2,13
10756,TR12001,Tree,Tree,77,77,0,0
2141,PG67000,Perennial graminoid,PerennialGraminoid,76,36,5,35
1587,SH13000,Shrub,Shrub,75,67,2,6
3458,AG70003,Annual graminoid,AnnualGraminoid,75,45,30,0
3639,PG03006,Perennial graminoid,PerennialGraminoid,73,51,21,1
1884,AG01000,Annual graminoid,AnnualGraminoid,71,39,30,2
1761,AF24000,Annual forb,AnnualForb,71,41,29,1
2651,TR02000,Tree,Tree,70,62,2,6
1586,SH06000,Shrub,Shrub,69,59,3,7
2750,TR09000,Tree,Tree,68,65,1,2
4539,SH01013,Shrub,Shrub,66,66,0,0
3644,PG12,Perennial graminoid,PerennialGraminoid,66,29,36,1
7445,AG21001,Annual graminoid,AnnualGraminoid,65,42,22,1
4012,PG10005,Perennial graminoid,PerennialGraminoid,65,41,20,4
6443,PG417,Perennial graminoid,PerennialGraminoid,65,32,19,14
1748,PG09000,Perennial graminoid,PerennialGraminoid,64,42,13,9
1623,AF13000,Annual forb,AnnualForb,64,37,25,2

In [14]:
# =========================================================================
# 12. RESOLVE EXPLICIT DESCRIPTIVE VEGETATION CLASSES
# =========================================================================

descriptive_plant_rules = {
    "Perennial grasses": (
        "Perennial grasses",
        "PerennialGraminoid"
    ),

    "Annual plants": (
        "Annual plants",
        "AnnualPlant"
    ),

    "Shrubs": (
        "Shrubs",
        "Shrub"
    ),

    "Sub-shrubs and perennial forbs": (
        "Sub-shrubs and perennial forbs",
        "SubshrubOrPerennialForb"
    ),

    "Trees": (
        "Trees",
        "Tree"
    ),
}

for code, (label, group) in descriptive_plant_rules.items():

    mask = (
        dictionary["code_class"].isna()
        & dictionary["observed_code"].eq(code)
    )

    dictionary.loc[mask, "code_class"] = "Plant"
    dictionary.loc[mask, "resolved_label"] = label
    dictionary.loc[mask, "protocol_plant_group"] = group

In [15]:
# =========================================================================
# 13. REMAINING UNRESOLVED AFTER GENERIC VEGETATION RESOLUTION
# =========================================================================

remaining = dictionary[
    dictionary["code_class"].isna()
].copy()

print(
    "Remaining unresolved codes:",
    f"{len(remaining):,}"
)

print(
    "Records represented:",
    f"{remaining['n_records'].sum():,}"
)

display(
    remaining[
        [
            "observed_code",
            "n_records",
            "n_plot_visits",
            "n_top",
            "n_lower",
            "n_soil_surface",
            "first_year",
            "last_year",
        ]
    ]
    .sort_values("n_records", ascending=False)
    .head(100)
)

Remaining unresolved codes: 403
Records represented: 336,238

,observed_code,n_records,n_plot_visits,n_top,n_lower,n_soil_surface,first_year,last_year
14,RF,177392,9091,0,0,177392,2018,2024
494,LM,68581,157,0,0,68581,2018,2023
42,CY,56462,2957,0,0,56462,2018,2025
111,Plant base,17980,1105,0,0,17980,2018,2024
509,GUTCFSAR,1894,149,1659,193,42,2019,2021
1980,PPGG,853,21,420,61,372,2019,2023
340,2FA1,849,250,524,276,49,2018,2024
1266,FG,751,43,0,1,750,2018,2023
678,CHJUMG,711,102,530,177,4,2018,2019
2184,ER,536,17,0,536,0,2018,2020
1759,AAFF,482,25,286,190,6,2018,2023
963,BOETRII,476,64,377,99,0,2018,2023
417,2FP1,450,192,252,175,23,2018,2024
1865,PINSCO,441,23,436,2,3,2018,2020
464,SU00,440,171,407,19,14,2018,2023
1155,PHYGOR,365,50,271,89,5,2018,2023
555,DS,351,135,49,302,0,2018,2023
1011,2GP1,338,59,230,87,21,2018,2024
631,DN,323,112,0,323,0,2018,2025
916,CHJUR,313,68,174,135,4,2018,2019
2919,AAGG,292,9,203,85,4,2018,2020
948,PHYFEN,290,66,193,90,7,2018,2023
523,AM,269,145,0,257,12,2018,2023
2814,ELELLA,267,10,180,87,0,2019,2019
1790,SIDTEN,246,25,227,17,2,2018,2024
1210,2SHRUB1,225,46,175,39,11,2018,2024
1392,SPOCFCRY,220,38,173,29,18,2018,2021
1224,Unk,195,46,195,0,0,2018,2018
970,CHJUMT,194,63,103,91,0,2018,2019
1963,GUTcfSAR,155,21,122,33,0,2020,2023
2256,CM,154,16,0,0,154,2018,2022
1991,2LICHN,128,20,52,76,0,2021,2021
2281,LIVR86,124,16,11,113,0,2019,2019
8140,Duff,114,1,0,0,114,2020,2020
1530,2FA2,104,32,43,59,2,2018,2024
2400,ALCOC,100,14,98,1,1,2020,2023
2221,SHRUB,99,17,50,4,45,2019,2023
2081,P,89,19,0,0,89,2019,2022
1794,UNK,86,25,60,24,2,2018,2020
2786,BOERHAF,75,10,72,3,0,2022,2023
6369,PG 06,74,2,55,19,0,2019,2019
1644,NT,70,29,0,70,0,2018,2023
3254,2MOSS,68,7,3,65,0,2021,2021
2873,POA*,67,10,32,29,6,2018,2023
10214,PS09009,63,1,45,12,6,2023,2023
2465,UN12000,61,14,38,20,3,2022,2022
10863,UN09011,59,1,59,0,0,2023,2023
6532,PS91006,57,2,41,15,1,2021,2021
2101,2GA1,57,18,29,28,0,2018,2024
2315,ALLIUM,56,15,15,41,0,2022,2022
5389,2TREE2,47,2,1,46,0,2018,2022
2757,2TREE1,45,10,12,32,1,2018,2022
3076,2LW,39,8,4,35,0,2021,2021
1831,SPHPUM,39,24,24,13,2,2018,2023
1836,2FP2,36,23,16,14,6,2018,2023
2596,ERITRA,34,12,27,7,0,2020,2023
4732,ASTRAAF,33,3,15,18,0,2019,2019
2871,PL,33,10,1,21,11,2018,2018
8303,Elel5,33,1,21,11,1,2020,2020
2561,2FA3,32,12,14,18,0,2018,2023
9692,PG 04,32,1,20,12,0,2019,2019
3255,2SHRUB2,31,7,14,16,1,2018,2023
2713,MOSS,30,11,6,24,0,2018,2019
1779,HT,28,25,0,28,0,2018,2023
2982,DRAR86,27,9,4,23,0,2021,2021
2684,CRYPTA,27,11,24,3,0,2020,2021
2657,2SUBS1,25,11,18,2,5,2018,2023
2497,DF,25,13,2,23,0,2021,2022
10210,PS09004,24,1,11,13,0,2023,2023
5225,PS09008,24,3,6,18,0,2023,2023
10211,PS09005,23,1,19,1,3,2023,2023
5365,UN06101,22,3,12,6,4,2020,2021
4106,VEWO,22,5,7,15,0,2021,2023
3248,UN06010,21,8,7,14,0,2021,2021
2918,2FP3,21,9,12,8,1,2018,2023
2682,CHIV8,20,11,17,3,0,2018,2023
5798,CRYPT1,20,2,11,9,0,2019,2019
3441,XANGRA,20,7,17,2,1,2019,2022
6717,TIQHISn,18,2,17,0,1,2020,2020
6751,UN06208,18,2,9,9,0,2021,2021
6836,ADWRW,18,1,15,3,0,2023,2023
10880,UN60000,18,1,18,0,0,2021,2021
10698,SYOR22,17,1,14,3,0,2021,2021
10215,PS09010,17,1,4,11,2,2023,2023
10216,PS09011,17,1,1,16,0,2023,2023
5318,SPAL86,17,3,6,11,0,2021,2021
3459,AGAPARN,16,6,11,3,2,2018,2022
3274,AMAPED,16,7,16,0,0,2019,2021
7643,ASRP5,16,1,15,1,0,2019,2019
6031,LEPCFMON,15,2,10,4,1,2019,2021
4476,PHACEA,15,4,11,4,0,2020,2020
7504,ALPR33,15,1,14,1,0,2020,2020
4193,BAPRV,14,4,13,1,0,2021,2021
3536,DIAVER,14,6,9,5,0,2020,2020
10872,UN23024,14,1,3,11,0,2023,2023
3247,UN03000,14,8,8,6,0,2023,2023
5013,MATPAR,13,3,9,4,0,2023,2023
6745,UN04001,13,2,2,11,0,2021,2022
4249,CYPERA,13,4,12,1,0,2019,2019
6749,UN06019,13,2,10,3,0,2021,2021

In [16]:
# ============================================================
# CONSOLIDATED LPI CODE RESOLUTION
#
# Run AFTER:
#   1. raw code canonicalization
#   2. core protocol classification
#   3. USDA accepted-symbol + synonym resolution
#
# This cell:
#   - preserves observed_code exactly
#   - only modifies currently unresolved codes
#   - handles protocol/material codes
#   - handles functional/project codes
#   - handles project-code regex families
#   - handles manual taxonomic aliases
#   - preserves uncertainty/provenance
# ============================================================

import re
import pandas as pd


# ============================================================
# 0. ENSURE REQUIRED OUTPUT COLUMNS EXIST
# ============================================================

required_resolution_columns = [
    "resolved_label",
    "resolution_source",
    "taxonomic_level",
    "protocol_plant_group",
    "USDA_match_method",
    "USDA_accepted_symbol",
    "USDA_scientific_name",
    "USDA_common_name",
    "USDA_family",
]

for col in required_resolution_columns:
    if col not in dictionary.columns:
        dictionary[col] = pd.NA


# ============================================================
# 1. FIXED PROTOCOL / MATERIAL / FUNCTIONAL RESOLUTIONS
#
# Format:
# observed_code:
#     resolved_label,
#     code_class,
#     protocol_plant_group,
#     resolution_source
# ============================================================

fixed_rules = {

    # --------------------------------------------------------
    # No-canopy sentinel
    # --------------------------------------------------------
    "__NO_CANOPY__": (
        "No canopy contact",
        "NoCanopy",
        pd.NA,
        "source_blank_sentinel",
    ),

    # --------------------------------------------------------
    # Standard / well-supported non-plant protocol codes
    # --------------------------------------------------------
    "S": (
        "Soil",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "R": (
        "Rock",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "BR": (
        "Bedrock",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "GR": (
        "Gravel",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "CB": (
        "Cobble",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "ST": (
        "Stone",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "BY": (
        "Boulder",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "RF": (
        "Rock fragment",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "FG": (
        "Fine gravel",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "HL": (
        "Herbaceous litter",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "WL": (
        "Woody litter",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "EL": (
        "Embedded litter",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "D": (
        "Duff",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "Duff": (
        "Duff",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    # IMPORTANT:
    # L = lichen, NOT litter
    "L": (
        "Lichen",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "LC": (
        "Lichen / biological crust",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "M": (
        "Moss",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "CY": (
        "Cyanobacterial crust",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "LM": (
        "Loose erodible mineral soil",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "DN": (
        "Dung",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "AM": (
        "Unattached animal material",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    "HT": (
        "Human trash",
        "NonPlant",
        pd.NA,
        "protocol_code",
    ),

    # --------------------------------------------------------
    # Additional project/material aliases
    # --------------------------------------------------------
    "2MOSS": (
        "Moss",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "MOSS": (
        "Moss",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "2LW": (
        "Woody litter",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "2LICHN": (
        "Lichen",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "LIVR86": (
        "Liverwort",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "LVRWORT": (
        "Liverwort",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "2LVRWRT": (
        "Liverwort",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "2FUNGI": (
        "Fungi",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "2ALGA": (
        "Algae",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    "ALGAE86": (
        "Algae",
        "NonPlant",
        pd.NA,
        "manual_protocol_alias",
    ),

    # Deposited soil interpretation
    "DS": (
        "Deposited soil",
        "NonPlant",
        pd.NA,
        "manual_protocol_interpretation",
    ),

    # Unknown material codes whose observed vertical placement
    # strongly suggests non-vegetation rather than plant taxa.
    "ER": (
        "Unknown lower-layer material",
        "NonPlant",
        pd.NA,
        "manual_context_resolution",
    ),

    "CM": (
        "Unknown surface material",
        "NonPlant",
        pd.NA,
        "manual_context_resolution",
    ),

    "P": (
        "Unknown surface material",
        "NonPlant",
        pd.NA,
        "manual_context_resolution",
    ),

    "NT": (
        "Unknown lower-layer material",
        "NonPlant",
        pd.NA,
        "manual_context_resolution",
    ),

    # --------------------------------------------------------
    # Basal vegetation
    # --------------------------------------------------------
    # SoilSurface DOES NOT imply non-plant.
    "Plant base": (
        "Plant base",
        "Plant",
        "UnknownPlant",
        "protocol_basal_vegetation",
    ),

    # --------------------------------------------------------
    # Explicit functional/project vegetation codes
    # --------------------------------------------------------
    "PPGG": (
        "Perennial graminoid",
        "Plant",
        "PerennialGraminoid",
        "manual_functional_resolution",
    ),

    "PPFF": (
        "Perennial forb",
        "Plant",
        "PerennialForb",
        "manual_functional_resolution",
    ),

    "AAFF": (
        "Annual forb",
        "Plant",
        "AnnualForb",
        "manual_functional_resolution",
    ),

    "AAGG": (
        "Annual graminoid",
        "Plant",
        "AnnualGraminoid",
        "manual_functional_resolution",
    ),

    "SHRUB": (
        "Shrub",
        "Plant",
        "Shrub",
        "manual_functional_resolution",
    ),

    "Sh01999": (
        "Shrub",
        "Plant",
        "Shrub",
        "manual_functional_resolution",
    ),

    # SU00 interpreted as Shrub Unknown
    "SU00": (
        "Unknown shrub",
        "Plant",
        "Shrub",
        "manual_project_code_inferred",
    ),

    "UKGR": (
        "Unknown grass",
        "Plant",
        "Graminoid",
        "manual_functional_resolution",
    ),

    "ASTERA": (
        "Aster / unknown forb",
        "Plant",
        "Forb",
        "manual_functional_resolution",
    ),

    "Af02": (
        "Annual forb",
        "Plant",
        "AnnualForb",
        "manual_functional_resolution",
    ),

    "LOTUSAF": (
        "Annual forb",
        "Plant",
        "AnnualForb",
        "manual_functional_resolution",
    ),

    "BRASS2PF": (
        "Perennial Brassicaceae",
        "Plant",
        "PerennialForb",
        "manual_functional_resolution",
    ),

    "POA*": (
        "Graminoid",
        "Plant",
        "Graminoid",
        "manual_functional_resolution",
    ),

    # Explicitly unknown taxonomically but clearly vegetation
    "BOETRII": (
        "Unknown plant",
        "Plant",
        "UnknownPlant",
        "manual_unknown_plant",
    ),

    "PINSCO": (
        "Unknown plant",
        "Plant",
        "UnknownPlant",
        "manual_unknown_plant",
    ),

    "Unk": (
        "Unknown plant",
        "Plant",
        "UnknownPlant",
        "manual_unknown_plant",
    ),

    "UNK": (
        "Unknown plant",
        "Plant",
        "UnknownPlant",
        "manual_unknown_plant",
    ),
}


# ============================================================
# 2. APPLY FIXED RULES
# ============================================================

for code, (
    label,
    code_class,
    plant_group,
    source,
) in fixed_rules.items():

    mask = (
        dictionary["code_class"].isna()
        & dictionary["observed_code"].eq(code)
    )

    if not mask.any():
        continue

    dictionary.loc[mask, "code_class"] = code_class
    dictionary.loc[mask, "resolved_label"] = label
    dictionary.loc[mask, "protocol_plant_group"] = plant_group
    dictionary.loc[mask, "resolution_source"] = source


# ============================================================
# 3. GENERIC NUMBERED AIM / PROJECT FUNCTIONAL CODES
#
# Strict patterns only.
# Bare AG is intentionally NOT handled here because AG can
# represent a SoilSurface aggregate code in some protocols.
# ============================================================

project_functional_patterns = [
    (r"^AF\d+$",      "Annual forb",         "AnnualForb"),
    (r"^PF\d+$",      "Perennial forb",      "PerennialForb"),
    (r"^AG\d+$",      "Annual graminoid",    "AnnualGraminoid"),
    (r"^PG\d+$",      "Perennial graminoid", "PerennialGraminoid"),
    (r"^SH\d+$",      "Shrub",               "Shrub"),
    (r"^TR\d+$",      "Tree",                "Tree"),

    # Project-prefixed variants
    (r"^2FA\d+$",     "Annual forb",         "AnnualForb"),
    (r"^2FP\d+$",     "Perennial forb",      "PerennialForb"),
    (r"^2GA\d+$",     "Annual graminoid",    "AnnualGraminoid"),
    (r"^2GP\d+$",     "Perennial graminoid", "PerennialGraminoid"),
    (r"^2SHRUB\d+$",  "Shrub",               "Shrub"),
    (r"^2TREE\d+$",   "Tree",                "Tree"),
    (r"^2SUBS\d+$",   "Subshrub",            "Subshrub"),
]


for pattern, label, group in project_functional_patterns:

    mask = (
        dictionary["code_class"].isna()
        & dictionary["observed_code"].str.match(pattern, na=False)
    )

    dictionary.loc[mask, "code_class"] = "Plant"
    dictionary.loc[mask, "resolved_label"] = label
    dictionary.loc[mask, "protocol_plant_group"] = group
    dictionary.loc[mask, "resolution_source"] = "project_code_pattern"


# ============================================================
# 4. SPACED PG PROJECT CODES
#
# PG 04, PG 05, PG 06, etc.
# ============================================================

mask = (
    dictionary["code_class"].isna()
    & dictionary["observed_code"].str.match(
        r"^PG\s+\d+$",
        na=False,
    )
)

dictionary.loc[mask, "code_class"] = "Plant"
dictionary.loc[mask, "resolved_label"] = "Perennial graminoid"
dictionary.loc[mask, "protocol_plant_group"] = "PerennialGraminoid"
dictionary.loc[mask, "resolution_source"] = "project_code_pattern"


# ============================================================
# 5. ALL UN... CODES = UNKNOWN PLANT
#
# Preserve the original observed code.
# ============================================================

mask = (
    dictionary["code_class"].isna()
    & dictionary["observed_code"].str.match(
        r"^UN",
        case=False,
        na=False,
    )
)

dictionary.loc[mask, "code_class"] = "Plant"
dictionary.loc[mask, "resolved_label"] = "Unknown plant"
dictionary.loc[mask, "protocol_plant_group"] = "UnknownPlant"
dictionary.loc[mask, "resolution_source"] = "project_unknown_code"


# ============================================================
# 6. ELELLA
#
# Observer ambiguity between Elymus elymoides and E. lanceolatus.
# Resolve only to Elymus / perennial graminoid.
# ============================================================

mask = (
    dictionary["code_class"].isna()
    & dictionary["observed_code"].eq("ELELLA")
)

dictionary.loc[mask, "code_class"] = "Plant"
dictionary.loc[mask, "resolved_label"] = "Elymus"
dictionary.loc[mask, "taxonomic_level"] = "genus"
dictionary.loc[mask, "protocol_plant_group"] = "PerennialGraminoid"
dictionary.loc[mask, "resolution_source"] = (
    "manual_ambiguous_species_to_genus"
)


# ============================================================
# 7. MANUAL TAXONOMIC ALIASES
#
# target = canonical USDA symbol we want to query/join.
#
# The original observed_code is NEVER overwritten.
# ============================================================

manual_alias_candidates = {

    # --------------------------------------------------------
    # Cryptantha variants
    # --------------------------------------------------------
    "CRYPTA": {
        "target": "CRYPT",
        "label": "Cryptantha",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "CRYPT1": {
        "target": "CRYPT",
        "label": "Cryptantha",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "CRYPTa": {
        "target": "CRYPT",
        "label": "Cryptantha",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    # --------------------------------------------------------
    # Genus aliases
    # --------------------------------------------------------
    "ALLIUM": {
        "target": "ALLIU",
        "label": "Allium",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "ASTRAAF": {
        "target": "ASTRA",
        "label": "Astragalus",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "PHACEA": {
        "target": "PHACE",
        "label": "Phacelia",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "PHACEAF": {
        "target": "PHACE",
        "label": "Phacelia",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "PHACEa": {
        "target": "PHACE",
        "label": "Phacelia",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "CYPERA": {
        "target": "CYPER",
        "label": "Cyperus",
        "taxonomic_level": "genus",
        "resolution_source": "manual_typo_genus",
    },

    "ALCOC": {
        "target": "CALOC",
        "label": "Calochortus",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "ERITRA": {
        "target": "ERITR",
        "label": "Eritrichium",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "CERASTIUM": {
        "target": "CERAS",
        "label": "Cerastium",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    # --------------------------------------------------------
    # Gutierrezia cf. sarothrae
    # Preserve cf. uncertainty in resolved label.
    # --------------------------------------------------------
    "GUTCFSAR": {
        "target": "GUSA2",
        "label": "Gutierrezia cf. sarothrae",
        "taxonomic_level": "species_cf",
        "resolution_source": "manual_cf_taxonomic_alias",
    },

    "GUTcfSAR": {
        "target": "GUSA2",
        "label": "Gutierrezia cf. sarothrae",
        "taxonomic_level": "species_cf",
        "resolution_source": "manual_cf_taxonomic_alias",
    },

    # --------------------------------------------------------
    # CHJU project variants
    # --------------------------------------------------------
    "CHJUMG": {
        "target": "CHJU",
        "label": "CHJU",
        "taxonomic_level": "project_base_code",
        "resolution_source": "manual_project_code_alias",
    },

    "CHJUR": {
        "target": "CHJU",
        "label": "CHJU",
        "taxonomic_level": "project_base_code",
        "resolution_source": "manual_project_code_alias",
    },

    "CHJUMT": {
        "target": "CHJU",
        "label": "CHJU",
        "taxonomic_level": "project_base_code",
        "resolution_source": "manual_project_code_alias",
    },

    # --------------------------------------------------------
    # Species / typo / capitalization corrections
    # --------------------------------------------------------
    "CHIV8": {
        "target": "CHVI8",
        "label": "Chrysothamnus viscidiflorus",
        "taxonomic_level": "species",
        "resolution_source": "manual_typo_correction",
    },

    "Elel5": {
        "target": "ELEL5",
        "label": "Elymus elymoides",
        "taxonomic_level": "species",
        "resolution_source": "manual_case_correction",
    },

    "DRAR86": {
        "target": "POARA4",
        "label": "Potentilla arguta",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_alias",
    },

    "SYOR22": {
        "target": "SYOR",
        "label": "Symphoricarpos orbiculatus",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_alias",
    },

    "ANDI": {
        "target": "ANDI2",
        "label": "Antennaria dimorpha",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_resolution",
    },

    "AMAL22": {
        "target": "AMAL2",
        "label": "Amelanchier alnifolia",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_resolution",
    },

    "ERNA1": {
        "target": "ERNA10",
        "label": "ERNA10",
        "taxonomic_level": "species",
        "resolution_source": "manual_typo_correction",
    },

    "Koma": {
        "target": "KOMA",
        "label": "Koeleria macrantha",
        "taxonomic_level": "species",
        "resolution_source": "manual_case_correction",
    },

    "BAPRV": {
        "target": "BAPR",
        "label": "Bassia prostrata",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_alias",
    },

    "ARTW8": {
        "target": "ARTRW8",
        "label": "Artemisia tridentata ssp. wyomingensis",
        "taxonomic_level": "subspecies",
        "resolution_source": "manual_typo_correction",
    },

    "POAR2R2": {
        "target": "PONIN",
        "label": "Potentilla nivea var. nivea",
        "taxonomic_level": "variety",
        "resolution_source": "manual_USDA_synonym_resolution",
    },

    "SPAL86": {
        "target": "SPAL",
        "label": "Spartina",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    "SPAL_01": {
        "target": "SPAL",
        "label": "Spartina",
        "taxonomic_level": "genus",
        "resolution_source": "manual_project_code_alias",

    # Sphaeralcea coccinea
    "SPCO86": {
        "target": "SPCO",
        "label": "Sphaeralcea coccinea",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_alias",
    },

    # Bassia prostrata variants
    "BAPRG": {
        "target": "BAPR5",
        "label": "Bassia prostrata",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_alias",
    },

    "BAPRV": {
        "target": "BAPR5",
        "label": "Bassia prostrata",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_alias",
    },

    # Ribes genus
    "RIBE5": {
        "target": "RIBES",
        "label": "Ribes",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    # Linum lewisii
    # observed LILEL3 -> likely intended LILE3
    "LILEL3": {
        "target": "LILE3",
        "label": "Linum lewisii",
        "taxonomic_level": "species",
        "resolution_source": "manual_typo_correction",
    },

    # Lepidium genus
    "LEPEAS": {
        "target": "LEPE",
        "label": "Lepidium",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },

    # Comandra umbellata
    "COUM3": {
        "target": "COUM3",
        "label": "Comandra umbellata",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_resolution",
    },

    # Phlox longifolia
    "PHLO22": {
        "target": "PHLO22",
        "label": "Phlox longifolia",
        "taxonomic_level": "species",
        "resolution_source": "manual_taxonomic_resolution",
    },

    # Penstemon genus
    "PENST4": {
        "target": "PENST",
        "label": "Penstemon",
        "taxonomic_level": "genus",
        "resolution_source": "manual_genus_alias",
    },
    },
}


# ============================================================
# 8. HELPER: ROBUST USDA TARGET LOOKUP
#
# Supports the column naming convention used in the current
# usda_accepted_lookup table.
# ============================================================

def get_usda_target_row(target):
    """
    Return exactly one USDA accepted-symbol row if available.
    Otherwise return None.
    """

    if "usda_accepted_lookup" not in globals():
        return None

    if "USDA_accepted_symbol" not in usda_accepted_lookup.columns:
        return None

    hit = usda_accepted_lookup[
        usda_accepted_lookup["USDA_accepted_symbol"].eq(target)
    ]

    if len(hit) == 1:
        return hit.iloc[0]

    return None


# ============================================================
# 9. APPLY MANUAL TAXONOMIC ALIASES
# ============================================================

alias_warnings = []

for observed_code, info in manual_alias_candidates.items():

    mask = (
        dictionary["code_class"].isna()
        & dictionary["observed_code"].eq(observed_code)
    )

    if not mask.any():
        continue

    target = info["target"]

    # We know these represent plants even if USDA target lookup fails.
    dictionary.loc[mask, "code_class"] = "Plant"
    dictionary.loc[mask, "resolved_label"] = info["label"]
    dictionary.loc[mask, "resolution_source"] = info["resolution_source"]
    dictionary.loc[mask, "taxonomic_level"] = info["taxonomic_level"]
    dictionary.loc[mask, "USDA_accepted_symbol"] = target
    dictionary.loc[mask, "USDA_match_method"] = "manual_alias"

    if "protocol_plant_group" in info:
        dictionary.loc[
            mask,
            "protocol_plant_group"
        ] = info["protocol_plant_group"]

    # Attach USDA metadata when target is found locally
    target_row = get_usda_target_row(target)

    if target_row is not None:

        metadata_cols = [
            "USDA_scientific_name",
            "USDA_common_name",
            "USDA_family",
        ]

        for col in metadata_cols:
            if col in target_row.index:
                dictionary.loc[mask, col] = target_row[col]

    else:
        alias_warnings.append(
            (observed_code, target)
        )


# ============================================================
# 10. OPTIONAL MANUAL FUNCTIONAL OVERRIDES FOR ALIASED TAXA
#
# These encode ecological information that is defensible even
# when the taxonomic alias itself is genus-level or uncertain.
# ============================================================

functional_overrides = {

    # Elymus ambiguity resolved structurally
    "ELELLA": "PerennialGraminoid",

    # Unknown grasses / graminoids
    "UKGR": "Graminoid",

    # Aster only known as forb
    "ASTERA": "Forb",

    # Explicit project functional encodings
    "LOTUSAF": "AnnualForb",
    "BRASS2PF": "PerennialForb",

    # Wyoming big sagebrush
    "ARTW8": "Shrub",

    # Koeleria
    "Koma": "PerennialGraminoid",

    # Cordgrass / Spartina
    "SPAL86": "PerennialGraminoid",
    "SPAL_01": "PerennialGraminoid",

    # Bassia prostrata:
    # treat as exotic forb in this framework, NOT shrub
    "BAPRV": "Forb",
    "BAPRG": "Forb",

    # Sphaeralcea coccinea
    "SPCO86": "Forb",

    # Ribes
    "RIBE5": "Shrub",

    # Linum lewisii
    "LILEL3": "Forb",

    # Lepidium
    "LEPEAS": "Forb",

    # Comandra umbellata
    "COUM3": "Forb",

    # Phlox longifolia
    "PHLO22": "Forb",

    # Penstemon
    "PENST4": "Forb",
}


for code, group in functional_overrides.items():

    mask = dictionary["observed_code"].eq(code)

    dictionary.loc[
        mask,
        "protocol_plant_group"
    ] = group


# ============================================================
# 11. QA: MANUAL RULES THAT FAILED USDA TARGET LOOKUP
#
# This does NOT undo their classification.
# It simply tells us which canonical targets were not found
# in the local accepted-symbol lookup.
# ============================================================

if alias_warnings:

    alias_warning_df = pd.DataFrame(
        alias_warnings,
        columns=[
            "observed_code",
            "requested_USDA_target",
        ],
    ).drop_duplicates()

    print(
        f"Manual alias targets not found in "
        f"usda_accepted_lookup: {len(alias_warning_df):,}"
    )

    display(alias_warning_df)

else:
    print(
        "All applied manual alias targets found "
        "in usda_accepted_lookup."
    )


# ============================================================
# 12. QA: DISPLAY ALL CODES TOUCHED BY THIS CONSOLIDATED CELL
# ============================================================

manual_codes = (
    set(fixed_rules.keys())
    | set(manual_alias_candidates.keys())
)

qa_manual = (
    dictionary[
        dictionary["observed_code"].isin(manual_codes)
        | dictionary["resolution_source"].isin(
            [
                "project_code_pattern",
                "project_unknown_code",
                "manual_ambiguous_species_to_genus",
            ]
        )
    ][
        [
            "observed_code",
            "n_records",
            "code_class",
            "resolved_label",
            "USDA_accepted_symbol",
            "protocol_plant_group",
            "taxonomic_level",
            "resolution_source",
        ]
    ]
    .sort_values(
        ["n_records", "observed_code"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

print(
    f"Codes represented in consolidated resolution QA: "
    f"{len(qa_manual):,}"
)

display(qa_manual)


# ============================================================
# 13. FINAL UNRESOLVED TABLE
# ============================================================

unresolved = (
    dictionary[
        dictionary["code_class"].isna()
    ][
        [
            "observed_code",
            "n_records",
            "n_plot_visits",
            "n_top",
            "n_lower",
            "n_soil_surface",
            "first_year",
            "last_year",
        ]
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
    .reset_index(drop=True)
)

print(
    f"Remaining unresolved codes: "
    f"{len(unresolved):,}"
)

print(
    f"Records represented: "
    f"{unresolved['n_records'].sum():,}"
)

display(unresolved.head(100))


# ============================================================
# 14. STOPPING-RULE QA
#
# Our manual-review threshold is 50 observations.
# Anything remaining below this threshold can be retained as
# unresolved rather than forcing increasingly speculative IDs.
# ============================================================

needs_review = unresolved[
    unresolved["n_records"] >= 50
].copy()

below_manual_threshold = unresolved[
    unresolved["n_records"] < 50
].copy()

print()
print(
    f"Still >= 50 records and requiring review: "
    f"{len(needs_review):,}"
)

print(
    f"Remaining < 50-record codes: "
    f"{len(below_manual_threshold):,}"
)

print(
    f"Records represented by <50 tail: "
    f"{below_manual_threshold['n_records'].sum():,}"
)

display(needs_review)

All applied manual alias targets found in usda_accepted_lookup.
Codes represented in consolidated resolution QA: 246

,observed_code,n_records,code_class,resolved_label,USDA_accepted_symbol,protocol_plant_group,taxonomic_level,resolution_source
0,S,4908062,NonPlant,Soil,<NA>,<NA>,<NA>,<NA>
1,HL,2420983,NonPlant,Herbaceous litter,<NA>,<NA>,<NA>,<NA>
2,L,853273,NonPlant,Lichen,<NA>,<NA>,<NA>,<NA>
3,GR,721055,NonPlant,Gravel,<NA>,<NA>,<NA>,<NA>
4,__NO_CANOPY__,442612,NoCanopy,No top-canopy contact,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...
241,UN23070,1,Plant,Unknown plant,<NA>,UnknownPlant,<NA>,project_unknown_code
242,UN25037,1,Plant,Unknown plant,<NA>,UnknownPlant,<NA>,project_unknown_code
243,UN33009,1,Plant,Unknown plant,<NA>,UnknownPlant,<NA>,project_unknown_code
244,UNK10,1,Plant,Unknown plant,<NA>,UnknownPlant,<NA>,project_unknown_code
245,UNK_ASTER_01,1,Plant,Unknown plant,<NA>,UnknownPlant,<NA>,project_unknown_code

Remaining unresolved codes: 172
Records represented: 2,186

,observed_code,n_records,n_plot_visits,n_top,n_lower,n_soil_surface,first_year,last_year
0,PHYGOR,365,50,271,89,5,2018,2023
1,PHYFEN,290,66,193,90,7,2018,2023
2,SIDTEN,246,25,227,17,2,2018,2024
3,SPOCFCRY,220,38,173,29,18,2018,2021
4,BOERHAF,75,10,72,3,0,2022,2023
5,PS09009,63,1,45,12,6,2023,2023
6,PS91006,57,2,41,15,1,2021,2021
7,SPHPUM,39,24,24,13,2,2018,2023
8,PL,33,10,1,21,11,2018,2018
9,DF,25,13,2,23,0,2021,2022
10,PS09008,24,3,6,18,0,2023,2023
11,PS09004,24,1,11,13,0,2023,2023
12,PS09005,23,1,19,1,3,2023,2023
13,VEWO,22,5,7,15,0,2021,2023
14,XANGRA,20,7,17,2,1,2019,2022
15,ADWRW,18,1,15,3,0,2023,2023
16,TIQHISn,18,2,17,0,1,2020,2020
17,PS09011,17,1,1,16,0,2023,2023
18,PS09010,17,1,4,11,2,2023,2023
19,ASRP5,16,1,15,1,0,2019,2019
20,AGAPARN,16,6,11,3,2,2018,2022
21,AMAPED,16,7,16,0,0,2019,2021
22,ALPR33,15,1,14,1,0,2020,2020
23,LEPCFMON,15,2,10,4,1,2019,2021
24,DIAVER,14,6,9,5,0,2020,2020
25,MATPAR,13,3,9,4,0,2023,2023
26,DG,13,5,1,12,0,2021,2022
27,POA3,12,1,10,1,1,2020,2020
28,PS09001,12,2,10,1,1,2023,2023
29,PS12021,11,2,1,10,0,2021,2021
30,RIM02,11,1,10,1,0,2019,2019
31,PS09006,11,1,9,2,0,2023,2023
32,PS40003,11,4,8,3,0,2021,2021
33,ACLCHE,11,7,8,3,0,2018,2022
34,PHYINT,11,6,6,5,0,2019,2022
35,Mucu3,10,1,9,1,0,2022,2022
36,PS09002,10,1,6,2,2,2023,2023
37,SPELAT,9,3,6,3,0,2019,2020
38,PECCFANG,9,1,8,1,0,2018,2018
39,ETRE18,9,2,8,1,0,2019,2019
40,PS12000,9,1,6,3,0,2021,2021
41,2VH1,8,4,2,6,0,2018,2023
42,CHAMA15AF,8,3,8,0,0,2022,2022
43,2FERN1,8,4,5,3,0,2018,2023
44,COTGRA,7,3,6,1,0,2019,2019
45,PS40004,7,3,4,3,0,2021,2021
46,CYLIMBSPI,7,3,4,2,1,2019,2019
47,PS09003,7,1,7,0,0,2023,2023
48,LAPcfCOR,7,2,3,4,0,2020,2020
49,LAPCOR,7,2,2,5,0,2019,2020
50,PGO5,6,1,3,2,1,2018,2018
51,PS04001,6,1,5,1,0,2023,2023
52,HETPOL,6,1,5,1,0,2023,2023
53,BOER44,6,1,5,1,0,2019,2019
54,TIQHISS,6,1,5,1,0,2018,2018
55,OENHARF2,6,2,6,0,0,2020,2020
56,LEPcfMON,6,2,5,1,0,2020,2020
57,LORPUL,6,3,6,0,0,2021,2023
58,PS91011,6,1,5,1,0,2022,2022
59,PS10004,5,2,2,3,0,2022,2022
60,PS90001,5,1,5,0,0,2022,2022
61,F02,5,1,0,5,0,2018,2018
62,PS10002,5,1,3,2,0,2022,2022
63,AS90001,5,1,3,2,0,2023,2023
64,FRAL211,5,1,3,2,0,2020,2020
65,PS09007,4,1,3,1,0,2023,2023
66,AS12002,4,1,0,4,0,2021,2021
67,SPCO86,4,2,1,3,0,2019,2019
68,SU01000,4,3,2,1,1,2021,2021
69,BAPRG,4,2,3,1,0,2021,2021
70,AMME12,4,3,2,2,0,2020,2021
71,OROB86,4,3,0,4,0,2019,2021
72,MOS213,4,2,0,4,0,2019,2019
73,SPOcfCRY,3,3,2,1,0,2020,2022
74,PS90003,3,3,3,0,0,2021,2021
75,OENGAY,3,2,3,0,0,2019,2020
76,PS03001,3,1,1,1,1,2022,2022
77,RIBE5,3,1,3,0,0,2020,2020
78,OFEBR,3,1,3,0,0,2018,2018
79,ASTRAPF,3,1,2,1,0,2019,2019
80,XANGRI,3,2,3,0,0,2021,2022
81,TIQHISs,3,2,3,0,0,2020,2021
82,ALDCOR,3,1,1,2,0,2021,2021
83,ARABIS,2,2,1,1,0,2019,2019
84,FUNGUS86,2,2,0,2,0,2019,2019
85,56,2,2,0,2,0,2018,2018
86,AFXX,2,2,0,2,0,2019,2019
87,MOS214,2,1,0,2,0,2019,2019
88,JUHO26,2,1,2,0,0,2020,2020
89,PAHU86,2,1,0,2,0,2019,2019
90,PENST4,2,1,1,1,0,2020,2020
91,PHYS,2,1,2,0,0,2019,2019
92,LILEL3,2,1,2,0,0,2019,2019
93,LEPEAS,2,1,1,1,0,2019,2019
94,LADLAN,2,1,2,0,0,2022,2022
95,MOS205,2,1,0,2,0,2019,2019
96,PHLO22,2,2,1,1,0,2021,2021
97,ANPA44,2,1,1,1,0,2020,2020
98,COUM3,2,1,1,1,0,2018,2018
99,DESUO86,2,1,2,0,0,2021,2021

Still >= 50 records and requiring review: 7
Remaining < 50-record codes: 165
Records represented by <50 tail: 870

,observed_code,n_records,n_plot_visits,n_top,n_lower,n_soil_surface,first_year,last_year
0,PHYGOR,365,50,271,89,5,2018,2023
1,PHYFEN,290,66,193,90,7,2018,2023
2,SIDTEN,246,25,227,17,2,2018,2024
3,SPOCFCRY,220,38,173,29,18,2018,2021
4,BOERHAF,75,10,72,3,0,2022,2023
5,PS09009,63,1,45,12,6,2023,2023
6,PS91006,57,2,41,15,1,2021,2021

In [17]:
# ============================================================
# FINALIZE REMAINING HIGH-FREQUENCY UNRESOLVED PLANT CODES
#
# These have been manually reviewed and cannot be resolved
# defensibly beyond unknown vegetation.
# ============================================================

reviewed_unknown_plant_codes = [
    "PHYGOR",
    "PHYFEN",
    "SIDTEN",
    "SPOCFCRY",
    "BOERHAF",
    "PS09009",
    "PS91006",
]

mask = (
    dictionary["code_class"].isna()
    & dictionary["observed_code"].isin(reviewed_unknown_plant_codes)
)

dictionary.loc[mask, "code_class"] = "Plant"
dictionary.loc[mask, "resolved_label"] = "Unknown plant"
dictionary.loc[mask, "protocol_plant_group"] = "UnknownPlant"
dictionary.loc[mask, "resolution_source"] = "manual_review_unresolvable"

In [18]:
# ============================================================
# TOTAL SPECIES-DICTIONARY METADATA + SUMMARY
#
# Purpose:
#   Audit the completed pre-functional-group dictionary at both:
#       1. unique observed-code level
#       2. LPI record-weighted level
#
# Assumes:
#   dictionary exists
#   n_records is present
# ============================================================

import numpy as np
import pandas as pd

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 180)


# ============================================================
# 0. BASIC INTEGRITY
# ============================================================

N_CODES = len(dictionary)
N_RECORDS = int(dictionary["n_records"].sum())

print("=" * 80)
print("LPI SPECIES / PROTOCOL DICTIONARY — TOTAL SUMMARY")
print("=" * 80)

print(f"Unique observed codes:             {N_CODES:,}")
print(f"Total LPI records represented:     {N_RECORDS:,}")

if "n_plot_visits" in dictionary.columns:
    print(
        f"Sum of code-level plot occurrences:{dictionary['n_plot_visits'].sum():,}"
    )

print()


# ============================================================
# 1. CORE COMPLETENESS
# ============================================================

summary_fields = [
    "code_class",
    "resolved_label",
    "resolution_source",
    "taxonomic_level",
    "protocol_plant_group",
    "USDA_accepted_symbol",
    "USDA_scientific_name",
    "USDA_common_name",
    "USDA_family",
]

completeness_rows = []

for col in summary_fields:

    if col not in dictionary.columns:
        continue

    resolved = dictionary[col].notna()

    n_codes = int(resolved.sum())
    records = int(dictionary.loc[resolved, "n_records"].sum())

    completeness_rows.append({
        "field": col,
        "codes_present": n_codes,
        "codes_pct": 100 * n_codes / N_CODES,
        "records_present": records,
        "records_pct": 100 * records / N_RECORDS,
    })

completeness = pd.DataFrame(completeness_rows)

print("FIELD COMPLETENESS")
display(
    completeness.style.format({
        "codes_pct": "{:.2f}",
        "records_pct": "{:.4f}",
    })
)


# ============================================================
# 2. CODE CLASS — UNIQUE CODES + RECORD-WEIGHTED
# ============================================================

def categorical_summary(df, column):
    """
    Summarize a categorical dictionary field by:
      - number of unique observed codes
      - percent of dictionary codes
      - represented LPI records
      - percent of all represented records
    """

    x = df.copy()

    x["_category"] = (
        x[column]
        .astype("string")
        .fillna("<UNRESOLVED>")
    )

    out = (
        x.groupby("_category", dropna=False)
        .agg(
            n_codes=("observed_code", "size"),
            n_records=("n_records", "sum"),
        )
        .reset_index()
        .rename(columns={"_category": column})
    )

    out["codes_pct"] = 100 * out["n_codes"] / N_CODES
    out["records_pct"] = 100 * out["n_records"] / N_RECORDS

    return (
        out.sort_values(
            ["n_records", "n_codes"],
            ascending=False,
        )
        .reset_index(drop=True)
    )


print()
print("CODE CLASS")
code_class_summary = categorical_summary(
    dictionary,
    "code_class",
)

display(
    code_class_summary.style.format({
        "codes_pct": "{:.2f}",
        "records_pct": "{:.4f}",
    })
)


# ============================================================
# 3. RESOLUTION SOURCE
# ============================================================

print()
print("RESOLUTION SOURCE")

resolution_summary = categorical_summary(
    dictionary,
    "resolution_source",
)

display(
    resolution_summary.style.format({
        "codes_pct": "{:.2f}",
        "records_pct": "{:.4f}",
    })
)


# ============================================================
# 4. TAXONOMIC LEVEL
# ============================================================

print()
print("TAXONOMIC LEVEL")

taxonomic_level_summary = categorical_summary(
    dictionary,
    "taxonomic_level",
)

display(
    taxonomic_level_summary.style.format({
        "codes_pct": "{:.2f}",
        "records_pct": "{:.4f}",
    })
)


# ============================================================
# 5. SOURCE-LEVEL FUNCTIONAL INFORMATION
#
# This is NOT the final MOSAIC functional-group derivation.
# It only summarizes protocol_plant_group already known from
# source/project information.
# ============================================================

print()
print("PROTOCOL / SOURCE-LEVEL PLANT GROUP")

protocol_group_summary = categorical_summary(
    dictionary,
    "protocol_plant_group",
)

display(
    protocol_group_summary.style.format({
        "codes_pct": "{:.2f}",
        "records_pct": "{:.4f}",
    })
)


# ============================================================
# 6. PLANT-ONLY SUMMARY
# ============================================================

plants = dictionary[
    dictionary["code_class"].eq("Plant")
].copy()

N_PLANT_CODES = len(plants)
N_PLANT_RECORDS = int(plants["n_records"].sum())

print()
print("=" * 80)
print("PLANT-CODE SUMMARY")
print("=" * 80)

print(f"Plant codes:                       {N_PLANT_CODES:,}")
print(f"Plant-contact records:             {N_PLANT_RECORDS:,}")
print(f"Plant codes / all codes:           {100*N_PLANT_CODES/N_CODES:.2f}%")
print(f"Plant records / all records:       {100*N_PLANT_RECORDS/N_RECORDS:.2f}%")

print()


# ============================================================
# 7. USDA TAXONOMY COVERAGE AMONG PLANTS
# ============================================================

if N_PLANT_CODES > 0:

    usda_resolved = plants[
        plants["USDA_accepted_symbol"].notna()
    ].copy()

    n_usda_codes = len(usda_resolved)
    n_usda_records = int(usda_resolved["n_records"].sum())

    print("USDA TAXONOMIC COVERAGE AMONG PLANTS")
    print(
        f"Plant codes with USDA target:      "
        f"{n_usda_codes:,} "
        f"({100*n_usda_codes/N_PLANT_CODES:.2f}%)"
    )

    print(
        f"Plant records with USDA target:    "
        f"{n_usda_records:,} "
        f"({100*n_usda_records/N_PLANT_RECORDS:.2f}%)"
    )

    print(
        f"Distinct USDA accepted symbols:    "
        f"{usda_resolved['USDA_accepted_symbol'].nunique():,}"
    )

    if "USDA_scientific_name" in usda_resolved.columns:
        print(
            f"Distinct scientific names:         "
            f"{usda_resolved['USDA_scientific_name'].nunique():,}"
        )


# ============================================================
# 8. UNKNOWN / UNRESOLVED VEGETATION
# ============================================================

unknown_plant_mask = (
    dictionary["code_class"].eq("Plant")
    & (
        dictionary["protocol_plant_group"].eq("UnknownPlant")
        | dictionary["resolved_label"].eq("Unknown plant")
    )
)

unknown_plants = dictionary[
    unknown_plant_mask
].copy()

unresolved = dictionary[
    dictionary["code_class"].isna()
].copy()

unknown_plant_records = int(
    unknown_plants["n_records"].sum()
)

unresolved_records = int(
    unresolved["n_records"].sum()
)

print()
print("=" * 80)
print("UNKNOWN / UNRESOLVED IMPACT")
print("=" * 80)

print(
    f"Explicit UnknownPlant codes:       "
    f"{len(unknown_plants):,}"
)

print(
    f"Explicit UnknownPlant records:     "
    f"{unknown_plant_records:,} "
    f"({100*unknown_plant_records/N_RECORDS:.5f}% of all records)"
)

print(
    f"Still-unresolved codes:            "
    f"{len(unresolved):,}"
)

print(
    f"Still-unresolved records:          "
    f"{unresolved_records:,} "
    f"({100*unresolved_records/N_RECORDS:.5f}% of all records)"
)

if N_PLANT_RECORDS > 0:
    print(
        f"UnknownPlant share of plant hits:  "
        f"{100*unknown_plant_records/N_PLANT_RECORDS:.4f}%"
    )


# ============================================================
# 9. TOP EXPLICIT UNKNOWN PLANT CODES
# ============================================================

print()
print("TOP UNKNOWN-PLANT CODES")

display(
    unknown_plants[
        [
            "observed_code",
            "n_records",
            "n_plot_visits",
            "n_top",
            "n_lower",
            "n_soil_surface",
            "resolved_label",
            "resolution_source",
        ]
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
    .head(30)
    .reset_index(drop=True)
)


# ============================================================
# 10. TOP REMAINING COMPLETELY UNRESOLVED CODES
# ============================================================

print()
print("TOP COMPLETELY UNRESOLVED CODES")

display(
    unresolved[
        [
            "observed_code",
            "n_records",
            "n_plot_visits",
            "n_top",
            "n_lower",
            "n_soil_surface",
            "first_year",
            "last_year",
        ]
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
    .head(50)
    .reset_index(drop=True)
)


# ============================================================
# 11. MOST ABUNDANT OBSERVED CODES
# ============================================================

print()
print("=" * 80)
print("MOST ABUNDANT OBSERVED CODES")
print("=" * 80)

display(
    dictionary[
        [
            "observed_code",
            "n_records",
            "n_plot_visits",
            "code_class",
            "resolved_label",
            "USDA_accepted_symbol",
            "protocol_plant_group",
            "resolution_source",
        ]
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
    .head(50)
    .reset_index(drop=True)
)


# ============================================================
# 12. MOST ABUNDANT PLANT CODES
# ============================================================

print()
print("MOST ABUNDANT PLANT CODES")

display(
    plants[
        [
            "observed_code",
            "n_records",
            "n_plot_visits",
            "resolved_label",
            "USDA_accepted_symbol",
            "USDA_scientific_name",
            "protocol_plant_group",
            "resolution_source",
        ]
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
    .head(50)
    .reset_index(drop=True)
)


# ============================================================
# 13. VERTICAL-CONTACT SUMMARY BY CODE CLASS
#
# Useful QA because TopCanopy / Lower / SoilSurface have very
# different ecological meanings.
# ============================================================

vertical_cols = [
    "n_top",
    "n_lower",
    "n_soil_surface",
]

if all(
    col in dictionary.columns
    for col in vertical_cols
):

    vertical_summary = (
        dictionary
        .assign(
            code_class_display=
                dictionary["code_class"]
                .astype("string")
                .fillna("<UNRESOLVED>")
        )
        .groupby(
            "code_class_display"
        )[vertical_cols]
        .sum()
        .reset_index()
    )

    vertical_summary["total_contacts"] = (
        vertical_summary[vertical_cols]
        .sum(axis=1)
    )

    for col in vertical_cols:
        vertical_summary[f"{col}_pct"] = (
            100
            * vertical_summary[col]
            / vertical_summary["total_contacts"]
        )

    print()
    print("VERTICAL CONTACT DISTRIBUTION BY CODE CLASS")

    display(
        vertical_summary.style.format({
            "n_top_pct": "{:.2f}",
            "n_lower_pct": "{:.2f}",
            "n_soil_surface_pct": "{:.2f}",
        })
    )


# ============================================================
# 14. TEMPORAL COVERAGE
# ============================================================

if {
    "first_year",
    "last_year",
}.issubset(dictionary.columns):

    print()
    print("TEMPORAL COVERAGE")

    print(
        f"Earliest code occurrence:          "
        f"{dictionary['first_year'].min()}"
    )

    print(
        f"Latest code occurrence:            "
        f"{dictionary['last_year'].max()}"
    )

    dictionary["_years_present_span"] = (
        dictionary["last_year"]
        - dictionary["first_year"]
        + 1
    )

    print(
        f"Codes observed in >1-year span:    "
        f"{(dictionary['_years_present_span'] > 1).sum():,}"
    )


# ============================================================
# 15. DUPLICATE / UNIQUENESS QA
# ============================================================

print()
print("=" * 80)
print("UNIQUENESS QA")
print("=" * 80)

n_duplicate_codes = int(
    dictionary["observed_code"].duplicated().sum()
)

print(
    f"Duplicate observed_code rows:      "
    f"{n_duplicate_codes:,}"
)

if n_duplicate_codes > 0:

    display(
        dictionary[
            dictionary["observed_code"].duplicated(
                keep=False
            )
        ].sort_values("observed_code")
    )


# ============================================================
# 16. USDA ACCEPTED SYMBOL CONVERGENCE
#
# How many raw/project codes converge onto the same accepted
# taxon? Useful for seeing the benefit of synonym + alias work.
# ============================================================

usda_convergence = (
    dictionary[
        dictionary["USDA_accepted_symbol"].notna()
    ]
    .groupby(
        "USDA_accepted_symbol"
    )
    .agg(
        n_observed_codes=("observed_code", "nunique"),
        n_records=("n_records", "sum"),
        scientific_name=(
            "USDA_scientific_name",
            "first",
        ),
    )
    .reset_index()
    .sort_values(
        ["n_observed_codes", "n_records"],
        ascending=False,
    )
)

print()
print("USDA SYMBOL CONVERGENCE")

print(
    f"Accepted taxa represented by >1 observed code: "
    f"{(usda_convergence['n_observed_codes'] > 1).sum():,}"
)

display(
    usda_convergence[
        usda_convergence["n_observed_codes"] > 1
    ]
    .head(50)
    .reset_index(drop=True)
)


# ============================================================
# 17. COMPACT FINAL AUDIT
# ============================================================

classified_mask = dictionary["code_class"].notna()

classified_codes = int(classified_mask.sum())
classified_records = int(
    dictionary.loc[
        classified_mask,
        "n_records",
    ].sum()
)

print()
print("=" * 80)
print("FINAL AUDIT")
print("=" * 80)

print(
    f"Classified codes:                  "
    f"{classified_codes:,} / {N_CODES:,} "
    f"({100*classified_codes/N_CODES:.2f}%)"
)

print(
    f"Classified records represented:    "
    f"{classified_records:,} / {N_RECORDS:,} "
    f"({100*classified_records/N_RECORDS:.5f}%)"
)

print(
    f"Unclassified record fraction:      "
    f"{100*(N_RECORDS-classified_records)/N_RECORDS:.5f}%"
)

print("=" * 80)

================================================================================
LPI SPECIES / PROTOCOL DICTIONARY — TOTAL SUMMARY
================================================================================
Unique observed codes:             10,960
Total LPI records represented:     16,150,101
Sum of code-level plot occurrences:812,524

FIELD COMPLETENESS

CODE CLASS

RESOLUTION SOURCE

TAXONOMIC LEVEL

PROTOCOL / SOURCE-LEVEL PLANT GROUP

================================================================================
PLANT-CODE SUMMARY
================================================================================
Plant codes:                       10,749
Plant-contact records:             5,436,341
Plant codes / all codes:           98.07%
Plant records / all records:       33.66%

USDA TAXONOMIC COVERAGE AMONG PLANTS
Plant codes with USDA target:      7,605 (70.75%)
Plant records with USDA target:    5,217,035 (95.97%)
Distinct USDA accepted symbols:    7,268
Distinct scientific names:         7,268

================================================================================
UNKNOWN / UNRESOLVED IMPACT
================================================================================
Explicit UnknownPlant codes:       142
Explicit UnknownPlant records:     21,114 (0.13074% of all records)
Still-unresolved codes:            165
Still-unresolved records:          870 (0.00539% of all records)
UnknownPlant share of plant hits:  0.3884%

TOP UNKNOWN-PLANT CODES

   observed_code  n_records  n_plot_visits  n_top  n_lower  n_soil_surface resolved_label           resolution_source
0     Plant base      17980           1105      0        0           17980     Plant base   protocol_basal_vegetation
1        BOETRII        476             64    377       99               0  Unknown plant        manual_unknown_plant
2         PINSCO        441             23    436        2               3  Unknown plant        manual_unknown_plant
3         PHYGOR        365             50    271       89               5  Unknown plant  manual_review_unresolvable
4         PHYFEN        290             66    193       90               7  Unknown plant  manual_review_unresolvable
5         SIDTEN        246             25    227       17               2  Unknown plant  manual_review_unresolvable
6       SPOCFCRY        220             38    173       29              18  Unknown plant  manual_review_unresolvable
7            Unk        195             46    195        0               0  Unknown plant        manual_unknown_plant
8            UNK         86             25     60       24               2  Unknown plant        manual_unknown_plant
9        BOERHAF         75             10     72        3               0  Unknown plant  manual_review_unresolvable
10       PS09009         63              1     45       12               6  Unknown plant  manual_review_unresolvable
11       UN12000         61             14     38       20               3  Unknown plant        project_unknown_code
12       UN09011         59              1     59        0               0  Unknown plant        project_unknown_code
13       PS91006         57              2     41       15               1  Unknown plant  manual_review_unresolvable
14       UN06101         22              3     12        6               4  Unknown plant        project_unknown_code
15       UN06010         21              8      7       14               0  Unknown plant        project_unknown_code
16       UN60000         18              1     18        0               0  Unknown plant        project_unknown_code
17       UN06208         18              2      9        9               0  Unknown plant        project_unknown_code
18       UN23024         14              1      3       11               0  Unknown plant        project_unknown_code
19       UN03000         14              8      8        6               0  Unknown plant        project_unknown_code
20       UN04001         13              2      2       11               0  Unknown plant        project_unknown_code
21       UN06019         13              2     10        3               0  Unknown plant        project_unknown_code
22       UN09032         12              2      9        1               2  Unknown plant        project_unknown_code
23       UN04013         12              1      0       12               0  Unknown plant        project_unknown_code
24       UN40016         12              1      9        3               0  Unknown plant        project_unknown_code
25       UN04017         11              1      0       11               0  Unknown plant        project_unknown_code
26       UN00207         11              1      8        1               2  Unknown plant        project_unknown_code
27       UN09000          9              6      8        1               0  Unknown plant        project_unknown_code
28       UN06403          9              3      2        7               0  Unknown plant        project_unknown_code
29       UN06401          9              5      5        3               1  Unknown plant        project_unknown_code

TOP COMPLETELY UNRESOLVED CODES

   observed_code  n_records  n_plot_visits  n_top  n_lower  n_soil_surface  first_year  last_year
0         SPHPUM         39             24     24       13               2        2018       2023
1             PL         33             10      1       21              11        2018       2018
2             DF         25             13      2       23               0        2021       2022
3        PS09008         24              3      6       18               0        2023       2023
4        PS09004         24              1     11       13               0        2023       2023
5        PS09005         23              1     19        1               3        2023       2023
6           VEWO         22              5      7       15               0        2021       2023
7         XANGRA         20              7     17        2               1        2019       2022
8        TIQHISn         18              2     17        0               1        2020       2020
9          ADWRW         18              1     15        3               0        2023       2023
10       PS09011         17              1      1       16               0        2023       2023
11       PS09010         17              1      4       11               2        2023       2023
12        AMAPED         16              7     16        0               0        2019       2021
13       AGAPARN         16              6     11        3               2        2018       2022
14         ASRP5         16              1     15        1               0        2019       2019
15        ALPR33         15              1     14        1               0        2020       2020
16      LEPCFMON         15              2     10        4               1        2019       2021
17        DIAVER         14              6      9        5               0        2020       2020
18            DG         13              5      1       12               0        2021       2022
19        MATPAR         13              3      9        4               0        2023       2023
20       PS09001         12              2     10        1               1        2023       2023
21          POA3         12              1     10        1               1        2020       2020
22        PHYINT         11              6      6        5               0        2019       2022
23       PS40003         11              4      8        3               0        2021       2021
24       PS12021         11              2      1       10               0        2021       2021
25         RIM02         11              1     10        1               0        2019       2019
26       PS09006         11              1      9        2               0        2023       2023
27        ACLCHE         11              7      8        3               0        2018       2022
28         Mucu3         10              1      9        1               0        2022       2022
29       PS09002         10              1      6        2               2        2023       2023
30       PS12000          9              1      6        3               0        2021       2021
31        SPELAT          9              3      6        3               0        2019       2020
32        ETRE18          9              2      8        1               0        2019       2019
33      PECCFANG          9              1      8        1               0        2018       2018
34          2VH1          8              4      2        6               0        2018       2023
35     CHAMA15AF          8              3      8        0               0        2022       2022
36        2FERN1          8              4      5        3               0        2018       2023
37        COTGRA          7              3      6        1               0        2019       2019
38       PS09003          7              1      7        0               0        2023       2023
39        LAPCOR          7              2      2        5               0        2019       2020
40      LAPcfCOR          7              2      3        4               0        2020       2020
41     CYLIMBSPI          7              3      4        2               1        2019       2019
42       PS40004          7              3      4        3               0        2021       2021
43          PGO5          6              1      3        2               1        2018       2018
44       PS91011          6              1      5        1               0        2022       2022
45       TIQHISS          6              1      5        1               0        2018       2018
46        HETPOL          6              1      5        1               0        2023       2023
47      LEPcfMON          6              2      5        1               0        2020       2020
48        LORPUL          6              3      6        0               0        2021       2023
49       PS04001          6              1      5        1               0        2023       2023

================================================================================
MOST ABUNDANT OBSERVED CODES
================================================================================

        observed_code  n_records  n_plot_visits        code_class                                     resolved_label USDA_accepted_symbol protocol_plant_group resolution_source
0                   S    4908062          51501          NonPlant                                               Soil                 <NA>                 <NA>              <NA>
1                  HL    2420983          40544          NonPlant                                  Herbaceous litter                 <NA>                 <NA>              <NA>
2                   L     853273          10209          NonPlant                                             Lichen                 <NA>                 <NA>              <NA>
3                  GR     721055          22333          NonPlant                                             Gravel                 <NA>                 <NA>              <NA>
4       __NO_CANOPY__     442612           8652          NoCanopy                              No top-canopy contact                 <NA>                 <NA>              <NA>
5                BRTE     429816          18317             Plant                                 Bromus tectorum L.                 BRTE                 <NA>              <NA>
6                POSE     332740          20687             Plant                               Poa secunda J. Presl                 POSE                 <NA>              <NA>
7                  WL     288075          34740          NonPlant                                       Woody litter                 <NA>                 <NA>              <NA>
8              ARTRW8     232161          13236             Plant  Artemisia tridentata Nutt. ssp. wyomingensis B...               ARTRW8                 <NA>              <NA>
9                  RF     177392           9091          NonPlant                                      Rock fragment                 <NA>                 <NA>     protocol_code
10              PSSP6     163393          10651             Plant            Pseudoroegneria spicata (Pursh) Á. Löve                PSSP6                 <NA>              <NA>
11              BOGR2     159606           8262             Plant  Bouteloua gracilis (Willd. ex Kunth) Lag. ex G...                BOGR2                 <NA>              <NA>
12                  M     150630          15914          NonPlant                                               Moss                 <NA>                 <NA>              <NA>
13               PASM     136002           8194             Plant                 Pascopyrum smithii (Rydb.) Á. Löve                 PASM                 <NA>              <NA>
14                 CB     128001          14289          NonPlant                                             Cobble                 <NA>                 <NA>              <NA>
15                  D     119146           4690          NonPlant                                               Duff                 <NA>                 <NA>              <NA>
16               POPR     115614           4198             Plant                                   Poa pratensis L.                 POPR                 <NA>              <NA>
17               AGCR      86637           4093             Plant                   Agropyron cristatum (L.) Gaertn.                 AGCR                 <NA>              <NA>
18             HECO26      80033           7189             Plant      Hesperostipa comata (Trin. & Rupr.) Barkworth               HECO26                 <NA>              <NA>
19              ARTRV      79491           3818             Plant  Artemisia tridentata Nutt. ssp. vaseyana (Rydb...                ARTRV                 <NA>              <NA>
20               FEID      78604           3775             Plant                           Festuca idahoensis Elmer                 FEID                 <NA>              <NA>
21                 PC      75156            168  ContextDependent                               Context-dependent PC                 <NA>                 <NA>              <NA>
22               JUOS      73087           4175             Plant               Juniperus osteosperma (Torr.) Little                 JUOS                 <NA>              <NA>
23              BRAR5      72303           4317             Plant                                 Bromus arvensis L.                BRAR5                 <NA>              <NA>
24                  R      69099           3656          NonPlant                                               Rock                 <NA>                 <NA>              <NA>
25                 LM      68581            157          NonPlant                        Loose erodible mineral soil                 <NA>                 <NA>     protocol_code
26  Perennial grasses      61012           1814             Plant                                  Perennial grasses                 <NA>   PerennialGraminoid              <NA>
27                 ST      58861           9325          NonPlant                                              Stone                 <NA>                 <NA>              <NA>
28              ELEL5      58454          12255             Plant                     Elymus elymoides (Raf.) Swezey                ELEL5                 <NA>              <NA>
29              BRIN2      56601           2081             Plant                              Bromus inermis Leyss.                BRIN2                 <NA>              <NA>
30                 CY      56462           2957          NonPlant                               Cyanobacterial crust                 <NA>                 <NA>     protocol_code
31              CHVI8      52275           9485             Plant          Chrysothamnus viscidiflorus (Hook.) Nutt.                CHVI8                 <NA>              <NA>
32                 LC      52266           7950          NonPlant                              Lichen / biotic crust                 <NA>                 <NA>              <NA>
33               PIED      46760           2443             Plant                               Pinus edulis Engelm.                 PIED                 <NA>              <NA>
34              SCAR7      46213           1135             Plant  Schedonorus arundinaceus (Schreb.) Dumort., no...                SCAR7                 <NA>              <NA>
35               CAFI      45000           3224             Plant                              Carex filifolia Nutt.                 CAFI                 <NA>              <NA>
36                 BR      43944           4222          NonPlant                                            Bedrock                 <NA>                 <NA>              <NA>
37              ARNO4      42879           2634             Plant                           Artemisia nova A. Nelson                ARNO4                 <NA>              <NA>
38               KOMA      41066           5902             Plant                Koeleria macrantha (Ledeb.) Schult.                 KOMA                 <NA>              <NA>
39               SCSC      36095           1971             Plant              Schizachyrium scoparium (Michx.) Nash                 SCSC                 <NA>              <NA>
40              SEDE2      35956            829             Plant                            Selaginella densa Rydb.                SEDE2                 <NA>              <NA>
41      Annual plants      35750           1507             Plant                                      Annual plants                 <NA>          AnnualPlant              <NA>
42              ARAR8      32897           1938             Plant                          Artemisia arbuscula Nutt.                ARAR8                 <NA>              <NA>
43              PRGL2      32583           1504             Plant                          Prosopis glandulosa Torr.                PRGL2                 <NA>              <NA>
44              LATR2      31613           2442             Plant                    Larrea tridentata (DC.) Coville                LATR2                 <NA>              <NA>
45              PUTR2      31259           2977             Plant                     Purshia tridentata (Pursh) DC.                PUTR2                 <NA>              <NA>
46               BOCU      30568           2262             Plant              Bouteloua curtipendula (Michx.) Torr.                 BOCU                 <NA>              <NA>
47              ARTRT      30220           2159             Plant         Artemisia tridentata Nutt. ssp. tridentata                ARTRT                 <NA>              <NA>
48               CYDA      30196            839             Plant                        Cynodon dactylon (L.) Pers.                 CYDA                 <NA>              <NA>
49               ACHY      28467           6295             Plant  Achnatherum hymenoides (Roem. & Schult.) Barkw...                 ACHY                 <NA>              <NA>

MOST ABUNDANT PLANT CODES

,observed_code,n_records,n_plot_visits,resolved_label,USDA_accepted_symbol,USDA_scientific_name,protocol_plant_group,resolution_source
0,BRTE,429816,18317,Bromus tectorum L.,BRTE,Bromus tectorum L.,<NA>,<NA>
1,POSE,332740,20687,Poa secunda J. Presl,POSE,Poa secunda J. Presl,<NA>,<NA>
2,ARTRW8,232161,13236,Artemisia tridentata Nutt. ssp. wyomingensis B...,ARTRW8,Artemisia tridentata Nutt. ssp. wyomingensis B...,<NA>,<NA>
3,PSSP6,163393,10651,Pseudoroegneria spicata (Pursh) Á. Löve,PSSP6,Pseudoroegneria spicata (Pursh) Á. Löve,<NA>,<NA>
4,BOGR2,159606,8262,Bouteloua gracilis (Willd. ex Kunth) Lag. ex G...,BOGR2,Bouteloua gracilis (Willd. ex Kunth) Lag. ex G...,<NA>,<NA>
5,PASM,136002,8194,Pascopyrum smithii (Rydb.) Á. Löve,PASM,Pascopyrum smithii (Rydb.) Á. Löve,<NA>,<NA>
6,POPR,115614,4198,Poa pratensis L.,POPR,Poa pratensis L.,<NA>,<NA>
7,AGCR,86637,4093,Agropyron cristatum (L.) Gaertn.,AGCR,Agropyron cristatum (L.) Gaertn.,<NA>,<NA>
8,HECO26,80033,7189,Hesperostipa comata (Trin. & Rupr.) Barkworth,HECO26,Hesperostipa comata (Trin. & Rupr.) Barkworth,<NA>,<NA>
9,ARTRV,79491,3818,Artemisia tridentata Nutt. ssp. vaseyana (Rydb...,ARTRV,Artemisia tridentata Nutt. ssp. vaseyana (Rydb...,<NA>,<NA>
10,FEID,78604,3775,Festuca idahoensis Elmer,FEID,Festuca idahoensis Elmer,<NA>,<NA>
11,JUOS,73087,4175,Juniperus osteosperma (Torr.) Little,JUOS,Juniperus osteosperma (Torr.) Little,<NA>,<NA>
12,BRAR5,72303,4317,Bromus arvensis L.,BRAR5,Bromus arvensis L.,<NA>,<NA>
13,Perennial grasses,61012,1814,Perennial grasses,<NA>,<NA>,PerennialGraminoid,<NA>
14,ELEL5,58454,12255,Elymus elymoides (Raf.) Swezey,ELEL5,Elymus elymoides (Raf.) Swezey,<NA>,<NA>
15,BRIN2,56601,2081,Bromus inermis Leyss.,BRIN2,Bromus inermis Leyss.,<NA>,<NA>
16,CHVI8,52275,9485,Chrysothamnus viscidiflorus (Hook.) Nutt.,CHVI8,Chrysothamnus viscidiflorus (Hook.) Nutt.,<NA>,<NA>
17,PIED,46760,2443,Pinus edulis Engelm.,PIED,Pinus edulis Engelm.,<NA>,<NA>
18,SCAR7,46213,1135,"Schedonorus arundinaceus (Schreb.) Dumort., no...",SCAR7,"Schedonorus arundinaceus (Schreb.) Dumort., no...",<NA>,<NA>
19,CAFI,45000,3224,Carex filifolia Nutt.,CAFI,Carex filifolia Nutt.,<NA>,<NA>
20,ARNO4,42879,2634,Artemisia nova A. Nelson,ARNO4,Artemisia nova A. Nelson,<NA>,<NA>
21,KOMA,41066,5902,Koeleria macrantha (Ledeb.) Schult.,KOMA,Koeleria macrantha (Ledeb.) Schult.,<NA>,<NA>
22,SCSC,36095,1971,Schizachyrium scoparium (Michx.) Nash,SCSC,Schizachyrium scoparium (Michx.) Nash,<NA>,<NA>
23,SEDE2,35956,829,Selaginella densa Rydb.,SEDE2,Selaginella densa Rydb.,<NA>,<NA>
24,Annual plants,35750,1507,Annual plants,<NA>,<NA>,AnnualPlant,<NA>
25,ARAR8,32897,1938,Artemisia arbuscula Nutt.,ARAR8,Artemisia arbuscula Nutt.,<NA>,<NA>
26,PRGL2,32583,1504,Prosopis glandulosa Torr.,PRGL2,Prosopis glandulosa Torr.,<NA>,<NA>
27,LATR2,31613,2442,Larrea tridentata (DC.) Coville,LATR2,Larrea tridentata (DC.) Coville,<NA>,<NA>
28,PUTR2,31259,2977,Purshia tridentata (Pursh) DC.,PUTR2,Purshia tridentata (Pursh) DC.,<NA>,<NA>
29,BOCU,30568,2262,Bouteloua curtipendula (Michx.) Torr.,BOCU,Bouteloua curtipendula (Michx.) Torr.,<NA>,<NA>
30,ARTRT,30220,2159,Artemisia tridentata Nutt. ssp. tridentata,ARTRT,Artemisia tridentata Nutt. ssp. tridentata,<NA>,<NA>
31,CYDA,30196,839,Cynodon dactylon (L.) Pers.,CYDA,Cynodon dactylon (L.) Pers.,<NA>,<NA>
32,ACHY,28467,6295,Achnatherum hymenoides (Roem. & Schult.) Barkw...,ACHY,Achnatherum hymenoides (Roem. & Schult.) Barkw...,<NA>,<NA>
33,ARTR2,27981,1628,Artemisia tridentata Nutt.,ARTR2,Artemisia tridentata Nutt.,<NA>,<NA>
34,GUSA2,27951,6100,Gutierrezia sarothrae (Pursh) Britton & Rusby,GUSA2,Gutierrezia sarothrae (Pursh) Britton & Rusby,<NA>,<NA>
35,TACA8,26357,1061,Taeniatherum caput-medusae (L.) Nevski,TACA8,Taeniatherum caput-medusae (L.) Nevski,<NA>,<NA>
36,ALDE,26258,3321,Alyssum desertorum Stapf,ALDE,Alyssum desertorum Stapf,<NA>,<NA>
37,ELLA3,26155,2196,Elymus lanceolatus (Scribn. & J.G. Sm.) Gould,ELLA3,Elymus lanceolatus (Scribn. & J.G. Sm.) Gould,<NA>,<NA>
38,QUGA,24748,934,Quercus gambelii Nutt.,QUGA,Quercus gambelii Nutt.,<NA>,<NA>
39,POBU,24009,1659,Poa bulbosa L.,POBU,Poa bulbosa L.,<NA>,<NA>
40,SAVE4,22495,2277,Sarcobatus vermiculatus (Hook.) Torr.,SAVE4,Sarcobatus vermiculatus (Hook.) Torr.,<NA>,<NA>
41,PHHO,22412,5933,Phlox hoodii Richardson,PHHO,Phlox hoodii Richardson,<NA>,<NA>
42,PLMU3,21959,659,Pleuraphis mutica Buckley,PLMU3,Pleuraphis mutica Buckley,<NA>,<NA>
43,SPCR,21750,2561,Sporobolus cryptandrus (Torr.) A. Gray,SPCR,Sporobolus cryptandrus (Torr.) A. Gray,<NA>,<NA>
44,ARPU9,21232,2881,Aristida purpurea Nutt.,ARPU9,Aristida purpurea Nutt.,<NA>,<NA>
45,Shrubs,21122,1221,Shrubs,<NA>,<NA>,Shrub,<NA>
46,ARARA,20985,1159,Artemisia arbuscula Nutt. ssp. arbuscula,ARARA,Artemisia arbuscula Nutt. ssp. arbuscula,<NA>,<NA>
47,PIMO,20850,1085,Pinus monophylla Torr. & Frém.,PIMO,Pinus monophylla Torr. & Frém.,<NA>,<NA>
48,SPAI,20780,796,Sporobolus airoides (Torr.) Torr.,SPAI,Sporobolus airoides (Torr.) Torr.,<NA>,<NA>
49,Sub-shrubs and perennial forbs,20140,1330,Sub-shrubs and perennial forbs,<NA>,<NA>,SubshrubOrPerennialForb,<NA>

VERTICAL CONTACT DISTRIBUTION BY CODE CLASS

TEMPORAL COVERAGE
Earliest code occurrence:          2018
Latest code occurrence:            2025
Codes observed in >1-year span:    5,604

================================================================================
UNIQUENESS QA
================================================================================
Duplicate observed_code rows:      0

USDA SYMBOL CONVERGENCE
Accepted taxa represented by >1 observed code: 292

   USDA_accepted_symbol  n_observed_codes  n_records                                    scientific_name
0                  KOMA                 6      41779                Koeleria macrantha (Ledeb.) Schult.
1                  POSE                 5     333033                               Poa secunda J. Presl
2                 THIN6                 5      11859  Thinopyrum intermedium (Host) Barkworth & D.R....
3                 GUSA2                 4      30001      Gutierrezia sarothrae (Pursh) Britton & Rusby
4                  CHJU                 4       3398                               Chondrilla juncea L.
5                 CRYPT                 4       1568                         Cryptantha Lehm. ex G. Don
6                 BRCA5                 4        643                      Bromus carinatus Hook. & Arn.
7                 PHACE                 4        287                                     Phacelia Juss.
8                EUGL19                 4        119                  Eurybia glauca (Nutt.) G.L. Nesom
9                  BRTE                 3     429829                                 Bromus tectorum L.
10               ARTRW8                 3     234749  Artemisia tridentata Nutt. ssp. wyomingensis B...
11                 PASM                 3     137439                 Pascopyrum smithii (Rydb.) Á. Löve
12                ARTRV                 3      79635  Artemisia tridentata Nutt. ssp. vaseyana (Rydb...
13               SATR12                 3      18477                                  Salsola tragus L.
14                BOBA2                 3      16671                             Bouteloua barbata Lag.
15                SEGR4                 3       2729         Senegalia greggii (A. Gray) Britton & Rose
16                DAPU7                 3       2615       Dasyochloa pulchella (Kunth) Willd. ex Rydb.
17                BAAM4                 3       1512            Bassia americana (S. Watson) A.J. Scott
18                 SUMO                 3       1369                     Suaeda moquinii (Torr.) Greene
19                 YUEL                 3       1210                      Yucca elata (Engelm.) Engelm.
20                 GUMI                 3       1096             Gutierrezia microcephala (DC.) A. Gray
21                CHER2                 3        790           Chaetopappa ericoides (Torr.) G.L. Nesom
22                JUARL                 3        694  Juncus arcticus Willd. ssp. littoralis (Engelm...
23               ARCOC4                 3        381              Arenaria congesta Nutt. var. congesta
24                ERAB2                 3        381                         Eriogonum abertianum Torr.
25               SCLI12                 3        322       Schoenocrambe linearifolia (A. Gray) Rollins
26                EUEX4                 3        320                      Euphorbia exstipulata Engelm.
27               PHAU13                 3        141           Phemeranthus aurantiacus (Engelm.) Kiger
28                ARPE2                 3        104                         Arabis perennans S. Watson
29                ARHOR                 3         58  Arabis holboellii Hornem. var. retrofracta (Gr...
30               ELELB2                 3         39  Elymus elymoides (Raf.) Swezey ssp. brevifoliu...
31                MILI5                 3         38                  Microseris lindleyi (DC.) A. Gray
32                BRAR5                 2      79994                                 Bromus arvensis L.
33                ELEL5                 2      58487                     Elymus elymoides (Raf.) Swezey
34                CHVI8                 2      52295          Chrysothamnus viscidiflorus (Hook.) Nutt.
35                 CAFI                 2      45002                              Carex filifolia Nutt.
36                ARNO4                 2      42882                           Artemisia nova A. Nelson
37                PUTR2                 2      31263                     Purshia tridentata (Pursh) DC.
38                 ACHY                 2      28537  Achnatherum hymenoides (Roem. & Schult.) Barkw...
39                 PLJA                 2      22327                           Pleuraphis jamesii Torr.
40                 SPCR                 2      21782             Sporobolus cryptandrus (Torr.) A. Gray
41                 SPAI                 2      20791                  Sporobolus airoides (Torr.) Torr.
42               ERNA10                 2      19793  Ericameria nauseosa (Pall. ex Pursh) G.L. Neso...
43                BODA2                 2      18930        Bouteloua dactyloides (Nutt.) J.T. Columbus
44                 MEOF                 2      14893                    Melilotus officinalis (L.) Lam.
45                BRRU2                 2      13475                                   Bromus rubens L.
46                EPBR3                 2      11345                    Epilobium brachycarpum C. Presl
47                LECI4                 2      11126          Leymus cinereus (Scribn. & Merr.) Á. Löve
48               HECOC8                 2      10851  Hesperostipa comata (Trin. & Rupr.) Barkworth ...
49                CETE5                 2      10356            Ceratocephala testiculata (Crantz) Roth

================================================================================
FINAL AUDIT
================================================================================
Classified codes:                  10,795 / 10,960 (98.49%)
Classified records represented:    16,149,231 / 16,150,101 (99.99461%)
Unclassified record fraction:      0.00539%
================================================================================

In [19]:
# ============================================================
# BACKFILL RESOLUTION PROVENANCE
#
# Earlier pipeline stages resolved many codes before
# resolution_source was introduced. This reconstructs
# provenance without overwriting later/manual decisions.
# ============================================================

source_missing = (
    dictionary["resolution_source"].isna()
    | dictionary["resolution_source"].astype("string").str.strip().eq("")
)


# ------------------------------------------------------------
# 1. No-canopy sentinel
# ------------------------------------------------------------

mask = (
    source_missing
    & dictionary["observed_code"].eq("__NO_CANOPY__")
)

dictionary.loc[
    mask,
    "resolution_source"
] = "source_blank_sentinel"


# ------------------------------------------------------------
# 2. USDA taxonomy resolution
#
# Prefer USDA_match_method because it preserves whether the
# original resolution was accepted-symbol vs synonym-symbol.
# ------------------------------------------------------------

if "USDA_match_method" in dictionary.columns:

    usda_exact = (
        source_missing
        & dictionary["USDA_match_method"].astype("string").isin([
            "accepted",
            "accepted_symbol",
            "exact",
            "exact_accepted_symbol",
        ])
    )

    dictionary.loc[
        usda_exact,
        "resolution_source"
    ] = "USDA_accepted_symbol"


    usda_synonym = (
        source_missing
        & dictionary["USDA_match_method"].astype("string").isin([
            "synonym",
            "synonym_symbol",
            "USDA_synonym",
        ])
    )

    dictionary.loc[
        usda_synonym,
        "resolution_source"
    ] = "USDA_synonym_symbol"


# Catch USDA-resolved rows whose older match-method naming
# does not match the strings above.
source_missing = dictionary["resolution_source"].isna()

mask = (
    source_missing
    & dictionary["USDA_accepted_symbol"].notna()
)

dictionary.loc[
    mask,
    "resolution_source"
] = "USDA_taxonomic_resolution"


# ------------------------------------------------------------
# 3. Previously resolved protocol/nonplant codes
#
# Only fills remaining missing provenance.
# ------------------------------------------------------------

source_missing = dictionary["resolution_source"].isna()

core_protocol_codes = {
    "S", "R", "BR", "GR", "CB", "ST", "BY",
    "RF", "FG",
    "HL", "WL", "EL", "D",
    "L", "LC", "M", "CY",
    "LM", "DN", "AM", "HT",
}

mask = (
    source_missing
    & dictionary["observed_code"].isin(core_protocol_codes)
)

dictionary.loc[
    mask,
    "resolution_source"
] = "protocol_code"


# ------------------------------------------------------------
# 4. Existing resolved rows lacking finer provenance
#
# This is deliberately generic. It prevents resolved rows from
# appearing as "unresolved" while retaining the fact that the
# exact historical resolution pathway was not recorded.
# ------------------------------------------------------------

source_missing = dictionary["resolution_source"].isna()

mask = (
    source_missing
    & dictionary["code_class"].notna()
)

dictionary.loc[
    mask,
    "resolution_source"
] = "legacy_resolved_pre_provenance"


# ------------------------------------------------------------
# QA
# ------------------------------------------------------------

print(
    dictionary["resolution_source"]
    .value_counts(dropna=False)
)

still_missing = dictionary[
    dictionary["resolution_source"].isna()
]

print(
    f"\nRows still lacking resolution_source: "
    f"{len(still_missing):,}"
)

resolution_source
USDA_accepted_symbol                 7160
legacy_resolved_pre_provenance       2967
USDA_synonym_symbol                   415
<NA>                                  165
project_unknown_code                  130
project_code_pattern                   29
protocol_code                          22
manual_functional_resolution           12
manual_genus_alias                     12
manual_protocol_alias                  10
manual_review_unresolvable              7
manual_project_code_alias               4
manual_unknown_plant                    4
manual_context_resolution               4
manual_typo_correction                  3
manual_taxonomic_alias                  3
manual_cf_taxonomic_alias               2
manual_taxonomic_resolution             2
manual_case_correction                  2
source_blank_sentinel                   1
protocol_basal_vegetation               1
manual_project_code_inferred            1
manual_protocol_interpretation          1
manual_ambiguous_species_to_genus       1
manual_typo_genus                       1
manual_USDA_synonym_resolution          1
Name: count, dtype: int64

Rows still lacking resolution_source: 165

In [20]:
# ============================================================
# USDA ECOLOGICAL ATTRIBUTES -> MOSAIC FUNCTIONAL GROUPS
#
# FINAL CONSERVATIVE CROSSWALK
#
# PRINCIPLES
# ----------
# 1. Preserve explicit source/project functional information.
#
# 2. Preserve PBG wherever PBG is already known.
#
# 3. USDA:
#       Perennial + Graminoid
#            -> PerennialGraminoid
#
#    NOT automatically:
#       Perennial + Graminoid
#            -> PBG
#
# 4. Explicit PBG therefore has precedence over the USDA
#    PerennialGraminoid fallback.
#
# 5. USDA nativity is encoded as:
#       N = Native
#       I = Introduced
#
# 6. Missing USDA traits are distinguished from genuinely
#    unresolved plant identity.
#
# 7. Raw dictionary taxonomy/provenance is preserved.
#
#
# EXPECTED INPUTS
# ---------------
# dictionary
# USDA_ATTRIBUTE_CACHE
#
#
# OUTPUTS
# -------
# dictionary_fg
#
# Important new columns:
#   USDA_duration
#   USDA_growth_habit
#   USDA_native_status_L48
#   USDA_trait_status
#   USDA_derived_group
#   resolved_plant_group
#   MOSAIC_FG
#   FG_resolution_source
#
# QA objects:
#   fg_summary
#   plant_fg_summary
#   trait_recovery_targets
#   ambiguous_fg
# ============================================================

import pandas as pd
import numpy as np


# ============================================================
# 0. LOAD USDA ECOLOGICAL ATTRIBUTE CACHE
# ============================================================

usda_attributes = pd.read_csv(
    USDA_ATTRIBUTE_CACHE,
    dtype="string",
    low_memory=False,
)

print(
    f"Loaded USDA ecological attribute cache: "
    f"{len(usda_attributes):,} rows"
)


# ============================================================
# 1. NORMALIZE USDA CACHE COLUMN NAMES
#
# Handles both older and current cache schemas.
# ============================================================

usda_attributes = usda_attributes.copy()

column_aliases = {
    # accepted symbol
    "accepted_symbol": "USDA_accepted_symbol",
    "Symbol": "USDA_accepted_symbol",

    # duration
    "USDA_duration_api": "USDA_duration",
    "duration": "USDA_duration",
    "Duration": "USDA_duration",

    # growth habit
    "USDA_growth_habit_api": "USDA_growth_habit",
    "growth_habit": "USDA_growth_habit",
    "GrowthHabit": "USDA_growth_habit",
    "Growth Habit": "USDA_growth_habit",

    # Lower-48 native status
    "USDA_L48_native_status_api": "USDA_native_status_L48",
    "native_status_l48": "USDA_native_status_L48",
    "NativeStatus_L48": "USDA_native_status_L48",
    "L48_native_status": "USDA_native_status_L48",
    "L48_status": "USDA_native_status_L48",
}

for old, new in column_aliases.items():
    if old in usda_attributes.columns and new not in usda_attributes.columns:
        usda_attributes = usda_attributes.rename(columns={old: new})

required_usda_columns = [
    "USDA_accepted_symbol",
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status_L48",
]

missing_usda_columns = [
    col
    for col in required_usda_columns
    if col not in usda_attributes.columns
]

if missing_usda_columns:
    raise ValueError(
        "USDA attribute cache is missing required columns:\n"
        + "\n".join(missing_usda_columns)
        + "\n\nAvailable columns:\n"
        + "\n".join(usda_attributes.columns.astype(str))
    )

print("USDA attribute columns normalized successfully.")
# ============================================================
# 2. CLEAN TEXT VALUES
# ============================================================

def clean_text(x):

    if pd.isna(x):
        return pd.NA

    x = str(x).strip()

    if x == "":
        return pd.NA

    if x.lower() in {
        "nan",
        "<na>",
        "none",
    }:
        return pd.NA

    return x


for col in required_usda_columns:

    usda_attributes[col] = (
        usda_attributes[col]
        .map(clean_text)
        .astype("string")
    )


# ============================================================
# 3. NORMALIZE LOWER-48 NATIVITY
#
# USDA API cache uses primarily:
#
#   N = Native
#   I = Introduced
#
# Convert these to explicit labels before FG classification.
#
# Multi-valued values remain multi-valued.
# ============================================================

def normalize_native_status(x):

    if pd.isna(x):
        return pd.NA

    raw_values = {
        value.strip()
        for value in str(x).split("|")
        if value.strip()
    }

    if not raw_values:
        return pd.NA

    normalized = set()

    for value in raw_values:

        value_upper = value.upper()

        if value_upper in {
            "N",
            "NATIVE",
        }:
            normalized.add("Native")

        elif value_upper in {
            "I",
            "INTRODUCED",
        }:
            normalized.add("Introduced")

        else:
            normalized.add(value)

    return "|".join(
        sorted(normalized)
    )


usda_attributes[
    "USDA_native_status_L48"
] = (
    usda_attributes[
        "USDA_native_status_L48"
    ]
    .map(normalize_native_status)
    .astype("string")
)


# ============================================================
# 4. BUILD ONE USDA TRAIT ROW PER ACCEPTED SYMBOL
# ============================================================

usda_fg_attributes = (
    usda_attributes[
        required_usda_columns
    ]
    .dropna(
        subset=["USDA_accepted_symbol"]
    )
    .copy()
)


# ------------------------------------------------------------
# Verify duplicated accepted symbols do not disagree.
# ------------------------------------------------------------

trait_conflicts = (
    usda_fg_attributes
    .groupby(
        "USDA_accepted_symbol",
        dropna=False,
    )
    .agg(
        n_duration=(
            "USDA_duration",
            lambda x: x.dropna().nunique()
        ),
        n_growth_habit=(
            "USDA_growth_habit",
            lambda x: x.dropna().nunique()
        ),
        n_native_status=(
            "USDA_native_status_L48",
            lambda x: x.dropna().nunique()
        ),
    )
    .reset_index()
)

trait_conflicts = trait_conflicts[
    (trait_conflicts["n_duration"] > 1)
    | (trait_conflicts["n_growth_habit"] > 1)
    | (trait_conflicts["n_native_status"] > 1)
]

if len(trait_conflicts) > 0:

    display(
        trait_conflicts.head(100)
    )

    raise ValueError(
        f"{len(trait_conflicts):,} USDA accepted symbols "
        "have conflicting ecological attributes."
    )


usda_fg_attributes = (
    usda_fg_attributes
    .drop_duplicates(
        subset=["USDA_accepted_symbol"]
    )
    .reset_index(drop=True)
)

print(
    f"Unique USDA accepted taxa available for join: "
    f"{len(usda_fg_attributes):,}"
)


# ============================================================
# 5. START FROM COMPLETED TAXONOMIC DICTIONARY
# ============================================================

dictionary_fg = dictionary.copy()


# ------------------------------------------------------------
# Remove outputs from an earlier run of this cell.
#
# Do NOT remove protocol_plant_group.
# That is precisely where explicit PBG or other known source
# functional information may already exist.
# ------------------------------------------------------------

stale_columns = [
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status_L48",
    "USDA_trait_status",
    "USDA_derived_group",
    "resolved_plant_group",
    "MOSAIC_FG",
    "FG_resolution_source",
]

dictionary_fg = dictionary_fg.drop(
    columns=[
        col
        for col in stale_columns
        if col in dictionary_fg.columns
    ],
    errors="ignore",
)


# ============================================================
# 6. JOIN USDA ECOLOGICAL ATTRIBUTES
# ============================================================

dictionary_fg = dictionary_fg.merge(
    usda_fg_attributes,
    on="USDA_accepted_symbol",
    how="left",
    validate="m:1",
)

print(
    f"Dictionary rows after USDA join: "
    f"{len(dictionary_fg):,}"
)


# ============================================================
# 7. TRAIT SET HELPER
#
# Examples:
#
#   Annual
#       -> {"Annual"}
#
#   Annual|Perennial
#       -> {"Annual", "Perennial"}
#
#   <NA>
#       -> set()
# ============================================================

def trait_set(x):

    if pd.isna(x):
        return set()

    return {
        value.strip()
        for value in str(x).split("|")
        if value.strip()
    }


# ============================================================
# 8. USDA TRAIT COMPLETENESS STATUS
#
# Important distinction:
#
#   No_USDA_taxon
#       taxonomy itself was not USDA-resolved
#
#   Missing_traits
#       USDA taxonomy exists, but ecological attribute
#       retrieval is incomplete
#
# These should NOT be treated as equivalent.
# ============================================================

def derive_trait_status(row):

    accepted = row[
        "USDA_accepted_symbol"
    ]

    if pd.isna(accepted):
        return "No_USDA_taxon"

    duration = pd.notna(
        row["USDA_duration"]
    )

    habit = pd.notna(
        row["USDA_growth_habit"]
    )

    native = pd.notna(
        row["USDA_native_status_L48"]
    )

    if (
        duration
        and habit
        and native
    ):
        return "Complete"

    missing_parts = []

    if not duration:
        missing_parts.append("duration")

    if not habit:
        missing_parts.append("growth_habit")

    if not native:
        missing_parts.append("nativity")

    return (
        "Missing_"
        + "_".join(missing_parts)
    )


dictionary_fg[
    "USDA_trait_status"
] = dictionary_fg.apply(
    derive_trait_status,
    axis=1,
)


# ============================================================
# 9. DERIVE STRUCTURAL/LIFE-HISTORY GROUP FROM USDA
#
# CONSERVATIVE RULE:
#
#   Perennial + Graminoid
#       -> PerennialGraminoid
#
# It does NOT become PBG here.
#
# Explicit PBG, if already present in protocol_plant_group,
# will be preserved later.
# ============================================================

def derive_usda_group(row):

    code_class = row[
        "code_class"
    ]

    # --------------------------------------------------------
    # NA-safe plant check
    # --------------------------------------------------------

    if pd.isna(code_class):
        return pd.NA

    if code_class != "Plant":
        return pd.NA


    duration = trait_set(
        row["USDA_duration"]
    )

    habit = trait_set(
        row["USDA_growth_habit"]
    )


    # --------------------------------------------------------
    # Cannot infer structural group without habit.
    # --------------------------------------------------------

    if not habit:
        return pd.NA


    # ========================================================
    # GRAMINOIDS
    # ========================================================

    if habit == {"Graminoid"}:

        if duration == {"Annual"}:
            return "AnnualGraminoid"

        if duration == {"Perennial"}:
            return "PerennialGraminoid"

        # Duration ambiguous or absent, but graminoid
        # structure itself is known.
        return "Graminoid"


    # ========================================================
    # FORBS / HERBS
    # ========================================================

    forb_terms = {
        "Forb/herb",
        "Forb",
        "Herb",
    }

    if habit.issubset(
        forb_terms
    ):

        if duration == {"Annual"}:
            return "AnnualForb"

        if duration == {"Perennial"}:
            return "PerennialForb"

        return "Forb"


    # ========================================================
    # SHRUB
    # ========================================================

    if habit == {"Shrub"}:
        return "Shrub"


    # ========================================================
    # SUBSHRUB
    # ========================================================

    if habit == {"Subshrub"}:
        return "Subshrub"


    # ========================================================
    # SHRUB / SUBSHRUB
    #
    # Both remain within shrub-domain vegetation for the
    # current broad MOSAIC FG representation.
    # ========================================================

    if habit and habit.issubset(
        {
            "Shrub",
            "Subshrub",
        }
    ):
        return "Shrub"


    # ========================================================
    # TREE
    # ========================================================

    if habit == {"Tree"}:
        return "Tree"


    # ========================================================
    # SHRUB / TREE
    #
    # Preserve ambiguity rather than arbitrarily selecting one.
    # ========================================================

    if habit and habit.issubset(
        {
            "Shrub",
            "Tree",
        }
    ):
        return "Woody"


    # ========================================================
    # FORB / SUBSHRUB
    # ========================================================

    if habit and habit.issubset(
        {
            "Forb/herb",
            "Forb",
            "Herb",
            "Subshrub",
        }
    ):
        return "SubshrubOrForb"


    # ========================================================
    # More complex combinations stay unresolved.
    # ========================================================

    return pd.NA


dictionary_fg[
    "USDA_derived_group"
] = dictionary_fg.apply(
    derive_usda_group,
    axis=1,
)


# ============================================================
# 10. RESOLVE SOURCE + USDA FUNCTIONAL INFORMATION
#
# PRECEDENCE
# ----------
#
#   explicit protocol/project functional group
#                >
#   USDA-derived group
#
#
# Therefore:
#
# protocol_plant_group = PBG
# USDA_derived_group   = PerennialGraminoid
#
# resolves to:
#
#   PBG
#
#
# But:
#
# protocol_plant_group = NA
# USDA_derived_group   = PerennialGraminoid
#
# resolves to:
#
#   PerennialGraminoid
#
# This is the intended asymmetry.
# ============================================================

dictionary_fg[
    "resolved_plant_group"
] = (
    dictionary_fg[
        "protocol_plant_group"
    ]
    .combine_first(
        dictionary_fg[
            "USDA_derived_group"
        ]
    )
)


# ============================================================
# 11. FINAL MOSAIC FUNCTIONAL GROUP
#
# Current working crosswalk:
#
#   PBG                         -> PBG
#
#   AnnualGraminoid + I         -> EAG
#   AnnualGraminoid + N         -> NAG
#
#   PerennialGraminoid          -> PerennialGraminoid
#
#   AnnualForb                  -> AF
#   PerennialForb               -> PF
#
#   Shrub                       -> SHR
#   Subshrub                    -> SUBSHR
#   Tree                        -> TREE
#
# USDA-resolved taxa missing traits are explicitly marked
# TraitUnresolvedPlant rather than collapsed into UnknownPlant.
# ============================================================

def derive_mosaic_fg(row):

    code_class = row[
        "code_class"
    ]

    # --------------------------------------------------------
    # NA-safe plant check
    # --------------------------------------------------------

    if pd.isna(code_class):
        return pd.NA

    if code_class != "Plant":
        return pd.NA


    group = row[
        "resolved_plant_group"
    ]

    native = trait_set(
        row[
            "USDA_native_status_L48"
        ]
    )


    # ========================================================
    # PLANT WITH NO RESOLVED FUNCTIONAL GROUP
    # ========================================================

    if pd.isna(group):

        # Taxonomy is known, traits are incomplete.
        if pd.notna(
            row["USDA_accepted_symbol"]
        ):
            return "TraitUnresolvedPlant"

        # Taxonomy itself is unresolved.
        return "UnknownPlant"


    # ========================================================
    # PRESERVE KNOWN PBG
    # ========================================================

    if group == "PBG":
        return "PBG"


    # Also tolerate expanded source labels if any occur.
    if group in {
        "PerennialBunchgrass",
        "Perennial bunchgrass",
    }:
        return "PBG"


    # ========================================================
    # ANNUAL GRAMINOIDS
    # ========================================================

    if group == "AnnualGraminoid":

        if native == {"Introduced"}:
            return "EAG"

        if native == {"Native"}:
            return "NAG"

        return "AnnualGraminoid_UnknownNativity"


    # ========================================================
    # PERENNIAL GRAMINOIDS
    #
    # IMPORTANT:
    # these remain PerennialGraminoid unless independently
    # identified as PBG above.
    # ========================================================

    if group == "PerennialGraminoid":
        return "PerennialGraminoid"


    if group == "Graminoid":
        return "Graminoid"


    # ========================================================
    # FORBS
    # ========================================================

    if group == "AnnualForb":
        return "AF"

    if group == "PerennialForb":
        return "PF"

    if group == "Forb":
        return "Forb"


    # ========================================================
    # SHRUB / WOODY
    # ========================================================

    if group == "Shrub":
        return "SHR"

    if group == "Subshrub":
        return "SUBSHR"

    if group == "Tree":
        return "TREE"

    if group == "Woody":
        return "Woody"


    # ========================================================
    # EXISTING BROAD SOURCE CLASSES
    # ========================================================

    if group == "SubshrubOrPerennialForb":
        return "SubshrubOrPF"

    if group == "SubshrubOrForb":
        return "SubshrubOrForb"

    if group == "AnnualPlant":
        return "AnnualPlant"

    if group == "UnknownPlant":
        return "UnknownPlant"


    # ========================================================
    # Preserve any unanticipated explicit project/source group.
    #
    # Do not silently destroy information.
    # ========================================================

    return group


dictionary_fg[
    "MOSAIC_FG"
] = dictionary_fg.apply(
    derive_mosaic_fg,
    axis=1,
)


# ============================================================
# 12. FUNCTIONAL-GROUP PROVENANCE
# ============================================================

dictionary_fg[
    "FG_resolution_source"
] = pd.NA


# ------------------------------------------------------------
# Explicit source/project group
# ------------------------------------------------------------

source_group_mask = (
    dictionary_fg[
        "protocol_plant_group"
    ].notna()
)

dictionary_fg.loc[
    source_group_mask,
    "FG_resolution_source"
] = "protocol_or_project_group"


# ------------------------------------------------------------
# Specifically flag PBG provenance
# ------------------------------------------------------------

pbg_source_mask = (
    dictionary_fg[
        "protocol_plant_group"
    ].isin(
        {
            "PBG",
            "PerennialBunchgrass",
            "Perennial bunchgrass",
        }
    )
)

dictionary_fg.loc[
    pbg_source_mask,
    "FG_resolution_source"
] = "explicit_PBG_source"


# ------------------------------------------------------------
# USDA traits supplied the functional group
# ------------------------------------------------------------

usda_group_mask = (
    dictionary_fg[
        "protocol_plant_group"
    ].isna()
    & dictionary_fg[
        "USDA_derived_group"
    ].notna()
)

dictionary_fg.loc[
    usda_group_mask,
    "FG_resolution_source"
] = "USDA_traits"


# ------------------------------------------------------------
# USDA taxonomy exists, but traits are incomplete
# ------------------------------------------------------------

trait_unresolved_mask = (
    dictionary_fg[
        "code_class"
    ].eq("Plant")
    & dictionary_fg[
        "USDA_accepted_symbol"
    ].notna()
    & dictionary_fg[
        "resolved_plant_group"
    ].isna()
)

dictionary_fg.loc[
    trait_unresolved_mask,
    "FG_resolution_source"
] = "USDA_taxon_missing_traits"


# ------------------------------------------------------------
# Plant identity/function genuinely unresolved
# ------------------------------------------------------------

unknown_plant_mask = (
    dictionary_fg[
        "code_class"
    ].eq("Plant")
    & dictionary_fg[
        "USDA_accepted_symbol"
    ].isna()
    & dictionary_fg[
        "resolved_plant_group"
    ].isna()
)

dictionary_fg.loc[
    unknown_plant_mask,
    "FG_resolution_source"
] = "unresolved_plant_group"


# ============================================================
# 13. QA — BRTE
#
# Should now be:
#
#   Annual
#   Graminoid
#   Introduced
#   AnnualGraminoid
#   EAG
# ============================================================

print()
print("=" * 90)
print("BRTE QA")
print("=" * 90)

qa_columns = [
    "observed_code",
    "n_records",
    "USDA_accepted_symbol",
    "USDA_scientific_name",
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status_L48",
    "protocol_plant_group",
    "USDA_derived_group",
    "resolved_plant_group",
    "MOSAIC_FG",
    "FG_resolution_source",
]

qa_columns = [
    col
    for col in qa_columns
    if col in dictionary_fg.columns
]

display(
    dictionary_fg.loc[
        dictionary_fg[
            "observed_code"
        ].eq("BRTE"),
        qa_columns,
    ]
)


# ============================================================
# 14. QA — EXISTING PBG
#
# Verify no known PBG was degraded to PerennialGraminoid.
# ============================================================

print()
print("=" * 90)
print("EXPLICIT PBG PRESERVATION QA")
print("=" * 90)

pbg_qa = (
    dictionary_fg.loc[
        dictionary_fg[
            "protocol_plant_group"
        ].isin(
            {
                "PBG",
                "PerennialBunchgrass",
                "Perennial bunchgrass",
            }
        )
    ]
    .copy()
)

print(
    f"Explicit PBG codes found: "
    f"{len(pbg_qa):,}"
)

if len(pbg_qa) > 0:

    print(
        f"Records represented: "
        f"{pbg_qa['n_records'].sum():,}"
    )

    display(
        pbg_qa[
            qa_columns
        ]
        .sort_values(
            "n_records",
            ascending=False,
        )
        .head(100)
    )

    bad_pbg = (
        pbg_qa[
            "MOSAIC_FG"
        ] != "PBG"
    )

    if bad_pbg.any():

        raise ValueError(
            "At least one explicitly identified PBG was "
            "not preserved as MOSAIC_FG='PBG'."
        )

    print(
        "PASS: all explicit PBG classifications were preserved."
    )

else:

    print(
        "No explicit PBG values currently occur in "
        "protocol_plant_group."
    )


# ============================================================
# 15. QA — USDA PERENNIAL GRAMINOID FALLBACK
#
# These should remain PerennialGraminoid unless source data
# independently identified them as PBG.
# ============================================================

print()
print("=" * 90)
print("PERENNIAL GRAMINOID FALLBACK QA")
print("=" * 90)

perennial_graminoid_qa = (
    dictionary_fg.loc[
        dictionary_fg[
            "MOSAIC_FG"
        ].eq("PerennialGraminoid")
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
)

print(
    f"PerennialGraminoid codes: "
    f"{len(perennial_graminoid_qa):,}"
)

print(
    f"Records represented: "
    f"{perennial_graminoid_qa['n_records'].sum():,}"
)

display(
    perennial_graminoid_qa[
        qa_columns
    ].head(50)
)


# ============================================================
# 16. QA — BAPR VARIANTS
#
# Preserve whatever manually reviewed protocol/project group
# has already been assigned upstream.
#
# This cell DOES NOT overwrite the user's existing BAPR
# functional decision.
# ============================================================

print()
print("=" * 90)
print("BAPR VARIANT QA")
print("=" * 90)

display(
    dictionary_fg.loc[
        dictionary_fg[
            "observed_code"
        ].isin(
            [
                "BAPR",
                "BAPRV",
                "BAPRG",
            ]
        ),
        qa_columns,
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
)


# ============================================================
# 17. TRAIT RECOVERY TARGETS
#
# These are USDA-resolved plant taxa for which the cached
# ecological attributes are incomplete.
#
# Sort by record weight so recovery effort targets the taxa
# that matter most to the national dataset.
# ============================================================

trait_recovery_targets = (
    dictionary_fg.loc[
        dictionary_fg[
            "code_class"
        ].eq("Plant")
        & dictionary_fg[
            "USDA_accepted_symbol"
        ].notna()
        & (
            dictionary_fg[
                "USDA_duration"
            ].isna()
            | dictionary_fg[
                "USDA_growth_habit"
            ].isna()
            | dictionary_fg[
                "USDA_native_status_L48"
            ].isna()
        )
    ]
    .copy()
)

trait_recovery_targets = (
    trait_recovery_targets
    .sort_values(
        "n_records",
        ascending=False,
    )
    .reset_index(drop=True)
)


print()
print("=" * 90)
print("USDA TRAIT RECOVERY TARGETS")
print("=" * 90)

print(
    f"Dictionary codes requiring >=1 USDA trait: "
    f"{len(trait_recovery_targets):,}"
)

print(
    f"Records represented: "
    f"{trait_recovery_targets['n_records'].sum():,}"
)

recovery_columns = [
    "observed_code",
    "n_records",
    "n_plot_visits",
    "USDA_accepted_symbol",
    "USDA_scientific_name",
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status_L48",
    "USDA_trait_status",
    "protocol_plant_group",
    "MOSAIC_FG",
    "FG_resolution_source",
]

recovery_columns = [
    col
    for col in recovery_columns
    if col in trait_recovery_targets.columns
]

display(
    trait_recovery_targets[
        recovery_columns
    ].head(100)
)


# ============================================================
# 18. UNIQUE USDA TAXA REQUIRING TRAIT RECOVERY
#
# This is the actual lookup target list.
# ============================================================

trait_recovery_taxa = (
    trait_recovery_targets[
        [
            "USDA_accepted_symbol",
            "USDA_scientific_name",
        ]
    ]
    .drop_duplicates()
    .sort_values(
        "USDA_accepted_symbol"
    )
    .reset_index(drop=True)
)

print(
    f"\nUnique USDA taxa requiring supplemental trait lookup: "
    f"{len(trait_recovery_taxa):,}"
)


# ============================================================
# 19. FUNCTIONAL-GROUP SUMMARY — ALL DICTIONARY RECORDS
# ============================================================

N_TOTAL_RECORDS = int(
    dictionary_fg[
        "n_records"
    ].sum()
)

fg_summary = (
    dictionary_fg
    .assign(
        MOSAIC_FG_display=(
            dictionary_fg[
                "MOSAIC_FG"
            ]
            .astype("string")
            .fillna("<NONPLANT_OR_UNCLASSIFIED>")
        )
    )
    .groupby(
        "MOSAIC_FG_display",
        dropna=False,
    )
    .agg(
        n_codes=(
            "observed_code",
            "size",
        ),
        n_records=(
            "n_records",
            "sum",
        ),
    )
    .reset_index()
)

fg_summary[
    "codes_pct"
] = (
    100
    * fg_summary["n_codes"]
    / len(dictionary_fg)
)

fg_summary[
    "records_pct"
] = (
    100
    * fg_summary["n_records"]
    / N_TOTAL_RECORDS
)

fg_summary = (
    fg_summary
    .sort_values(
        "n_records",
        ascending=False,
    )
    .reset_index(drop=True)
)

print()
print("=" * 90)
print("MOSAIC FUNCTIONAL-GROUP SUMMARY — ALL RECORDS")
print("=" * 90)

display(
    fg_summary.style.format(
        {
            "codes_pct": "{:.2f}",
            "records_pct": "{:.4f}",
        }
    )
)


# ============================================================
# 20. PLANT-ONLY FUNCTIONAL-GROUP SUMMARY
# ============================================================

plant_fg = (
    dictionary_fg.loc[
        dictionary_fg[
            "code_class"
        ].eq("Plant")
    ]
    .copy()
)

N_PLANT_RECORDS = int(
    plant_fg[
        "n_records"
    ].sum()
)

plant_fg_summary = (
    plant_fg
    .assign(
        MOSAIC_FG_display=(
            plant_fg[
                "MOSAIC_FG"
            ]
            .astype("string")
            .fillna("<UNRESOLVED>")
        )
    )
    .groupby(
        "MOSAIC_FG_display",
        dropna=False,
    )
    .agg(
        n_codes=(
            "observed_code",
            "size",
        ),
        n_records=(
            "n_records",
            "sum",
        ),
    )
    .reset_index()
)

plant_fg_summary[
    "plant_codes_pct"
] = (
    100
    * plant_fg_summary["n_codes"]
    / len(plant_fg)
)

plant_fg_summary[
    "plant_records_pct"
] = (
    100
    * plant_fg_summary["n_records"]
    / N_PLANT_RECORDS
)

plant_fg_summary = (
    plant_fg_summary
    .sort_values(
        "n_records",
        ascending=False,
    )
    .reset_index(drop=True)
)

print()
print("=" * 90)
print("PLANT-ONLY FUNCTIONAL-GROUP SUMMARY")
print("=" * 90)

display(
    plant_fg_summary.style.format(
        {
            "plant_codes_pct": "{:.2f}",
            "plant_records_pct": "{:.4f}",
        }
    )
)


# ============================================================
# 21. FUNCTIONAL-GROUP PROVENANCE SUMMARY
# ============================================================

fg_source_summary = (
    plant_fg
    .assign(
        FG_source_display=(
            plant_fg[
                "FG_resolution_source"
            ]
            .astype("string")
            .fillna("<UNRESOLVED>")
        )
    )
    .groupby(
        "FG_source_display",
        dropna=False,
    )
    .agg(
        n_codes=(
            "observed_code",
            "size",
        ),
        n_records=(
            "n_records",
            "sum",
        ),
    )
    .reset_index()
)

fg_source_summary[
    "plant_records_pct"
] = (
    100
    * fg_source_summary["n_records"]
    / N_PLANT_RECORDS
)

fg_source_summary = (
    fg_source_summary
    .sort_values(
        "n_records",
        ascending=False,
    )
    .reset_index(drop=True)
)

print()
print("=" * 90)
print("FUNCTIONAL-GROUP RESOLUTION SOURCE")
print("=" * 90)

display(
    fg_source_summary.style.format(
        {
            "plant_records_pct": "{:.4f}",
        }
    )
)


# ============================================================
# 22. AMBIGUOUS BUT INFORMATIVE GROUPS
#
# These are intentionally not forced into narrower classes.
# ============================================================

ambiguous_groups = {
    "Graminoid",
    "Forb",
    "Woody",
    "SubshrubOrForb",
    "SubshrubOrPF",
    "AnnualPlant",
    "AnnualGraminoid_UnknownNativity",
    "TraitUnresolvedPlant",
}

ambiguous_fg = (
    dictionary_fg.loc[
        dictionary_fg[
            "MOSAIC_FG"
        ].isin(
            ambiguous_groups
        )
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
    .reset_index(drop=True)
)

print()
print("=" * 90)
print("AMBIGUOUS / TRAIT-INCOMPLETE FUNCTIONAL GROUPS")
print("=" * 90)

print(
    f"Codes:   "
    f"{len(ambiguous_fg):,}"
)

print(
    f"Records: "
    f"{ambiguous_fg['n_records'].sum():,}"
)

display(
    ambiguous_fg[
        [
            col
            for col in [
                "observed_code",
                "n_records",
                "USDA_accepted_symbol",
                "USDA_scientific_name",
                "USDA_duration",
                "USDA_growth_habit",
                "USDA_native_status_L48",
                "USDA_trait_status",
                "protocol_plant_group",
                "USDA_derived_group",
                "resolved_plant_group",
                "MOSAIC_FG",
                "FG_resolution_source",
            ]
            if col in ambiguous_fg.columns
        ]
    ].head(100)
)


# ============================================================
# 23. TRUE UNKNOWN PLANTS
#
# These lack both a resolved source group and usable USDA
# taxonomy/traits.
# ============================================================

unknown_plants = (
    dictionary_fg.loc[
        dictionary_fg[
            "code_class"
        ].eq("Plant")
        & dictionary_fg[
            "MOSAIC_FG"
        ].eq("UnknownPlant")
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
    .reset_index(drop=True)
)

print()
print("=" * 90)
print("TRUE UNKNOWN PLANTS")
print("=" * 90)

print(
    f"UnknownPlant codes: "
    f"{len(unknown_plants):,}"
)

print(
    f"Records represented: "
    f"{unknown_plants['n_records'].sum():,}"
)


# ============================================================
# 24. FINAL PBG/PERENNIAL-GRAMINOID AUDIT
# ============================================================

n_pbg_codes = int(
    plant_fg[
        "MOSAIC_FG"
    ].eq("PBG").sum()
)

n_pbg_records = int(
    plant_fg.loc[
        plant_fg[
            "MOSAIC_FG"
        ].eq("PBG"),
        "n_records",
    ].sum()
)

n_pg_codes = int(
    plant_fg[
        "MOSAIC_FG"
    ].eq(
        "PerennialGraminoid"
    ).sum()
)

n_pg_records = int(
    plant_fg.loc[
        plant_fg[
            "MOSAIC_FG"
        ].eq(
            "PerennialGraminoid"
        ),
        "n_records",
    ].sum()
)

print()
print("=" * 90)
print("PBG / PERENNIAL GRAMINOID AUDIT")
print("=" * 90)

print(
    f"Explicit PBG:             "
    f"{n_pbg_codes:,} codes | "
    f"{n_pbg_records:,} records"
)

print(
    f"PerennialGraminoid:       "
    f"{n_pg_codes:,} codes | "
    f"{n_pg_records:,} records"
)

print()
print(
    "Interpretation:"
)

print(
    "  PBG = bunchgrass identity already known from an "
    "explicit source/project classification."
)

print(
    "  PerennialGraminoid = perennial graminoid supported "
    "by available information, but bunchgrass architecture "
    "has not yet been independently established."
)


# ============================================================
# 25. FINAL COVERAGE AUDIT
# ============================================================

resolved_mask = (
    plant_fg[
        "MOSAIC_FG"
    ].notna()
)

n_resolved_codes = int(
    resolved_mask.sum()
)

n_resolved_records = int(
    plant_fg.loc[
        resolved_mask,
        "n_records",
    ].sum()
)

print()
print("=" * 90)
print("FINAL FUNCTIONAL-GROUP COVERAGE AUDIT")
print("=" * 90)

print(
    f"Plant codes with MOSAIC_FG:    "
    f"{n_resolved_codes:,} / {len(plant_fg):,} "
    f"({100*n_resolved_codes/len(plant_fg):.2f}%)"
)

print(
    f"Plant records with MOSAIC_FG:  "
    f"{n_resolved_records:,} / {N_PLANT_RECORDS:,} "
    f"({100*n_resolved_records/N_PLANT_RECORDS:.5f}%)"
)

print(
    f"Plant records lacking any FG:  "
    f"{N_PLANT_RECORDS - n_resolved_records:,}"
)

print("=" * 90)

Loaded USDA ecological attribute cache: 7,268 rows
USDA attribute columns normalized successfully.
Unique USDA accepted taxa available for join: 7,267
Dictionary rows after USDA join: 10,960

==========================================================================================
BRTE QA
==========================================================================================

,observed_code,n_records,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,protocol_plant_group,USDA_derived_group,resolved_plant_group,MOSAIC_FG,FG_resolution_source
5,BRTE,429816,BRTE,Bromus tectorum L.,Annual,Graminoid,Introduced,<NA>,AnnualGraminoid,AnnualGraminoid,EAG,USDA_traits

==========================================================================================
EXPLICIT PBG PRESERVATION QA
==========================================================================================
Explicit PBG codes found: 0
No explicit PBG values currently occur in protocol_plant_group.

==========================================================================================
PERENNIAL GRAMINOID FALLBACK QA
==========================================================================================
PerennialGraminoid codes: 1,492
Records represented: 2,267,084

,observed_code,n_records,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,protocol_plant_group,USDA_derived_group,resolved_plant_group,MOSAIC_FG,FG_resolution_source
4,POSE,332740,POSE,Poa secunda J. Presl,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
10,PSSP6,163393,PSSP6,Pseudoroegneria spicata (Pursh) Á. Löve,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
16,BOGR2,159606,BOGR2,Bouteloua gracilis (Willd. ex Kunth) Lag. ex G...,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
17,PASM,136002,PASM,Pascopyrum smithii (Rydb.) Á. Löve,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
29,POPR,115614,POPR,Poa pratensis L.,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
31,AGCR,86637,AGCR,Agropyron cristatum (L.) Gaertn.,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
19,HECO26,80033,HECO26,Hesperostipa comata (Trin. & Rupr.) Barkworth,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
34,FEID,78604,FEID,Festuca idahoensis Elmer,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
75,Perennial grasses,61012,<NA>,<NA>,<NA>,<NA>,<NA>,PerennialGraminoid,NaN,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group
9,ELEL5,58454,ELEL5,Elymus elymoides (Raf.) Swezey,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
63,BRIN2,56601,BRIN2,Bromus inermis Leyss.,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
109,SCAR7,46213,SCAR7,"Schedonorus arundinaceus (Schreb.) Dumort., no...",Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
39,CAFI,45000,CAFI,Carex filifolia Nutt.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
23,KOMA,41066,KOMA,Koeleria macrantha (Ledeb.) Schult.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
68,SCSC,36095,SCSC,Schizachyrium scoparium (Michx.) Nash,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
56,BOCU,30568,BOCU,Bouteloua curtipendula (Michx.) Torr.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
139,CYDA,30196,CYDA,Cynodon dactylon (L.) Pers.,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
20,ACHY,28467,ACHY,Achnatherum hymenoides (Roem. & Schult.) Barkw...,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
59,ELLA3,26155,ELLA3,Elymus lanceolatus (Scribn. & J.G. Sm.) Gould,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
79,POBU,24009,POBU,Poa bulbosa L.,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
158,PLMU3,21959,PLMU3,Pleuraphis mutica Buckley,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
49,SPCR,21750,SPCR,Sporobolus cryptandrus (Torr.) A. Gray,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
145,SPAI,20780,SPAI,Sporobolus airoides (Torr.) Torr.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
46,ACTH7,18668,ACTH7,Achnatherum thurberianum (Piper) Barkworth,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
66,PLJA,18650,PLJA,Pleuraphis jamesii Torr.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
98,BODA2,18358,BODA2,Bouteloua dactyloides (Nutt.) J.T. Columbus,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
54,NAVI4,18240,NAVI4,Nassella viridula (Trin.) Barkworth,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
134,BOER4,16382,BOER4,Bouteloua eriopoda (Torr.) Torr.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
247,PANO2,15997,PANO2,Paspalum notatum Flueggé,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
121,ANGE,15510,ANGE,Andropogon gerardii Vitman,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
97,CALO,13408,CALO,Calamovilfa longifolia (Hook.) Scribn.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
258,BOIS,11541,BOIS,Bothriochloa ischaemum (L.) Keng,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
136,THIN6,11462,THIN6,Thinopyrum intermedium (Host) Barkworth & D.R....,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
77,LECI4,11054,LECI4,Leymus cinereus (Scribn. & Merr.) Á. Löve,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
150,DISP,10944,DISP,Distichlis spicata (L.) Greene,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
1354,HECOC8,10401,HECOC8,Hesperostipa comata (Trin. & Rupr.) Barkworth ...,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
170,CAGE2,10359,CAGE2,Carex geyeri Boott,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
99,POFE,9967,POFE,Poa fendleriana (Steud.) Vasey,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
135,MUPO2,8399,MUPO2,Muhlenbergia porteri Scribn. ex Beal,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
174,DAGL,8128,DAGL,Dactylis glomerata L.,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
153,SPCO16,8117,SPCO16,Sporobolus compositus (Poir.) Merr.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
236,NALE3,8109,NALE3,Nassella leucotricha (Trin. & Rupr.) Pohl,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
178,BOHI2,7567,BOHI2,Bouteloua hirsuta Lag.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
127,CADU6,7237,CADU6,Carex duriuscula C.A. Mey.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
149,PAVI2,7218,PAVI2,Panicum virgatum L.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
133,ELTR7,7178,ELTR7,Elymus trachycaulus (Link) Gould ex Shinners,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
356,ERLE,6718,ERLE,Eragrostis lehmanniana Nees,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
202,PHPR3,6653,PHPR3,Phleum pratense L.,Perennial,Graminoid,Introduced,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
343,PHAR3,6339,PHAR3,Phalaris arundinacea L.,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits
162,CAIN9,5735,CAIN9,Carex inops L.H. Bailey,Perennial,Graminoid,Native,<NA>,PerennialGraminoid,PerennialGraminoid,PerennialGraminoid,USDA_traits

==========================================================================================
BAPR VARIANT QA
==========================================================================================

,observed_code,n_records,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,protocol_plant_group,USDA_derived_group,resolved_plant_group,MOSAIC_FG,FG_resolution_source
4193,BAPRV,14,BAPR,Barleria prionitis L.,Perennial,Shrub,<NA>,Forb,Shrub,Forb,Forb,protocol_or_project_group
5664,BAPRG,4,<NA>,<NA>,<NA>,<NA>,<NA>,Forb,NaN,Forb,NaN,protocol_or_project_group

==========================================================================================
USDA TRAIT RECOVERY TARGETS
==========================================================================================
Dictionary codes requiring >=1 USDA trait: 462
Records represented: 25,622

,observed_code,n_records,n_plot_visits,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,USDA_trait_status,protocol_plant_group,MOSAIC_FG,FG_resolution_source
0,BOSA,2126,255,BOSA,Bothriochloa saccharoides (Sw.) Rydb.,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
1,CALU2,1291,56,CALU2,Carex lugens T. Holm,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
2,LEPAD,1266,74,LEPAD,Ledum palustre L. ssp. decumbens (Aiton) Hultén,Perennial,Shrub,<NA>,Missing_nativity,<NA>,SHR,USDA_traits
3,HYSP70,1025,86,HYSP70,Hylocomium splendens (Hedw.) Schimp.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
4,BENAE,940,66,BENAE,Betula nana L. ssp. exilis (Sukaczev) Hultén,Perennial,Shrub|Subshrub,<NA>,Missing_nativity,<NA>,SHR,USDA_traits
5,SPHAG2,884,44,SPHAG2,Sphagnum L.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
6,DICR3,753,61,DICR3,Digitaria cruciata (Nees ex Steud.) A. Camus,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
7,SCSC70,649,32,SCSC70,Scorpidium scorpioides (Hedw.) Limpr.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
8,SARI4,626,23,SARI4,Salix richardsonii Hook.,Perennial,Shrub|Tree,<NA>,Missing_nativity,<NA>,Woody,USDA_traits
9,SAPU15,615,74,SAPU15,Salix pulchra Cham.,Perennial,Shrub|Subshrub|Tree,<NA>,Missing_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
10,TONI70,589,62,TONI70,Tomentypnum nitens (Hedw.) Loeske,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
11,BENE4,541,23,BENE4,Betula neoalaskana Sarg.,Perennial,Shrub|Tree,<NA>,Missing_nativity,<NA>,Woody,USDA_traits
12,PUTR,512,53,PUAN,Puccinellia andersonii Swallen,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
13,LIRE13,484,40,LIRE13,Limprichtia revolvens (Sw.) Loeske,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
14,AUTU70,427,73,AUTU70,Aulacomnium turgidum (Wahlenb.) Schwägr.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
15,PLSC70,426,38,PLSC70,Pleurozium schreberi (Brid.) Mitt.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
16,NONE,398,13,NONE,Notholaena neglecta Maxon,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
17,FLCU,374,75,FLCU,Flavocetraria cucullata (Bellardi) Karnefelt &...,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
18,CATET,325,33,CATET,Cassiope tetragona (L.) D. Don var. tetragona,Perennial,Shrub|Subshrub,<NA>,Missing_nativity,<NA>,SHR,USDA_traits
19,CARO7,320,34,CARO7,Carex rotundata Wahlenb.,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
20,CAMI4,309,10,CAMI4,Carex microchaeta T. Holm,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
21,CLRA60,302,38,CLRA60,Cladina rangiferina (L.) Nyl.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
22,JUHA2,293,10,JUHA2,Juncus haenkei E. Mey.,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
23,CAST51,284,49,CAST51,Campylium stellatum (Hedw.) C.E.O. Jensen,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
24,SAAL,267,16,SAAL,Salix alaxensis (Andersson) Coville,Perennial,Shrub|Tree,<NA>,Missing_nativity,<NA>,Woody,USDA_traits
25,BRSA7,246,27,BRSA7,Brachythecium salebrosum (F. Weber & D. Mohr) ...,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
26,DICRA8,228,37,DICRA8,Dicranum Hedw.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
27,CHRYS16,220,22,CHRYS16,Chrysothemis Decne.,Perennial,Forb/herb,<NA>,Missing_nativity,<NA>,PF,USDA_traits
28,DIEL70,202,41,DIEL70,Dicranum elongatum Schleich. ex Schwägr.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
29,BLTR2,192,27,BLTR2,Blepharostoma trichophyllum (L.) Dumort.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
30,SAUN8,190,38,SAUN8,Sanionia uncinata (Hedw.) Loeske,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
31,ALBR12,190,26,ALBR12,Alopecurus brachystachus M. Bieb.,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
32,SARE2,189,51,SARE2,Salix reticulata L.,Perennial,Shrub|Subshrub,<NA>,Missing_nativity,<NA>,SHR,USDA_traits
33,RACA11,168,8,RACA11,Racomitrium canescens (Hedw.) Brid.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
34,STPA60,166,7,STPA60,Stereocaulon paschale (L.) Hoffm.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
35,PTCI,160,38,PTCI,Ptilidium ciliare (L.) Hampe,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
36,CEIS60,160,45,CEIS60,Cetraria islandica (L.) Ach.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
37,RHRU70,149,28,RHRU70,Rhytidium rugosum (Hedw.) Kindb.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
38,CLAR60,146,15,CLAR60,Cladina arbuscula (Wallr.) Hale & W.L. Culb.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
39,PEAP60,133,47,PEAP60,Peltigera aphthosa (L.) Willd.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
40,BRPS70,127,18,BRPS70,"Bryum pseudotriquetrum (Hedw.) G. Gaertn., B. ...",<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
41,THVE60,126,34,THVE60,Thamnolia vermicularis (Sw.) Ach. ex Schaerer,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
42,DIGR71,123,26,DIGR71,Dicranum groenlandicum Brid.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
43,ACSC2,122,29,VASC4,Vachellia schaffneri (S. Watson) Seigler & Ebi...,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
44,BRIN13,121,10,BRIN13,Bromus intermedius Guss.,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
45,POCO38,119,17,POCO38,Polytrichum commune Hedw.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
46,CLST5,118,15,CLST5,Cladina stygia (Fr.) Ahti,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
47,ARFA8,117,16,ARFA8,Arthrostylidium farctum (Aubl.) Soderstr. & Lo...,Perennial,Graminoid|Shrub|Vine,<NA>,Missing_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
48,ONWA70,116,29,ONWA70,Oncophorus wahlenbergii Brid.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
49,COSU4,115,5,COSU4,Cornus suecica L.,Perennial,Shrub|Subshrub,<NA>,Missing_nativity,<NA>,SHR,USDA_traits
50,DICA29,109,19,DICA29,Distichium capillaceum (Hedw.) Bruch & Schimp.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
51,CLMI60,109,19,CLMI60,Cladina mitis (Sandst.) Hustich,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
52,CELA60,106,21,CELA60,Cetraria laevigata Rass.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
53,POLYT5,102,23,POLYT5,Polytrichum Hedw.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
54,BRBI2,100,9,BRBI2,Bromus biebersteinii Roem. & Schult. [excluded],<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
55,BRRI7,99,9,BRRI7,Bromus riparius Rehmann,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
56,AUPA70,95,38,AUPA70,Aulacomnium palustre (Hedw.) Schwägr.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
57,HAVE70,86,11,HAVE70,Hamatocaulis vernicosus (Mitt.) Hedenäs,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
58,SPFU70,85,18,SPFU70,Sphagnum fuscum (Schimp.) Klinggr.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
59,THAMN3,82,15,THAMN3,Thamnolia Ach. ex Schaerer,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
60,STPU10,82,19,STPU10,Stipagrostis pungens (Desf.) De Winter,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
61,PYGR,81,33,PYGR,Pyrola grandiflora Radius,Perennial,Subshrub,<NA>,Missing_nativity,<NA>,SUBSHR,USDA_traits
62,POHY70,78,31,POHY70,Polytrichum hyperboreum R. Br.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
63,ELCO11,77,6,ELCO11,Eleocharis congesta D. Don,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
64,PRJU3,77,17,PRJU3,Prosopis juliflora (Sw.) DC.,Perennial,Shrub|Tree,<NA>,Missing_nativity,<NA>,Woody,USDA_traits
65,CLGR13,72,20,CLGR13,Cladonia gracilis (L.) Willd.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
66,PELTI2,69,14,PELTI2,Peltigera Willd.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
67,DIAC70,66,9,DIAC70,Dicranum acutifolium (Lindb. & Arnell) C.E.O. ...,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
68,POAL11,64,4,POAL11,Polygonum alpinum All.,Perennial,Forb/herb,<NA>,Missing_nativity,<NA>,PF,USDA_traits
69,ALAS2,64,32,ALAS2,Allium ascalonicum L.,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
70,LOBA70,63,6,LOBA70,Loeskypnum badium (Hartm.) Paul,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
71,CLADO3,62,37,CLADO3,Cladonia P. Browne,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
72,ARLAL6,61,20,ARLAL6,Arctagrostis latifolia (R. Br.) Griseb. ssp. l...,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
73,IPJA,61,10,IPJA,Ipomoea jaegeri Pilg.,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
74,LEPI2,60,15,LEPI2,Lepidium pinnatisectum (O.E. Schulz) C.L. Hitchc.,Annual,Forb/herb,<NA>,Missing_nativity,<NA>,AF,USDA_traits
75,SPLE5,54,5,SPLE5,Sphagnum lenense H. Lindb.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
76,SPWA70,53,24,SPWA70,Sphagnum warnstorfii Russow,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
77,AXSU2,53,3,AXSU2,Axonopus suffultus (J.C. Mikan ex Trin.) Parodi,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
78,ELOV,51,2,ELOV,Eleocharis ovata (Roth) Roem. & Schult.,Annual,Graminoid,<NA>,Missing_nativity,<NA>,AnnualGraminoid_UnknownNativity,USDA_traits
79,CASTI,51,22,CASTI,Castilla Cerv.,Perennial,Tree,<NA>,Missing_nativity,<NA>,TREE,USDA_traits
80,SAFU,51,18,SAFU,Salix fuscescens Andersson,Perennial,Shrub|Subshrub,<NA>,Missing_nativity,<NA>,SHR,USDA_traits
81,POJU70,50,12,POJU70,Polytrichum juniperinum Hedw.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
82,POST70,48,3,POST70,Polytrichum strictum Brid.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
83,DRAD2,48,9,DRAD2,Drepanocladus aduncus (Hedw.) Warnst.,<NA>,Nonvascular,Native,Missing_duration,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
84,CARI70,48,16,CARI70,Calliergon richardsonii (Mitt.) Kindb.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
85,HYLI70,47,5,HYLI70,Hypnum lindbergii Mitt.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
86,DILAO2,46,4,DILAO2,Diapensia lapponica L. var. obovata F. Schmidt,Perennial,Subshrub,<NA>,Missing_nativity,<NA>,SUBSHR,USDA_traits
87,CLUN60,46,19,CLUN60,Cladonia uncialis (L.) F.H. Wigg.,<NA>,Lichenous,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
88,CEPU12,45,6,CEPU12,Ceratodon purpureus (Hedw.) Brid.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
89,DISP7,41,12,DISP7,Dicranum spadiceum J.E. Zetterst.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
90,BLYSM3,40,2,BLYSM3,Blysmus Panzer ex Schult.,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
91,METR70,38,10,METR70,Meesia triquetra (L. ex Jolycl.) Ångstr.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
92,SAPH,38,10,SAPH,Salix phlebophylla Andersson,Perennial,Shrub|Subshrub,<NA>,Missing_nativity,<NA>,SHR,USDA_traits
93,SAAN3,37,15,SAAN3,Saussurea angustifolia (Willd.) DC.,Perennial,Forb/herb,<NA>,Missing_nativity,<NA>,PF,USDA_traits
94,CERAT9,36,3,CERAT9,Ceratodon Brid.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
95,SOAC2,35,1,SOAC2,Solanum aculeastrum Dunal,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
96,DIFL70,34,6,DIFL70,Ditrichum flexicaule (Schwägr.) Hampe,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
97,STIPA,33,7,STIPA,Stipa L.,<NA>,Graminoid,<NA>,Missing_duration_nativity,<NA>,Graminoid,USDA_traits
98,CAWI3,32,16,CAWI3,Carex williamsii Britton,Perennial,Graminoid,<NA>,Missing_nativity,<NA>,PerennialGraminoid,USDA_traits
99,PTCR70,32,16,PTCR70,Ptilium crista-castrensis (Hedw.) De Not.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits

Unique USDA taxa requiring supplemental trait lookup: 462

==========================================================================================
MOSAIC FUNCTIONAL-GROUP SUMMARY — ALL RECORDS
==========================================================================================

==========================================================================================
PLANT-ONLY FUNCTIONAL-GROUP SUMMARY
==========================================================================================

==========================================================================================
FUNCTIONAL-GROUP RESOLUTION SOURCE
==========================================================================================

==========================================================================================
AMBIGUOUS / TRAIT-INCOMPLETE FUNCTIONAL GROUPS
==========================================================================================
Codes:   2,718
Records: 1,105,011

,observed_code,n_records,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,USDA_trait_status,protocol_plant_group,USDA_derived_group,resolved_plant_group,MOSAIC_FG,FG_resolution_source
0,ARTRW8,232161,ARTRW8,Artemisia tridentata Nutt. ssp. wyomingensis B...,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
1,ARTRV,79491,ARTRV,Artemisia tridentata Nutt. ssp. vaseyana (Rydb...,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
2,Annual plants,35750,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualPlant,NaN,AnnualPlant,AnnualPlant,protocol_or_project_group
3,PRGL2,32583,PRGL2,Prosopis glandulosa Torr.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
4,ARTRT,30220,ARTRT,Artemisia tridentata Nutt. ssp. tridentata,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
5,ARTR2,27981,ARTR2,Artemisia tridentata Nutt.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
6,GUSA2,27951,GUSA2,Gutierrezia sarothrae (Pursh) Britton & Rusby,Perennial,Forb/herb|Shrub|Subshrub,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
7,QUGA,24748,QUGA,Quercus gambelii Nutt.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
8,ARPU9,21232,ARPU9,Aristida purpurea Nutt.,Annual|Perennial,Graminoid,Native,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
9,Sub-shrubs and perennial forbs,20140,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,SubshrubOrPerennialForb,NaN,SubshrubOrPerennialForb,SubshrubOrPF,protocol_or_project_group
10,SIAL2,18009,SIAL2,Sisymbrium altissimum L.,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
11,ERCI6,16863,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
12,MEOF,14865,MEOF,Melilotus officinalis (L.) Lam.,Annual|Biennial|Perennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
13,AMPS,12541,AMPS,Ambrosia psilostachya DC.,Annual|Perennial,Forb/herb,Native,Complete,<NA>,Forb,Forb,Forb,USDA_traits
14,JUSC2,12284,JUSC2,Juniperus scopulorum Sarg.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
15,CAREX,12263,CAREX,Carex L.,Annual|Perennial,Forb/herb|Graminoid,Introduced,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
16,JUMO,11511,JUMO,Juniperus monosperma (Engelm.) Sarg.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
17,PHLO2,11316,PHLO2,Phlox longifolia Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
18,LUAR3,10267,LUAR3,Lupinus argenteus Pursh,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
19,AMAL2,9999,AMAL2,Amelanchier alnifolia (Nutt.) Nutt. ex M. Roem.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
20,DEPI,9183,DEPI,Descurainia pinnata (Walter) Britton,Annual|Biennial|Perennial,Forb/herb,Native,Complete,<NA>,Forb,Forb,Forb,USDA_traits
21,LEPE2,8619,LEPE2,Lepidium perfoliatum L.,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
22,AMUT,8409,AMUT,Amelanchier utahensis Koehne,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
23,CELE3,7402,CELE3,Cercocarpus ledifolius Nutt.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
24,CEMO2,6664,CEMO2,Cercocarpus montanus Raf.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
25,LASE,6311,LASE,Lactuca serriola L.,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
26,ARLU,5989,ARLU,Artemisia ludoviciana Nutt.,Perennial,Forb/herb|Subshrub,Introduced,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
27,ALAL3,5257,ALAL3,Alyssum alyssoides (L.) L.,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
28,VIAM,5105,VIAM,Vicia americana Muhl. ex Willd.,Perennial,Forb/herb|Vine,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
29,LIPU11,4987,LIPU11,Linanthus pungens (Torr.) J.M. Porter & L.A. J...,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
30,DESO2,4805,DESO2,Descurainia sophia (L.) Webb ex Prantl,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
31,SPCO,4794,SPCO,Sphaeralcea coccinea (Nutt.) Rydb.,Biennial|Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
32,DIGIT2,4792,DIGIT2,Digitaria Haller,Annual|Perennial,Graminoid,Introduced,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
33,ERUM,4443,ERUM,Eriogonum umbellatum Torr.,Perennial,Forb/herb|Shrub|Subshrub,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
34,LEDE,4359,LEDE,Lepidium densiflorum Schrad.,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
35,YUGL,4042,YUGL,Yucca glauca Nutt.,Perennial,Forb/herb|Shrub|Subshrub,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
36,LOPE,4037,LOPE,Lolium perenne L.,Annual|Perennial,Graminoid,Introduced,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
37,TRPR2,3980,TRPR2,Trifolium pratense L.,Biennial|Perennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
38,PAMI5,3825,PAMI5,Parkinsonia microphylla Torr.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
39,HEVI4,3752,HEVI4,Heterotheca villosa (Pursh) Shinners,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
40,TRDU,3686,TRDU,Tragopogon dubius Scop.,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
41,LAOC3,3603,LAOC3,Lappula occidentalis (S. Watson) Greene,Annual|Biennial,Forb/herb,Native,Complete,<NA>,Forb,Forb,Forb,USDA_traits
42,MESA,3509,MESA,Medicago sativa L.,Annual|Perennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
43,PRVE,3417,PRVE,Prosopis velutina Wooton,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
44,PRVI,3263,PRVI,Prunus virginiana L.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
45,SPORO,3128,SPORO,Sporobolus R. Br.,Annual|Perennial,Graminoid,Introduced,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
46,STAC,2921,STAC,Stenotus acaulis (Nutt.) Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
47,LUPIN,2918,LUPIN,Lupinus L.,Annual|Perennial,Forb/herb|Shrub|Subshrub,Introduced,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
48,LEPID,2837,LEPID,Lepidium L.,Annual|Biennial|Perennial,Forb/herb|Shrub|Subshrub,Introduced,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
49,JUCO6,2829,JUCO6,Juniperus communis L.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
50,QUTU2,2790,QUTU2,Quercus turbinella Greene,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
51,COUM,2747,COUM,Comandra umbellata (L.) Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
52,COCA5,2694,COCA5,Conyza canadensis (L.) Cronquist,Annual|Biennial,Forb/herb,Native,Complete,<NA>,Forb,Forb,Forb,USDA_traits
53,ARTRW,2585,ARTRW8,Artemisia tridentata Nutt. ssp. wyomingensis B...,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
54,BRDI3,2576,BRDI3,Bromus diandrus Roth,Annual|Perennial,Graminoid,Introduced,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
55,JUNCU,2560,JUNCU,Juncus L.,Annual|Perennial,Graminoid,Introduced,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
56,ERHE2,2524,ERHE2,Eriogonum heracleoides Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
57,VACO9,2442,VACO9,Vachellia constricta (Benth.) Seigler & Ebinger,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
58,LUSE4,2438,LUSE4,Lupinus sericeus Pursh,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
59,POA,2426,POA,Poa L.,Annual|Perennial,Graminoid,Introduced,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
60,ARIST,2372,ARIST,Aristida L.,Annual|Perennial,Graminoid,Native,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
61,MELU,2223,MELU,Medicago lupulina L.,Annual|Perennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
62,COAR4,2147,COAR4,Convolvulus arvensis L.,Perennial,Forb/herb|Vine,Introduced,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
63,QUHA3,2145,QUHA3,Quercus havardii Rydb.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
64,CROTO,2012,CROTO,Croton L.,Annual|Perennial,Forb/herb|Shrub|Subshrub|Tree,Introduced,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
65,SPAM2,1929,SPAM2,Sphaeralcea ambigua A. Gray,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
66,SERE2,1925,SERE2,Serenoa repens (W. Bartram) Small,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
67,GUTCFSAR,1894,GUSA2,Gutierrezia sarothrae (Pursh) Britton & Rusby,Perennial,Forb/herb|Shrub|Subshrub,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
68,PUST,1893,PUST,Purshia stansburiana (Torr.) Henrickson,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
69,PLLA,1865,PLLA,Plantago lanceolata L.,Annual|Biennial|Perennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
70,CROC,1706,CROC,Crepis occidentalis Nutt.,Annual|Perennial,Forb/herb,Native,Complete,<NA>,Forb,Forb,Forb,USDA_traits
71,PLANT,1652,PLANT,Plantago L.,Annual|Biennial|Perennial,Forb/herb|Shrub|Subshrub,Introduced,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
72,CRPO5,1608,CRPO5,Croton pottsii (Klotzsch) Müll. Arg.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
73,LECU,1588,LECU,Lespedeza cuneata (Dum. Cours.) G. Don,Perennial,Forb/herb|Subshrub,Introduced,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
74,GABO2,1568,GABO2,Galium boreale L.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
75,CEVE,1547,CEVE,Ceanothus velutinus Douglas ex Hook.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
76,ARKI,1540,ARKI,Arenaria kingii (S. Watson) M.E. Jones,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
77,CRYPT,1514,CRYPT,Cryptantha Lehm. ex G. Don,Annual|Biennial|Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
78,QUGA4,1500,QUGA4,Quercus garryana Douglas ex Hook.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
79,ARHO4,1495,ARHO4,Arenaria hookeri Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
80,JUAS,1484,JUAS,Juniperus ashei J. Buchholz,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
81,ERCA8,1469,ERCA8,Eriogonum caespitosum Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
82,ARCO5,1448,ARCO5,Arenaria congesta Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
83,OPUNT,1416,OPUNT,Opuntia Mill.,Perennial,Shrub|Subshrub|Tree,Introduced,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
84,PEPU7,1416,PEPU7,Petradoria pumila (Nutt.) Greene,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
85,BOERH2,1412,BOERH2,Boerhavia L.,Annual|Perennial,Forb/herb|Shrub|Subshrub|Vine,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
86,QUCH2,1398,QUCH2,Quercus chrysolepis Liebm.,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
87,ERBO,1395,ERBO,Erodium botrys (Cav.) Bertol.,Annual|Biennial,Forb/herb,Introduced,Complete,<NA>,Forb,Forb,Forb,USDA_traits
88,AGGL,1387,AGGL,Agoseris glauca (Pursh) Raf.,Perennial,Forb/herb|Shrub|Subshrub,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
89,LOLIU,1367,LOLIU,Lolium L.,Annual|Perennial,Graminoid,Introduced,Complete,<NA>,Graminoid,Graminoid,Graminoid,USDA_traits
90,ERIOG,1357,ERIOG,Eriogonum Michx.,Annual|Biennial|Perennial,Forb/herb|Shrub|Subshrub,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits
91,SOCA3,1336,SOCA3,Solanum carolinense L.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
92,SOLID,1332,SOLID,Solidago L.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
93,ANTEN,1301,ANTEN,Antennaria Gaertn.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
94,TRGY,1296,TRGY,Trifolium gymnocarpon Nutt.,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
95,ACRI,1292,VARI,Vachellia rigidula (Benth.) Seigler & Ebinger,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
96,ACCO2,1288,VACO9,Vachellia constricta (Benth.) Seigler & Ebinger,Perennial,Shrub|Tree,Native,Complete,<NA>,Woody,Woody,Woody,USDA_traits
97,ANDI2,1277,ANDI2,Antennaria dimorpha (Nutt.) Torr. & A. Gray,Perennial,Forb/herb|Subshrub,Native,Complete,<NA>,SubshrubOrForb,SubshrubOrForb,SubshrubOrForb,USDA_traits
98,GRSQ,1273,GRSQ,Grindelia squarrosa (Pursh) Dunal,Annual|Biennial|Perennial,Forb/herb,Native,Complete,<NA>,Forb,Forb,Forb,USDA_traits
99,YUBA,1266,YUBA,Yucca baccata Torr.,Perennial,Forb/herb|Shrub|Subshrub,Native,Complete,<NA>,NaN,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits

==========================================================================================
TRUE UNKNOWN PLANTS
==========================================================================================
UnknownPlant codes: 142
Records represented: 21,114

==========================================================================================
PBG / PERENNIAL GRAMINOID AUDIT
==========================================================================================
Explicit PBG:             0 codes | 0 records
PerennialGraminoid:       1,492 codes | 2,267,084 records

Interpretation:
  PBG = bunchgrass identity already known from an explicit source/project classification.
  PerennialGraminoid = perennial graminoid supported by available information, but bunchgrass architecture has not yet been independently established.

==========================================================================================
FINAL FUNCTIONAL-GROUP COVERAGE AUDIT
==========================================================================================
Plant codes with MOSAIC_FG:    10,749 / 10,749 (100.00%)
Plant records with MOSAIC_FG:  5,436,341 / 5,436,341 (100.00000%)
Plant records lacking any FG:  0
==========================================================================================

In [21]:
# ============================================================
# DIAGNOSE USDA TRAIT-MISSINGNESS
#
# Separates:
#
#   1. accepted USDA symbol absent from trait cache
#   2. symbol present in cache but trait fields are blank
#
# This tells us whether we need:
#   - additional taxa queried
#   - or failed/incomplete taxa re-queried
# ============================================================

# Normalize cache symbol column if needed
usda_cache_check = pd.read_csv(
    USDA_ATTRIBUTE_CACHE,
    dtype="string",
    low_memory=False,
).copy()

if (
    "accepted_symbol" in usda_cache_check.columns
    and "USDA_accepted_symbol" not in usda_cache_check.columns
):
    usda_cache_check = usda_cache_check.rename(
        columns={"accepted_symbol": "USDA_accepted_symbol"}
    )


# ------------------------------------------------------------
# Basic cache membership
# ------------------------------------------------------------

cache_symbols = set(
    usda_cache_check[
        "USDA_accepted_symbol"
    ]
    .dropna()
    .astype(str)
    .str.strip()
)


dictionary_fg["USDA_symbol_in_trait_cache"] = (
    dictionary_fg[
        "USDA_accepted_symbol"
    ]
    .astype("string")
    .isin(cache_symbols)
)


# ------------------------------------------------------------
# Examine the important unresolved taxa
# ------------------------------------------------------------

check_codes = [
    "TRDU",
    "PSSP6",
    "POPR",
    "AGCR",
    "HECO26",
    "FEID",
    "ELEL5",
    "BRIN2",
    "CHVI8",
    "SCAR7",
    "TACA8",
    "ALDE",
    "ARTR2",
    "SIAL2",
    "ERCI6",
]


diagnostic = (
    dictionary_fg.loc[
        dictionary_fg["observed_code"].isin(check_codes),
        [
            "observed_code",
            "n_records",
            "USDA_accepted_symbol",
            "USDA_scientific_name",
            "USDA_symbol_in_trait_cache",
            "USDA_duration",
            "USDA_growth_habit",
            "USDA_native_status_L48",
            "USDA_trait_status",
        ],
    ]
    .sort_values(
        "n_records",
        ascending=False,
    )
)

display(diagnostic)

,observed_code,n_records,USDA_accepted_symbol,USDA_scientific_name,USDA_symbol_in_trait_cache,USDA_duration,USDA_growth_habit,USDA_native_status_L48,USDA_trait_status
10,PSSP6,163393,PSSP6,Pseudoroegneria spicata (Pursh) Á. Löve,True,Perennial,Graminoid,Native,Complete
29,POPR,115614,POPR,Poa pratensis L.,True,Perennial,Graminoid,Introduced,Complete
31,AGCR,86637,AGCR,Agropyron cristatum (L.) Gaertn.,True,Perennial,Graminoid,Introduced,Complete
19,HECO26,80033,HECO26,Hesperostipa comata (Trin. & Rupr.) Barkworth,True,Perennial,Graminoid,Native,Complete
34,FEID,78604,FEID,Festuca idahoensis Elmer,True,Perennial,Graminoid,Native,Complete
9,ELEL5,58454,ELEL5,Elymus elymoides (Raf.) Swezey,True,Perennial,Graminoid,Native,Complete
63,BRIN2,56601,BRIN2,Bromus inermis Leyss.,True,Perennial,Graminoid,Introduced,Complete
12,CHVI8,52275,CHVI8,Chrysothamnus viscidiflorus (Hook.) Nutt.,True,Perennial,Shrub,Native,Complete
109,SCAR7,46213,SCAR7,"Schedonorus arundinaceus (Schreb.) Dumort., no...",True,Perennial,Graminoid,Introduced,Complete
82,ARTR2,27981,ARTR2,Artemisia tridentata Nutt.,True,Perennial,Shrub|Tree,Native,Complete
115,TACA8,26357,TACA8,Taeniatherum caput-medusae (L.) Nevski,True,Annual,Graminoid,Introduced,Complete
38,ALDE,26258,ALDE,Alyssum desertorum Stapf,True,Annual,Forb/herb,Introduced,Complete
44,SIAL2,18009,SIAL2,Sisymbrium altissimum L.,True,Annual|Biennial,Forb/herb,Introduced,Complete
73,ERCI6,16863,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,True,Annual|Biennial,Forb/herb,Introduced,Complete
70,TRDU,3686,TRDU,Tragopogon dubius Scop.,True,Annual|Biennial,Forb/herb,Introduced,Complete

In [22]:
display(
    usda_cache_check.loc[
        usda_cache_check[
            "USDA_accepted_symbol"
        ].eq("TRDU")
    ]
)

     USDA_accepted_symbol USDA_plant_id USDA_rank USDA_duration_api USDA_growth_habit_api USDA_L48_native_status_api USDA_L48_native_type_api                     retrieved_utc
6890                 TRDU       41535.0   Species   Annual|Biennial             Forb/herb                          I               Introduced  2026-09-01T20:26:28.390058+00:00

In [23]:
# ============================================================
# FIND USDA-RESOLVED TAXA MISSING FROM ECOLOGICAL TRAIT CACHE
# ============================================================

# Current cache symbols
cache_symbols = set(
    usda_attributes["USDA_accepted_symbol"]
    .dropna()
    .astype(str)
    .str.strip()
)

# Current dictionary USDA symbols
dictionary_symbols = set(
    dictionary_fg["USDA_accepted_symbol"]
    .dropna()
    .astype(str)
    .str.strip()
)

missing_trait_symbols = sorted(
    dictionary_symbols - cache_symbols
)

print(f"USDA taxa represented in dictionary: {len(dictionary_symbols):,}")
print(f"USDA taxa already in trait cache:      {len(cache_symbols):,}")
print(f"USDA taxa missing from trait cache:    {len(missing_trait_symbols):,}")

USDA taxa represented in dictionary: 7,268
USDA taxa already in trait cache:      7,267
USDA taxa missing from trait cache:    2

In [24]:
missing_trait_taxa = (
    dictionary_fg.loc[
        dictionary_fg["USDA_accepted_symbol"].isin(missing_trait_symbols),
        [
            "USDA_accepted_symbol",
            "USDA_scientific_name",
            "n_records",
        ],
    ]
    .groupby(
        ["USDA_accepted_symbol", "USDA_scientific_name"],
        dropna=False,
        as_index=False,
    )
    ["n_records"]
    .sum()
    .sort_values(
        "n_records",
        ascending=False,
    )
)

display(missing_trait_taxa.head(100))

print(
    "\nRecords represented by taxa missing from trait cache:",
    f"{missing_trait_taxa['n_records'].sum():,}"
)

  USDA_accepted_symbol            USDA_scientific_name  n_records
0                 NONE       Notholaena neglecta Maxon        398
1                PONIN  Potentilla nivea L. var. nivea         10

Records represented by taxa missing from trait cache: 408

In [25]:
# ============================================================
# TRAIT CACHE COVERAGE GATE
# ============================================================

plant_usda = dictionary_fg.loc[
    dictionary_fg["code_class"].eq("Plant")
    & dictionary_fg["USDA_accepted_symbol"].notna()
].copy()

plant_usda["has_trait_cache"] = (
    plant_usda["USDA_accepted_symbol"]
    .isin(
        set(
            usda_attributes["USDA_accepted_symbol"]
            .dropna()
            .astype(str)
            .str.strip()
        )
    )
)

code_coverage = plant_usda["has_trait_cache"].mean()

record_coverage = (
    plant_usda.loc[
        plant_usda["has_trait_cache"],
        "n_records"
    ].sum()
    /
    plant_usda["n_records"].sum()
)

print(
    f"USDA trait-cache coverage by plant code: "
    f"{code_coverage:.2%}"
)

print(
    f"USDA trait-cache coverage by plant records: "
    f"{record_coverage:.2%}"
)

if record_coverage < 0.99:
    print(
        "\nWARNING: <99% of USDA-resolved plant records "
        "are represented in the ecological trait cache."
    )

USDA trait-cache coverage by plant code: 99.97%
USDA trait-cache coverage by plant records: 99.99%

In [26]:
missing_trait_taxa = (
    dictionary_fg.loc[
        dictionary_fg["code_class"].eq("Plant")
        & dictionary_fg["USDA_accepted_symbol"].notna()
        & ~dictionary_fg["USDA_accepted_symbol"].isin(
            set(
                usda_attributes["USDA_accepted_symbol"]
                .dropna()
                .astype(str)
                .str.strip()
            )
        ),
        [
            "USDA_accepted_symbol",
            "USDA_scientific_name",
            "n_records",
        ],
    ]
    .groupby(
        ["USDA_accepted_symbol", "USDA_scientific_name"],
        dropna=False,
        as_index=False,
    )
    ["n_records"]
    .sum()
    .sort_values("n_records", ascending=False)
)

print(f"Missing USDA taxa: {len(missing_trait_taxa):,}")
print(
    "Plant records represented by missing taxa:",
    f"{missing_trait_taxa['n_records'].sum():,}"
)

display(missing_trait_taxa.head(100))

Missing USDA taxa: 2
Plant records represented by missing taxa: 408

  USDA_accepted_symbol            USDA_scientific_name  n_records
0                 NONE       Notholaena neglecta Maxon        398
1                PONIN  Potentilla nivea L. var. nivea         10

In [27]:
# ============================================================
# INSPECT RAW USDA PlantProfile JSON FOR ONE KNOWN TAXON
# ============================================================

import json
import requests

symbol = "PSSP6"

url = f"{USDA_SERVICE_BASE}/PlantProfile"

response = requests.get(
    url,
    params={"symbol": symbol},
    timeout=REQUEST_TIMEOUT,
    headers={
        "Accept": "application/json",
        "User-Agent": "MOSAIC-USDA-trait-debug/1.0",
    },
)

print("HTTP status:", response.status_code)
print("Final URL:", response.url)
print("Content-Type:", response.headers.get("content-type"))

response.raise_for_status()

payload = response.json()

print("\nTOP-LEVEL TYPE:")
print(type(payload))

print("\nTOP-LEVEL KEYS:")
if isinstance(payload, dict):
    print(list(payload.keys()))
else:
    print("Not a dictionary")

print("\nRAW JSON:")
print(
    json.dumps(
        payload,
        indent=2,
        ensure_ascii=False,
    )
)

NameError: name 'USDA_SERVICE_BASE' is not defined

In [ ]:
# ============================================================
# INVENTORY ALL KEYS / VALUES IN THE PSSP6 RESPONSE
# ============================================================

def inspect_json(obj, path="root"):

    if isinstance(obj, dict):

        for key, value in obj.items():

            current_path = f"{path}.{key}"

            if isinstance(value, (dict, list)):
                print(
                    f"{current_path:<80} "
                    f"[{type(value).__name__}]"
                )
                inspect_json(
                    value,
                    current_path,
                )

            else:
                print(
                    f"{current_path:<80} "
                    f"= {value!r}"
                )

    elif isinstance(obj, list):

        for i, value in enumerate(obj):

            inspect_json(
                value,
                f"{path}[{i}]",
            )


inspect_json(payload)

root.Id                                                                          = 25163
root.Symbol                                                                      = 'PSSP6'
root.ScientificName                                                              = '<i>Pseudoroegneria spicata</i> (Pursh) Á. Löve'
root.ScientificNameComponents                                                    = None
root.CommonName                                                                  = 'bluebunch wheatgrass'
root.Group                                                                       = 'Monocot'
root.RankId                                                                      = 180
root.Rank                                                                        = 'Species'
root.Durations                                                                   [list]
root.GrowthHabits                                                                [list]
root.NativeStatuses                                                              [list]
root.NativeStatuses[0].Region                                                    = 'AK'
root.NativeStatuses[0].Status                                                    = 'N'
root.NativeStatuses[0].Type                                                      = 'Native'
root.NativeStatuses[1].Region                                                    = 'CAN'
root.NativeStatuses[1].Status                                                    = 'N'
root.NativeStatuses[1].Type                                                      = 'Native'
root.NativeStatuses[2].Region                                                    = 'L48'
root.NativeStatuses[2].Status                                                    = 'N'
root.NativeStatuses[2].Type                                                      = 'Native'
root.MapCoordinates                                                              [list]
root.MapCoordinates[0].StateAbbr                                                 = 'AK'
root.MapCoordinates[0].XMin                                                      = -179.14733
root.MapCoordinates[0].YMin                                                      = 51.21526
root.MapCoordinates[0].XMax                                                      = -129.97951
root.MapCoordinates[0].YMax                                                      = 71.38961
root.MapCoordinates[1].StateAbbr                                                 = 'HI'
root.MapCoordinates[1].XMin                                                      = -178.33958
root.MapCoordinates[1].YMin                                                      = 18.91382
root.MapCoordinates[1].XMax                                                      = -154.80927
root.MapCoordinates[1].YMax                                                      = 28.40128
root.MapCoordinates[2].StateAbbr                                                 = 'PR'
root.MapCoordinates[2].XMin                                                      = -67.95418
root.MapCoordinates[2].YMin                                                      = 17.88124
root.MapCoordinates[2].XMax                                                      = -65.22111
root.MapCoordinates[2].YMax                                                      = 18.51601
root.MapCoordinates[3].StateAbbr                                                 = 'VI'
root.MapCoordinates[3].XMin                                                      = -65.08551
root.MapCoordinates[3].YMin                                                      = 17.67385
root.MapCoordinates[3].XMax                                                      = -64.56549
root.MapCoordinates[3].YMax                                                      = 18.41301
root.MapCoordinates[4].StateAbbr                                                 = 'L48'
root.MapCoordinates[4].XMin                                                      = -124.76257
root.MapCoordinates[4].YMin                                                      = 24.52105
root.MapCoordinates[4].XMax                                                      = -66.94983
root.MapCoordinates[4].YMax                                                      = 49.38435
root.PlantsDistributionResults                                                   = None
root.AcceptedId                                                                  = 25163
root.OtherCommonNames                                                            [list]
root.HasSynonyms                                                                 = False
root.Synonyms                                                                    = None
root.Ancestors                                                                   [list]
root.Ancestors[0].Id                                                             = 7168
root.Ancestors[0].Symbol                                                         = 'Plantae'
root.Ancestors[0].ScientificName                                                 = '<i>Plantae</i>'
root.Ancestors[0].ScientificNameComponents                                       = None
root.Ancestors[0].CommonName                                                     = 'Plants'
root.Ancestors[0].Group                                                          = None
root.Ancestors[0].RankId                                                         = 10
root.Ancestors[0].Rank                                                           = 'Kingdom'
root.Ancestors[0].Durations                                                      = None
root.Ancestors[0].GrowthHabits                                                   = None
root.Ancestors[0].NativeStatuses                                                 = None
root.Ancestors[0].MapCoordinates                                                 = None
root.Ancestors[0].PlantsDistributionResults                                      = None
root.Ancestors[0].AcceptedId                                                     = 0
root.Ancestors[0].OtherCommonNames                                               = None
root.Ancestors[0].HasSynonyms                                                    = False
root.Ancestors[0].Synonyms                                                       = None
root.Ancestors[0].Ancestors                                                      = None
root.Ancestors[0].HasSubordinateTaxa                                             = False
root.Ancestors[0].SubordinateTaxa                                                = None
root.Ancestors[0].HasWildlife                                                    = False
root.Ancestors[0].Wildlife                                                       = None
root.Ancestors[0].HasWetlandData                                                 = False
root.Ancestors[0].WetlandData                                                    = None
root.Ancestors[0].HasImages                                                      = False
root.Ancestors[0].HasRelatedLinks                                                = False
root.Ancestors[0].RelatedLinks                                                   = None
root.Ancestors[0].HasLegalStatuses                                               = False
root.Ancestors[0].LegalStatuses                                                  = None
root.Ancestors[0].HasNoxiousStatuses                                             = False
root.Ancestors[0].NoxiousStatuses                                                = None
root.Ancestors[0].HasDocumentation                                               = False
root.Ancestors[0].HasDistributionData                                            = False
root.Ancestors[0].Documentation                                                  = None
root.Ancestors[0].PlantNotes                                                     = None
root.Ancestors[0].NumImages                                                      = 0
root.Ancestors[0].ProfileImageFilename                                           = None
root.Ancestors[0].ImageId                                                        = 0
root.Ancestors[0].HasInvasiveStatuses                                            = False
root.Ancestors[0].InvasiveStatuses                                               = None
root.Ancestors[0].ProtectedStatuses                                              = None
root.Ancestors[0].PlantGuideUrls                                                 = None
root.Ancestors[0].FactSheetUrls                                                  = None
root.Ancestors[0].HasCharacteristics                                             = False
root.Ancestors[0].PlantLocationId                                                = 0
root.Ancestors[0].Characteristics                                                = None
root.Ancestors[0].HasEthnobotany                                                 = False
root.Ancestors[0].Ethnobotanies                                                  = None
root.Ancestors[0].HasPollinator                                                  = False
root.Ancestors[0].ScientificNameWithoutAuthor                                    = None
root.Ancestors[0].ScientificSort                                                 = None
root.Ancestors[0].SynonymSymbol                                                  = None
root.Ancestors[0].AcceptedSymbol                                                 = None
root.Ancestors[0].AcceptedScientificName                                         = None
root.Ancestors[0].AcceptedCommonName                                             = None
root.Ancestors[0].WetlandDataString                                              = None
root.Ancestors[0].RarityDataString                                               = None
root.Ancestors[0].NoxiousInvasiveDataString                                      = None
root.Ancestors[0].GrowthHabitName                                                = None
root.Ancestors[0].Duration                                                       = None
root.Ancestors[0].GroupName                                                      = None
root.Ancestors[0].FipsCode                                                       = None
root.Ancestors[1].Id                                                             = 12206
root.Ancestors[1].Symbol                                                         = 'Tracheobionta'
root.Ancestors[1].ScientificName                                                 = '<i>Tracheobionta</i>'
root.Ancestors[1].ScientificNameComponents                                       = None
root.Ancestors[1].CommonName                                                     = 'Vascular plants'
root.Ancestors[1].Group                                                          = None
root.Ancestors[1].RankId                                                         = 20
root.Ancestors[1].Rank                                                           = 'Subkingdom'
root.Ancestors[1].Durations                                                      = None
root.Ancestors[1].GrowthHabits                                                   = None
root.Ancestors[1].NativeStatuses                                                 = None
root.Ancestors[1].MapCoordinates                                                 = None
root.Ancestors[1].PlantsDistributionResults                                      = None
root.Ancestors[1].AcceptedId                                                     = 0
root.Ancestors[1].OtherCommonNames                                               = None
root.Ancestors[1].HasSynonyms                                                    = False
root.Ancestors[1].Synonyms                                                       = None
root.Ancestors[1].Ancestors                                                      = None
root.Ancestors[1].HasSubordinateTaxa                                             = False
root.Ancestors[1].SubordinateTaxa                                                = None
root.Ancestors[1].HasWildlife                                                    = False
root.Ancestors[1].Wildlife                                                       = None
root.Ancestors[1].HasWetlandData                                                 = False
root.Ancestors[1].WetlandData                                                    = None
root.Ancestors[1].HasImages                                                      = False
root.Ancestors[1].HasRelatedLinks                                                = False
root.Ancestors[1].RelatedLinks                                                   = None
root.Ancestors[1].HasLegalStatuses                                               = False
root.Ancestors[1].LegalStatuses                                                  = None
root.Ancestors[1].HasNoxiousStatuses                                             = False
root.Ancestors[1].NoxiousStatuses                                                = None
root.Ancestors[1].HasDocumentation                                               = False
root.Ancestors[1].HasDistributionData                                            = False
root.Ancestors[1].Documentation                                                  = None
root.Ancestors[1].PlantNotes                                                     = None
root.Ancestors[1].NumImages                                                      = 0
root.Ancestors[1].ProfileImageFilename                                           = None
root.Ancestors[1].ImageId                                                        = 0
root.Ancestors[1].HasInvasiveStatuses                                            = False
root.Ancestors[1].InvasiveStatuses                                               = None
root.Ancestors[1].ProtectedStatuses                                              = None
root.Ancestors[1].PlantGuideUrls                                                 = None
root.Ancestors[1].FactSheetUrls                                                  = None
root.Ancestors[1].HasCharacteristics                                             = False
root.Ancestors[1].PlantLocationId                                                = 0
root.Ancestors[1].Characteristics                                                = None
root.Ancestors[1].HasEthnobotany                                                 = False
root.Ancestors[1].Ethnobotanies                                                  = None
root.Ancestors[1].HasPollinator                                                  = False
root.Ancestors[1].ScientificNameWithoutAuthor                                    = None
root.Ancestors[1].ScientificSort                                                 = None
root.Ancestors[1].SynonymSymbol                                                  = None
root.Ancestors[1].AcceptedSymbol                                                 = None
root.Ancestors[1].AcceptedScientificName                                         = None
root.Ancestors[1].AcceptedCommonName                                             = None
root.Ancestors[1].WetlandDataString                                              = None
root.Ancestors[1].RarityDataString                                               = None
root.Ancestors[1].NoxiousInvasiveDataString                                      = None
root.Ancestors[1].GrowthHabitName                                                = None
root.Ancestors[1].Duration                                                       = None
root.Ancestors[1].GroupName                                                      = None
root.Ancestors[1].FipsCode                                                       = None
root.Ancestors[2].Id                                                             = 14987
root.Ancestors[2].Symbol                                                         = 'Spermatophyta'
root.Ancestors[2].ScientificName                                                 = '<i>Spermatophyta</i>'
root.Ancestors[2].ScientificNameComponents                                       = None
root.Ancestors[2].CommonName                                                     = 'Seed plants'
root.Ancestors[2].Group                                                          = None
root.Ancestors[2].RankId                                                         = 30
root.Ancestors[2].Rank                                                           = 'Superdivision'
root.Ancestors[2].Durations                                                      = None
root.Ancestors[2].GrowthHabits                                                   = None
root.Ancestors[2].NativeStatuses                                                 = None
root.Ancestors[2].MapCoordinates                                                 = None
root.Ancestors[2].PlantsDistributionResults                                      = None
root.Ancestors[2].AcceptedId                                                     = 0
root.Ancestors[2].OtherCommonNames                                               = None
root.Ancestors[2].HasSynonyms                                                    = False
root.Ancestors[2].Synonyms                                                       = None
root.Ancestors[2].Ancestors                                                      = None
root.Ancestors[2].HasSubordinateTaxa                                             = False
root.Ancestors[2].SubordinateTaxa                                                = None
root.Ancestors[2].HasWildlife                                                    = False
root.Ancestors[2].Wildlife                                                       = None
root.Ancestors[2].HasWetlandData                                                 = False
root.Ancestors[2].WetlandData                                                    = None
root.Ancestors[2].HasImages                                                      = False
root.Ancestors[2].HasRelatedLinks                                                = False
root.Ancestors[2].RelatedLinks                                                   = None
root.Ancestors[2].HasLegalStatuses                                               = False
root.Ancestors[2].LegalStatuses                                                  = None
root.Ancestors[2].HasNoxiousStatuses                                             = False
root.Ancestors[2].NoxiousStatuses                                                = None
root.Ancestors[2].HasDocumentation                                               = False
root.Ancestors[2].HasDistributionData                                            = False
root.Ancestors[2].Documentation                                                  = None
root.Ancestors[2].PlantNotes                                                     = None
root.Ancestors[2].NumImages                                                      = 0
root.Ancestors[2].ProfileImageFilename                                           = None
root.Ancestors[2].ImageId                                                        = 0
root.Ancestors[2].HasInvasiveStatuses                                            = False
root.Ancestors[2].InvasiveStatuses                                               = None
root.Ancestors[2].ProtectedStatuses                                              = None
root.Ancestors[2].PlantGuideUrls                                                 = None
root.Ancestors[2].FactSheetUrls                                                  = None
root.Ancestors[2].HasCharacteristics                                             = False
root.Ancestors[2].PlantLocationId                                                = 0
root.Ancestors[2].Characteristics                                                = None
root.Ancestors[2].HasEthnobotany                                                 = False

In [ ]:
# ============================================================
# RECOVER THE 478 USDA TAXA MISSING FROM THE TRAIT CACHE
#
# Purpose:
#   Query ecological traits ONLY for accepted USDA symbols
#   absent from the existing cache.
#
# Recovers:
#   - duration
#   - growth habit
#   - Lower-48 native status
#
# Behavior:
#   - resumable
#   - checkpointed
#   - never re-queries existing cached taxa
#   - appends recovered rows to the existing cache
#   - writes failures separately
# ============================================================

from pathlib import Path
from datetime import datetime, timezone
import time
import re
import pandas as pd
import requests


# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

USDA_SERVICE_BASE = "https://plantsservices.sc.egov.usda.gov/api"

REQUEST_TIMEOUT = 30
REQUEST_DELAY_SECONDS = 0.25
MAX_RETRIES = 3
SAVE_EVERY = 20

OUTPUT_DIR = Path(OUTPUT_DIR)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RECOVERY_PROGRESS_FILE = (
    OUTPUT_DIR /
    "USDA_PLANTS_ecological_attributes_missing_taxa_progress.csv"
)

RECOVERY_FAILURE_FILE = (
    OUTPUT_DIR /
    "USDA_PLANTS_ecological_attributes_missing_taxa_failures.csv"
)


# ------------------------------------------------------------
# GENERAL CLEANING
# ------------------------------------------------------------

def clean_text(x):
    if x is None:
        return None

    x = str(x).strip()

    if (
        x == ""
        or x.lower() in {
            "nan",
            "none",
            "null",
            "<na>",
        }
    ):
        return None

    return x


def unique_pipe(values):
    """
    Collapse repeated values while preserving multiple legitimate
    trait states such as Annual|Biennial|Perennial.
    """
    seen = []

    for x in values:
        x = clean_text(x)

        if x is not None and x not in seen:
            seen.append(x)

    return "|".join(seen) if seen else None


# ------------------------------------------------------------
# WALK ARBITRARY USDA JSON
# ------------------------------------------------------------

def walk_json(obj):
    """
    Recursively yield every dictionary in a nested JSON object.
    """

    if isinstance(obj, dict):

        yield obj

        for value in obj.values():
            yield from walk_json(value)

    elif isinstance(obj, list):

        for value in obj:
            yield from walk_json(value)


def values_for_keys(dicts, possible_keys):
    """
    Search nested dictionaries for candidate field names.
    """

    values = []

    for d in dicts:

        for key in possible_keys:

            if key in d:

                value = d[key]

                # Scalar
                if not isinstance(
                    value,
                    (dict, list),
                ):

                    value = clean_text(value)

                    if value is not None:
                        values.append(value)

    return unique_pipe(values)


# ------------------------------------------------------------
# NORMALIZE LOWER-48 NATIVITY
# ------------------------------------------------------------

def normalize_l48_nativity(raw):
    """
    Normalize USDA nativity into:

        compact:
            N
            I
            N|I
            None

        text:
            Native
            Introduced
            Native|Introduced
            None
    """

    raw = clean_text(raw)

    if raw is None:
        return None, None

    text = raw.upper()

    native = bool(
        re.search(r"\bL48\s*N\b", text)
        or text == "N"
        or "NATIVE" in text
    )

    introduced = bool(
        re.search(r"\bL48\s*I\b", text)
        or text == "I"
        or "INTRODUCED" in text
    )

    # Avoid "Introduced" accidentally triggering the word "Native"
    if "INTRODUCED" in text and "NATIVE" not in text:
        native = False

    if native and introduced:
        return "N|I", "Native|Introduced"

    if native:
        return "N", "Native"

    if introduced:
        return "I", "Introduced"

    return raw, None


# ------------------------------------------------------------
# PARSE USDA PROFILE RESPONSE
# ------------------------------------------------------------

def parse_profile_payload(symbol, payload):

    dicts = list(
        walk_json(payload)
    )

    if not dicts:
        raise ValueError(
            "USDA response contained no JSON dictionaries."
        )


    # --------------------------------------------------------
    # Plant ID
    # --------------------------------------------------------

    plant_id = values_for_keys(
        dicts,
        [
            "PlantID",
            "PlantId",
            "plantID",
            "plantId",
        ],
    )


    # --------------------------------------------------------
    # Taxonomic rank
    # --------------------------------------------------------

    rank = values_for_keys(
        dicts,
        [
            "Rank",
            "rank",
            "TaxonRank",
            "taxonRank",
        ],
    )


    # --------------------------------------------------------
    # Duration
    # --------------------------------------------------------

    duration = values_for_keys(
        dicts,
        [
            "Duration",
            "duration",
            "DurationName",
            "durationName",
        ],
    )


    # --------------------------------------------------------
    # Growth habit
    # --------------------------------------------------------

    growth_habit = values_for_keys(
        dicts,
        [
            "GrowthHabit",
            "growthHabit",
            "GrowthHabitName",
            "growthHabitName",
        ],
    )


    # --------------------------------------------------------
    # Native status
    #
    # We specifically want Lower-48 status.
    # --------------------------------------------------------

    native_raw_values = []

    for d in dicts:

        for key, value in d.items():

            if isinstance(
                value,
                (dict, list),
            ):
                continue

            value = clean_text(value)

            if value is None:
                continue

            key_upper = str(key).upper()
            value_upper = value.upper()

            # Explicit L48-named property
            if "L48" in key_upper:
                native_raw_values.append(value)

            # Generic native-status field that itself says L48
            elif (
                "NATIVE" in key_upper
                and "L48" in value_upper
            ):
                native_raw_values.append(value)

            elif (
                "STATUS" in key_upper
                and "L48" in value_upper
            ):
                native_raw_values.append(value)


    native_raw = unique_pipe(
        native_raw_values
    )

    native_status, native_type = (
        normalize_l48_nativity(
            native_raw
        )
    )


    return {
        "USDA_accepted_symbol":
            symbol,

        "USDA_plant_id":
            plant_id,

        "USDA_rank":
            rank,

        "USDA_duration_api":
            duration,

        "USDA_growth_habit_api":
            growth_habit,

        "USDA_L48_native_status_api":
            native_status,

        "USDA_L48_native_type_api":
            native_type,

        "retrieved_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),
    }


# ------------------------------------------------------------
# FETCH ONE USDA SYMBOL
# ------------------------------------------------------------

def fetch_usda_traits(symbol):

    url = (
        f"{USDA_SERVICE_BASE}/PlantProfile"
    )

    last_error = None

    # The service has historically accepted symbol.
    # Try capitalization variant only if needed.
    param_options = [
        {"symbol": symbol},
        {"Symbol": symbol},
    ]

    for params in param_options:

        for attempt in range(
            1,
            MAX_RETRIES + 1,
        ):

            try:

                response = requests.get(
                    url,
                    params=params,
                    timeout=REQUEST_TIMEOUT,
                    headers={
                        "Accept":
                            "application/json",

                        "User-Agent":
                            "MOSAIC-USDA-trait-recovery/1.0",
                    },
                )

                response.raise_for_status()

                payload = response.json()

                result = parse_profile_payload(
                    symbol,
                    payload,
                )

                # Successful HTTP response is not enough.
                # Require at least one useful profile field.
                useful = any(
                    result[x] is not None
                    for x in [
                        "USDA_plant_id",
                        "USDA_rank",
                        "USDA_duration_api",
                        "USDA_growth_habit_api",
                        "USDA_L48_native_status_api",
                    ]
                )

                if useful:
                    return result

                last_error = (
                    "Profile returned but no usable "
                    "ecological/taxonomic fields were found."
                )

            except Exception as exc:

                last_error = repr(exc)


            if attempt < MAX_RETRIES:

                wait = (
                    REQUEST_DELAY_SECONDS
                    * (2 ** (attempt - 1))
                )

                time.sleep(wait)


    raise RuntimeError(
        last_error
    )


# ------------------------------------------------------------
# LOAD CURRENT CACHE
# ------------------------------------------------------------

cache = pd.read_csv(
    USDA_ATTRIBUTE_CACHE,
    dtype="string",
    low_memory=False,
).copy()


# Normalize historical schema
if (
    "accepted_symbol" in cache.columns
    and
    "USDA_accepted_symbol"
    not in cache.columns
):

    cache = cache.rename(
        columns={
            "accepted_symbol":
                "USDA_accepted_symbol"
        }
    )


if "USDA_accepted_symbol" not in cache.columns:

    raise ValueError(
        "Could not locate accepted-symbol field "
        "in USDA ecological trait cache."
    )


cache["USDA_accepted_symbol"] = (
    cache["USDA_accepted_symbol"]
    .astype("string")
    .str.strip()
)


cached_symbols = set(
    cache[
        "USDA_accepted_symbol"
    ]
    .dropna()
)


print(
    f"Existing USDA cache taxa: "
    f"{len(cached_symbols):,}"
)


# ------------------------------------------------------------
# DEFINE TARGETS DIRECTLY FROM CURRENT MISSING TABLE
# ------------------------------------------------------------

targets = (
    missing_trait_taxa[
        "USDA_accepted_symbol"
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
    .tolist()
)


# Safety check:
# remove anything already cached
targets = [
    x
    for x in targets
    if x not in cached_symbols
]


print(
    f"Taxa requiring recovery: "
    f"{len(targets):,}"
)


# Expected right now:
# 478
if len(targets) != 478:

    print(
        "\nNOTE:"
        f" expected 478 based on current audit, "
        f"but found {len(targets):,}."
    )


# ------------------------------------------------------------
# RESUME PRIOR RECOVERY IF ONE EXISTS
# ------------------------------------------------------------

if RECOVERY_PROGRESS_FILE.exists():

    recovered = pd.read_csv(
        RECOVERY_PROGRESS_FILE,
        dtype="string",
        low_memory=False,
    )

    recovered_symbols = set(
        recovered[
            "USDA_accepted_symbol"
        ]
        .dropna()
        .astype(str)
        .str.strip()
    )

else:

    recovered = pd.DataFrame()

    recovered_symbols = set()


remaining = [
    x
    for x in targets
    if x not in recovered_symbols
]


print(
    f"Previously recovered: "
    f"{len(recovered_symbols):,}"
)

print(
    f"Remaining this run: "
    f"{len(remaining):,}"
)


# ------------------------------------------------------------
# RECOVERY LOOP
# ------------------------------------------------------------

pending_rows = []
pending_failures = []


for i, symbol in enumerate(
    remaining,
    start=1,
):

    try:

        result = fetch_usda_traits(
            symbol
        )

        pending_rows.append(
            result
        )

        print(
            f"[{i:03d}/{len(remaining):03d}] "
            f"{symbol:<10} "
            f"D={str(result['USDA_duration_api']):<24} "
            f"H={str(result['USDA_growth_habit_api']):<28} "
            f"L48={result['USDA_L48_native_type_api']}"
        )

    except Exception as exc:

        pending_failures.append(
            {
                "USDA_accepted_symbol":
                    symbol,

                "error":
                    repr(exc),

                "failed_utc":
                    datetime.now(
                        timezone.utc
                    ).isoformat(),
            }
        )

        print(
            f"[{i:03d}/{len(remaining):03d}] "
            f"{symbol:<10} FAILED | {exc}"
        )


    # --------------------------------------------------------
    # CHECKPOINT
    # --------------------------------------------------------

    if (
        i % SAVE_EVERY == 0
        or i == len(remaining)
    ):

        if pending_rows:

            new_df = pd.DataFrame(
                pending_rows
            )

            if recovered.empty:

                recovered = (
                    new_df.copy()
                )

            else:

                recovered = pd.concat(
                    [
                        recovered,
                        new_df,
                    ],
                    ignore_index=True,
                )


            recovered = (
                recovered
                .drop_duplicates(
                    subset=[
                        "USDA_accepted_symbol"
                    ],
                    keep="last",
                )
                .sort_values(
                    "USDA_accepted_symbol"
                )
                .reset_index(
                    drop=True
                )
            )


            recovered.to_csv(
                RECOVERY_PROGRESS_FILE,
                index=False,
            )

            pending_rows = []


        if pending_failures:

            fail_df = pd.DataFrame(
                pending_failures
            )


            if RECOVERY_FAILURE_FILE.exists():

                old_fail = pd.read_csv(
                    RECOVERY_FAILURE_FILE,
                    dtype="string",
                    low_memory=False,
                )

                fail_df = pd.concat(
                    [
                        old_fail,
                        fail_df,
                    ],
                    ignore_index=True,
                )


            fail_df.to_csv(
                RECOVERY_FAILURE_FILE,
                index=False,
            )

            pending_failures = []


    time.sleep(
        REQUEST_DELAY_SECONDS
    )


# ------------------------------------------------------------
# RELOAD RECOVERED RESULTS
# ------------------------------------------------------------

if RECOVERY_PROGRESS_FILE.exists():

    recovered = pd.read_csv(
        RECOVERY_PROGRESS_FILE,
        dtype="string",
        low_memory=False,
    )

else:

    recovered = pd.DataFrame()


print()
print(
    f"Successfully recovered taxa: "
    f"{len(recovered):,}"
)


# ------------------------------------------------------------
# APPEND TO MAIN CACHE
# ------------------------------------------------------------

if len(recovered):

    updated_cache = pd.concat(
        [
            cache,
            recovered,
        ],
        ignore_index=True,
        sort=False,
    )

else:

    updated_cache = cache.copy()


# Existing rows and recovered rows should have
# unique USDA accepted symbols.
updated_cache = (
    updated_cache
    .drop_duplicates(
        subset=[
            "USDA_accepted_symbol"
        ],
        keep="first",
    )
    .sort_values(
        "USDA_accepted_symbol"
    )
    .reset_index(
        drop=True
    )
)


updated_cache.to_csv(
    USDA_ATTRIBUTE_CACHE,
    index=False,
)


print(
    f"Updated cache taxa: "
    f"{len(updated_cache):,}"
)

print(
    f"Updated cache written to:\n"
    f"{USDA_ATTRIBUTE_CACHE}"
)


# ------------------------------------------------------------
# MEMBERSHIP QA
# ------------------------------------------------------------

updated_symbols = set(
    updated_cache[
        "USDA_accepted_symbol"
    ]
    .dropna()
    .astype(str)
    .str.strip()
)


still_absent = sorted(
    set(targets)
    - updated_symbols
)


print()
print(
    f"Recovery targets still absent "
    f"from cache: {len(still_absent):,}"
)


if still_absent:

    print(
        "First 50 still absent:"
    )

    print(
        still_absent[:50]
    )


# ------------------------------------------------------------
# TRAIT COMPLETENESS AMONG RECOVERED TAXA
# ------------------------------------------------------------

if len(recovered):

    for c in [
        "USDA_duration_api",
        "USDA_growth_habit_api",
        "USDA_L48_native_status_api",
    ]:

        n = (
            recovered[c]
            .notna()
            .sum()
            if c in recovered.columns
            else 0
        )

        print(
            f"{c}: "
            f"{n:,} / {len(recovered):,} "
            f"({n / len(recovered):.1%})"
        )


# ------------------------------------------------------------
# HIGH-PRIORITY SPECIES QA
# ------------------------------------------------------------

priority_symbols = [
    "PSSP6",
    "POPR",
    "AGCR",
    "HECO26",
    "FEID",
    "ELEL5",
    "BRIN2",
    "CHVI8",
    "ARTR2",
    "TACA8",
    "SIAL2",
    "ERCI6",
    "TRDU",
]


qa_columns = [
    x
    for x in [
        "USDA_accepted_symbol",
        "USDA_duration_api",
        "USDA_growth_habit_api",
        "USDA_L48_native_status_api",
        "USDA_L48_native_type_api",
        "USDA_rank",
        "retrieved_utc",
    ]
    if x in updated_cache.columns
]


display(
    updated_cache.loc[
        updated_cache[
            "USDA_accepted_symbol"
        ].isin(
            priority_symbols
        ),
        qa_columns,
    ]
    .sort_values(
        "USDA_accepted_symbol"
    )
)


print(
    "\nUSDA trait recovery finished."
)

Existing USDA cache taxa: 6,790
Taxa requiring recovery: 478
Previously recovered: 0
Remaining this run: 478
[001/478] PSSP6      D=None                     H=None                         L48=None
[002/478] POPR       D=None                     H=None                         L48=None
[003/478] AGCR       D=None                     H=None                         L48=None
[004/478] HECO26     D=None                     H=None                         L48=None
[005/478] FEID       D=None                     H=None                         L48=None
[006/478] ELEL5      D=None                     H=None                         L48=None
[007/478] BRIN2      D=None                     H=None                         L48=None
[008/478] CHVI8      D=None                     H=None                         L48=None
[009/478] SCAR7      D=None                     H=None                         L48=None
[010/478] ARAR8      D=None                     H=None                         L48=None
[011/478] ARTR2      D=None                     H=None                         L48=None
[012/478] TACA8      D=None                     H=None                         L48=None
[013/478] ALDE       D=None                     H=None                         L48=None
[014/478] ELLA3      D=None                     H=None                         L48=None
[015/478] POBU       D=None                     H=None                         L48=None
[016/478] SAVE4      D=None                     H=None                         L48=None
[017/478] PHHO       D=None                     H=None                         L48=None
[018/478] ARPU9      D=None                     H=None                         L48=None
[019/478] JUOC       D=None                     H=None                         L48=None
[020/478] ERNA10     D=None                     H=None                         L48=None
[021/478] ACTH7      D=None                     H=None                         L48=None
[022/478] SIAL2      D=None                     H=None                         L48=None
[023/478] ERCI6      D=None                     H=None                         L48=None
[024/478] POTR5      D=None                     H=None                         L48=None
[025/478] ATCO       D=None                     H=None                         L48=None
[026/478] ACMI2      D=None                     H=None                         L48=None
[027/478] CAREX      D=None                     H=None                         L48=None
[028/478] SYOR2      D=None                     H=None                         L48=None
[029/478] VUOC       D=None                     H=None                         L48=None
[030/478] PHLO2      D=None                     H=None                         L48=None
[031/478] DISP       D=None                     H=None                         L48=None
[032/478] AMAL2      D=None                     H=None                         L48=None
[033/478] COPA3      D=None                     H=None                         L48=None
[034/478] TAOF       D=None                     H=None                         L48=None
[035/478] DEPI       D=None                     H=None                         L48=None
[036/478] LEPE2      D=None                     H=None                         L48=None
[037/478] AMUT       D=None                     H=None                         L48=None
[038/478] HAGL       D=None                     H=None                         L48=None
[039/478] ATGA       D=None                     H=None                         L48=None
[040/478] BASA3      D=None                     H=None                         L48=None
[041/478] CELE3      D=None                     H=None                         L48=None
[042/478] ARTR4      D=None                     H=None                         L48=None
[043/478] ARCA13     D=None                     H=None                         L48=None
[044/478] PHPR3      D=None                     H=None                         L48=None
[045/478] ATCA2      D=None                     H=None                         L48=None
[046/478] BRHO2      D=None                     H=None                         L48=None
[047/478] DRVE2      D=None                     H=None                         L48=None
[048/478] PHAR3      D=None                     H=None                         L48=None
[049/478] LASE       D=None                     H=None                         L48=None
[050/478] ARLU       D=None                     H=None                         L48=None
[051/478] SYAL       D=None                     H=None                         L48=None
[052/478] GRSP       D=None                     H=None                         L48=None
[053/478] VEDU       D=None                     H=None                         L48=None
[054/478] ALAL3      D=None                     H=None                         L48=None
[055/478] VIAM       D=None                     H=None                         L48=None
[056/478] MIGR       D=None                     H=None                         L48=None
[057/478] SPCO       D=None                     H=None                         L48=None
[058/478] CRAC2      D=None                     H=None                         L48=None
[059/478] ERUM       D=None                     H=None                         L48=None
[060/478] TECA2      D=None                     H=None                         L48=None
[061/478] TRDU       D=None                     H=None                         L48=None
[062/478] LAOC3      D=None                     H=None                         L48=None
[063/478] MESA       D=None                     H=None                         L48=None
[064/478] HOJU       D=None                     H=None                         L48=None
[065/478] AGFR       D=None                     H=None                         L48=None
[066/478] CHJU       D=None                     H=None                         L48=None
[067/478] HOUM       D=None                     H=None                         L48=None
[068/478] ERTR13     D=None                     H=None                         L48=None
[069/478] PRVI       D=None                     H=None                         L48=None
[070/478] EPMI       D=None                     H=None                         L48=None
[071/478] SPORO      D=None                     H=None                         L48=None
[072/478] ROWO       D=None                     H=None                         L48=None
[073/478] ANRO2      D=None                     H=None                         L48=None
[074/478] LUPIN      D=None                     H=None                         L48=None
[075/478] LEPID      D=None                     H=None                         L48=None
[076/478] LUCA       D=None                     H=None                         L48=None
[077/478] COUM       D=None                     H=None                         L48=None
[078/478] COCA5      D=None                     H=None                         L48=None
[079/478] ACOC3      D=None                     H=None                         L48=None
[080/478] VUMI       D=None                     H=None                         L48=None
[081/478] JUNCU      D=None                     H=None                         L48=None
[082/478] ERHE2      D=None                     H=None                         L48=None
[083/478] VUMY       D=None                     H=None                         L48=None
[084/478] POA        D=None                     H=None                         L48=None
[085/478] GIIN2      D=None                     H=None                         L48=None
[086/478] MELU       D=None                     H=None                         L48=None
[087/478] VUBR       D=None                     H=None                         L48=None
[088/478] COAR4      D=None                     H=None                         L48=None
[089/478] ERMI4      D=None                     H=None                         L48=None
[090/478] BLSC       D=None                     H=None                         L48=None
[091/478] LESA4      D=None                     H=None                         L48=None
[092/478] MEAL6      D=None                     H=None                         L48=None
[093/478] TEGL       D=None                     H=None                         L48=None
[094/478] COLI2      D=None                     H=None                         L48=None
[095/478] PLLA       D=None                     H=None                         L48=None
[096/478] CIAR4      D=None                     H=None                         L48=None
[097/478] GADI2      D=None                     H=None                         L48=None
[098/478] AMTE3      D=None                     H=None                         L48=None
[099/478] CHAL7      D=None                     H=None                         L48=None
[100/478] ANPA4      D=None                     H=None                         L48=None
[101/478] LOTR2      D=None                     H=None                         L48=None
[102/478] CRYPT      D=None                     H=None                         L48=None
[103/478] PODO4      D=None                     H=None                         L48=None
[104/478] CEVE       D=None                     H=None                         L48=None
[105/478] ARKI       D=None                     H=None                         L48=None
[106/478] POCU3      D=None                     H=None                         L48=None
[107/478] ERCA8      D=None                     H=None                         L48=None
[108/478] HEAN3      D=None                     H=None                         L48=None
[109/478] ARCO5      D=None                     H=None                         L48=None
[110/478] BAHO       D=None                     H=None                         L48=None
[111/478] AGGL       D=None                     H=None                         L48=None
[112/478] FERU2      D=None                     H=None                         L48=None
[113/478] ERIOG      D=None                     H=None                         L48=None
[114/478] CHTE2      D=None                     H=None                         L48=None
[115/478] SOLID      D=None                     H=None                         L48=None
[116/478] MEBU       D=None                     H=None                         L48=None
[117/478] ANTEN      D=None                     H=None                         L48=None
[118/478] ANDI2      D=None                     H=None                         L48=None
[119/478] GRSQ       D=None                     H=None                         L48=None
[120/478] EROV       D=None                     H=None                         L48=None
[121/478] RICE       D=None                     H=None                         L48=None
[122/478] BRBR5      D=None                     H=None                         L48=None
[123/478] CHLE4      D=None                     H=None                         L48=None
[124/478] ASTRA      D=None                     H=None                         L48=None
[125/478] LILE3      D=None                     H=None                         L48=None
[126/478] ELGL       D=None                     H=None                         L48=None
[127/478] RIVE       D=None                     H=None                         L48=None
[128/478] SOMI2      D=None                     H=None                         L48=None
[129/478] SEIN2      D=None                     H=None                         L48=None
[130/478] MACA2      D=None                     H=None                         L48=None
[131/478] ERIGE2     D=None                     H=None                         L48=None
[132/478] IVAX       D=None                     H=None                         L48=None
[133/478] TRMA3      D=None                     H=None                         L48=None
[134/478] PHLOX      D=None                     H=None                         L48=None
[135/478] AGST2      D=None                     H=None                         L48=None
[136/478] IOAL       D=None                     H=None                         L48=None
[137/478] GETR       D=None                     H=None                         L48=None
[138/478] LIRU4      D=None                     H=None                         L48=None
[139/478] ASFI       D=None                     H=None                         L48=None
[140/478] RANUN      D=None                     H=None                         L48=None
[141/478] ERPU2      D=None                     H=None                         L48=None
[142/478] ARSO2      D=None                     H=None                         L48=None
[143/478] EPILO      D=None                     H=None                         L48=None
[144/478] CHAN9      D=None                     H=None                         L48=None
[145/478] TESP2      D=None                     H=None                         L48=None
[146/478] ECCR       D=None                     H=None                         L48=None
[147/478] GAAP2      D=None                     H=None                         L48=None
[148/478] NOTR2      D=None                     H=None                         L48=None
[149/478] APIN       D=None                     H=None                         L48=None
[150/478] THAR5      D=None                     H=None                         L48=None
[151/478] ALPR3      D=None                     H=None                         L48=None
[152/478] VICIA      D=None                     H=None                         L48=None
[153/478] DAUN       D=None                     H=None                         L48=None
[154/478] PHAL2      D=None                     H=None                         L48=None
[155/478] LOMAT      D=None                     H=None                         L48=None
[156/478] SYMPH      D=None                     H=None                         L48=None
[157/478] ELWA2      D=None                     H=None                         L48=None
[158/478] THPO7      D=None                     H=None                         L48=None
[159/478] GALIU      D=None                     H=None                         L48=None
[160/478] AGUR       D=None                     H=None                         L48=None
[161/478] LYJU       D=None                     H=None                         L48=None
[162/478] GEVI2      D=None                     H=None                         L48=None
[163/478] LODI       D=None                     H=None                         L48=None
[164/478] GERI       D=None                     H=None                         L48=None
[165/478] AMSIN      D=None                     H=None                         L48=None
[166/478] PSJA2      D=None                     H=None                         L48=None
[167/478] WYAM       D=None                     H=None                         L48=None
[168/478] ANUM       D=None                     H=None                         L48=None
[169/478] ERPA30     D=None                     H=None                         L48=None
[170/478] NEST5      D=None                     H=None                         L48=None
[171/478] FRVI       D=None                     H=None                         L48=None
[172/478] POGR9      D=None                     H=None                         L48=None
[173/478] HOMU       D=None                     H=None                         L48=None
[174/478] CLPA5      D=None                     H=None                         L48=None
[175/478] ASPU9      D=None                     H=None                         L48=None
[176/478] POAV       D=None                     H=None                         L48=None
[177/478] ERLI       D=None                     H=None                         L48=None
[178/478] LARA       D=None                     H=None                         L48=None
[179/478] HEMU3      D=None                     H=None                         L48=None
[180/478] SYAS3      D=None                     H=None                         L48=None
[181/478] COGR4      D=None                     H=None                         L48=None
[182/478] MAEX       D=None                     H=None                         L48=None
[183/478] PREM       D=None                     H=None                         L48=None
[184/478] CAMI2      D=None                     H=None                         L48=None
[185/478] RUCR       D=None                     H=None                         L48=None
[186/478] ERSP7      D=None                     H=None                         L48=None
[187/478] PLMA2      D=None                     H=None                         L48=None
[188/478] MAGR3      D=None                     H=None                         L48=None
[189/478] LOGR       D=None                     H=None                         L48=None
[190/478] ERSP4      D=None                     H=None                         L48=None
[191/478] LIPA5      D=None                     H=None                         L48=None
[192/478] PHLEU      D=None                     H=None                         L48=None
[193/478] LASQ       D=None                     H=None                         L48=None
[194/478] ULPU       D=None                     H=None                         L48=None
[195/478] SELA       D=None                     H=None                         L48=None
[196/478] LIGL2      D=None                     H=None                         L48=None
[197/478] ARAC2      D=None                     H=None                         L48=None
[198/478] CHENO      D=None                     H=None                         L48=None
[199/478] PHMA5      D=None                     H=None                         L48=None
[200/478] CHDO       D=None                     H=None                         L48=None
[201/478] HEUN       D=None                     H=None                         L48=None
[202/478] NONE       D=None                     H=None                         L48=None
[203/478] PHLI       D=None                     H=None                         L48=None
[204/478] AGHE2      D=None                     H=None                         L48=None
[205/478] IRMI       D=None                     H=None                         L48=None
[206/478] ZIVE       D=None                     H=None                         L48=None
[207/478] ERDI4      D=None                     H=None                         L48=None
[208/478] ERLA6      D=None                     H=None                         L48=None
[209/478] CIUN       D=None                     H=None                         L48=None
[210/478] POMI       D=None                     H=None                         L48=None
[211/478] AMAL       D=None                     H=None                         L48=None
[212/478] ERSP3      D=None                     H=None                         L48=None
[213/478] CIRSI      D=None                     H=None                         L48=None
[214/478] SAEX       D=None                     H=None                         L48=None
[215/478] CRIN4      D=None                     H=None                         L48=None
[216/478] ALLIU      D=None                     H=None                         L48=None
[217/478] ARLO6      D=None                     H=None                         L48=None
[218/478] HYCA4      D=None                     H=None                         L48=None
[219/478] GECA5      D=None                     H=None                         L48=None
[220/478] ERFI2      D=None                     H=None                         L48=None
[221/478] HACKE      D=None                     H=None                         L48=None
[222/478] XAST       D=None                     H=None                         L48=None
[223/478] ARHO2      D=None                     H=None                         L48=None
[224/478] DEDA       D=None                     H=None                         L48=None
[225/478] PHACE      D=None                     H=None                         L48=None
[226/478] VIOLA      D=None                     H=None                         L48=None

,USDA_accepted_symbol,USDA_duration_api,USDA_growth_habit_api,USDA_L48_native_status_api,USDA_L48_native_type_api,USDA_rank,retrieved_utc
131,AGCR,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:37.103993+00:00
642,ARTR2,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:45.389504+00:00
1085,BRIN2,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:41.258874+00:00
1755,CHVI8,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:42.285878+00:00
2543,ELEL5,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:40.214832+00:00
2711,ERCI6,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:02:00.927287+00:00
3093,FEID,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:39.154428+00:00
3411,HECO26,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:38.110862+00:00
5591,POPR,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:36.096027+00:00
5715,PSSP6,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:34.948611+00:00
6356,SIAL2,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:59.851556+00:00
6710,TACA8,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:01:46.552677+00:00
6890,TRDU,<NA>,<NA>,<NA>,<NA>,Species|Kingdom|Subkingdom|Superdivision|Divis...,2026-09-01T20:02:40.107413+00:00

USDA trait recovery finished.

In [ ]:
# ============================================================
# CORRECT USDA PlantProfile PARSER
# ============================================================

from datetime import datetime, timezone


def clean_text(x):
    if x is None:
        return None

    x = str(x).strip()

    if x == "" or x.lower() in {
        "nan", "none", "null", "<na>"
    }:
        return None

    return x


def unique_pipe(values):
    if values is None:
        return None

    if not isinstance(values, (list, tuple, set)):
        values = [values]

    out = []

    for value in values:
        value = clean_text(value)

        if value is not None and value not in out:
            out.append(value)

    return "|".join(out) if out else None


def parse_profile_payload(symbol, payload):
    """
    Parse ecological traits directly from the ROOT USDA PlantProfile object.

    Important:
        Do NOT recursively search the JSON.
        Ancestors contain the same field names with null values.
    """

    if not isinstance(payload, dict):
        raise TypeError(
            f"{symbol}: expected dictionary response, "
            f"got {type(payload).__name__}"
        )

    # --------------------------------------------------------
    # Verify that the returned profile corresponds to symbol
    # --------------------------------------------------------

    returned_symbol = clean_text(payload.get("Symbol"))

    if returned_symbol is not None and returned_symbol != symbol:
        raise ValueError(
            f"Requested {symbol}, USDA returned {returned_symbol}"
        )

    # --------------------------------------------------------
    # Identity
    # --------------------------------------------------------

    plant_id = payload.get("Id")
    rank = clean_text(payload.get("Rank"))

    # --------------------------------------------------------
    # Duration
    #
    # USDA JSON:
    #   "Durations": ["Perennial"]
    # --------------------------------------------------------

    duration = unique_pipe(
        payload.get("Durations")
    )

    # --------------------------------------------------------
    # Growth habit
    #
    # USDA JSON:
    #   "GrowthHabits": ["Graminoid"]
    # --------------------------------------------------------

    growth_habit = unique_pipe(
        payload.get("GrowthHabits")
    )

    # --------------------------------------------------------
    # Lower-48 native status
    #
    # USDA JSON:
    #   "NativeStatuses": [
    #       {"Region": "AK",  ...},
    #       {"Region": "CAN", ...},
    #       {"Region": "L48", "Status": "N", "Type": "Native"}
    #   ]
    # --------------------------------------------------------

    l48_status = None
    l48_type = None

    native_statuses = payload.get("NativeStatuses") or []

    for item in native_statuses:

        if not isinstance(item, dict):
            continue

        region = clean_text(
            item.get("Region")
        )

        if region == "L48":

            l48_status = clean_text(
                item.get("Status")
            )

            l48_type = clean_text(
                item.get("Type")
            )

            break

    return {
        "USDA_accepted_symbol":
            symbol,

        "USDA_plant_id":
            plant_id,

        "USDA_rank":
            rank,

        "USDA_duration_api":
            duration,

        "USDA_growth_habit_api":
            growth_habit,

        "USDA_L48_native_status_api":
            l48_status,

        "USDA_L48_native_type_api":
            l48_type,

        "retrieved_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),
    }

In [ ]:
test = parse_profile_payload(
    "PSSP6",
    payload
)

display(
    pd.DataFrame([test])
)

  USDA_accepted_symbol  USDA_plant_id USDA_rank USDA_duration_api USDA_growth_habit_api USDA_L48_native_status_api USDA_L48_native_type_api                     retrieved_utc
0                PSSP6          25163   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:12:06.349353+00:00

In [ ]:
# ============================================================
# CHECK / REMOVE BAD RECOVERY CHECKPOINT
# ============================================================

if RECOVERY_PROGRESS_FILE.exists():

    old_recovery = pd.read_csv(
        RECOVERY_PROGRESS_FILE,
        dtype="string",
        low_memory=False,
    )

    trait_cols = [
        "USDA_duration_api",
        "USDA_growth_habit_api",
        "USDA_L48_native_status_api",
    ]

    existing_trait_cols = [
        c for c in trait_cols
        if c in old_recovery.columns
    ]

    if existing_trait_cols:

        all_traits_blank = (
            old_recovery[
                existing_trait_cols
            ]
            .isna()
            .all(axis=1)
        )

        print(
            "Rows in recovery checkpoint:",
            len(old_recovery)
        )

        print(
            "Rows with all ecological traits blank:",
            int(all_traits_blank.sum())
        )

        if all_traits_blank.any():

            backup = (
                RECOVERY_PROGRESS_FILE
                .with_name(
                    RECOVERY_PROGRESS_FILE.stem
                    + "_BAD_PARSER_BACKUP.csv"
                )
            )

            old_recovery.to_csv(
                backup,
                index=False
            )

            RECOVERY_PROGRESS_FILE.unlink()

            print(
                "\nRemoved contaminated recovery checkpoint."
            )

            print(
                "Backup preserved at:"
            )

            print(backup)

        else:

            print(
                "\nExisting recovery checkpoint appears usable."
            )

else:

    print(
        "No recovery checkpoint exists. "
        "Safe to start from 0."
    )

Rows in recovery checkpoint: 478
Rows with all ecological traits blank: 478

Removed contaminated recovery checkpoint.
Backup preserved at:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\USDA_PLANTS_ecological_attributes_missing_taxa_progress_BAD_PARSER_BACKUP.csv

In [28]:
# ============================================================
# RECOVER ALL USDA TAXA MISSING FROM THE TRAIT CACHE
# USING CORRECT ROOT-LEVEL PlantProfile PARSER
# ============================================================

from pathlib import Path
from datetime import datetime, timezone
import time
import pandas as pd
import requests


# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

USDA_SERVICE_BASE = "https://plantsservices.sc.egov.usda.gov/api"

REQUEST_TIMEOUT = 30
REQUEST_DELAY_SECONDS = 0.25
MAX_RETRIES = 3
SAVE_EVERY = 20

OUTPUT_DIR = Path(OUTPUT_DIR)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RECOVERY_PROGRESS_FILE = (
    OUTPUT_DIR /
    "USDA_PLANTS_ecological_attributes_missing_taxa_progress.csv"
)

RECOVERY_FAILURE_FILE = (
    OUTPUT_DIR /
    "USDA_PLANTS_ecological_attributes_missing_taxa_failures.csv"
)


# ------------------------------------------------------------
# HELPERS
# ------------------------------------------------------------

def clean_text(x):
    if x is None:
        return None

    x = str(x).strip()

    if x == "" or x.lower() in {
        "nan",
        "none",
        "null",
        "<na>",
    }:
        return None

    return x


def unique_pipe(values):
    """
    Preserve multiple USDA values such as:
        Annual|Biennial|Perennial
    """

    if values is None:
        return None

    if not isinstance(values, (list, tuple, set)):
        values = [values]

    out = []

    for value in values:
        value = clean_text(value)

        if value is not None and value not in out:
            out.append(value)

    return "|".join(out) if out else None


# ------------------------------------------------------------
# CORRECT USDA PlantProfile PARSER
# ------------------------------------------------------------

def parse_profile_payload(symbol, payload):
    """
    Parse ONLY the root PlantProfile object.

    USDA root fields:
        Id
        Symbol
        Rank
        Durations
        GrowthHabits
        NativeStatuses

    Do not recursively traverse Ancestors because those objects
    repeat these field names with null values.
    """

    if not isinstance(payload, dict):
        raise TypeError(
            f"{symbol}: expected dict response, "
            f"got {type(payload).__name__}"
        )

    returned_symbol = clean_text(
        payload.get("Symbol")
    )

    if (
        returned_symbol is not None
        and returned_symbol != symbol
    ):
        raise ValueError(
            f"Requested {symbol}, USDA returned "
            f"{returned_symbol}"
        )

    plant_id = payload.get("Id")
    rank = clean_text(
        payload.get("Rank")
    )

    duration = unique_pipe(
        payload.get("Durations")
    )

    growth_habit = unique_pipe(
        payload.get("GrowthHabits")
    )

    l48_status = None
    l48_type = None

    native_statuses = (
        payload.get("NativeStatuses")
        or []
    )

    for item in native_statuses:

        if not isinstance(item, dict):
            continue

        region = clean_text(
            item.get("Region")
        )

        if region == "L48":

            l48_status = clean_text(
                item.get("Status")
            )

            l48_type = clean_text(
                item.get("Type")
            )

            break

    return {
        "USDA_accepted_symbol":
            symbol,

        "USDA_plant_id":
            plant_id,

        "USDA_rank":
            rank,

        "USDA_duration_api":
            duration,

        "USDA_growth_habit_api":
            growth_habit,

        "USDA_L48_native_status_api":
            l48_status,

        "USDA_L48_native_type_api":
            l48_type,

        "retrieved_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),
    }


# ------------------------------------------------------------
# FETCH ONE USDA PROFILE
# ------------------------------------------------------------

def fetch_usda_traits(symbol):

    url = (
        f"{USDA_SERVICE_BASE}/PlantProfile"
    )

    last_error = None

    for attempt in range(
        1,
        MAX_RETRIES + 1,
    ):

        try:

            response = requests.get(
                url,
                params={
                    "symbol": symbol
                },
                timeout=REQUEST_TIMEOUT,
                headers={
                    "Accept":
                        "application/json",

                    "User-Agent":
                        "MOSAIC-USDA-trait-recovery/1.1",
                },
            )

            response.raise_for_status()

            payload = response.json()

            result = parse_profile_payload(
                symbol,
                payload,
            )

            # A profile is considered successfully recovered
            # if USDA returned the requested symbol/profile.
            # Traits may legitimately be blank for some taxa.
            if (
                result["USDA_accepted_symbol"]
                == symbol
            ):
                return result

        except Exception as exc:

            last_error = exc


        if attempt < MAX_RETRIES:

            wait = (
                REQUEST_DELAY_SECONDS
                * (2 ** (attempt - 1))
            )

            time.sleep(wait)

    raise RuntimeError(
        f"{symbol}: {repr(last_error)}"
    )


# ------------------------------------------------------------
# LOAD EXISTING MAIN CACHE
# ------------------------------------------------------------

cache = pd.read_csv(
    USDA_ATTRIBUTE_CACHE,
    dtype="string",
    low_memory=False,
).copy()


# Normalize historical cache schema
column_aliases = {
    "accepted_symbol":
        "USDA_accepted_symbol",

    "USDA_duration":
        "USDA_duration_api",

    "USDA_growth_habit":
        "USDA_growth_habit_api",

    "USDA_native_status_L48":
        "USDA_L48_native_status_api",
}


for old, new in column_aliases.items():

    if (
        old in cache.columns
        and new not in cache.columns
    ):

        cache = cache.rename(
            columns={
                old: new
            }
        )


if (
    "USDA_accepted_symbol"
    not in cache.columns
):

    raise ValueError(
        "No USDA accepted-symbol field "
        "found in ecological trait cache."
    )


cache[
    "USDA_accepted_symbol"
] = (
    cache[
        "USDA_accepted_symbol"
    ]
    .astype("string")
    .str.strip()
)


cached_symbols = set(
    cache[
        "USDA_accepted_symbol"
    ]
    .dropna()
)


print(
    f"Existing USDA cache taxa: "
    f"{len(cached_symbols):,}"
)


# ------------------------------------------------------------
# DEFINE RECOVERY TARGETS FROM CURRENT DICTIONARY
# ------------------------------------------------------------

targets = (
    missing_trait_taxa[
        "USDA_accepted_symbol"
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
    .tolist()
)


# Never query anything already in main cache
targets = [
    symbol
    for symbol in targets
    if symbol not in cached_symbols
]


print(
    f"Taxa requiring recovery: "
    f"{len(targets):,}"
)


# ------------------------------------------------------------
# LOAD PRIOR GOOD RECOVERY PROGRESS, IF ANY
# ------------------------------------------------------------

if RECOVERY_PROGRESS_FILE.exists():

    recovered = pd.read_csv(
        RECOVERY_PROGRESS_FILE,
        dtype="string",
        low_memory=False,
    )

    if (
        "USDA_accepted_symbol"
        not in recovered.columns
    ):
        raise ValueError(
            "Recovery progress file does not "
            "contain USDA_accepted_symbol."
        )

    recovered[
        "USDA_accepted_symbol"
    ] = (
        recovered[
            "USDA_accepted_symbol"
        ]
        .astype("string")
        .str.strip()
    )

    recovered_symbols = set(
        recovered[
            "USDA_accepted_symbol"
        ]
        .dropna()
    )

else:

    recovered = pd.DataFrame()

    recovered_symbols = set()


remaining = [
    symbol
    for symbol in targets
    if symbol not in recovered_symbols
]


print(
    f"Previously recovered: "
    f"{len(recovered_symbols):,}"
)

print(
    f"Remaining this run: "
    f"{len(remaining):,}"
)


# ------------------------------------------------------------
# RECOVERY LOOP
# ------------------------------------------------------------

pending_rows = []
pending_failures = []


for i, symbol in enumerate(
    remaining,
    start=1,
):

    try:

        row = fetch_usda_traits(
            symbol
        )

        pending_rows.append(
            row
        )

        print(
            f"[{i:03d}/{len(remaining):03d}] "
            f"{symbol:<10} "
            f"D={str(row['USDA_duration_api']):<24} "
            f"H={str(row['USDA_growth_habit_api']):<28} "
            f"L48={str(row['USDA_L48_native_type_api'])}"
        )

    except Exception as exc:

        pending_failures.append(
            {
                "USDA_accepted_symbol":
                    symbol,

                "error":
                    repr(exc),

                "failed_utc":
                    datetime.now(
                        timezone.utc
                    ).isoformat(),
            }
        )

        print(
            f"[{i:03d}/{len(remaining):03d}] "
            f"{symbol:<10} FAILED | "
            f"{repr(exc)}"
        )


    # --------------------------------------------------------
    # PERIODIC CHECKPOINT
    # --------------------------------------------------------

    if (
        i % SAVE_EVERY == 0
        or i == len(remaining)
    ):

        # Save successful recoveries
        if pending_rows:

            batch = pd.DataFrame(
                pending_rows
            )

            if recovered.empty:

                recovered = (
                    batch.copy()
                )

            else:

                recovered = pd.concat(
                    [
                        recovered,
                        batch,
                    ],
                    ignore_index=True,
                    sort=False,
                )


            recovered = (
                recovered
                .drop_duplicates(
                    subset=[
                        "USDA_accepted_symbol"
                    ],
                    keep="last",
                )
                .sort_values(
                    "USDA_accepted_symbol"
                )
                .reset_index(
                    drop=True
                )
            )


            recovered.to_csv(
                RECOVERY_PROGRESS_FILE,
                index=False,
            )

            pending_rows = []


        # Save failures
        if pending_failures:

            fail_batch = pd.DataFrame(
                pending_failures
            )

            if RECOVERY_FAILURE_FILE.exists():

                prior_failures = pd.read_csv(
                    RECOVERY_FAILURE_FILE,
                    dtype="string",
                    low_memory=False,
                )

                fail_batch = pd.concat(
                    [
                        prior_failures,
                        fail_batch,
                    ],
                    ignore_index=True,
                    sort=False,
                )


            fail_batch = (
                fail_batch
                .drop_duplicates(
                    subset=[
                        "USDA_accepted_symbol",
                        "error",
                    ],
                    keep="last",
                )
                .reset_index(
                    drop=True
                )
            )


            fail_batch.to_csv(
                RECOVERY_FAILURE_FILE,
                index=False,
            )

            pending_failures = []


    time.sleep(
        REQUEST_DELAY_SECONDS
    )


# ------------------------------------------------------------
# RELOAD COMPLETE RECOVERY TABLE
# ------------------------------------------------------------

if RECOVERY_PROGRESS_FILE.exists():

    recovered = pd.read_csv(
        RECOVERY_PROGRESS_FILE,
        dtype="string",
        low_memory=False,
    )

else:

    recovered = pd.DataFrame()


print()
print(
    f"Successfully recovered taxa: "
    f"{len(recovered):,}"
)


# ------------------------------------------------------------
# APPEND RECOVERED TAXA TO MAIN CACHE
# ------------------------------------------------------------

if not recovered.empty:

    updated_cache = pd.concat(
        [
            cache,
            recovered,
        ],
        ignore_index=True,
        sort=False,
    )

else:

    updated_cache = cache.copy()


# Existing cached symbols should never be overwritten.
# Since recovery targets excluded existing symbols, duplicates
# should not normally exist.
updated_cache = (
    updated_cache
    .drop_duplicates(
        subset=[
            "USDA_accepted_symbol"
        ],
        keep="first",
    )
    .sort_values(
        "USDA_accepted_symbol"
    )
    .reset_index(
        drop=True
    )
)


updated_cache.to_csv(
    USDA_ATTRIBUTE_CACHE,
    index=False,
)


print(
    f"Updated USDA cache taxa: "
    f"{len(updated_cache):,}"
)

print(
    f"Updated cache written to:\n"
    f"{USDA_ATTRIBUTE_CACHE}"
)


# ------------------------------------------------------------
# QA 1 — ARE ANY TARGET SYMBOLS STILL ABSENT?
# ------------------------------------------------------------

updated_symbols = set(
    updated_cache[
        "USDA_accepted_symbol"
    ]
    .dropna()
    .astype(str)
    .str.strip()
)


still_absent = sorted(
    set(targets)
    - updated_symbols
)


print()
print(
    f"Recovery targets still absent "
    f"from cache: {len(still_absent):,}"
)


if still_absent:

    print(
        "First 50 absent symbols:"
    )

    print(
        still_absent[:50]
    )


# ------------------------------------------------------------
# QA 2 — TRAIT COMPLETENESS IN RECOVERED TAXA
# ------------------------------------------------------------

if len(recovered):

    print(
        "\nRecovered-taxon trait completeness:"
    )

    for col in [
        "USDA_duration_api",
        "USDA_growth_habit_api",
        "USDA_L48_native_status_api",
    ]:

        n_present = (
            recovered[col]
            .notna()
            .sum()
            if col in recovered.columns
            else 0
        )

        print(
            f"{col}: "
            f"{n_present:,} / {len(recovered):,} "
            f"({n_present / len(recovered):.2%})"
        )


# ------------------------------------------------------------
# QA 3 — HIGH-PRIORITY SPECIES
# ------------------------------------------------------------

priority_symbols = [
    "PSSP6",
    "POPR",
    "AGCR",
    "HECO26",
    "FEID",
    "ELEL5",
    "BRIN2",
    "CHVI8",
    "SCAR7",
    "ARTR2",
    "TACA8",
    "ALDE",
    "SIAL2",
    "ERCI6",
    "TRDU",
]


qa_cols = [
    col
    for col in [
        "USDA_accepted_symbol",
        "USDA_plant_id",
        "USDA_rank",
        "USDA_duration_api",
        "USDA_growth_habit_api",
        "USDA_L48_native_status_api",
        "USDA_L48_native_type_api",
        "retrieved_utc",
    ]
    if col in updated_cache.columns
]


display(
    updated_cache.loc[
        updated_cache[
            "USDA_accepted_symbol"
        ].isin(
            priority_symbols
        ),
        qa_cols,
    ]
    .sort_values(
        "USDA_accepted_symbol"
    )
)


print(
    "\nUSDA missing-taxon recovery complete."
)

print(
    "Next: reload this updated cache into dictionary_fg "
    "and rerun record-weighted cache coverage."
)

Existing USDA cache taxa: 7,268
Taxa requiring recovery: 1
Previously recovered: 0
Remaining this run: 1
[001/001] PONIN      D=Perennial                H=Forb/herb|Subshrub           L48=Native

Successfully recovered taxa: 1
Updated USDA cache taxa: 7,269
Updated cache written to:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\USDA_PLANTS_ecological_attributes.csv

Recovery targets still absent from cache: 0

Recovered-taxon trait completeness:
USDA_duration_api: 1 / 1 (100.00%)
USDA_growth_habit_api: 1 / 1 (100.00%)
USDA_L48_native_status_api: 1 / 1 (100.00%)

     USDA_accepted_symbol USDA_plant_id USDA_rank USDA_duration_api USDA_growth_habit_api USDA_L48_native_status_api USDA_L48_native_type_api                     retrieved_utc
131                  AGCR       20068.0   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:19:14.115727+00:00
207                  ALDE       61805.0   Species            Annual             Forb/herb                          I               Introduced  2026-09-01T20:19:23.118227+00:00
642                 ARTR2       32390.0   Species         Perennial            Shrub|Tree                          N                   Native  2026-09-01T20:19:59.612017+00:00
1085                BRIN2       20954.0   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:20:20.233090+00:00
1755                CHVI8       33492.0   Species         Perennial                 Shrub                          N                   Native  2026-09-01T20:20:52.319662+00:00
2543                ELEL5       22420.0   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:21:38.980060+00:00
2711                ERCI6       83665.0   Species   Annual|Biennial             Forb/herb                          I               Introduced  2026-09-01T20:21:59.522310+00:00
3093                 FEID       23094.0   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:22:28.108292+00:00
3411               HECO26       23323.0   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:22:52.765229+00:00
5592                 POPR       25028.0   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:25:09.294033+00:00
5716                PSSP6       25163.0   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:25:16.932182+00:00
6191                SCAR7       25394.0   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:25:48.164445+00:00
6357                SIAL2       63983.0   Species   Annual|Biennial             Forb/herb                          I               Introduced  2026-09-01T20:25:53.358516+00:00
6711                TACA8       25969.0   Species            Annual             Graminoid                          I               Introduced  2026-09-01T20:26:19.358376+00:00
6891                 TRDU       41535.0   Species   Annual|Biennial             Forb/herb                          I               Introduced  2026-09-01T20:26:28.390058+00:00

USDA missing-taxon recovery complete.
Next: reload this updated cache into dictionary_fg and rerun record-weighted cache coverage.

In [30]:
# ============================================================================
# FINAL REPAIR — REJOIN REPAIRED USDA ECOLOGICAL ATTRIBUTES
# AND OVERWRITE LDC_LPI_species_dictionary_FINAL_MASTER.csv
# ============================================================================

from pathlib import Path
import shutil
import pandas as pd
import numpy as np
from datetime import datetime


# ============================================================================
# PATHS
# ============================================================================

FINAL_MASTER_PATH = (
    Path(r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present")
    / "species_dictionary_outputs"
    / "LDC_LPI_species_dictionary_FINAL_MASTER.csv"
)

USDA_TRAIT_PATH = (
    Path(r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present")
    / "species_dictionary_outputs"
    / "USDA_PLANTS_ecological_attributes.csv"
)

assert FINAL_MASTER_PATH.exists(), FINAL_MASTER_PATH
assert USDA_TRAIT_PATH.exists(), USDA_TRAIT_PATH

print("FINAL MASTER:")
print(FINAL_MASTER_PATH)

print("\nUSDA trait cache:")
print(USDA_TRAIT_PATH)


# ============================================================================
# 1. READ CURRENT FINAL MASTER + REPAIRED USDA TRAIT CACHE
# ============================================================================

master = pd.read_csv(
    FINAL_MASTER_PATH,
    dtype="string",
    keep_default_na=True
)

traits = pd.read_csv(
    USDA_TRAIT_PATH,
    dtype="string",
    keep_default_na=True
)

print("\nLoaded:")
print(f"  final master: {len(master):,} rows")
print(f"  USDA cache:   {len(traits):,} rows")


# ============================================================================
# 2. BASIC FINAL-MASTER INVARIANTS BEFORE TOUCHING ANYTHING
# ============================================================================

assert len(master) == 10960, (
    f"Unexpected FINAL_MASTER row count: {len(master):,}"
)

assert master["observed_code"].nunique(dropna=False) == 10960, (
    "FINAL_MASTER observed_code is no longer unique."
)

assert "USDA_accepted_symbol" in master.columns
assert "MOSAIC_FG" in master.columns


# ============================================================================
# 3. NORMALIZATION HELPERS
# ============================================================================

def clean_string(s):
    """
    Normalize blanks/whitespace to pandas NA while preserving string content.
    """
    s = s.astype("string").str.strip()
    return s.mask(s.eq(""))


def first_existing(df, candidates, required=False):
    """
    Return first existing column name from candidates.
    """
    for c in candidates:
        if c in df.columns:
            return c

    if required:
        raise KeyError(
            "None of these expected columns were found:\n"
            + "\n".join(candidates)
        )

    return None


# Normalize master key.
master["USDA_accepted_symbol"] = (
    clean_string(master["USDA_accepted_symbol"])
    .str.upper()
)


# ============================================================================
# 4. DETECT ACTUAL USDA CACHE SCHEMA
#
# The repaired cache has changed slightly during development, so explicitly
# map the fields rather than assuming a single historical column spelling.
# ============================================================================

trait_symbol_col = first_existing(
    traits,
    [
        "USDA_accepted_symbol",
        "USDA_symbol",
        "AcceptedSymbol",
        "accepted_symbol",
        "symbol",
    ],
    required=True,
)

duration_col = first_existing(
    traits,
    [
        "USDA_duration",
        "USDA_duration_api",
        "Duration",
        "duration",
    ],
    required=True,
)

growth_col = first_existing(
    traits,
    [
        "USDA_growth_habit",
        "USDA_growth_habit_api",
        "GrowthHabit",
        "GrowthHabitName",
        "growth_habit",
    ],
    required=True,
)

native_col = first_existing(
    traits,
    [
        "USDA_native_status_L48",
        "USDA_L48_native_status_api",
        "USDA_native_status",
        "NativeStatus_L48",
        "native_status_L48",
    ],
    required=True,
)

print("\nDetected USDA-cache fields:")
print("  symbol:      ", trait_symbol_col)
print("  duration:    ", duration_col)
print("  growth habit:", growth_col)
print("  L48 nativity:", native_col)


# ============================================================================
# 5. BUILD ONE-ROW-PER-USDA-SYMBOL TRAIT LOOKUP
# ============================================================================

trait_lookup = traits[
    [
        trait_symbol_col,
        duration_col,
        growth_col,
        native_col,
    ]
].copy()

trait_lookup = trait_lookup.rename(
    columns={
        trait_symbol_col: "_USDA_JOIN_SYMBOL",
        duration_col: "_repair_duration",
        growth_col: "_repair_growth_habit",
        native_col: "_repair_native_L48",
    }
)

trait_lookup["_USDA_JOIN_SYMBOL"] = (
    clean_string(trait_lookup["_USDA_JOIN_SYMBOL"])
    .str.upper()
)

for c in [
    "_repair_duration",
    "_repair_growth_habit",
    "_repair_native_L48",
]:
    trait_lookup[c] = clean_string(trait_lookup[c])


# Remove empty symbols.
trait_lookup = trait_lookup.loc[
    trait_lookup["_USDA_JOIN_SYMBOL"].notna()
].copy()


# We must have at most one ecological-trait row per USDA symbol.
duplicate_symbols = (
    trait_lookup[
        trait_lookup["_USDA_JOIN_SYMBOL"].duplicated(keep=False)
    ]
    .sort_values("_USDA_JOIN_SYMBOL")
)

if len(duplicate_symbols):
    print("\nWARNING: duplicate USDA symbols in ecological cache:")
    display(duplicate_symbols.head(50))

    # Collapse only when duplicate rows are ecologically identical.
    conflict_check = (
        trait_lookup
        .groupby("_USDA_JOIN_SYMBOL", dropna=False)
        .agg(
            n_duration=("_repair_duration", "nunique"),
            n_growth=("_repair_growth_habit", "nunique"),
            n_native=("_repair_native_L48", "nunique"),
        )
        .reset_index()
    )

    true_conflicts = conflict_check.loc[
        (conflict_check["n_duration"] > 1)
        | (conflict_check["n_growth"] > 1)
        | (conflict_check["n_native"] > 1)
    ]

    assert len(true_conflicts) == 0, (
        "USDA ecological cache contains conflicting duplicate symbols. "
        "Do not collapse them automatically."
    )

trait_lookup = (
    trait_lookup
    .drop_duplicates("_USDA_JOIN_SYMBOL", keep="first")
    .reset_index(drop=True)
)

print(
    "\nUnique USDA symbols available for trait repair:",
    f"{len(trait_lookup):,}"
)


# ============================================================================
# 6. JOIN TRAITS ONTO CURRENT FINAL MASTER
# ============================================================================

before_n = len(master)

master = master.merge(
    trait_lookup,
    left_on="USDA_accepted_symbol",
    right_on="_USDA_JOIN_SYMBOL",
    how="left",
    validate="many_to_one",
)

assert len(master) == before_n


# ============================================================================
# 7. ENSURE TARGET COLUMNS EXIST
# ============================================================================

for c in [
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status_L48",
    "USDA_trait_status",
    "USDA_derived_group",
    "resolved_plant_group",
    "MOSAIC_FG",
    "FG_resolution_source",
]:
    if c not in master.columns:
        master[c] = pd.NA


for c in [
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status_L48",
]:
    master[c] = clean_string(master[c])


# ============================================================================
# 8. FILL ONLY MISSING ECOLOGICAL TRAITS
#
# Existing valid values win.
# Repaired cache is used only where FINAL_MASTER is blank.
# ============================================================================

missing_duration_before = master["USDA_duration"].isna()
missing_growth_before = master["USDA_growth_habit"].isna()
missing_native_before = master["USDA_native_status_L48"].isna()

master["USDA_duration"] = (
    master["USDA_duration"]
    .fillna(master["_repair_duration"])
)

master["USDA_growth_habit"] = (
    master["USDA_growth_habit"]
    .fillna(master["_repair_growth_habit"])
)

master["USDA_native_status_L48"] = (
    master["USDA_native_status_L48"]
    .fillna(master["_repair_native_L48"])
)

duration_repaired = (
    missing_duration_before
    & master["USDA_duration"].notna()
)

growth_repaired = (
    missing_growth_before
    & master["USDA_growth_habit"].notna()
)

native_repaired = (
    missing_native_before
    & master["USDA_native_status_L48"].notna()
)

print("\nTrait values repaired:")
print(f"  duration:     {duration_repaired.sum():,}")
print(f"  growth habit: {growth_repaired.sum():,}")
print(f"  L48 nativity: {native_repaired.sum():,}")


# ============================================================================
# 9. STANDARDIZE TRAIT TEXT FOR ECOLOGICAL PARSING
# ============================================================================

duration = (
    master["USDA_duration"]
    .fillna("")
    .str.lower()
)

growth = (
    master["USDA_growth_habit"]
    .fillna("")
    .str.lower()
)

native = (
    master["USDA_native_status_L48"]
    .fillna("")
    .str.lower()
)


# ============================================================================
# 10. DERIVE USDA ECOLOGICAL GROUP
#
# This is intentionally conservative.
#
# Priority:
#   tree
#   shrub/subshrub
#   graminoid -> annual/perennial
#   forb/herb -> exotic/native
#
# Ambiguous/missing combinations stay unresolved rather than being guessed.
# ============================================================================

derived = pd.Series(
    pd.NA,
    index=master.index,
    dtype="string"
)


# --------------------------------------------------------------------------
# Trees
# --------------------------------------------------------------------------

tree_mask = growth.str.contains(
    r"\btree\b",
    regex=True,
    na=False,
)

derived.loc[tree_mask] = "Tree"


# --------------------------------------------------------------------------
# Shrubs / subshrubs
# --------------------------------------------------------------------------

shrub_mask = (
    derived.isna()
    & growth.str.contains(
        r"shrub|subshrub",
        regex=True,
        na=False,
    )
)

derived.loc[shrub_mask] = "Shrub"


# --------------------------------------------------------------------------
# Graminoids
#
# USDA growth-habit strings commonly contain Graminoid or Grass.
# --------------------------------------------------------------------------

graminoid_mask = (
    derived.isna()
    & growth.str.contains(
        r"graminoid|grass|grass-like",
        regex=True,
        na=False,
    )
)

annual_mask = duration.str.contains(
    r"annual",
    regex=True,
    na=False,
)

biennial_mask = duration.str.contains(
    r"biennial",
    regex=True,
    na=False,
)

perennial_mask = duration.str.contains(
    r"perennial",
    regex=True,
    na=False,
)


derived.loc[
    graminoid_mask
    & annual_mask
    & ~perennial_mask
] = "AnnualGrass"

derived.loc[
    graminoid_mask
    & perennial_mask
] = "PerennialGrass"


# --------------------------------------------------------------------------
# Forbs / herbs
# --------------------------------------------------------------------------

forb_mask = (
    derived.isna()
    & growth.str.contains(
        r"forb|herb",
        regex=True,
        na=False,
    )
)


# Native-status interpretation:
#
# Treat explicit "introduced", "non-native", "not native", "exotic",
# or "alien" language as exotic.
#
# Treat explicit native presence as native unless an exotic marker is also
# present.
# --------------------------------------------------------------------------

exotic_mask = native.str.contains(
    r"introduced|non[- ]?native|not native|exotic|alien",
    regex=True,
    na=False,
)

native_mask = (
    native.str.contains(
        r"\bnative\b",
        regex=True,
        na=False,
    )
    & ~exotic_mask
)


derived.loc[
    forb_mask
    & exotic_mask
] = "ExoticForb"

derived.loc[
    forb_mask
    & native_mask
] = "NativeForb"


master["USDA_derived_group"] = derived


# ============================================================================
# 11. REBUILD USDA TRAIT STATUS
# ============================================================================

def trait_status_row(row):

    code_class = row.get("code_class")

    # pd.NA must be handled explicitly before comparison.
    if pd.isna(code_class):
        return pd.NA

    if str(code_class).strip() != "Plant":
        return pd.NA

    accepted_symbol = row.get(
        "USDA_accepted_symbol"
    )

    if pd.isna(accepted_symbol):
        return "No_USDA_taxon"

    missing = []

    duration = row.get(
        "USDA_duration"
    )

    growth_habit = row.get(
        "USDA_growth_habit"
    )

    nativity = row.get(
        "USDA_native_status_L48"
    )

    derived_group = row.get(
        "USDA_derived_group"
    )

    if pd.isna(duration):
        missing.append("duration")

    if pd.isna(growth_habit):
        missing.append("growth_habit")

    if pd.isna(nativity):
        missing.append("nativity")

    if missing:
        return (
            "Missing_"
            + "_".join(missing)
        )

    if pd.isna(derived_group):
        return "Traits_present_group_unresolved"

    return "Traits_complete"


master["USDA_trait_status"] = (
    master.apply(
        trait_status_row,
        axis=1,
    )
)

print(
    "USDA trait-status rebuild complete."
)

display(
    master["USDA_trait_status"]
    .value_counts(
        dropna=False
    )
    .rename_axis(
        "USDA_trait_status"
    )
    .reset_index(
        name="n_codes"
    )
)


# ============================================================================
# 12. UPDATE FUNCTIONAL GROUP ONLY WHERE USDA TRAITS WERE THE MISSING PIECE
#
# Preserve:
#   - manual ecological overrides
#   - protocol-derived classifications
#   - existing resolved MOSAIC_FG
#
# Replace only:
#   - TraitUnresolvedPlant
#   - blank MOSAIC_FG on Plant rows
#   - USDA_taxon_missing_traits provenance
# ============================================================================

current_fg = clean_string(master["MOSAIC_FG"])

repairable_fg = (
    master["code_class"].eq("Plant")
    & master["USDA_derived_group"].notna()
    & (
        current_fg.isna()
        | current_fg.eq("TraitUnresolvedPlant")
        | master["FG_resolution_source"].eq(
            "USDA_taxon_missing_traits"
        )
    )
)

master.loc[
    repairable_fg,
    "resolved_plant_group"
] = master.loc[
    repairable_fg,
    "USDA_derived_group"
]

master.loc[
    repairable_fg,
    "MOSAIC_FG"
] = master.loc[
    repairable_fg,
    "USDA_derived_group"
]

master.loc[
    repairable_fg,
    "FG_resolution_source"
] = "USDA_ecological_traits"

print(
    "\nFunctional-group rows repaired:",
    f"{repairable_fg.sum():,}"
)


# ============================================================================
# 13. RESTORE KNOWN MANUAL ECOLOGICAL OVERRIDES
#
# These explicitly outrank generic USDA-derived traits.
# ============================================================================

bassia_override = master["observed_code"].isin(
    ["BAPRV", "BAPRG"]
)

master.loc[
    bassia_override,
    "resolved_plant_group"
] = "Forb"

master.loc[
    bassia_override,
    "MOSAIC_FG"
] = "ExoticForb"

master.loc[
    bassia_override,
    "FG_resolution_source"
] = "manual_ecological_functional_override"


# ============================================================================
# 14. HARD QA — STRUCTURE
# ============================================================================

assert len(master) == 10960

assert master["observed_code"].nunique(dropna=False) == 10960

assert not master["observed_code"].isna().any()


# ============================================================================
# 15. HARD QA — SENTINELS / KNOWN REPAIRS
# ============================================================================

no_canopy = master.loc[
    master["observed_code"].eq("__NO_CANOPY__")
]

literal_none = master.loc[
    master["observed_code"].eq("NONE")
]

poar = master.loc[
    master["observed_code"].eq("POAR2R2")
]

assert len(no_canopy) == 1
assert len(literal_none) == 1
assert len(poar) == 1

assert (
    no_canopy.iloc[0]["MOSAIC_FG"]
    == "NO_CANOPY"
)

assert (
    poar.iloc[0]["USDA_accepted_symbol"]
    == "PONIN"
)


# ============================================================================
# 16. QA — COMMON TAXA SHOULD NOW HAVE TRAITS
# ============================================================================

common_codes = [
    "PSSP6",
    "POPR",
    "AGCR",
    "HECO26",
    "FEID",
    "ELEL5",
    "CHVI8",
    "ARTR2",
    "TACA8",
    "ERCI6",
]

common_qa = master.loc[
    master["observed_code"].isin(common_codes),
    [
        "observed_code",
        "USDA_accepted_symbol",
        "USDA_scientific_name",
        "USDA_duration",
        "USDA_growth_habit",
        "USDA_native_status_L48",
        "USDA_trait_status",
        "USDA_derived_group",
        "MOSAIC_FG",
        "FG_resolution_source",
        "n_records",
    ]
].sort_values(
    "observed_code"
)

print("\nCommon-taxon QA:")
display(common_qa)


# ============================================================================
# 17. COVERAGE QA
# ============================================================================

plant = master["code_class"].eq("Plant")

resolved_usda = (
    plant
    & master["USDA_accepted_symbol"].notna()
)

coverage = pd.DataFrame(
    {
        "metric": [
            "Plant codes",
            "USDA-resolved plant codes",
            "USDA-resolved with duration",
            "USDA-resolved with growth habit",
            "USDA-resolved with L48 nativity",
            "USDA-resolved with all 3 traits",
            "Plant codes still TraitUnresolvedPlant",
        ],
        "n": [
            int(plant.sum()),
            int(resolved_usda.sum()),
            int(
                (
                    resolved_usda
                    & master["USDA_duration"].notna()
                ).sum()
            ),
            int(
                (
                    resolved_usda
                    & master["USDA_growth_habit"].notna()
                ).sum()
            ),
            int(
                (
                    resolved_usda
                    & master["USDA_native_status_L48"].notna()
                ).sum()
            ),
            int(
                (
                    resolved_usda
                    & master["USDA_duration"].notna()
                    & master["USDA_growth_habit"].notna()
                    & master["USDA_native_status_L48"].notna()
                ).sum()
            ),
            int(
                (
                    plant
                    & master["MOSAIC_FG"].eq(
                        "TraitUnresolvedPlant"
                    )
                ).sum()
            ),
        ],
    }
)

print("\nTrait / FG coverage after repair:")
display(coverage)


# ============================================================================
# 18. REMOVE TEMPORARY JOIN COLUMNS
# ============================================================================

master = master.drop(
    columns=[
        "_USDA_JOIN_SYMBOL",
        "_repair_duration",
        "_repair_growth_habit",
        "_repair_native_L48",
    ],
    errors="ignore",
)


# ============================================================================
# 19. BACK UP CURRENT FILE, THEN OVERWRITE FINAL MASTER
#
# The requested product is overwritten, but we retain one timestamped backup
# of the pre-repair file for auditability.
# ============================================================================

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

backup_path = FINAL_MASTER_PATH.with_name(
    FINAL_MASTER_PATH.stem
    + f"_PRE_TRAIT_REPAIR_{timestamp}"
    + FINAL_MASTER_PATH.suffix
)

shutil.copy2(
    FINAL_MASTER_PATH,
    backup_path,
)

master.to_csv(
    FINAL_MASTER_PATH,
    index=False,
)


# ============================================================================
# 20. READ BACK FROM DISK AND VERIFY THE ACTUAL WRITTEN PRODUCT
# ============================================================================

check = pd.read_csv(
    FINAL_MASTER_PATH,
    dtype="string",
)

assert len(check) == 10960
assert check["observed_code"].nunique(dropna=False) == 10960

assert (
    check.loc[
        check["observed_code"].eq("POAR2R2"),
        "USDA_accepted_symbol",
    ].iloc[0]
    == "PONIN"
)

assert (
    check.loc[
        check["observed_code"].eq("__NO_CANOPY__"),
        "MOSAIC_FG",
    ].iloc[0]
    == "NO_CANOPY"
)


print("\n" + "=" * 80)
print("FINAL MASTER USDA TRAIT REPAIR COMPLETE")
print("=" * 80)

print("\nBackup of pre-repair master:")
print(backup_path)

print("\nOverwritten FINAL_MASTER:")
print(FINAL_MASTER_PATH)

print("\nRows:", f"{len(check):,}")
print(
    "Unique observed codes:",
    f"{check['observed_code'].nunique(dropna=False):,}"
)

print("\nDONE")

FINAL MASTER:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\LDC_LPI_species_dictionary_FINAL_MASTER.csv

USDA trait cache:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\USDA_PLANTS_ecological_attributes.csv

Loaded:
  final master: 10,960 rows
  USDA cache:   7,269 rows

Detected USDA-cache fields:
  symbol:       USDA_accepted_symbol
  duration:     USDA_duration_api
  growth habit: USDA_growth_habit_api
  L48 nativity: USDA_L48_native_status_api

Unique USDA symbols available for trait repair: 7,269

Trait values repaired:
  duration:     497
  growth habit: 497
  L48 nativity: 497
USDA trait-status rebuild complete.

                        USDA_trait_status  n_codes
0                         Traits_complete     6825
1                           No_USDA_taxon     3144
2         Traits_present_group_unresolved      321
3               Missing_duration_nativity      231
4                                     NaN      211
5                        Missing_nativity      153
6  Missing_duration_growth_habit_nativity       73
7                        Missing_duration        2

Functional-group rows repaired: 575

Common-taxon QA:

,observed_code,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,USDA_trait_status,USDA_derived_group,MOSAIC_FG,FG_resolution_source,n_records
31,AGCR,AGCR,Agropyron cristatum (L.) Gaertn.,Perennial,Graminoid,I,Traits_complete,PerennialGrass,PerennialGrass,USDA_ecological_traits,86637
82,ARTR2,ARTR2,Artemisia tridentata Nutt.,Perennial,Shrub|Tree,N,Traits_complete,Tree,Tree,USDA_ecological_traits,27981
12,CHVI8,CHVI8,Chrysothamnus viscidiflorus (Hook.) Nutt.,Perennial,Shrub,N,Traits_complete,Shrub,Shrub,USDA_ecological_traits,52275
9,ELEL5,ELEL5,Elymus elymoides (Raf.) Swezey,Perennial,Graminoid,N,Traits_complete,PerennialGrass,PerennialGrass,USDA_ecological_traits,58454
73,ERCI6,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,Annual|Biennial,Forb/herb,I,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,16863
34,FEID,FEID,Festuca idahoensis Elmer,Perennial,Graminoid,N,Traits_complete,PerennialGrass,PerennialGrass,USDA_ecological_traits,78604
19,HECO26,HECO26,Hesperostipa comata (Trin. & Rupr.) Barkworth,Perennial,Graminoid,N,Traits_complete,PerennialGrass,PerennialGrass,USDA_ecological_traits,80033
29,POPR,POPR,Poa pratensis L.,Perennial,Graminoid,I,Traits_complete,PerennialGrass,PerennialGrass,USDA_ecological_traits,115614
10,PSSP6,PSSP6,Pseudoroegneria spicata (Pursh) Á. Löve,Perennial,Graminoid,N,Traits_complete,PerennialGrass,PerennialGrass,USDA_ecological_traits,163393
115,TACA8,TACA8,Taeniatherum caput-medusae (L.) Nevski,Annual,Graminoid,I,Traits_complete,AnnualGrass,AnnualGrass,USDA_ecological_traits,26357

Trait / FG coverage after repair:

                                   metric      n
0                             Plant codes  10749
1               USDA-resolved plant codes   7605
2             USDA-resolved with duration   7299
3         USDA-resolved with growth habit   7532
4         USDA-resolved with L48 nativity   7148
5         USDA-resolved with all 3 traits   7146
6  Plant codes still TraitUnresolvedPlant    604

================================================================================
FINAL MASTER USDA TRAIT REPAIR COMPLETE
================================================================================

Backup of pre-repair master:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\LDC_LPI_species_dictionary_FINAL_MASTER_PRE_TRAIT_REPAIR_20260902_130541.csv

Overwritten FINAL_MASTER:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\LDC_LPI_species_dictionary_FINAL_MASTER.csv

Rows: 10,960
Unique observed codes: 10,960

DONE

In [31]:
# ============================================================================
# RECORD-WEIGHTED REPRESENTATION OF UNRESOLVED PLANT CODES
# ============================================================================

# Ensure numeric record counts.
master["n_records_num"] = pd.to_numeric(
    master["n_records"],
    errors="coerce"
).fillna(0)

plant_mask = master["code_class"].eq("Plant")

unresolved_mask = (
    plant_mask
    & master["MOSAIC_FG"].eq("TraitUnresolvedPlant")
)

# --------------------------------------------------------------------------
# Overall weighted representation
# --------------------------------------------------------------------------

total_plant_codes = int(plant_mask.sum())

total_plant_records = master.loc[
    plant_mask,
    "n_records_num"
].sum()

unresolved_codes = int(unresolved_mask.sum())

unresolved_records = master.loc[
    unresolved_mask,
    "n_records_num"
].sum()

summary = pd.DataFrame({
    "metric": [
        "Total plant codes",
        "TraitUnresolvedPlant codes",
        "TraitUnresolvedPlant code share (%)",
        "Total plant records",
        "TraitUnresolvedPlant records",
        "TraitUnresolvedPlant record share (%)",
    ],
    "value": [
        total_plant_codes,
        unresolved_codes,
        100 * unresolved_codes / total_plant_codes,
        int(total_plant_records),
        int(unresolved_records),
        100 * unresolved_records / total_plant_records,
    ]
})

print("=" * 80)
print("WEIGHTED UNRESOLVED REPRESENTATION")
print("=" * 80)

display(summary)


# ============================================================================
# USDA-RESOLVED VS NON-USDA UNRESOLVED
# ============================================================================

unresolved_detail = master.loc[
    unresolved_mask
].copy()

unresolved_detail["resolution_bucket"] = np.where(
    unresolved_detail["USDA_accepted_symbol"].notna(),
    "USDA-resolved but FG unresolved",
    "No USDA taxon"
)

bucket_summary = (
    unresolved_detail
    .groupby(
        "resolution_bucket",
        dropna=False
    )
    .agg(
        n_codes=("observed_code", "nunique"),
        n_records=("n_records_num", "sum"),
    )
    .reset_index()
)

bucket_summary["pct_of_unresolved_records"] = (
    100
    * bucket_summary["n_records"]
    / unresolved_records
)

bucket_summary["pct_of_all_plant_records"] = (
    100
    * bucket_summary["n_records"]
    / total_plant_records
)

print("\nUnresolved records by origin:")
display(
    bucket_summary.sort_values(
        "n_records",
        ascending=False
    )
)


# ============================================================================
# TOP UNRESOLVED CODES BY RECORD ABUNDANCE
# ============================================================================

top_unresolved = (
    unresolved_detail[
        [
            "observed_code",
            "resolved_label",
            "USDA_accepted_symbol",
            "USDA_scientific_name",
            "USDA_duration",
            "USDA_growth_habit",
            "USDA_native_status_L48",
            "USDA_trait_status",
            "FG_resolution_source",
            "n_records_num",
            "n_plot_visits",
        ]
    ]
    .sort_values(
        "n_records_num",
        ascending=False
    )
    .reset_index(drop=True)
)

top_unresolved["pct_of_unresolved_records"] = (
    100
    * top_unresolved["n_records_num"]
    / unresolved_records
)

top_unresolved["pct_of_all_plant_records"] = (
    100
    * top_unresolved["n_records_num"]
    / total_plant_records
)

top_unresolved["cumulative_unresolved_pct"] = (
    100
    * top_unresolved["n_records_num"].cumsum()
    / unresolved_records
)

print("\nTop unresolved codes:")
display(
    top_unresolved.head(50)
)


# ============================================================================
# HOW CONCENTRATED IS THE UNRESOLVED TAIL?
# ============================================================================

concentration_rows = []

for n in [5, 10, 20, 50, 100]:

    n = min(
        n,
        len(top_unresolved)
    )

    records_n = (
        top_unresolved
        .head(n)["n_records_num"]
        .sum()
    )

    concentration_rows.append({
        "top_n_codes": n,
        "records": int(records_n),
        "pct_of_unresolved_records":
            100 * records_n / unresolved_records,
        "pct_of_all_plant_records":
            100 * records_n / total_plant_records,
    })

concentration = pd.DataFrame(
    concentration_rows
)

print("\nConcentration of unresolved records:")
display(concentration)


# ============================================================================
# RECORD-WEIGHTED USDA TRAIT STATUS
# ============================================================================

trait_status_weighted = (
    master.loc[plant_mask]
    .groupby(
        "USDA_trait_status",
        dropna=False
    )
    .agg(
        n_codes=("observed_code", "nunique"),
        n_records=("n_records_num", "sum"),
    )
    .reset_index()
)

trait_status_weighted["pct_of_plant_records"] = (
    100
    * trait_status_weighted["n_records"]
    / total_plant_records
)

trait_status_weighted = trait_status_weighted.sort_values(
    "n_records",
    ascending=False
)

print("\nRecord-weighted USDA trait status:")
display(trait_status_weighted)

================================================================================
WEIGHTED UNRESOLVED REPRESENTATION
================================================================================

                                  metric         value
0                      Total plant codes  1.074900e+04
1             TraitUnresolvedPlant codes  6.040000e+02
2    TraitUnresolvedPlant code share (%)  5.619127e+00
3                    Total plant records  5.436341e+06
4           TraitUnresolvedPlant records  3.039460e+05
5  TraitUnresolvedPlant record share (%)  5.591003e+00

Unresolved records by origin:

                 resolution_bucket  n_codes  n_records  pct_of_unresolved_records  pct_of_all_plant_records
0  USDA-resolved but FG unresolved      604     303946                      100.0                  5.591003

Top unresolved codes:

,observed_code,resolved_label,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,USDA_trait_status,FG_resolution_source,n_records_num,n_plot_visits,pct_of_unresolved_records,pct_of_all_plant_records,cumulative_unresolved_pct
0,ALDE,Alyssum desertorum Stapf,ALDE,Alyssum desertorum Stapf,Annual,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,26258,3321,8.639035,0.483009,8.639035
1,PHHO,Phlox hoodii Richardson,PHHO,Phlox hoodii Richardson,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,22412,5933,7.373678,0.412263,16.012713
2,SIAL2,Sisymbrium altissimum L.,SIAL2,Sisymbrium altissimum L.,Annual|Biennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,18009,2851,5.925066,0.331271,21.937778
3,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,Annual|Biennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,16863,1831,5.548025,0.31019,27.485803
4,ACMI2,Achillea millefolium L.,ACMI2,Achillea millefolium L.,Perennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,12985,3766,4.27214,0.238856,31.757944
5,COPA3,Collinsia parviflora Lindl.,COPA3,Collinsia parviflora Lindl.,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,9380,2213,3.086075,0.172543,34.844018
6,TAOF,Taraxacum officinale F.H. Wigg.,TAOF,Taraxacum officinale F.H. Wigg.,Perennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,9240,2211,3.040014,0.169967,37.884032
7,DEPI,Descurainia pinnata (Walter) Britton,DEPI,Descurainia pinnata (Walter) Britton,Annual|Biennial|Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,9183,2719,3.02126,0.168919,40.905292
8,LEPE2,Lepidium perfoliatum L.,LEPE2,Lepidium perfoliatum L.,Annual|Biennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,8619,1060,2.835701,0.158544,43.740993
9,HAGL,Halogeton glomeratus (M. Bieb.) C.A. Mey.,HAGL,Halogeton glomeratus (M. Bieb.) C.A. Mey.,Annual,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,8041,1044,2.645536,0.147912,46.386529
10,BASA3,Balsamorhiza sagittata (Pursh) Nutt.,BASA3,Balsamorhiza sagittata (Pursh) Nutt.,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,7624,1381,2.50834,0.140241,48.894869
11,DRVE2,Draba verna L.,DRVE2,Draba verna L.,Annual,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,6341,1208,2.086226,0.116641,50.981095
12,LASE,Lactuca serriola L.,LASE,Lactuca serriola L.,Annual|Biennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,6311,1429,2.076356,0.116089,53.057451
13,ALAL3,Alyssum alyssoides (L.) L.,ALAL3,Alyssum alyssoides (L.) L.,Annual|Biennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,5257,794,1.729584,0.096701,54.787035
14,VIAM,Vicia americana Muhl. ex Willd.,VIAM,Vicia americana Muhl. ex Willd.,Perennial,Forb/herb|Vine,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,5105,1422,1.679575,0.093905,56.466609
15,MIGR,Microsteris gracilis (Hook.) Greene,MIGR,Microsteris gracilis (Hook.) Greene,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,4837,1468,1.591401,0.088975,58.05801
16,CRAC2,Crepis acuminata Nutt.,CRAC2,Crepis acuminata Nutt.,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,4585,1875,1.508492,0.08434,59.566502
17,TRDU,Tragopogon dubius Scop.,TRDU,Tragopogon dubius Scop.,Annual|Biennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,3686,1907,1.212715,0.067803,60.779217
18,LAOC3,Lappula occidentalis (S. Watson) Greene,LAOC3,Lappula occidentalis (S. Watson) Greene,Annual|Biennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,3603,1054,1.185408,0.066276,61.964625
19,MESA,Medicago sativa L.,MESA,Medicago sativa L.,Annual|Perennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,3509,508,1.154481,0.064547,63.119107
20,HOUM,Holosteum umbellatum L.,HOUM,Holosteum umbellatum L.,Annual,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,3305,707,1.087364,0.060795,64.206471
21,EPMI,Epilobium minutum Lindl. ex Lehm.,EPMI,Epilobium minutum Lindl. ex Lehm.,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,3209,613,1.05578,0.059029,65.262251
22,ANRO2,Antennaria rosea Greene,ANRO2,Antennaria rosea Greene,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,2967,592,0.97616,0.054577,66.238411
23,LUCA,Lupinus caudatus Kellogg,LUCA,Lupinus caudatus Kellogg,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,2812,522,0.925164,0.051726,67.163575
24,COCA5,Conyza canadensis (L.) Cronquist,COCA5,Conyza canadensis (L.) Cronquist,Annual|Biennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,2694,545,0.886342,0.049555,68.049917
25,GIIN2,Gilia inconspicua (Sm.) Sweet,GIIN2,Gilia inconspicua (Sm.) Sweet,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,2243,437,0.73796,0.041259,68.787877
26,MELU,Medicago lupulina L.,MELU,Medicago lupulina L.,Annual|Perennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,2223,487,0.73138,0.040891,69.519257
27,CHJU,Chondrilla juncea L.,CHJU,Chondrilla juncea L.,Perennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,2180,350,0.717233,0.040101,70.236489
28,COAR4,Convolvulus arvensis L.,COAR4,Convolvulus arvensis L.,Perennial,Forb/herb|Vine,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,2147,463,0.706375,0.039493,70.942865
29,BLSC,Blepharipappus scaber Hook.,BLSC,Blepharipappus scaber Hook.,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,2081,446,0.684661,0.038279,71.627526
30,MEAL6,Mentzelia albicaulis (Hook.) Torr. & A. Gray,MEAL6,Mentzelia albicaulis (Hook.) Torr. & A. Gray,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1937,566,0.637284,0.035631,72.26481
31,COLI2,Collomia linearis Nutt.,COLI2,Collomia linearis Nutt.,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1874,522,0.616557,0.034472,72.881367
32,PLLA,Plantago lanceolata L.,PLLA,Plantago lanceolata L.,Annual|Biennial|Perennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,1865,249,0.613596,0.034306,73.494963
33,CIAR4,Cirsium arvense (L.) Scop.,CIAR4,Cirsium arvense (L.) Scop.,Perennial,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,1720,410,0.56589,0.031639,74.060853
34,GADI2,Gayophytum diffusum Torr. & A. Gray,GADI2,Gayophytum diffusum Torr. & A. Gray,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1647,398,0.541873,0.030296,74.602725
35,AMTE3,Amsinckia tessellata A. Gray,AMTE3,Amsinckia tessellata A. Gray,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1615,457,0.531344,0.029707,75.13407
36,CHAL7,Chenopodium album L.,CHAL7,Chenopodium album L.,Annual,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,1604,347,0.527725,0.029505,75.661795
37,ANPA4,Antennaria parvifolia Nutt.,ANPA4,Antennaria parvifolia Nutt.,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1600,480,0.526409,0.029432,76.188204
38,LOTR2,Lomatium triternatum (Pursh) J.M. Coult. & Rose,LOTR2,Lomatium triternatum (Pursh) J.M. Coult. & Rose,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1596,494,0.525093,0.029358,76.713298
39,PODO4,Polygonum douglasii Greene,PODO4,Polygonum douglasii Greene,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1557,491,0.512262,0.028641,77.22556
40,HEAN3,Helianthus annuus L.,HEAN3,Helianthus annuus L.,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1456,395,0.479032,0.026783,77.704592
41,BAHO,Balsamorhiza hookeri (Hook.) Nutt.,BAHO,Balsamorhiza hookeri (Hook.) Nutt.,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1418,473,0.46653,0.026084,78.171123
42,CHTE2,Chorispora tenella (Pall.) DC.,CHTE2,Chorispora tenella (Pall.) DC.,Annual,Forb/herb,I,Traits_present_group_unresolved,USDA_taxon_missing_traits,1332,182,0.438236,0.024502,78.609358
43,GRSQ,Grindelia squarrosa (Pursh) Dunal,GRSQ,Grindelia squarrosa (Pursh) Dunal,Annual|Biennial|Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1273,472,0.418824,0.023416,79.028183
44,CHLE4,Chenopodium leptophyllum (Moq.) Nutt. ex S. Wa...,CHLE4,Chenopodium leptophyllum (Moq.) Nutt. ex S. Wa...,Annual,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1221,269,0.401716,0.02246,79.429899
45,SOMI2,Solidago missouriensis Nutt.,SOMI2,Solidago missouriensis Nutt.,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1100,428,0.361906,0.020234,79.791805
46,SEIN2,Senecio integerrimus Nutt.,SEIN2,Senecio integerrimus Nutt.,Biennial|Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1088,402,0.357958,0.020013,80.149763
47,MACA2,Machaeranthera canescens (Pursh) A. Gray,MACA2,Machaeranthera canescens (Pursh) A. Gray,Annual|Biennial|Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1079,393,0.354997,0.019848,80.504761
48,HYSP70,Hylocomium splendens (Hedw.) Schimp.,HYSP70,Hylocomium splendens (Hedw.) Schimp.,<NA>,Nonvascular,<NA>,Missing_duration_nativity,USDA_taxon_missing_traits,1025,86,0.337231,0.018855,80.841992
49,TRMA3,Trifolium macrocephalum (Pursh) Poir.,TRMA3,Trifolium macrocephalum (Pursh) Poir.,Perennial,Forb/herb,N,Traits_present_group_unresolved,USDA_taxon_missing_traits,1006,276,0.33098,0.018505,81.172972

Concentration of unresolved records:

   top_n_codes  records  pct_of_unresolved_records  pct_of_all_plant_records
0            5    96527                  31.757944                  1.775588
1           10   140990                  46.386529                  2.593472
2           20   191848                  63.119107                  3.528991
3           50   246722                  81.172972                  4.538383
4          100   277297                  91.232324                  5.100802

Record-weighted USDA trait status:

                        USDA_trait_status  n_codes  n_records  pct_of_plant_records
5                         Traits_complete     6825    4899935             90.132959
6         Traits_present_group_unresolved      321     291900               5.36942
4                           No_USDA_taxon     3144     219306              4.034074
2               Missing_duration_nativity      231      12894              0.237182
3                        Missing_nativity      153      11516              0.211834
1  Missing_duration_growth_habit_nativity       73        737              0.013557
0                        Missing_duration        2         53              0.000975

In [32]:
# ============================================================================
# DIAGNOSTIC — DECOMPOSE USDA TRAIT-FAILURE GROUPS
# ============================================================================

# Ensure record counts are numeric.
master["n_records_num"] = pd.to_numeric(
    master["n_records"],
    errors="coerce"
).fillna(0)

plant_mask = master["code_class"].eq("Plant")

# --------------------------------------------------------------------------
# Define the specific USDA-resolved failure groups
# --------------------------------------------------------------------------

status_groups = {
    "missing_all_three": "Missing_duration_growth_habit_nativity",
    "missing_nativity_only": "Missing_nativity",
    "missing_duration_and_nativity": "Missing_duration_nativity",
    "missing_duration_only": "Missing_duration",
    "traits_present_group_unresolved": "Traits_present_group_unresolved",
    "no_usda_taxon": "No_USDA_taxon",
}

group_tables = {}

for group_name, status_value in status_groups.items():

    df = master.loc[
        plant_mask
        & master["USDA_trait_status"].eq(status_value)
    ].copy()

    df = df.sort_values(
        "n_records_num",
        ascending=False
    ).reset_index(drop=True)

    group_tables[group_name] = df


# ============================================================================
# 1. HIGH-LEVEL SUMMARY
# ============================================================================

summary_rows = []

total_plant_records = master.loc[
    plant_mask,
    "n_records_num"
].sum()

for group_name, df in group_tables.items():

    n_records = df["n_records_num"].sum()

    summary_rows.append({
        "group": group_name,
        "n_codes": len(df),
        "n_records": int(n_records),
        "pct_of_all_plant_records":
            100 * n_records / total_plant_records
            if total_plant_records else np.nan,
    })

group_summary = (
    pd.DataFrame(summary_rows)
    .sort_values(
        "n_records",
        ascending=False
    )
)

print("=" * 90)
print("TRAIT-FAILURE GROUP SUMMARY")
print("=" * 90)

display(group_summary)


# ============================================================================
# 2. HELPER FOR DISTRIBUTION TABLES
# ============================================================================

def summarize_field(df, field, top_n=30):

    if field not in df.columns:
        return pd.DataFrame()

    x = df.copy()

    x[field] = (
        x[field]
        .astype("string")
        .fillna("<NA>")
        .str.strip()
        .replace("", "<BLANK>")
    )

    out = (
        x.groupby(
            field,
            dropna=False
        )
        .agg(
            n_codes=("observed_code", "nunique"),
            n_records=("n_records_num", "sum"),
        )
        .reset_index()
        .sort_values(
            "n_records",
            ascending=False
        )
        .head(top_n)
    )

    total = df["n_records_num"].sum()

    if total:
        out["pct_group_records"] = (
            100
            * out["n_records"]
            / total
        )

    return out


# ============================================================================
# 3. INSPECT EACH FAILURE GROUP
# ============================================================================

fields_to_summarize = [
    "USDA_growth_habit",
    "USDA_duration",
    "USDA_native_status_L48",
    "taxonomic_level",
    "USDA_rank",
    "resolved_plant_group",
    "MOSAIC_FG",
    "FG_resolution_source",
]

for group_name, df in group_tables.items():

    print("\n\n")
    print("=" * 90)
    print(group_name.upper())
    print("=" * 90)

    print(
        f"Codes: {len(df):,} | "
        f"Records: {df['n_records_num'].sum():,.0f}"
    )

    # ----------------------------------------------------------------------
    # Field distributions
    # ----------------------------------------------------------------------

    for field in fields_to_summarize:

        if field not in df.columns:
            continue

        print(f"\n--- {field} ---")

        display(
            summarize_field(
                df,
                field,
                top_n=25
            )
        )

    # ----------------------------------------------------------------------
    # Highest-weight individual codes
    # ----------------------------------------------------------------------

    show_cols = [
        "observed_code",
        "resolved_label",
        "USDA_accepted_symbol",
        "USDA_scientific_name",
        "USDA_duration",
        "USDA_growth_habit",
        "USDA_native_status_L48",
        "taxonomic_level",
        "USDA_rank",
        "USDA_trait_status",
        "resolved_plant_group",
        "MOSAIC_FG",
        "FG_resolution_source",
        "n_records_num",
        "n_plot_visits",
    ]

    show_cols = [
        c for c in show_cols
        if c in df.columns
    ]

    top = df[show_cols].head(50).copy()

    group_records = df["n_records_num"].sum()

    if group_records:

        top["pct_group_records"] = (
            100
            * top["n_records_num"]
            / group_records
        )

        top["cumulative_group_pct"] = (
            100
            * top["n_records_num"].cumsum()
            / group_records
        )

    print("\nTop taxa / codes:")
    display(top)


# ============================================================================
# 4. SPECIFIC FAILURE-REASON LOGIC
#
# This classifies WHY a row is still unresolved from the perspective of
# our functional-group rules.
# ============================================================================

def infer_failure_reason(row):

    status = row.get("USDA_trait_status")

    growth = row.get("USDA_growth_habit")
    duration = row.get("USDA_duration")
    native = row.get("USDA_native_status_L48")

    growth = (
        "" if pd.isna(growth)
        else str(growth).strip().lower()
    )

    duration = (
        "" if pd.isna(duration)
        else str(duration).strip().lower()
    )

    native = (
        "" if pd.isna(native)
        else str(native).strip().upper()
    )

    # --------------------------------------------------------
    # No USDA taxon
    # --------------------------------------------------------

    if status == "No_USDA_taxon":
        return "No_USDA_taxonomic_match"

    # --------------------------------------------------------
    # Completely missing traits
    # --------------------------------------------------------

    if status == "Missing_duration_growth_habit_nativity":
        return "USDA_profile_has_no_ecological_traits"

    # --------------------------------------------------------
    # Habit known, but nativity missing
    # --------------------------------------------------------

    if "forb/herb" in growth:

        if native == "":
            return "Forb_known_but_native_exotic_unknown"

        return "Forb_should_now_resolve"

    if "shrub" in growth:
        return "Shrub_should_resolve_without_duration_or_nativity"

    if "tree" in growth:
        return "Tree_should_resolve_without_duration_or_nativity"

    if (
        "graminoid" in growth
        or "grass" in growth
    ):

        if duration == "":
            return "Grass_known_but_annual_perennial_unknown"

        return "Grass_should_resolve_from_duration"

    if "nonvascular" in growth:
        return "Nonvascular_should_resolve"

    if growth:
        return "Other_growth_habit_requires_rule_review"

    return "Growth_habit_missing"


master["trait_failure_reason"] = master.apply(
    infer_failure_reason,
    axis=1
)


# ============================================================================
# 5. RECORD-WEIGHTED FAILURE REASONS
# ============================================================================

failure_reason_summary = (
    master.loc[
        plant_mask
        & master["USDA_trait_status"].isin(
            list(status_groups.values())
        )
    ]
    .groupby(
        "trait_failure_reason",
        dropna=False
    )
    .agg(
        n_codes=("observed_code", "nunique"),
        n_records=("n_records_num", "sum"),
    )
    .reset_index()
    .sort_values(
        "n_records",
        ascending=False
    )
)

failure_reason_summary[
    "pct_of_all_plant_records"
] = (
    100
    * failure_reason_summary["n_records"]
    / total_plant_records
)

print("\n")
print("=" * 90)
print("INFERRED FAILURE REASONS")
print("=" * 90)

display(failure_reason_summary)

==========================================================================================
TRAIT-FAILURE GROUP SUMMARY
==========================================================================================

                             group  n_codes  n_records  pct_of_all_plant_records
4  traits_present_group_unresolved      321     291900                  5.369420
5                    no_usda_taxon     3144     219306                  4.034074
2    missing_duration_and_nativity      231      12894                  0.237182
1            missing_nativity_only      153      11516                  0.211834
0                missing_all_three       73        737                  0.013557
3            missing_duration_only        2         53                  0.000975

==========================================================================================
MISSING_ALL_THREE
==========================================================================================
Codes: 73 | Records: 737

--- USDA_growth_habit ---

  USDA_growth_habit  n_codes  n_records  pct_group_records
0              <NA>       73        737              100.0

--- USDA_duration ---

  USDA_duration  n_codes  n_records  pct_group_records
0          <NA>       73        737              100.0

--- USDA_native_status_L48 ---

  USDA_native_status_L48  n_codes  n_records  pct_group_records
0                   <NA>       73        737              100.0

--- taxonomic_level ---

  taxonomic_level  n_codes  n_records  pct_group_records
0            <NA>       73        737              100.0

--- resolved_plant_group ---

  resolved_plant_group  n_codes  n_records  pct_group_records
0                 <NA>       73        737              100.0

--- MOSAIC_FG ---

              MOSAIC_FG  n_codes  n_records  pct_group_records
0  TraitUnresolvedPlant       73        737              100.0

--- FG_resolution_source ---

        FG_resolution_source  n_codes  n_records  pct_group_records
0  USDA_taxon_missing_traits       73        737              100.0

Top taxa / codes:

,observed_code,resolved_label,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,taxonomic_level,USDA_trait_status,resolved_plant_group,MOSAIC_FG,FG_resolution_source,n_records_num,n_plot_visits,pct_group_records,cumulative_group_pct
0,ACSC2,Vachellia schaffneri (S. Watson) Seigler & Ebi...,VASC4,Vachellia schaffneri (S. Watson) Seigler & Ebi...,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,122,29,16.553596,16.553596
1,ALAS2,Allium ascalonicum L.,ALAS2,Allium ascalonicum L.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,64,32,8.683853,25.237449
2,IPJA,Ipomoea jaegeri Pilg.,IPJA,Ipomoea jaegeri Pilg.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,61,10,8.276798,33.514247
3,SOAC2,Solanum aculeastrum Dunal,SOAC2,Solanum aculeastrum Dunal,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,35,1,4.748982,38.263229
4,KRAR,Krascheninnikovia arborescens (Losinsk.) Czerep.,KRAR,Krascheninnikovia arborescens (Losinsk.) Czerep.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,30,13,4.070556,42.333786
5,ACAG,Achillea ageratifolia (Sm.) Boiss.,ACAG,Achillea ageratifolia (Sm.) Boiss.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,29,13,3.934871,46.268657
6,LISE7,Ligustrum sempervirens (Franch.) Linglesh.,LISE7,Ligustrum sempervirens (Franch.) Linglesh.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,26,3,3.527815,49.796472
7,TRGR18,Trifolium grandiflorum Schreb.,TRGR18,Trifolium grandiflorum Schreb.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,25,5,3.39213,53.188602
8,TRMI17,Trifolium micranthum Viv.,TRMI17,Trifolium micranthum Viv.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,22,6,2.985075,56.173677
9,SAGI3,Salix gilgiana Fr.,SAGI3,Salix gilgiana Fr.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,19,1,2.578019,58.751696
10,VEGA,Vernonia galamensis (Cass.) Less.,VEGA,Vernonia galamensis (Cass.) Less.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,18,3,2.442334,61.19403
11,VEPO4,Verbena polystachya Kunth,VEPO4,Verbena polystachya Kunth,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,17,4,2.306649,63.500678
12,EUGA6,Euphorbia gaudichaudii Boiss.,EUGA6,Euphorbia gaudichaudii Boiss.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,16,8,2.170963,65.671642
13,ROAR6,Rosa arvensis Huds.,ROAR6,Rosa arvensis Huds.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,16,2,2.170963,67.842605
14,GEAC4,Gentiana acaulis L.,GEAC4,Gentiana acaulis L.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,15,2,2.035278,69.877883
15,PHDO5,Phytolacca dodecandra L'Her.,PHDO5,Phytolacca dodecandra L'Her.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,14,7,1.899593,71.777476
16,FACA2,Fagonia californica Benth. [excluded],FACA2,Fagonia californica Benth. [excluded],<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,12,3,1.628223,73.405699
17,LOMA16,Lotus maritimus L.,LOMA16,Lotus maritimus L.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,12,2,1.628223,75.033921
18,GMPH,Gmelina philippensis Cham.,GMPH,Gmelina philippensis Cham.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,12,1,1.628223,76.662144
19,DESE2,Desmodium sericophyllum Schltdl.,DESE2,Desmodium sericophyllum Schltdl.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,11,1,1.492537,78.154681
20,EUSID,Eusideroxylon Teijsm. & Binnend.,EUSID,Eusideroxylon Teijsm. & Binnend.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,11,1,1.492537,79.647218
21,OPAU10,Opuntia aurantiaca Lindl.,OPAU10,Opuntia aurantiaca Lindl.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,11,2,1.492537,81.139756
22,VEAN5,Vernonia anthelmintica (L.) Willd.,VEAN5,Vernonia anthelmintica (L.) Willd.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,9,4,1.221167,82.360923
23,DIGR13,Dietes grandiflora N.E. Br.,DIGR13,Dietes grandiflora N.E. Br.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,8,3,1.085482,83.446404
24,ERCR8,Eryngium creticum Lam.,ERCR8,Eryngium creticum Lam.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,8,2,1.085482,84.531886
25,POPA33,Polygonum paronychioides Small ex Rydb.,POPA33,Polygonum paronychioides Small ex Rydb.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,8,4,1.085482,85.617368
26,ASED2,Astragalus edulis Durieu ex Bunge,ASED2,Astragalus edulis Durieu ex Bunge,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,7,2,0.949796,86.567164
27,TADI6,Tamarix dioica Roxb. ex Roth,TADI6,Tamarix dioica Roxb. ex Roth,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,6,2,0.814111,87.381275
28,TEVO4,Tetrastigma voinieranum (Baltet) Pierre ex Gag...,TEVO4,Tetrastigma voinieranum (Baltet) Pierre ex Gag...,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,5,1,0.678426,88.059701
29,LEPO15,Lespedeza potaninii Vassiliev,LEPO15,Lespedeza potaninii Vassiliev,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,5,2,0.678426,88.738128
30,HAPLO11,Haplopappus Cass.,HAPLO11,Haplopappus Cass.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,5,4,0.678426,89.416554
31,OXMA7,Oxalis macrocarpa (Small) R. Knuth,OXMA7,Oxalis macrocarpa (Small) R. Knuth,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,5,3,0.678426,90.09498
32,LIMNO5,Limnocharis Humb. & Bonpl.,LIMNO5,Limnocharis Humb. & Bonpl.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,4,2,0.542741,90.63772
33,DRYOB,Dryobalanops C.F. Gaertn.,DRYOB,Dryobalanops C.F. Gaertn.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,4,1,0.542741,91.180461
34,ROMI9,Rosa missouriensis hort. ex Steud. [excluded],ROMI9,Rosa missouriensis hort. ex Steud. [excluded],<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,4,1,0.542741,91.723202
35,OXRO4,Oxalis rosea Feuillee ex Jacq.,OXRO4,Oxalis rosea Feuillee ex Jacq.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,4,3,0.542741,92.265943
36,SABI8,Salix bicolor Fr.,SABI8,Salix bicolor Fr.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3,2,0.407056,92.672999
37,ANNE10,Antenoron neofiliforme (Nakai) H. Hara,ANNE10,Antenoron neofiliforme (Nakai) H. Hara,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3,1,0.407056,93.080054
38,CRRI8,Croton ripensis Kanehira & Hatusima,CRRI8,Croton ripensis Kanehira & Hatusima,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3,1,0.407056,93.48711
39,ERCA36,Erigeron candidus Widder,ERCA36,Erigeron candidus Widder,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3,1,0.407056,93.894166
40,EUGR14,Eucalyptus gregsoniana L.A.S. Johnson & Blaxell,EUGR14,Eucalyptus gregsoniana L.A.S. Johnson & Blaxell,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3,1,0.407056,94.301221
41,SAAF,Sambucus africana Standl.,SAAF,Sambucus africana Standl.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3,1,0.407056,94.708277
42,CHMA17,Chrysanthemum majus (Desf.) Asch.,CHMA17,Chrysanthemum majus (Desf.) Asch.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,2,0.27137,94.979647
43,IPER,Ipomoea eriocarpa R. Br.,IPER,Ipomoea eriocarpa R. Br.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,2,0.27137,95.251018
44,ACRO5,Vachellia robusta (Burch.) Kyal. & Boatwr.,VARO,Vachellia robusta (Burch.) Kyal. & Boatwr.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,2,0.27137,95.522388
45,LINA2,Linum narbonense L.,LINA2,Linum narbonense L.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,1,0.27137,95.793758
46,AGAN4,Agave angustifolia Haw.,AGAN4,Agave angustifolia Haw.,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,1,0.27137,96.065129
47,ACCO24,Vachellia collinsii (Saff.) Seigler & Ebinger,VACO8,Vachellia collinsii (Saff.) Seigler & Ebinger,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,1,0.27137,96.336499
48,VIDE6,Viguiera deltoidea A. Gray [excluded],VIDE6,Viguiera deltoidea A. Gray [excluded],<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,2,0.27137,96.60787
49,EUDE11,Eucalyptus dealbata A. Cunn. ex Schauer,EUDE11,Eucalyptus dealbata A. Cunn. ex Schauer,<NA>,<NA>,<NA>,<NA>,Missing_duration_growth_habit_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2,1,0.27137,96.87924

==========================================================================================
MISSING_NATIVITY_ONLY
==========================================================================================
Codes: 153 | Records: 11,516

--- USDA_growth_habit ---

           USDA_growth_habit  n_codes  n_records  pct_group_records
5                  Graminoid       34       5245          45.545328
8             Shrub|Subshrub       12       1690          14.675234
10                Shrub|Tree       14       1574           13.66794
7                      Shrub        9       1336           11.60125
0                  Forb/herb       66        686           5.956929
9        Shrub|Subshrub|Tree        1        615           5.340396
11                  Subshrub        3        128           1.111497
6       Graminoid|Shrub|Vine        1        117           1.015978
12                      Tree        5         66           0.573116
1   Forb/herb|Shrub|Subshrub        2         43           0.373394
2         Forb/herb|Subshrub        2          7           0.060785
13                      Vine        2          7           0.060785
4             Forb/herb|Vine        1          1           0.008684
3    Forb/herb|Subshrub|Vine        1          1           0.008684

--- USDA_duration ---

               USDA_duration  n_codes  n_records  pct_group_records
5                  Perennial      141      11366          98.697464
0                     Annual        5        136           1.180966
2  Annual|Biennial|Perennial        2          7           0.060785
1            Annual|Biennial        2          3           0.026051
3           Annual|Perennial        2          2           0.017367
4                   Biennial        1          2           0.017367

--- USDA_native_status_L48 ---

  USDA_native_status_L48  n_codes  n_records  pct_group_records
0                   <NA>      153      11516              100.0

--- taxonomic_level ---

  taxonomic_level  n_codes  n_records  pct_group_records
0            <NA>      153      11516              100.0

--- resolved_plant_group ---

   resolved_plant_group  n_codes  n_records  pct_group_records
6    PerennialGraminoid       31       5190          45.067732
7                 Shrub       25       3187           27.67454
11                Woody       14       1574           13.66794
10                 Tree        6        681           5.913512
5         PerennialForb       58        592           5.140674
8              Subshrub        3        128           1.111497
1            AnnualForb        3         82           0.712053
2       AnnualGraminoid        2         54           0.468913
3                  Forb        5         12           0.104203
0                  <NA>        3          8           0.069469
9        SubshrubOrForb        2          7           0.060785
4             Graminoid        1          1           0.008684

--- MOSAIC_FG ---

                          MOSAIC_FG  n_codes  n_records  pct_group_records
5                PerennialGraminoid       31       5190          45.067732
6                               SHR       21       3026          26.276485
13                            Woody       14       1574           13.66794
12                             Tree        1        615           5.340396
4                                PF       58        592           5.140674
8                             Shrub        4        161           1.398055
7                            SUBSHR        3        128           1.111497
0                                AF        3         82           0.712053
10                             TREE        5         66           0.573116
1   AnnualGraminoid_UnknownNativity        2         54           0.468913
2                              Forb        5         12           0.104203
11             TraitUnresolvedPlant        3          8           0.069469
9                    SubshrubOrForb        2          7           0.060785
3                         Graminoid        1          1           0.008684

--- FG_resolution_source ---

        FG_resolution_source  n_codes  n_records  pct_group_records
2                USDA_traits      145      10732          93.192081
0     USDA_ecological_traits        5        776           6.738451
1  USDA_taxon_missing_traits        3          8           0.069469

Top taxa / codes:

,observed_code,resolved_label,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,taxonomic_level,USDA_trait_status,resolved_plant_group,MOSAIC_FG,FG_resolution_source,n_records_num,n_plot_visits,pct_group_records,cumulative_group_pct
0,BOSA,Bothriochloa saccharoides (Sw.) Rydb.,BOSA,Bothriochloa saccharoides (Sw.) Rydb.,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,2126,255,18.461271,18.461271
1,CALU2,Carex lugens T. Holm,CALU2,Carex lugens T. Holm,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,1291,56,11.21049,29.671761
2,LEPAD,Ledum palustre L. ssp. decumbens (Aiton) Hultén,LEPAD,Ledum palustre L. ssp. decumbens (Aiton) Hultén,Perennial,Shrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,1266,74,10.9934,40.665162
3,BENAE,Betula nana L. ssp. exilis (Sukaczev) Hultén,BENAE,Betula nana L. ssp. exilis (Sukaczev) Hultén,Perennial,Shrub|Subshrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,940,66,8.162556,48.827718
4,SARI4,Salix richardsonii Hook.,SARI4,Salix richardsonii Hook.,Perennial,Shrub|Tree,<NA>,<NA>,Missing_nativity,Woody,Woody,USDA_traits,626,23,5.435915,54.263633
5,SAPU15,Salix pulchra Cham.,SAPU15,Salix pulchra Cham.,Perennial,Shrub|Subshrub|Tree,<NA>,<NA>,Missing_nativity,Tree,Tree,USDA_ecological_traits,615,74,5.340396,59.604029
6,BENE4,Betula neoalaskana Sarg.,BENE4,Betula neoalaskana Sarg.,Perennial,Shrub|Tree,<NA>,<NA>,Missing_nativity,Woody,Woody,USDA_traits,541,23,4.697812,64.301841
7,PUTR,Puccinellia andersonii Swallen,PUAN,Puccinellia andersonii Swallen,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,512,53,4.445988,68.747829
8,CATET,Cassiope tetragona (L.) D. Don var. tetragona,CATET,Cassiope tetragona (L.) D. Don var. tetragona,Perennial,Shrub|Subshrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,325,33,2.82216,71.56999
9,CARO7,Carex rotundata Wahlenb.,CARO7,Carex rotundata Wahlenb.,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,320,34,2.778743,74.348732
10,CAMI4,Carex microchaeta T. Holm,CAMI4,Carex microchaeta T. Holm,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,309,10,2.683223,77.031956
11,JUHA2,Juncus haenkei E. Mey.,JUHA2,Juncus haenkei E. Mey.,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,293,10,2.544286,79.576242
12,SAAL,Salix alaxensis (Andersson) Coville,SAAL,Salix alaxensis (Andersson) Coville,Perennial,Shrub|Tree,<NA>,<NA>,Missing_nativity,Woody,Woody,USDA_traits,267,16,2.318513,81.894755
13,CHRYS16,Chrysothemis Decne.,CHRYS16,Chrysothemis Decne.,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,220,22,1.910386,83.805141
14,SARE2,Salix reticulata L.,SARE2,Salix reticulata L.,Perennial,Shrub|Subshrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,189,51,1.641195,85.446336
15,ARFA8,Arthrostylidium farctum (Aubl.) Soderstr. & Lo...,ARFA8,Arthrostylidium farctum (Aubl.) Soderstr. & Lo...,Perennial,Graminoid|Shrub|Vine,<NA>,<NA>,Missing_nativity,Shrub,Shrub,USDA_ecological_traits,117,16,1.015978,86.462313
16,COSU4,Cornus suecica L.,COSU4,Cornus suecica L.,Perennial,Shrub|Subshrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,115,5,0.998611,87.460924
17,PYGR,Pyrola grandiflora Radius,PYGR,Pyrola grandiflora Radius,Perennial,Subshrub,<NA>,<NA>,Missing_nativity,Subshrub,SUBSHR,USDA_traits,81,33,0.703369,88.164293
18,PRJU3,Prosopis juliflora (Sw.) DC.,PRJU3,Prosopis juliflora (Sw.) DC.,Perennial,Shrub|Tree,<NA>,<NA>,Missing_nativity,Woody,Woody,USDA_traits,77,17,0.668635,88.832928
19,POAL11,Polygonum alpinum All.,POAL11,Polygonum alpinum All.,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,64,4,0.555749,89.388677
20,ARLAL6,Arctagrostis latifolia (R. Br.) Griseb. ssp. l...,ARLAL6,Arctagrostis latifolia (R. Br.) Griseb. ssp. l...,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,61,20,0.529698,89.918374
21,LEPI2,Lepidium pinnatisectum (O.E. Schulz) C.L. Hitchc.,LEPI2,Lepidium pinnatisectum (O.E. Schulz) C.L. Hitchc.,Annual,Forb/herb,<NA>,<NA>,Missing_nativity,AnnualForb,AF,USDA_traits,60,15,0.521014,90.439389
22,CASTI,Castilla Cerv.,CASTI,Castilla Cerv.,Perennial,Tree,<NA>,<NA>,Missing_nativity,Tree,TREE,USDA_traits,51,22,0.442862,90.882251
23,SAFU,Salix fuscescens Andersson,SAFU,Salix fuscescens Andersson,Perennial,Shrub|Subshrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,51,18,0.442862,91.325113
24,ELOV,Eleocharis ovata (Roth) Roem. & Schult.,ELOV,Eleocharis ovata (Roth) Roem. & Schult.,Annual,Graminoid,<NA>,<NA>,Missing_nativity,AnnualGraminoid,AnnualGraminoid_UnknownNativity,USDA_traits,51,2,0.442862,91.767975
25,DILAO2,Diapensia lapponica L. var. obovata F. Schmidt,DILAO2,Diapensia lapponica L. var. obovata F. Schmidt,Perennial,Subshrub,<NA>,<NA>,Missing_nativity,Subshrub,SUBSHR,USDA_traits,46,4,0.399444,92.167419
26,BLYSM3,Blysmus Panzer ex Schult.,BLYSM3,Blysmus Panzer ex Schult.,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,40,2,0.347343,92.514762
27,SAPH,Salix phlebophylla Andersson,SAPH,Salix phlebophylla Andersson,Perennial,Shrub|Subshrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,38,10,0.329976,92.844738
28,SAAN3,Saussurea angustifolia (Willd.) DC.,SAAN3,Saussurea angustifolia (Willd.) DC.,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,37,15,0.321292,93.16603
29,DROCA2,Dryas octopetala L. ssp. alaskensis (A.E. Pors...,DROCA2,Dryas octopetala L. ssp. alaskensis (A.E. Pors...,Perennial,Forb/herb|Shrub|Subshrub,<NA>,<NA>,Missing_nativity,Shrub,Shrub,USDA_ecological_traits,32,3,0.277874,93.443904
30,SCSU11,Schoenoplectus subulatus (Vahl) Lye,SCSU11,Schoenoplectus subulatus (Vahl) Lye,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,32,2,0.277874,93.721778
31,CAWI3,Carex williamsii Britton,CAWI3,Carex williamsii Britton,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,32,16,0.277874,93.999653
32,ARLA2,Arctagrostis latifolia (R. Br.) Griseb.,ARLA2,Arctagrostis latifolia (R. Br.) Griseb.,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,28,2,0.24314,94.242793
33,POBIP,Polygonum bistorta L. var. plumosum (Small) B....,POBIP,Polygonum bistorta L. var. plumosum (Small) B....,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,26,11,0.225773,94.468565
34,TEUR,Tetrazygia urbanii Cogn.,TEUR,Tetrazygia urbanii Cogn.,Perennial,Shrub|Tree,<NA>,<NA>,Missing_nativity,Woody,Woody,USDA_traits,26,2,0.225773,94.694338
35,CAAT7,Carex atrofusca Schkuhr,CAAT7,Carex atrofusca Schkuhr,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,24,8,0.208406,94.902744
36,ARFR2,Arnica frigida C.A. Mey. ex Iljin,ARFR2,Arnica frigida C.A. Mey. ex Iljin,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,24,12,0.208406,95.11115
37,ELEL,Eleocharis elegans (Kunth) Roem. & Schult.,ELEL,Eleocharis elegans (Kunth) Roem. & Schult.,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,24,6,0.208406,95.319555
38,ANMOA3,Anthoxanthum monticola (Bigelow) Veldkamp ssp....,ANMOA3,Anthoxanthum monticola (Bigelow) Veldkamp ssp....,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,24,7,0.208406,95.527961
39,SPST3,Spiraea stevenii (C.K. Schneid.) Rydb.,SPST3,Spiraea stevenii (C.K. Schneid.) Rydb.,Perennial,Shrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,21,6,0.182355,95.710316
40,POKA,Polygonum kawagoeanum Makino,POKA,Polygonum kawagoeanum Makino,Annual,Forb/herb,<NA>,<NA>,Missing_nativity,AnnualForb,AF,USDA_traits,20,3,0.173671,95.883987
41,JUBE2,Justicia betonica L.,JUBE2,Justicia betonica L.,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,19,2,0.164988,96.048975
42,CAHO4,Carex holostoma Drejer,CAHO4,Carex holostoma Drejer,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,17,5,0.147621,96.196596
43,PECA2,Pedicularis capitata M.F. Adams,PECA2,Pedicularis capitata M.F. Adams,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,16,16,0.138937,96.335533
44,RHCAG,Rhododendron camtschaticum Pall. ssp. glandulo...,RHCAG,Rhododendron camtschaticum Pall. ssp. glandulo...,Perennial,Shrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,16,4,0.138937,96.47447
45,ASUM2,Astragalus umbellatus Bunge,ASUM2,Astragalus umbellatus Bunge,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,14,5,0.12157,96.59604
46,BORI2,Boykinia richardsonii (Hook.) Rothr.,BORI2,Boykinia richardsonii (Hook.) Rothr.,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,14,2,0.12157,96.71761
47,SANI10,Salix niphoclada Rydb.,SANI10,Salix niphoclada Rydb.,Perennial,Shrub,<NA>,<NA>,Missing_nativity,Shrub,SHR,USDA_traits,13,2,0.112886,96.830497
48,POSE4,Polygonum segetum Kunth,POSE4,Polygonum segetum Kunth,Perennial,Forb/herb,<NA>,<NA>,Missing_nativity,PerennialForb,PF,USDA_traits,12,4,0.104203,96.9347
49,CABI4,Carex bicolor Bellardi ex All.,CABI4,Carex bicolor Bellardi ex All.,Perennial,Graminoid,<NA>,<NA>,Missing_nativity,PerennialGraminoid,PerennialGraminoid,USDA_traits,12,6,0.104203,97.038902

==========================================================================================
MISSING_DURATION_AND_NATIVITY
==========================================================================================
Codes: 231 | Records: 12,894

--- USDA_growth_habit ---

  USDA_growth_habit  n_codes  n_records  pct_group_records
2       Nonvascular      135       8812          68.341864
1         Lichenous       70       2436          18.892508
0         Graminoid       26       1646          12.765627

--- USDA_duration ---

  USDA_duration  n_codes  n_records  pct_group_records
0          <NA>      231      12894              100.0

--- USDA_native_status_L48 ---

  USDA_native_status_L48  n_codes  n_records  pct_group_records
0                   <NA>      231      12894              100.0

--- taxonomic_level ---

  taxonomic_level  n_codes  n_records  pct_group_records
0            <NA>      231      12894              100.0

--- resolved_plant_group ---

  resolved_plant_group  n_codes  n_records  pct_group_records
0                 <NA>      205      11248          87.234373
1            Graminoid       26       1646          12.765627

--- MOSAIC_FG ---

              MOSAIC_FG  n_codes  n_records  pct_group_records
1  TraitUnresolvedPlant      205      11248          87.234373
0             Graminoid       26       1646          12.765627

--- FG_resolution_source ---

        FG_resolution_source  n_codes  n_records  pct_group_records
0  USDA_taxon_missing_traits      205      11248          87.234373
1                USDA_traits       26       1646          12.765627

Top taxa / codes:

,observed_code,resolved_label,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,taxonomic_level,USDA_trait_status,resolved_plant_group,MOSAIC_FG,FG_resolution_source,n_records_num,n_plot_visits,pct_group_records,cumulative_group_pct
0,HYSP70,Hylocomium splendens (Hedw.) Schimp.,HYSP70,Hylocomium splendens (Hedw.) Schimp.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1025,86,7.949434,7.949434
1,SPHAG2,Sphagnum L.,SPHAG2,Sphagnum L.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,884,44,6.855902,14.805336
2,DICR3,Digitaria cruciata (Nees ex Steud.) A. Camus,DICR3,Digitaria cruciata (Nees ex Steud.) A. Camus,<NA>,Graminoid,<NA>,<NA>,Missing_duration_nativity,Graminoid,Graminoid,USDA_traits,753,61,5.839926,20.645261
3,SCSC70,Scorpidium scorpioides (Hedw.) Limpr.,SCSC70,Scorpidium scorpioides (Hedw.) Limpr.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,649,32,5.033349,25.67861
4,TONI70,Tomentypnum nitens (Hedw.) Loeske,TONI70,Tomentypnum nitens (Hedw.) Loeske,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,589,62,4.568016,30.246626
5,LIRE13,Limprichtia revolvens (Sw.) Loeske,LIRE13,Limprichtia revolvens (Sw.) Loeske,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,484,40,3.753684,34.00031
6,AUTU70,Aulacomnium turgidum (Wahlenb.) Schwägr.,AUTU70,Aulacomnium turgidum (Wahlenb.) Schwägr.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,427,73,3.311618,37.311928
7,PLSC70,Pleurozium schreberi (Brid.) Mitt.,PLSC70,Pleurozium schreberi (Brid.) Mitt.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,426,38,3.303862,40.61579
8,FLCU,Flavocetraria cucullata (Bellardi) Karnefelt &...,FLCU,Flavocetraria cucullata (Bellardi) Karnefelt &...,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,374,75,2.900574,43.516364
9,CLRA60,Cladina rangiferina (L.) Nyl.,CLRA60,Cladina rangiferina (L.) Nyl.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,302,38,2.342175,45.858539
10,CAST51,Campylium stellatum (Hedw.) C.E.O. Jensen,CAST51,Campylium stellatum (Hedw.) C.E.O. Jensen,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,284,49,2.202575,48.061114
11,BRSA7,Brachythecium salebrosum (F. Weber & D. Mohr) ...,BRSA7,Brachythecium salebrosum (F. Weber & D. Mohr) ...,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,246,27,1.907864,49.968978
12,DICRA8,Dicranum Hedw.,DICRA8,Dicranum Hedw.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,228,37,1.768264,51.737242
13,DIEL70,Dicranum elongatum Schleich. ex Schwägr.,DIEL70,Dicranum elongatum Schleich. ex Schwägr.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,202,41,1.56662,53.303862
14,BLTR2,Blepharostoma trichophyllum (L.) Dumort.,BLTR2,Blepharostoma trichophyllum (L.) Dumort.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,192,27,1.489065,54.792927
15,SAUN8,Sanionia uncinata (Hedw.) Loeske,SAUN8,Sanionia uncinata (Hedw.) Loeske,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,190,38,1.473554,56.266481
16,ALBR12,Alopecurus brachystachus M. Bieb.,ALBR12,Alopecurus brachystachus M. Bieb.,<NA>,Graminoid,<NA>,<NA>,Missing_duration_nativity,Graminoid,Graminoid,USDA_traits,190,26,1.473554,57.740034
17,RACA11,Racomitrium canescens (Hedw.) Brid.,RACA11,Racomitrium canescens (Hedw.) Brid.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,168,8,1.302932,59.042966
18,STPA60,Stereocaulon paschale (L.) Hoffm.,STPA60,Stereocaulon paschale (L.) Hoffm.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,166,7,1.287421,60.330386
19,PTCI,Ptilidium ciliare (L.) Hampe,PTCI,Ptilidium ciliare (L.) Hampe,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,160,38,1.240887,61.571273
20,CEIS60,Cetraria islandica (L.) Ach.,CEIS60,Cetraria islandica (L.) Ach.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,160,45,1.240887,62.812161
21,RHRU70,Rhytidium rugosum (Hedw.) Kindb.,RHRU70,Rhytidium rugosum (Hedw.) Kindb.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,149,28,1.155576,63.967737
22,CLAR60,Cladina arbuscula (Wallr.) Hale & W.L. Culb.,CLAR60,Cladina arbuscula (Wallr.) Hale & W.L. Culb.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,146,15,1.13231,65.100047
23,PEAP60,Peltigera aphthosa (L.) Willd.,PEAP60,Peltigera aphthosa (L.) Willd.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,133,47,1.031488,66.131534
24,BRPS70,"Bryum pseudotriquetrum (Hedw.) G. Gaertn., B. ...",BRPS70,"Bryum pseudotriquetrum (Hedw.) G. Gaertn., B. ...",<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,127,18,0.984954,67.116488
25,THVE60,Thamnolia vermicularis (Sw.) Ach. ex Schaerer,THVE60,Thamnolia vermicularis (Sw.) Ach. ex Schaerer,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,126,34,0.977199,68.093687
26,DIGR71,Dicranum groenlandicum Brid.,DIGR71,Dicranum groenlandicum Brid.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,123,26,0.953932,69.047619
27,BRIN13,Bromus intermedius Guss.,BRIN13,Bromus intermedius Guss.,<NA>,Graminoid,<NA>,<NA>,Missing_duration_nativity,Graminoid,Graminoid,USDA_traits,121,10,0.938421,69.98604
28,POCO38,Polytrichum commune Hedw.,POCO38,Polytrichum commune Hedw.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,119,17,0.92291,70.90895
29,CLST5,Cladina stygia (Fr.) Ahti,CLST5,Cladina stygia (Fr.) Ahti,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,118,15,0.915154,71.824104
30,ONWA70,Oncophorus wahlenbergii Brid.,ONWA70,Oncophorus wahlenbergii Brid.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,116,29,0.899643,72.723747
31,CLMI60,Cladina mitis (Sandst.) Hustich,CLMI60,Cladina mitis (Sandst.) Hustich,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,109,19,0.845354,73.569102
32,DICA29,Distichium capillaceum (Hedw.) Bruch & Schimp.,DICA29,Distichium capillaceum (Hedw.) Bruch & Schimp.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,109,19,0.845354,74.414456
33,CELA60,Cetraria laevigata Rass.,CELA60,Cetraria laevigata Rass.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,106,21,0.822088,75.236544
34,POLYT5,Polytrichum Hedw.,POLYT5,Polytrichum Hedw.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,102,23,0.791066,76.02761
35,BRBI2,Bromus biebersteinii Roem. & Schult. [excluded],BRBI2,Bromus biebersteinii Roem. & Schult. [excluded],<NA>,Graminoid,<NA>,<NA>,Missing_duration_nativity,Graminoid,Graminoid,USDA_traits,100,9,0.775555,76.803164
36,BRRI7,Bromus riparius Rehmann,BRRI7,Bromus riparius Rehmann,<NA>,Graminoid,<NA>,<NA>,Missing_duration_nativity,Graminoid,Graminoid,USDA_traits,99,9,0.767799,77.570963
37,AUPA70,Aulacomnium palustre (Hedw.) Schwägr.,AUPA70,Aulacomnium palustre (Hedw.) Schwägr.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,95,38,0.736777,78.30774
38,HAVE70,Hamatocaulis vernicosus (Mitt.) Hedenäs,HAVE70,Hamatocaulis vernicosus (Mitt.) Hedenäs,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,86,11,0.666977,78.974717
39,SPFU70,Sphagnum fuscum (Schimp.) Klinggr.,SPFU70,Sphagnum fuscum (Schimp.) Klinggr.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,85,18,0.659221,79.633938
40,THAMN3,Thamnolia Ach. ex Schaerer,THAMN3,Thamnolia Ach. ex Schaerer,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,82,15,0.635955,80.269893
41,STPU10,Stipagrostis pungens (Desf.) De Winter,STPU10,Stipagrostis pungens (Desf.) De Winter,<NA>,Graminoid,<NA>,<NA>,Missing_duration_nativity,Graminoid,Graminoid,USDA_traits,82,19,0.635955,80.905848
42,POHY70,Polytrichum hyperboreum R. Br.,POHY70,Polytrichum hyperboreum R. Br.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,78,31,0.604933,81.51078
43,ELCO11,Eleocharis congesta D. Don,ELCO11,Eleocharis congesta D. Don,<NA>,Graminoid,<NA>,<NA>,Missing_duration_nativity,Graminoid,Graminoid,USDA_traits,77,6,0.597177,82.107957
44,CLGR13,Cladonia gracilis (L.) Willd.,CLGR13,Cladonia gracilis (L.) Willd.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,72,20,0.558399,82.666356
45,PELTI2,Peltigera Willd.,PELTI2,Peltigera Willd.,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,69,14,0.535133,83.201489
46,DIAC70,Dicranum acutifolium (Lindb. & Arnell) C.E.O. ...,DIAC70,Dicranum acutifolium (Lindb. & Arnell) C.E.O. ...,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,66,9,0.511866,83.713355
47,LOBA70,Loeskypnum badium (Hartm.) Paul,LOBA70,Loeskypnum badium (Hartm.) Paul,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,63,6,0.488599,84.201954
48,CLADO3,Cladonia P. Browne,CLADO3,Cladonia P. Browne,<NA>,Lichenous,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,62,37,0.480844,84.682798
49,SPLE5,Sphagnum lenense H. Lindb.,SPLE5,Sphagnum lenense H. Lindb.,<NA>,Nonvascular,<NA>,<NA>,Missing_duration_nativity,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,54,5,0.418799,85.101598

==========================================================================================
MISSING_DURATION_ONLY
==========================================================================================
Codes: 2 | Records: 53

--- USDA_growth_habit ---

  USDA_growth_habit  n_codes  n_records  pct_group_records
0       Nonvascular        2         53              100.0

--- USDA_duration ---

  USDA_duration  n_codes  n_records  pct_group_records
0          <NA>        2         53              100.0

--- USDA_native_status_L48 ---

  USDA_native_status_L48  n_codes  n_records  pct_group_records
0                 Native        2         53              100.0

--- taxonomic_level ---

  taxonomic_level  n_codes  n_records  pct_group_records
0            <NA>        2         53              100.0

--- resolved_plant_group ---

  resolved_plant_group  n_codes  n_records  pct_group_records
0                 <NA>        2         53              100.0

--- MOSAIC_FG ---

              MOSAIC_FG  n_codes  n_records  pct_group_records
0  TraitUnresolvedPlant        2         53              100.0

--- FG_resolution_source ---

        FG_resolution_source  n_codes  n_records  pct_group_records
0  USDA_taxon_missing_traits        2         53              100.0

Top taxa / codes:

,observed_code,resolved_label,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,taxonomic_level,USDA_trait_status,resolved_plant_group,MOSAIC_FG,FG_resolution_source,n_records_num,n_plot_visits,pct_group_records,cumulative_group_pct
0,DRAD2,Drepanocladus aduncus (Hedw.) Warnst.,DRAD2,Drepanocladus aduncus (Hedw.) Warnst.,<NA>,Nonvascular,Native,<NA>,Missing_duration,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,48,9,90.566038,90.566038
1,DREPA3,Drepanocladus (Müll. Hal.) G. Roth,DREPA3,Drepanocladus (Müll. Hal.) G. Roth,<NA>,Nonvascular,Native,<NA>,Missing_duration,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,5,3,9.433962,100.0

==========================================================================================
TRAITS_PRESENT_GROUP_UNRESOLVED
==========================================================================================
Codes: 321 | Records: 291,900

--- USDA_growth_habit ---

  USDA_growth_habit  n_codes  n_records  pct_group_records
0         Forb/herb      272     281036          96.278177
1    Forb/herb|Vine        8       9305           3.187736
2              Vine       41       1559           0.534087

--- USDA_duration ---

               USDA_duration  n_codes  n_records  pct_group_records
6                  Perennial      181     107784          36.924974
0                     Annual       83      90471          30.993834
1            Annual|Biennial       14      66482          22.775608
2  Annual|Biennial|Perennial       17      16295           5.582391
3           Annual|Perennial       10       7264           2.488523
5         Biennial|Perennial       10       2622           0.898253
4                   Biennial        6        982           0.336417

--- USDA_native_status_L48 ---

  USDA_native_status_L48  n_codes  n_records  pct_group_records
0                      I       59     151122           51.77184
2                      N      222     139275          47.713258
3                 Native       32       1050           0.359712
1             Introduced        8        453            0.15519

--- taxonomic_level ---

     taxonomic_level  n_codes  n_records  pct_group_records
0               <NA>      315     290492          99.517643
2  project_base_code        3       1218           0.417266
1              genus        3        190           0.065091

--- resolved_plant_group ---

  resolved_plant_group  n_codes  n_records  pct_group_records
0                 <NA>      321     291900              100.0

--- MOSAIC_FG ---

              MOSAIC_FG  n_codes  n_records  pct_group_records
0  TraitUnresolvedPlant      321     291900              100.0

--- FG_resolution_source ---

        FG_resolution_source  n_codes  n_records  pct_group_records
0  USDA_taxon_missing_traits      321     291900              100.0

Top taxa / codes:

,observed_code,resolved_label,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,taxonomic_level,USDA_trait_status,resolved_plant_group,MOSAIC_FG,FG_resolution_source,n_records_num,n_plot_visits,pct_group_records,cumulative_group_pct
0,ALDE,Alyssum desertorum Stapf,ALDE,Alyssum desertorum Stapf,Annual,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,26258,3321,8.995546,8.995546
1,PHHO,Phlox hoodii Richardson,PHHO,Phlox hoodii Richardson,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,22412,5933,7.677972,16.673518
2,SIAL2,Sisymbrium altissimum L.,SIAL2,Sisymbrium altissimum L.,Annual|Biennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,18009,2851,6.169579,22.843097
3,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,Annual|Biennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,16863,1831,5.776978,28.620075
4,ACMI2,Achillea millefolium L.,ACMI2,Achillea millefolium L.,Perennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,12985,3766,4.448441,33.068517
5,COPA3,Collinsia parviflora Lindl.,COPA3,Collinsia parviflora Lindl.,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,9380,2213,3.213429,36.281946
6,TAOF,Taraxacum officinale F.H. Wigg.,TAOF,Taraxacum officinale F.H. Wigg.,Perennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,9240,2211,3.165468,39.447413
7,DEPI,Descurainia pinnata (Walter) Britton,DEPI,Descurainia pinnata (Walter) Britton,Annual|Biennial|Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,9183,2719,3.14594,42.593354
8,LEPE2,Lepidium perfoliatum L.,LEPE2,Lepidium perfoliatum L.,Annual|Biennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,8619,1060,2.952724,45.546077
9,HAGL,Halogeton glomeratus (M. Bieb.) C.A. Mey.,HAGL,Halogeton glomeratus (M. Bieb.) C.A. Mey.,Annual,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,8041,1044,2.754711,48.300788
10,BASA3,Balsamorhiza sagittata (Pursh) Nutt.,BASA3,Balsamorhiza sagittata (Pursh) Nutt.,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,7624,1381,2.611853,50.912641
11,DRVE2,Draba verna L.,DRVE2,Draba verna L.,Annual,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,6341,1208,2.172319,53.084961
12,LASE,Lactuca serriola L.,LASE,Lactuca serriola L.,Annual|Biennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,6311,1429,2.162042,55.247002
13,ALAL3,Alyssum alyssoides (L.) L.,ALAL3,Alyssum alyssoides (L.) L.,Annual|Biennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,5257,794,1.800959,57.047962
14,VIAM,Vicia americana Muhl. ex Willd.,VIAM,Vicia americana Muhl. ex Willd.,Perennial,Forb/herb|Vine,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,5105,1422,1.748887,58.796848
15,MIGR,Microsteris gracilis (Hook.) Greene,MIGR,Microsteris gracilis (Hook.) Greene,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,4837,1468,1.657074,60.453923
16,CRAC2,Crepis acuminata Nutt.,CRAC2,Crepis acuminata Nutt.,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,4585,1875,1.570743,62.024666
17,TRDU,Tragopogon dubius Scop.,TRDU,Tragopogon dubius Scop.,Annual|Biennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3686,1907,1.262761,63.287427
18,LAOC3,Lappula occidentalis (S. Watson) Greene,LAOC3,Lappula occidentalis (S. Watson) Greene,Annual|Biennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3603,1054,1.234327,64.521754
19,MESA,Medicago sativa L.,MESA,Medicago sativa L.,Annual|Perennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3509,508,1.202124,65.723878
20,HOUM,Holosteum umbellatum L.,HOUM,Holosteum umbellatum L.,Annual,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3305,707,1.132237,66.856115
21,EPMI,Epilobium minutum Lindl. ex Lehm.,EPMI,Epilobium minutum Lindl. ex Lehm.,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,3209,613,1.099349,67.955464
22,ANRO2,Antennaria rosea Greene,ANRO2,Antennaria rosea Greene,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2967,592,1.016444,68.971908
23,LUCA,Lupinus caudatus Kellogg,LUCA,Lupinus caudatus Kellogg,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2812,522,0.963344,69.935252
24,COCA5,Conyza canadensis (L.) Cronquist,COCA5,Conyza canadensis (L.) Cronquist,Annual|Biennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2694,545,0.922919,70.858171
25,GIIN2,Gilia inconspicua (Sm.) Sweet,GIIN2,Gilia inconspicua (Sm.) Sweet,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2243,437,0.768414,71.626584
26,MELU,Medicago lupulina L.,MELU,Medicago lupulina L.,Annual|Perennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2223,487,0.761562,72.388147
27,CHJU,Chondrilla juncea L.,CHJU,Chondrilla juncea L.,Perennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2180,350,0.746831,73.134978
28,COAR4,Convolvulus arvensis L.,COAR4,Convolvulus arvensis L.,Perennial,Forb/herb|Vine,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2147,463,0.735526,73.870504
29,BLSC,Blepharipappus scaber Hook.,BLSC,Blepharipappus scaber Hook.,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,2081,446,0.712915,74.583419
30,MEAL6,Mentzelia albicaulis (Hook.) Torr. & A. Gray,MEAL6,Mentzelia albicaulis (Hook.) Torr. & A. Gray,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1937,566,0.663583,75.247002
31,COLI2,Collomia linearis Nutt.,COLI2,Collomia linearis Nutt.,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1874,522,0.642001,75.889003
32,PLLA,Plantago lanceolata L.,PLLA,Plantago lanceolata L.,Annual|Biennial|Perennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1865,249,0.638917,76.527921
33,CIAR4,Cirsium arvense (L.) Scop.,CIAR4,Cirsium arvense (L.) Scop.,Perennial,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1720,410,0.589243,77.117163
34,GADI2,Gayophytum diffusum Torr. & A. Gray,GADI2,Gayophytum diffusum Torr. & A. Gray,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1647,398,0.564234,77.681398
35,AMTE3,Amsinckia tessellata A. Gray,AMTE3,Amsinckia tessellata A. Gray,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1615,457,0.553272,78.234669
36,CHAL7,Chenopodium album L.,CHAL7,Chenopodium album L.,Annual,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1604,347,0.549503,78.784173
37,ANPA4,Antennaria parvifolia Nutt.,ANPA4,Antennaria parvifolia Nutt.,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1600,480,0.548133,79.332306
38,LOTR2,Lomatium triternatum (Pursh) J.M. Coult. & Rose,LOTR2,Lomatium triternatum (Pursh) J.M. Coult. & Rose,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1596,494,0.546763,79.879068
39,PODO4,Polygonum douglasii Greene,PODO4,Polygonum douglasii Greene,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1557,491,0.533402,80.41247
40,HEAN3,Helianthus annuus L.,HEAN3,Helianthus annuus L.,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1456,395,0.498801,80.911271
41,BAHO,Balsamorhiza hookeri (Hook.) Nutt.,BAHO,Balsamorhiza hookeri (Hook.) Nutt.,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1418,473,0.485783,81.397054
42,CHTE2,Chorispora tenella (Pall.) DC.,CHTE2,Chorispora tenella (Pall.) DC.,Annual,Forb/herb,I,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1332,182,0.456321,81.853374
43,GRSQ,Grindelia squarrosa (Pursh) Dunal,GRSQ,Grindelia squarrosa (Pursh) Dunal,Annual|Biennial|Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1273,472,0.436108,82.289483
44,CHLE4,Chenopodium leptophyllum (Moq.) Nutt. ex S. Wa...,CHLE4,Chenopodium leptophyllum (Moq.) Nutt. ex S. Wa...,Annual,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1221,269,0.418294,82.707777
45,SOMI2,Solidago missouriensis Nutt.,SOMI2,Solidago missouriensis Nutt.,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1100,428,0.376841,83.084618
46,SEIN2,Senecio integerrimus Nutt.,SEIN2,Senecio integerrimus Nutt.,Biennial|Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1088,402,0.37273,83.457348
47,MACA2,Machaeranthera canescens (Pursh) A. Gray,MACA2,Machaeranthera canescens (Pursh) A. Gray,Annual|Biennial|Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1079,393,0.369647,83.826996
48,TRMA3,Trifolium macrocephalum (Pursh) Poir.,TRMA3,Trifolium macrocephalum (Pursh) Poir.,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,1006,276,0.344639,84.171634
49,GETR,Geum triflorum Pursh,GETR,Geum triflorum Pursh,Perennial,Forb/herb,N,<NA>,Traits_present_group_unresolved,<NA>,TraitUnresolvedPlant,USDA_taxon_missing_traits,983,257,0.336759,84.508393

==========================================================================================
NO_USDA_TAXON
==========================================================================================
Codes: 3,144 | Records: 219,306

--- USDA_growth_habit ---

  USDA_growth_habit  n_codes  n_records  pct_group_records
0              <NA>     3144     219306              100.0

--- USDA_duration ---

  USDA_duration  n_codes  n_records  pct_group_records
0          <NA>     3144     219306              100.0

--- USDA_native_status_L48 ---

  USDA_native_status_L48  n_codes  n_records  pct_group_records
0                   <NA>     3144     219306              100.0

--- taxonomic_level ---

  taxonomic_level  n_codes  n_records  pct_group_records
0            <NA>     3143     219039          99.878252
1           genus        1        267           0.121748

--- resolved_plant_group ---

       resolved_plant_group  n_codes  n_records  pct_group_records
6        PerennialGraminoid      596      72557          33.084822
2               AnnualPlant        1      35750          16.301424
7                     Shrub      283      30999          14.135044
11             UnknownPlant      142      21114           9.627644
9   SubshrubOrPerennialForb        1      20140           9.183515
10                     Tree       38      16654           7.593955
0                AnnualForb      820      10940           4.988464
5             PerennialForb     1110       6991           3.187783
1           AnnualGraminoid      149       4055           1.849015
4                 Graminoid        2         74           0.033743
8                  Subshrub        1         25             0.0114
3                      Forb        1          7           0.003192

--- MOSAIC_FG ---

                          MOSAIC_FG  n_codes  n_records  pct_group_records
6                PerennialGraminoid      596      72557          33.084822
2                       AnnualPlant        1      35750          16.301424
7                               SHR      283      30999          14.135044
11                     UnknownPlant      142      21114           9.627644
9                      SubshrubOrPF        1      20140           9.183515
10                             TREE       38      16654           7.593955
0                                AF      820      10940           4.988464
5                                PF     1110       6991           3.187783
1   AnnualGraminoid_UnknownNativity      149       4055           1.849015
4                         Graminoid        2         74           0.033743
8                            SUBSHR        1         25             0.0114
3                              Forb        1          7           0.003192

--- FG_resolution_source ---

        FG_resolution_source  n_codes  n_records  pct_group_records
0  protocol_or_project_group     3144     219306              100.0

Top taxa / codes:

,observed_code,resolved_label,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,taxonomic_level,USDA_trait_status,resolved_plant_group,MOSAIC_FG,FG_resolution_source,n_records_num,n_plot_visits,pct_group_records,cumulative_group_pct
0,Perennial grasses,Perennial grasses,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,61012,1814,27.820488,27.820488
1,Annual plants,Annual plants,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualPlant,AnnualPlant,protocol_or_project_group,35750,1507,16.301424,44.121912
2,Shrubs,Shrubs,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,21122,1221,9.631291,53.753203
3,Sub-shrubs and perennial forbs,Sub-shrubs and perennial forbs,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,SubshrubOrPerennialForb,SubshrubOrPF,protocol_or_project_group,20140,1330,9.183515,62.936719
4,Plant base,Plant base,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,17980,1105,8.19859,71.135309
5,Trees,Trees,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Tree,TREE,protocol_or_project_group,14631,841,6.6715,77.806809
6,SH00,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,4187,903,1.909204,79.716013
7,AF00,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,2058,661,0.938415,80.654428
8,PF00,Perennial forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialForb,PF,protocol_or_project_group,1268,454,0.578188,81.232616
9,TR00,Tree,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Tree,TREE,protocol_or_project_group,972,94,0.443216,81.675832
10,PPGG,Perennial graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,853,21,0.388954,82.064786
11,2FA1,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,849,250,0.38713,82.451917
12,PG00,Perennial graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,687,173,0.313261,82.765177
13,AG04001,Annual graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualGraminoid,AnnualGraminoid_UnknownNativity,protocol_or_project_group,567,88,0.258543,83.02372
14,AF01000,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,528,142,0.240759,83.26448
15,AF02000,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,498,125,0.22708,83.49156
16,AAFF,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,482,25,0.219784,83.711344
17,BOETRII,Unknown plant,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,476,64,0.217048,83.928392
18,PG01,Perennial graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,456,85,0.207929,84.136321
19,2FP1,Perennial forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialForb,PF,protocol_or_project_group,450,192,0.205193,84.341514
20,PINSCO,Unknown plant,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,441,23,0.201089,84.542603
21,SU00,Unknown shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,440,171,0.200633,84.743235
22,PHYGOR,Unknown plant,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,365,50,0.166434,84.90967
23,2GP1,Perennial graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,338,59,0.154123,85.063792
24,SH03000,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,319,105,0.145459,85.209251
25,AG60001,Annual graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualGraminoid,AnnualGraminoid_UnknownNativity,protocol_or_project_group,309,16,0.140899,85.35015
26,SH01000,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,308,103,0.140443,85.490593
27,AAGG,Annual graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualGraminoid,AnnualGraminoid_UnknownNativity,protocol_or_project_group,292,9,0.133147,85.62374
28,PHYFEN,Unknown plant,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,290,66,0.132235,85.755976
29,ELELLA,Elymus,<NA>,<NA>,<NA>,<NA>,<NA>,genus,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,267,10,0.121748,85.877723
30,SH07000,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,265,101,0.120836,85.998559
31,AF07000,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,254,95,0.11582,86.114379
32,SIDTEN,Unknown plant,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,246,25,0.112172,86.226551
33,AG00,Annual graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualGraminoid,AnnualGraminoid_UnknownNativity,protocol_or_project_group,243,68,0.110804,86.337355
34,AF03000,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,242,102,0.110348,86.447703
35,PG02,Perennial graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,238,20,0.108524,86.556227
36,2SHRUB1,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,225,46,0.102596,86.658824
37,SPOCFCRY,Unknown plant,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,220,38,0.100316,86.75914
38,SH05000,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,215,86,0.098037,86.857177
39,PF01,Perennial forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialForb,PF,protocol_or_project_group,196,58,0.089373,86.94655
40,Unk,Unknown plant,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,UnknownPlant,UnknownPlant,protocol_or_project_group,195,46,0.088917,87.035466
41,AF10000,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,194,61,0.088461,87.123927
42,AG01001,Annual graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualGraminoid,AnnualGraminoid_UnknownNativity,protocol_or_project_group,192,10,0.087549,87.211476
43,AF20000,Annual forb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualForb,AF,protocol_or_project_group,185,42,0.084357,87.295833
44,AG04002,Annual graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualGraminoid,AnnualGraminoid_UnknownNativity,protocol_or_project_group,177,13,0.080709,87.376542
45,SH10000,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,159,65,0.072501,87.449044
46,SH09000,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,157,82,0.071589,87.520633
47,PG03000,Perennial graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,PerennialGraminoid,PerennialGraminoid,protocol_or_project_group,157,48,0.071589,87.592223
48,SH02000,Shrub,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,Shrub,SHR,protocol_or_project_group,153,79,0.069766,87.661988
49,AG01,Annual graminoid,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,No_USDA_taxon,AnnualGraminoid,AnnualGraminoid_UnknownNativity,protocol_or_project_group,152,33,0.06931,87.731298

==========================================================================================
INFERRED FAILURE REASONS
==========================================================================================

                                trait_failure_reason  n_codes  n_records  pct_of_all_plant_records
1                            Forb_should_now_resolve      280     290341                  5.340743
4                            No_USDA_taxonomic_match     3144     219306                  4.034074
5                         Nonvascular_should_resolve      137       8865                  0.163069
7  Shrub_should_resolve_without_duration_or_nativity       40       5460                  0.100435
3                 Grass_should_resolve_from_duration       34       5245                   0.09648
6            Other_growth_habit_requires_rule_review      113       4002                  0.073616
2           Grass_known_but_annual_perennial_unknown       26       1646                  0.030278
0               Forb_known_but_native_exotic_unknown       72        738                  0.013575
9              USDA_profile_has_no_ecological_traits       73        737                  0.013557
8   Tree_should_resolve_without_duration_or_nativity        5         66                  0.001214

In [36]:
# ============================================================================
# CANONICAL TWO-LEVEL MOSAIC FUNCTIONAL-GROUP CLASSIFICATION — REVISED
#
# LEVEL 1: MOSAIC_FG_structural
#   Uses growth habit + duration.
#
# LEVEL 2: MOSAIC_FG
#   Adds nativity where available.
#   Falls back to structural FG where nativity is unavailable.
#
# IMPORTANT:
#   - USDA source values remain untouched, including piped values.
#   - Both N/I and Native/Introduced are recognized.
#   - Duration is structurally meaningful for BOTH graminoids and forbs.
#   - Mixed woody habits retain Woody.
#   - Manual/project/protocol overrides retain precedence.
# ============================================================================

import pandas as pd
import numpy as np


# ============================================================================
# 1. HELPERS
# ============================================================================

def pipe_tokens(value):
    """
    Split USDA pipe-delimited values into normalized lowercase tokens.
    Original USDA fields are NOT modified.
    """

    if pd.isna(value):
        return set()

    value = str(value).strip()

    if value == "":
        return set()

    return {
        x.strip().lower()
        for x in value.split("|")
        if x.strip()
    }


def normalize_nativity_tokens(value):
    """
    USDA cache contains both abbreviated and full-word forms:

        N
        I
        Native
        Introduced

    Normalize all of them to:
        native
        introduced
    """

    tokens = pipe_tokens(value)

    normalized = set()

    for x in tokens:

        if x in {
            "n",
            "native",
        }:
            normalized.add("native")

        elif x in {
            "i",
            "introduced",
            "non-native",
            "nonnative",
            "exotic",
        }:
            normalized.add("introduced")

        else:
            normalized.add(x)

    return normalized


# ============================================================================
# 2. PARSE USDA FIELDS WITHOUT ALTERING SOURCE VALUES
# ============================================================================

growth_tokens = (
    master["USDA_growth_habit"]
    .apply(pipe_tokens)
)

duration_tokens = (
    master["USDA_duration"]
    .apply(pipe_tokens)
)

nativity_tokens = (
    master["USDA_native_status_L48"]
    .apply(normalize_nativity_tokens)
)


# ============================================================================
# 3. STRUCTURAL CLASSIFICATION
#
# Uses HABIT + DURATION.
#
# Nativity is deliberately NOT used here.
# ============================================================================

def classify_structural(
    growth_set,
    duration_set,
):
    """
    Derive structural / life-history functional group.
    """

    if not growth_set:
        return pd.NA


    # ========================================================================
    # NONVASCULAR
    # ========================================================================

    if growth_set == {
        "nonvascular"
    }:
        return "Nonvascular"


    # ========================================================================
    # GRAMINOIDS
    # ========================================================================

    if growth_set == {
        "graminoid"
    }:

        annual = (
            "annual"
            in duration_set
        )

        perennial = (
            "perennial"
            in duration_set
        )

        # Annual or Annual|Biennial
        if (
            annual
            and not perennial
        ):
            return "AnnualGrass"

        # Perennial or Biennial|Perennial
        if (
            perennial
            and not annual
        ):
            return "PerennialGrass"

        # Annual|Perennial or missing duration
        return "Grass"


    # ========================================================================
    # FORBS / HERBS
    #
    # Forb/herb|Vine still behaves structurally as a forb.
    #
    # But duration IS retained.
    # ========================================================================

    if "forb/herb" in growth_set:

        remaining = (
            growth_set
            - {
                "forb/herb",
                "vine",
            }
        )

        # Pure herbaceous forb / forb-vine
        if len(remaining) == 0:

            annual = (
                "annual"
                in duration_set
            )

            perennial = (
                "perennial"
                in duration_set
            )

            # Annual or Annual|Biennial
            if (
                annual
                and not perennial
            ):
                return "AnnualForb"

            # Perennial or Biennial|Perennial
            if (
                perennial
                and not annual
            ):
                return "PerennialForb"

            # Annual|Perennial, missing duration,
            # or otherwise ambiguous duration.
            return "Forb"


    # ========================================================================
    # PURE WOODY HABITS
    # ========================================================================

    if growth_set == {
        "shrub"
    }:
        return "Shrub"

    if growth_set == {
        "subshrub"
    }:
        return "Subshrub"

    if growth_set == {
        "tree"
    }:
        return "Tree"


    # ========================================================================
    # SHRUB + SUBSHRUB
    #
    # Treat as Shrub at our desired resolution.
    # ========================================================================

    if (
        growth_set
        and growth_set.issubset(
            {
                "shrub",
                "subshrub",
            }
        )
    ):
        return "Shrub"


    # ========================================================================
    # MIXED WOODY HABITS
    #
    # Examples:
    #   Shrub|Tree
    #   Shrub|Subshrub|Tree
    #
    # Do NOT arbitrarily choose Tree or Shrub.
    # ========================================================================

    woody = {
        "shrub",
        "subshrub",
        "tree",
    }

    woody_intersection = (
        growth_set
        .intersection(
            woody
        )
    )

    if (
        len(woody_intersection) >= 2
        and growth_set.issubset(
            woody
        )
    ):
        return "Woody"


    # ========================================================================
    # FORB + WOODY HABIT
    #
    # USDA genuinely regards these as spanning growth forms.
    # ========================================================================

    if (
        "forb/herb"
        in growth_set
        and len(
            growth_set.intersection(
                woody
            )
        ) > 0
    ):
        return "Woody"


    # ========================================================================
    # VINE ONLY
    # ========================================================================

    if growth_set == {
        "vine"
    }:
        return "Vine"


    # ========================================================================
    # REMAINING COMPLEX USDA HABITS
    #
    # Example:
    #   Graminoid|Shrub|Vine
    #
    # Do not invent a dominant structural class.
    # ========================================================================

    return "MixedGrowthHabit"


master[
    "MOSAIC_FG_structural"
] = pd.Series(
    [
        classify_structural(
            g,
            d,
        )
        for g, d
        in zip(
            growth_tokens,
            duration_tokens,
        )
    ],
    index=master.index,
    dtype="string",
)


# ============================================================================
# 4. NATIVITY CLASS
# ============================================================================

def classify_nativity(
    token_set
):

    if not token_set:
        return pd.NA

    # Introduced wins if USDA somehow contains both.
    if (
        "introduced"
        in token_set
    ):
        return "Introduced"

    if (
        "native"
        in token_set
    ):
        return "Native"

    return pd.NA


master[
    "MOSAIC_nativity_class"
] = pd.Series(
    [
        classify_nativity(x)
        for x
        in nativity_tokens
    ],
    index=master.index,
    dtype="string",
)


# ============================================================================
# 5. BUILD NATIVITY-REFINED FG
# ============================================================================

structural = (
    master[
        "MOSAIC_FG_structural"
    ]
    .astype("string")
)

native_class = (
    master[
        "MOSAIC_nativity_class"
    ]
    .astype("string")
)

refined = (
    structural.copy()
)


# ============================================================================
# ANNUAL GRASS
# ============================================================================

mask = (
    structural.eq(
        "AnnualGrass"
    )
    & native_class.eq(
        "Introduced"
    )
)

refined.loc[
    mask
] = "EAG"


mask = (
    structural.eq(
        "AnnualGrass"
    )
    & native_class.eq(
        "Native"
    )
)

refined.loc[
    mask
] = "NAG"


# ============================================================================
# PERENNIAL GRASS
# ============================================================================

mask = (
    structural.eq(
        "PerennialGrass"
    )
    & native_class.eq(
        "Introduced"
    )
)

refined.loc[
    mask
] = "EPG"


mask = (
    structural.eq(
        "PerennialGrass"
    )
    & native_class.eq(
        "Native"
    )
)

refined.loc[
    mask
] = "NPG"


# ============================================================================
# ANNUAL FORBS
# ============================================================================

mask = (
    structural.eq(
        "AnnualForb"
    )
    & native_class.eq(
        "Introduced"
    )
)

refined.loc[
    mask
] = "ExoticAnnualForb"


mask = (
    structural.eq(
        "AnnualForb"
    )
    & native_class.eq(
        "Native"
    )
)

refined.loc[
    mask
] = "NativeAnnualForb"


# ============================================================================
# PERENNIAL FORBS
# ============================================================================

mask = (
    structural.eq(
        "PerennialForb"
    )
    & native_class.eq(
        "Introduced"
    )
)

refined.loc[
    mask
] = "ExoticPerennialForb"


mask = (
    structural.eq(
        "PerennialForb"
    )
    & native_class.eq(
        "Native"
    )
)

refined.loc[
    mask
] = "NativePerennialForb"


# ============================================================================
# DURATION-AMBIGUOUS / DURATION-MISSING FORBS
#
# We still know they are forbs.
# ============================================================================

mask = (
    structural.eq(
        "Forb"
    )
    & native_class.eq(
        "Introduced"
    )
)

refined.loc[
    mask
] = "ExoticForb"


mask = (
    structural.eq(
        "Forb"
    )
    & native_class.eq(
        "Native"
    )
)

refined.loc[
    mask
] = "NativeForb"


# ============================================================================
# 6. STORE USDA-DERIVED VALUES
# ============================================================================

master[
    "USDA_derived_group"
] = (
    master[
        "MOSAIC_FG_structural"
    ]
)

master[
    "USDA_MOSAIC_FG"
] = refined


# ============================================================================
# 7. PROTECT MANUAL / PROJECT / PROTOCOL CLASSIFICATIONS
# ============================================================================

fg_source = (
    master[
        "FG_resolution_source"
    ]
    .astype("string")
    .fillna("")
    .str.lower()
    .str.strip()
)

protected = pd.Series(
    False,
    index=master.index,
)

for pattern in [
    "manual",
    "protocol",
    "project",
    "local",
]:

    protected = (
        protected
        | fg_source.str.contains(
            pattern,
            regex=False,
            na=False,
        )
    )


# Explicit known Bassia overrides.
protected = (
    protected
    | master[
        "observed_code"
    ].isin(
        [
            "BAPRV",
            "BAPRG",
        ]
    )
)


# ============================================================================
# 8. APPLY USDA TWO-LEVEL CLASSIFICATION
# ============================================================================

eligible = (
    master[
        "code_class"
    ].eq(
        "Plant"
    )
    & refined.notna()
    & ~protected
)


master.loc[
    eligible,
    "resolved_plant_group"
] = master.loc[
    eligible,
    "MOSAIC_FG_structural"
]

master.loc[
    eligible,
    "MOSAIC_FG"
] = refined.loc[
    eligible
]

master.loc[
    eligible,
    "FG_resolution_source"
] = (
    "USDA_two_level_traits"
)


# ============================================================================
# 9. REASSERT MANUAL BASSIA OVERRIDE
#
# Preserve the ecological decision already made for these records.
# ============================================================================

bassia = master[
    "observed_code"
].isin(
    [
        "BAPRV",
        "BAPRG",
    ]
)

master.loc[
    bassia,
    "MOSAIC_FG_structural"
] = "Forb"

master.loc[
    bassia,
    "resolved_plant_group"
] = "Forb"

master.loc[
    bassia,
    "MOSAIC_FG"
] = "ExoticForb"

master.loc[
    bassia,
    "FG_resolution_source"
] = (
    "manual_ecological_functional_override"
)


# ============================================================================
# 10. RECORD COUNTS
# ============================================================================

master[
    "n_records_num"
] = pd.to_numeric(
    master["n_records"],
    errors="coerce",
).fillna(0)


# ============================================================================
# 11. QA — CRITICAL TAXA
# ============================================================================

qa_codes = [
    "BRTE",
    "POSE",
    "PSSP6",
    "AGCR",
    "HECO26",
    "FEID",
    "ELEL5",
    "TACA8",
    "ALDE",
    "PHHO",
    "SIAL2",
    "ERCI6",
    "BAPRV",
    "BAPRG",
]

qa_cols = [
    "observed_code",
    "USDA_accepted_symbol",
    "USDA_scientific_name",
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status_L48",
    "MOSAIC_nativity_class",
    "MOSAIC_FG_structural",
    "USDA_MOSAIC_FG",
    "MOSAIC_FG",
    "FG_resolution_source",
    "n_records_num",
]

print(
    "=" * 90
)

print(
    "CRITICAL TAXON QA"
)

print(
    "=" * 90
)

display(
    master.loc[
        master[
            "observed_code"
        ].isin(
            qa_codes
        ),
        qa_cols,
    ]
    .sort_values(
        "observed_code"
    )
)


# ============================================================================
# 12. HARD BRTE ASSERTION
# ============================================================================

brte = master.loc[
    master[
        "observed_code"
    ].eq(
        "BRTE"
    )
]

assert (
    len(brte)
    == 1
)

assert (
    brte.iloc[0][
        "MOSAIC_FG_structural"
    ]
    == "AnnualGrass"
), (
    "BRTE structural FG is not AnnualGrass."
)


brte_nat = brte.iloc[0][
    "MOSAIC_nativity_class"
]

assert not pd.isna(
    brte_nat
), (
    "BRTE nativity did not parse."
)

assert (
    brte_nat
    == "Introduced"
), (
    f"Expected BRTE Introduced; got {brte_nat!r}"
)

assert (
    brte.iloc[0][
        "MOSAIC_FG"
    ]
    == "EAG"
), (
    "BRTE did not resolve to EAG."
)


# ============================================================================
# 13. POSE ASSERTION
# ============================================================================

pose = master.loc[
    master[
        "observed_code"
    ].eq(
        "POSE"
    )
]

if len(pose) == 1:

    assert (
        pose.iloc[0][
            "MOSAIC_FG_structural"
        ]
        == "PerennialGrass"
    )

    pose_nat = pose.iloc[0][
        "MOSAIC_nativity_class"
    ]

    if not pd.isna(
        pose_nat
    ):

        assert (
            pose_nat
            == "Native"
        )

        assert (
            pose.iloc[0][
                "MOSAIC_FG"
            ]
            == "NPG"
        )


# ============================================================================
# 14. FORB ASSERTIONS
# ============================================================================

alde = master.loc[
    master[
        "observed_code"
    ].eq(
        "ALDE"
    )
]

if len(alde) == 1:

    assert (
        alde.iloc[0][
            "MOSAIC_FG_structural"
        ]
        == "AnnualForb"
    )

    assert (
        alde.iloc[0][
            "MOSAIC_FG"
        ]
        == "ExoticAnnualForb"
    )


phho = master.loc[
    master[
        "observed_code"
    ].eq(
        "PHHO"
    )
]

if len(phho) == 1:

    assert (
        phho.iloc[0][
            "MOSAIC_FG_structural"
        ]
        == "PerennialForb"
    )

    assert (
        phho.iloc[0][
            "MOSAIC_FG"
        ]
        == "NativePerennialForb"
    )


# ============================================================================
# 15. DISTRIBUTION OF BOTH LABEL LEVELS
# ============================================================================

plant = master[
    "code_class"
].eq(
    "Plant"
)

total_plant_records = (
    master.loc[
        plant,
        "n_records_num"
    ]
    .sum()
)


structural_summary = (
    master.loc[
        plant
    ]
    .groupby(
        "MOSAIC_FG_structural",
        dropna=False,
    )
    .agg(
        n_codes=(
            "observed_code",
            "nunique",
        ),
        n_records=(
            "n_records_num",
            "sum",
        ),
    )
    .reset_index()
    .sort_values(
        "n_records",
        ascending=False,
    )
)

structural_summary[
    "pct_of_plant_records"
] = (
    100
    * structural_summary[
        "n_records"
    ]
    / total_plant_records
)


refined_summary = (
    master.loc[
        plant
    ]
    .groupby(
        "MOSAIC_FG",
        dropna=False,
    )
    .agg(
        n_codes=(
            "observed_code",
            "nunique",
        ),
        n_records=(
            "n_records_num",
            "sum",
        ),
    )
    .reset_index()
    .sort_values(
        "n_records",
        ascending=False,
    )
)

refined_summary[
    "pct_of_plant_records"
] = (
    100
    * refined_summary[
        "n_records"
    ]
    / total_plant_records
)


print(
    "\n"
    + "=" * 90
)

print(
    "STRUCTURAL FUNCTIONAL GROUPS"
)

print(
    "=" * 90
)

display(
    structural_summary
)


print(
    "\n"
    + "=" * 90
)

print(
    "NATIVITY-REFINED FUNCTIONAL GROUPS"
)

print(
    "=" * 90
)

display(
    refined_summary
)


print(
    "\nTwo-level MOSAIC classification: PASS"
)

==========================================================================================
CRITICAL TAXON QA
==========================================================================================

,observed_code,USDA_accepted_symbol,USDA_scientific_name,USDA_duration,USDA_growth_habit,USDA_native_status_L48,MOSAIC_nativity_class,MOSAIC_FG_structural,USDA_MOSAIC_FG,MOSAIC_FG,FG_resolution_source,n_records_num
31,AGCR,AGCR,Agropyron cristatum (L.) Gaertn.,Perennial,Graminoid,I,Introduced,PerennialGrass,EPG,EPG,USDA_two_level_traits,86637
38,ALDE,ALDE,Alyssum desertorum Stapf,Annual,Forb/herb,I,Introduced,AnnualForb,ExoticAnnualForb,ExoticAnnualForb,USDA_two_level_traits,26258
5664,BAPRG,BAPR5,<NA>,Perennial,Subshrub,I,Introduced,Forb,Subshrub,ExoticForb,manual_ecological_functional_override,4
4193,BAPRV,BAPR5,Barleria prionitis L.,Perennial,Subshrub,I,Introduced,Forb,Subshrub,ExoticForb,manual_ecological_functional_override,14
5,BRTE,BRTE,Bromus tectorum L.,Annual,Graminoid,Introduced,Introduced,AnnualGrass,EAG,EAG,USDA_two_level_traits,429816
9,ELEL5,ELEL5,Elymus elymoides (Raf.) Swezey,Perennial,Graminoid,N,Native,PerennialGrass,NPG,NPG,USDA_two_level_traits,58454
73,ERCI6,ERCI6,Erodium cicutarium (L.) L'Hér. ex Aiton,Annual|Biennial,Forb/herb,I,Introduced,AnnualForb,ExoticAnnualForb,ExoticAnnualForb,USDA_two_level_traits,16863
34,FEID,FEID,Festuca idahoensis Elmer,Perennial,Graminoid,N,Native,PerennialGrass,NPG,NPG,USDA_two_level_traits,78604
19,HECO26,HECO26,Hesperostipa comata (Trin. & Rupr.) Barkworth,Perennial,Graminoid,N,Native,PerennialGrass,NPG,NPG,USDA_two_level_traits,80033
22,PHHO,PHHO,Phlox hoodii Richardson,Perennial,Forb/herb,N,Native,PerennialForb,NativePerennialForb,NativePerennialForb,USDA_two_level_traits,22412
4,POSE,POSE,Poa secunda J. Presl,Perennial,Graminoid,Native,Native,PerennialGrass,NPG,NPG,USDA_two_level_traits,332740
10,PSSP6,PSSP6,Pseudoroegneria spicata (Pursh) Á. Löve,Perennial,Graminoid,N,Native,PerennialGrass,NPG,NPG,USDA_two_level_traits,163393
44,SIAL2,SIAL2,Sisymbrium altissimum L.,Annual|Biennial,Forb/herb,I,Introduced,AnnualForb,ExoticAnnualForb,ExoticAnnualForb,USDA_two_level_traits,18009
115,TACA8,TACA8,Taeniatherum caput-medusae (L.) Nevski,Annual,Graminoid,I,Introduced,AnnualGrass,EAG,EAG,USDA_two_level_traits,26357

==========================================================================================
STRUCTURAL FUNCTIONAL GROUPS
==========================================================================================

   MOSAIC_FG_structural  n_codes  n_records  pct_of_plant_records
7        PerennialGrass      896    2194527             40.367722
12                Woody     1374     769074             14.146905
1           AnnualGrass      163     684519             12.591539
8                 Shrub      656     518383              9.535513
0            AnnualForb     1261     326670              6.009005
6         PerennialForb     2173     267135              4.913875
10                 Tree      171     254418              4.679949
13                 <NA>     3217     220043              4.047631
2                  Forb      328      76229              1.402212
3                 Grass      104      59209              1.089133
9              Subshrub      105      36697              0.675031
4      MixedGrowthHabit      121      19006               0.34961
5           Nonvascular      137       8865              0.163069
11                 Vine       43       1566              0.028806

==========================================================================================
NATIVITY-REFINED FUNCTIONAL GROUPS
==========================================================================================

                          MOSAIC_FG  n_codes  n_records  pct_of_plant_records
15                              NPG      758    1718849             31.617755
34                            Woody     1373     769071              14.14685
5                               EAG       94     629830              11.58555
26                            Shrub      656     518383              9.535513
6                               EPG      104     470461              8.654001
31                             Tree      171     254418              4.679949
18              NativePerennialForb     1924     204474              3.761243
7                  ExoticAnnualForb      247     176308              3.243137
16                 NativeAnnualForb     1009     150277              2.764304
22               PerennialGraminoid      599      72584              1.335163
9               ExoticPerennialForb      190      62068              1.141724
12                            Grass      104      59209              1.089133
14                              NAG       67      54635              1.004996
17                       NativeForb      214      41603              0.765276
27                         Subshrub      105      36697              0.675031
4                       AnnualPlant        1      35750              0.657611
8                        ExoticForb      111      34617               0.63677
24                              SHR      284      31002              0.570273
32                     UnknownPlant      142      21114              0.388386
28                     SubshrubOrPF        1      20140               0.37047
13                 MixedGrowthHabit      121      19006               0.34961
29                             TREE       38      16654              0.306346
0                                AF      820      10940              0.201238
19                      Nonvascular      137       8865              0.163069
20                               PF     1110       6991              0.128598
23                   PerennialGrass       31       5190              0.095469
2   AnnualGraminoid_UnknownNativity      149       4055              0.074591
33                             Vine       43       1566              0.028806
30             TraitUnresolvedPlant       73        737              0.013557
21                    PerennialForb       59        593              0.010908
1                        AnnualForb        5         85              0.001564
11                        Graminoid        2         74              0.001361
3                       AnnualGrass        2         54              0.000993
25                           SUBSHR        1         25               0.00046
10                             Forb        4         16              0.000294

Two-level MOSAIC classification: PASS

In [34]:
# ============================================================
# REPAIR MALFORMED USDA TRAIT CACHE ROWS
#
# Problem:
# Old recursive parser wrote rows such as:
#   USDA_plant_id = NA
#   USDA_rank = Species|Kingdom|Subkingdom|...
#   traits = NA
#
# Those symbols are "present" in the cache, so ordinary
# missing-symbol recovery will not query them.
#
# This cell:
#   1. backs up cache
#   2. identifies malformed rows
#   3. re-queries them with ROOT-LEVEL parser
#   4. replaces malformed rows
#   5. validates priority taxa and cache integrity
# ============================================================

from pathlib import Path
from datetime import datetime, timezone
import shutil
import time
import pandas as pd
import requests


# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

USDA_SERVICE_BASE = "https://plantsservices.sc.egov.usda.gov/api"

REQUEST_TIMEOUT = 30
REQUEST_DELAY_SECONDS = 0.25
MAX_RETRIES = 3
SAVE_EVERY = 20

OUTPUT_DIR = Path(OUTPUT_DIR)

REPAIR_PROGRESS_FILE = (
    OUTPUT_DIR /
    "USDA_PLANTS_ecological_attributes_malformed_repair_progress.csv"
)

REPAIR_FAILURE_FILE = (
    OUTPUT_DIR /
    "USDA_PLANTS_ecological_attributes_malformed_repair_failures.csv"
)


# ------------------------------------------------------------
# HELPERS
# ------------------------------------------------------------

def clean_text(x):
    if x is None:
        return None

    x = str(x).strip()

    if x == "" or x.lower() in {
        "nan",
        "none",
        "null",
        "<na>",
    }:
        return None

    return x


def unique_pipe(values):
    if values is None:
        return None

    if not isinstance(values, (list, tuple, set)):
        values = [values]

    out = []

    for value in values:
        value = clean_text(value)

        if value is not None and value not in out:
            out.append(value)

    return "|".join(out) if out else None


# ------------------------------------------------------------
# CORRECT ROOT-LEVEL USDA PARSER
# ------------------------------------------------------------

def parse_profile_payload(symbol, payload):

    if not isinstance(payload, dict):
        raise TypeError(
            f"{symbol}: expected dict, "
            f"got {type(payload).__name__}"
        )

    returned_symbol = clean_text(
        payload.get("Symbol")
    )

    if returned_symbol != symbol:
        raise ValueError(
            f"Requested {symbol}, "
            f"USDA returned {returned_symbol}"
        )

    duration = unique_pipe(
        payload.get("Durations")
    )

    growth_habit = unique_pipe(
        payload.get("GrowthHabits")
    )

    l48_status = None
    l48_type = None

    for item in (
        payload.get("NativeStatuses")
        or []
    ):

        if not isinstance(item, dict):
            continue

        if clean_text(
            item.get("Region")
        ) == "L48":

            l48_status = clean_text(
                item.get("Status")
            )

            l48_type = clean_text(
                item.get("Type")
            )

            break

    return {
        "USDA_accepted_symbol":
            symbol,

        "USDA_plant_id":
            payload.get("Id"),

        "USDA_rank":
            clean_text(
                payload.get("Rank")
            ),

        "USDA_duration_api":
            duration,

        "USDA_growth_habit_api":
            growth_habit,

        "USDA_L48_native_status_api":
            l48_status,

        "USDA_L48_native_type_api":
            l48_type,

        "retrieved_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),
    }


# ------------------------------------------------------------
# FETCH ONE PROFILE
# ------------------------------------------------------------

def fetch_usda_traits(symbol):

    url = (
        f"{USDA_SERVICE_BASE}/PlantProfile"
    )

    last_error = None

    for attempt in range(
        1,
        MAX_RETRIES + 1
    ):

        try:

            response = requests.get(
                url,
                params={
                    "symbol": symbol
                },
                timeout=REQUEST_TIMEOUT,
                headers={
                    "Accept":
                        "application/json",

                    "User-Agent":
                        "MOSAIC-USDA-cache-repair/1.0",
                },
            )

            response.raise_for_status()

            return parse_profile_payload(
                symbol,
                response.json(),
            )

        except Exception as exc:

            last_error = exc

            if attempt < MAX_RETRIES:

                time.sleep(
                    REQUEST_DELAY_SECONDS
                    * (2 ** (attempt - 1))
                )

    raise RuntimeError(
        f"{symbol}: {repr(last_error)}"
    )


# ------------------------------------------------------------
# LOAD CACHE
# ------------------------------------------------------------

cache = pd.read_csv(
    USDA_ATTRIBUTE_CACHE,
    dtype="string",
    low_memory=False,
).copy()


# Normalize possible historical names
column_aliases = {
    "accepted_symbol":
        "USDA_accepted_symbol",

    "USDA_duration":
        "USDA_duration_api",

    "USDA_growth_habit":
        "USDA_growth_habit_api",

    "USDA_native_status_L48":
        "USDA_L48_native_status_api",
}


for old, new in column_aliases.items():

    if (
        old in cache.columns
        and new not in cache.columns
    ):

        cache = cache.rename(
            columns={
                old: new
            }
        )


required = [
    "USDA_accepted_symbol",
    "USDA_plant_id",
    "USDA_rank",
    "USDA_duration_api",
    "USDA_growth_habit_api",
    "USDA_L48_native_status_api",
    "USDA_L48_native_type_api",
]


for col in required:

    if col not in cache.columns:
        cache[col] = pd.NA


cache[
    "USDA_accepted_symbol"
] = (
    cache[
        "USDA_accepted_symbol"
    ]
    .astype("string")
    .str.strip()
)


# ------------------------------------------------------------
# BACK UP CURRENT CACHE BEFORE MODIFYING
# ------------------------------------------------------------

timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

backup_file = (
    OUTPUT_DIR /
    f"USDA_PLANTS_ecological_attributes_PRE_REPAIR_{timestamp}.csv"
)

cache.to_csv(
    backup_file,
    index=False,
)

print(
    "Backup written to:"
)

print(
    backup_file
)


# ------------------------------------------------------------
# IDENTIFY MALFORMED ROWS
# ------------------------------------------------------------
#
# Strong evidence of recursive-parser corruption:
#
# 1. USDA plant ID missing
#       Root PlantProfile should provide Id.
#
# 2. Rank contains "|"
#       Root rank is one value.
#       "Species|Kingdom|..." proves recursive aggregation.
#
# Either condition is enough to trigger repair.
# ------------------------------------------------------------

plant_id_missing = (
    cache[
        "USDA_plant_id"
    ]
    .isna()
    |
    cache[
        "USDA_plant_id"
    ]
    .astype("string")
    .str.strip()
    .isin(
        [
            "",
            "<NA>",
            "nan",
            "None",
        ]
    )
)


rank_has_pipe = (
    cache[
        "USDA_rank"
    ]
    .astype("string")
    .str.contains(
        r"\|",
        regex=True,
        na=False,
    )
)


malformed_mask = (
    plant_id_missing
    |
    rank_has_pipe
)


malformed = (
    cache.loc[
        malformed_mask
    ]
    .copy()
)


repair_symbols = (
    malformed[
        "USDA_accepted_symbol"
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
    .tolist()
)


print()
print(
    f"Current cache taxa: "
    f"{cache['USDA_accepted_symbol'].nunique():,}"
)

print(
    f"Malformed cache rows detected: "
    f"{len(malformed):,}"
)

print(
    f"Unique taxa requiring repair: "
    f"{len(repair_symbols):,}"
)


# ------------------------------------------------------------
# SHOW WHY THEY WERE FLAGGED
# ------------------------------------------------------------

display(
    malformed[
        [
            "USDA_accepted_symbol",
            "USDA_plant_id",
            "USDA_rank",
            "USDA_duration_api",
            "USDA_growth_habit_api",
            "USDA_L48_native_status_api",
            "USDA_L48_native_type_api",
            "retrieved_utc",
        ]
    ]
    .head(30)
)


# ------------------------------------------------------------
# LOAD ANY VALID REPAIR PROGRESS
# ------------------------------------------------------------

if REPAIR_PROGRESS_FILE.exists():

    repaired = pd.read_csv(
        REPAIR_PROGRESS_FILE,
        dtype="string",
        low_memory=False,
    )

    repaired_symbols = set(
        repaired[
            "USDA_accepted_symbol"
        ]
        .dropna()
        .astype(str)
        .str.strip()
    )

else:

    repaired = pd.DataFrame()
    repaired_symbols = set()


remaining = [
    symbol
    for symbol in repair_symbols
    if symbol not in repaired_symbols
]


print()
print(
    f"Previously repaired: "
    f"{len(repaired_symbols):,}"
)

print(
    f"Remaining this run: "
    f"{len(remaining):,}"
)


# ------------------------------------------------------------
# REPAIR LOOP
# ------------------------------------------------------------

pending_rows = []
pending_failures = []


for i, symbol in enumerate(
    remaining,
    start=1,
):

    try:

        row = fetch_usda_traits(
            symbol
        )

        pending_rows.append(
            row
        )

        print(
            f"[{i:03d}/{len(remaining):03d}] "
            f"{symbol:<10} "
            f"ID={str(row['USDA_plant_id']):<8} "
            f"R={str(row['USDA_rank']):<12} "
            f"D={str(row['USDA_duration_api']):<22} "
            f"H={str(row['USDA_growth_habit_api']):<24} "
            f"L48={str(row['USDA_L48_native_type_api'])}"
        )

    except Exception as exc:

        pending_failures.append(
            {
                "USDA_accepted_symbol":
                    symbol,

                "error":
                    repr(exc),

                "failed_utc":
                    datetime.now(
                        timezone.utc
                    ).isoformat(),
            }
        )

        print(
            f"[{i:03d}/{len(remaining):03d}] "
            f"{symbol:<10} FAILED | "
            f"{repr(exc)}"
        )


    # --------------------------------------------------------
    # CHECKPOINT
    # --------------------------------------------------------

    if (
        i % SAVE_EVERY == 0
        or i == len(remaining)
    ):

        if pending_rows:

            batch = pd.DataFrame(
                pending_rows
            )

            if repaired.empty:

                repaired = batch.copy()

            else:

                repaired = pd.concat(
                    [
                        repaired,
                        batch,
                    ],
                    ignore_index=True,
                    sort=False,
                )


            repaired = (
                repaired
                .drop_duplicates(
                    subset=[
                        "USDA_accepted_symbol"
                    ],
                    keep="last",
                )
                .sort_values(
                    "USDA_accepted_symbol"
                )
                .reset_index(
                    drop=True
                )
            )


            repaired.to_csv(
                REPAIR_PROGRESS_FILE,
                index=False,
            )

            pending_rows = []


        if pending_failures:

            failure_batch = pd.DataFrame(
                pending_failures
            )

            if REPAIR_FAILURE_FILE.exists():

                old_failures = pd.read_csv(
                    REPAIR_FAILURE_FILE,
                    dtype="string",
                    low_memory=False,
                )

                failure_batch = pd.concat(
                    [
                        old_failures,
                        failure_batch,
                    ],
                    ignore_index=True,
                    sort=False,
                )


            failure_batch.to_csv(
                REPAIR_FAILURE_FILE,
                index=False,
            )

            pending_failures = []


    time.sleep(
        REQUEST_DELAY_SECONDS
    )


# ------------------------------------------------------------
# RELOAD COMPLETE REPAIR TABLE
# ------------------------------------------------------------

if REPAIR_PROGRESS_FILE.exists():

    repaired = pd.read_csv(
        REPAIR_PROGRESS_FILE,
        dtype="string",
        low_memory=False,
    )

else:

    repaired = pd.DataFrame()


print()
print(
    f"Successfully repaired taxa: "
    f"{len(repaired):,}"
)


# ------------------------------------------------------------
# REPLACE MALFORMED CACHE ROWS
# ------------------------------------------------------------
#
# IMPORTANT:
# This is replacement, not append + keep-first.
# ------------------------------------------------------------

repaired_symbols = set(
    repaired[
        "USDA_accepted_symbol"
    ]
    .dropna()
    .astype(str)
    .str.strip()
)


# Remove ONLY rows successfully replaced.
# Failed queries remain in original cache for inspection.

cache_good = cache.loc[
    ~cache[
        "USDA_accepted_symbol"
    ].isin(
        repaired_symbols
    )
].copy()


updated_cache = pd.concat(
    [
        cache_good,
        repaired,
    ],
    ignore_index=True,
    sort=False,
)


updated_cache = (
    updated_cache
    .drop_duplicates(
        subset=[
            "USDA_accepted_symbol"
        ],
        keep="last",
    )
    .sort_values(
        "USDA_accepted_symbol"
    )
    .reset_index(
        drop=True
    )
)


updated_cache.to_csv(
    USDA_ATTRIBUTE_CACHE,
    index=False,
)


print()
print(
    f"Updated cache taxa: "
    f"{updated_cache['USDA_accepted_symbol'].nunique():,}"
)

print(
    "Repaired cache written to:"
)

print(
    USDA_ATTRIBUTE_CACHE
)


# ------------------------------------------------------------
# FINAL MALFORMED-ROW QA
# ------------------------------------------------------------

id_still_missing = (
    updated_cache[
        "USDA_plant_id"
    ]
    .isna()
)

rank_still_bad = (
    updated_cache[
        "USDA_rank"
    ]
    .astype("string")
    .str.contains(
        r"\|",
        regex=True,
        na=False,
    )
)


still_bad = updated_cache.loc[
    id_still_missing
    |
    rank_still_bad
].copy()


print()
print(
    f"Rows still structurally malformed: "
    f"{len(still_bad):,}"
)


if len(still_bad):

    display(
        still_bad[
            [
                "USDA_accepted_symbol",
                "USDA_plant_id",
                "USDA_rank",
                "USDA_duration_api",
                "USDA_growth_habit_api",
                "USDA_L48_native_status_api",
                "USDA_L48_native_type_api",
            ]
        ]
        .head(50)
    )


# ------------------------------------------------------------
# PRIORITY TAXON QA
# ------------------------------------------------------------

priority_symbols = [
    "PSSP6",
    "POPR",
    "AGCR",
    "HECO26",
    "FEID",
    "ELEL5",
    "BRIN2",
    "CHVI8",
    "SCAR7",
    "ARTR2",
    "TACA8",
    "ALDE",
    "SIAL2",
    "ERCI6",
    "TRDU",
]


priority_qa = (
    updated_cache.loc[
        updated_cache[
            "USDA_accepted_symbol"
        ].isin(
            priority_symbols
        ),
        [
            "USDA_accepted_symbol",
            "USDA_plant_id",
            "USDA_rank",
            "USDA_duration_api",
            "USDA_growth_habit_api",
            "USDA_L48_native_status_api",
            "USDA_L48_native_type_api",
            "retrieved_utc",
        ],
    ]
    .sort_values(
        "USDA_accepted_symbol"
    )
)


print(
    "\nPriority taxa after repair:"
)

display(
    priority_qa
)


print(
    "\nCACHE REPAIR COMPLETE"
)

Backup written to:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\USDA_PLANTS_ecological_attributes_PRE_REPAIR_20260903_094210.csv

Current cache taxa: 7,269
Malformed cache rows detected: 1
Unique taxa requiring repair: 1

,USDA_accepted_symbol,USDA_plant_id,USDA_rank,USDA_duration_api,USDA_growth_habit_api,USDA_L48_native_status_api,USDA_L48_native_type_api,retrieved_utc
5458,POAR22,<NA>,Variety|Kingdom|Subkingdom|Superdivision|Divis...,<NA>,<NA>,<NA>,<NA>,2026-09-01T20:09:22.201544+00:00

Previously repaired: 476
Remaining this run: 1
[001/001] POAR22     FAILED | RuntimeError("POAR22: ValueError('Requested POAR22, USDA returned PONIN')")

Successfully repaired taxa: 476

Updated cache taxa: 7,269
Repaired cache written to:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\species_dictionary_outputs\USDA_PLANTS_ecological_attributes.csv

Rows still structurally malformed: 1

,USDA_accepted_symbol,USDA_plant_id,USDA_rank,USDA_duration_api,USDA_growth_habit_api,USDA_L48_native_status_api,USDA_L48_native_type_api
5458,POAR22,<NA>,Variety|Kingdom|Subkingdom|Superdivision|Divis...,<NA>,<NA>,<NA>,<NA>

Priority taxa after repair:

     USDA_accepted_symbol USDA_plant_id USDA_rank USDA_duration_api USDA_growth_habit_api USDA_L48_native_status_api USDA_L48_native_type_api                     retrieved_utc
131                  AGCR         20068   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:19:14.115727+00:00
207                  ALDE         61805   Species            Annual             Forb/herb                          I               Introduced  2026-09-01T20:19:23.118227+00:00
642                 ARTR2         32390   Species         Perennial            Shrub|Tree                          N                   Native  2026-09-01T20:19:59.612017+00:00
1085                BRIN2         20954   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:20:20.233090+00:00
1755                CHVI8         33492   Species         Perennial                 Shrub                          N                   Native  2026-09-01T20:20:52.319662+00:00
2543                ELEL5         22420   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:21:38.980060+00:00
2711                ERCI6         83665   Species   Annual|Biennial             Forb/herb                          I               Introduced  2026-09-01T20:21:59.522310+00:00
3093                 FEID         23094   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:22:28.108292+00:00
3411               HECO26         23323   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:22:52.765229+00:00
5592                 POPR         25028   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:25:09.294033+00:00
5716                PSSP6         25163   Species         Perennial             Graminoid                          N                   Native  2026-09-01T20:25:16.932182+00:00
6191                SCAR7         25394   Species         Perennial             Graminoid                          I               Introduced  2026-09-01T20:25:48.164445+00:00
6357                SIAL2         63983   Species   Annual|Biennial             Forb/herb                          I               Introduced  2026-09-01T20:25:53.358516+00:00
6711                TACA8         25969   Species            Annual             Graminoid                          I               Introduced  2026-09-01T20:26:19.358376+00:00
6891                 TRDU         41535   Species   Annual|Biennial             Forb/herb                          I               Introduced  2026-09-01T20:26:28.390058+00:00

CACHE REPAIR COMPLETE

In [ ]:
# ============================================================
# PRE-QA HOTFIX / NORMALIZATION CELL
#
# Purpose:
#   Apply known final corrections directly to dictionary_fg
#   before running the hard QA/QC gate.
#
# This does NOT overwrite observed_code provenance.
# ============================================================

import pandas as pd

final = dictionary_fg.copy()


# ============================================================
# 1. POAR2R2 -> accepted USDA taxon PONIN
# ============================================================

mask = final["observed_code"].eq("POAR2R2")

assert mask.sum() == 1, (
    f"Expected exactly one POAR2R2 row, found {mask.sum()}."
)

idx = final.index[mask][0]

final.loc[idx, "USDA_symbol"] = "POAR2R2"
final.loc[idx, "USDA_accepted_symbol"] = "PONIN"

if "resolved_label" in final.columns:
    final.loc[idx, "resolved_label"] = "Potentilla nivea var. nivea"

if "code_class" in final.columns:
    final.loc[idx, "code_class"] = "Plant"

if "resolution_source" in final.columns:
    final.loc[idx, "resolution_source"] = "manual_USDA_synonym_resolution"

if "resolved" in final.columns:
    final.loc[idx, "resolved"] = True

if "needs_review" in final.columns:
    final.loc[idx, "needs_review"] = False

if "manual_note" in final.columns:
    final.loc[idx, "manual_note"] = (
        "POAR2R2 manually resolved through USDA synonym POAR22 "
        "to accepted symbol PONIN, Potentilla nivea var. nivea."
    )


# ============================================================
# 2. Pull PONIN taxonomy/traits from an existing PONIN row
#    if available in the current dictionary
# ============================================================

ponin = final.loc[
    final["USDA_accepted_symbol"].eq("PONIN")
    & ~final["observed_code"].eq("POAR2R2")
].copy()

if len(ponin):

    src = ponin.iloc[0]

    copy_cols = [
        "USDA_scientific_name",
        "USDA_common_name",
        "USDA_family",
        "USDA_genus",
        "USDA_rank",
        "USDA_duration",
        "USDA_growth_habit",
        "USDA_native_status",
        "USDA_native_status_L48",
        "USDA_wetland_status",
        "scientific_name",
        "common_name",
        "family",
        "genus",
        "taxonomic_rank",
        "native_status",
        "duration",
        "growth_habit",
        "wetland_status",
        "accepted_name_USDA",
        "SG_Group_resolved",
        "MOSAIC_FG",
        "FG_resolution_source",
    ]

    for col in copy_cols:
        if col in final.columns and col in src.index:
            final.loc[idx, col] = src[col]


# ============================================================
# 3. Restore __NO_CANOPY__ / literal NONE invariant
#    if stale notebook state reintroduced the collision
# ============================================================

# Identify by known record signatures, not row index.
no_canopy_mask = (
    final["n_records"].eq(442612)
    & final["n_top"].eq(442612)
)

literal_none_mask = (
    final["n_records"].eq(398)
    & final["n_top"].eq(394)
)

assert no_canopy_mask.sum() == 1
assert literal_none_mask.sum() == 1

no_canopy_idx = final.index[no_canopy_mask][0]
literal_none_idx = final.index[literal_none_mask][0]


# True blank sentinel
final.loc[no_canopy_idx, "observed_code"] = "__NO_CANOPY__"

if "code_upper" in final.columns:
    final.loc[no_canopy_idx, "code_upper"] = "__NO_CANOPY__"

if "resolved_label" in final.columns:
    final.loc[no_canopy_idx, "resolved_label"] = "No canopy contact"

if "code_class" in final.columns:
    final.loc[no_canopy_idx, "code_class"] = "NoCanopy"

if "MOSAIC_FG" in final.columns:
    final.loc[no_canopy_idx, "MOSAIC_FG"] = "NO_CANOPY"

if "resolution_source" in final.columns:
    final.loc[no_canopy_idx, "resolution_source"] = "blank_source_sentinel"


taxonomy_cols = [
    "scientific_name",
    "common_name",
    "family",
    "genus",
    "taxonomic_rank",
    "native_status",
    "duration",
    "growth_habit",
    "wetland_status",
    "synonym",
    "accepted_name_USDA",
    "USDA_symbol",
    "USDA_accepted_symbol",
    "USDA_match_type",
    "USDA_scientific_name",
    "USDA_common_name",
    "USDA_family",
    "USDA_genus",
    "USDA_rank",
    "USDA_duration",
    "USDA_growth_habit",
    "USDA_native_status",
    "USDA_native_status_L48",
    "USDA_wetland_status",
]

for col in taxonomy_cols:
    if col in final.columns:
        final.loc[no_canopy_idx, col] = pd.NA


# Genuine USDA plant symbol NONE
final.loc[literal_none_idx, "observed_code"] = "NONE"

if "code_upper" in final.columns:
    final.loc[literal_none_idx, "code_upper"] = "NONE"

if "code_class" in final.columns:
    final.loc[literal_none_idx, "code_class"] = "Plant"

if "USDA_symbol" in final.columns:
    final.loc[literal_none_idx, "USDA_symbol"] = "NONE"

if "USDA_accepted_symbol" in final.columns:
    final.loc[literal_none_idx, "USDA_accepted_symbol"] = "NONE"


# ============================================================
# 4. BASSIA final ecological override
# ============================================================

bassia_mask = final["observed_code"].isin(["BAPRV", "BAPRG"])

if bassia_mask.any():

    final.loc[
        bassia_mask,
        "USDA_accepted_symbol"
    ] = "BAPR5"

    if "MOSAIC_FG" in final.columns:
        final.loc[
            bassia_mask,
            "MOSAIC_FG"
        ] = "ExoticForb"

    if "FG_resolution_source" in final.columns:
        final.loc[
            bassia_mask,
            "FG_resolution_source"
        ] = "manual_ecological_functional_override"


# ============================================================
# 5. REMOVE POAR22 AS AN ACCEPTED SYMBOL
# ============================================================

# POAR22 is a synonym/legacy symbol, not the accepted taxon.
assert not final[
    "USDA_accepted_symbol"
].eq("POAR22").any(), (
    "POAR22 still survives as an accepted USDA symbol."
)


# ============================================================
# 6. CORE STRUCTURAL CHECKS
# ============================================================

assert len(final) == 10960

assert (
    final["observed_code"]
    .nunique(dropna=False)
    == 10960
)

assert (
    final["observed_code"]
    .duplicated(keep=False)
    .sum()
    == 0
)

assert (
    final["observed_code"]
    .eq("__NO_CANOPY__")
    .sum()
    == 1
)

assert (
    final["observed_code"]
    .eq("NONE")
    .sum()
    == 1
)

poar_check = final.loc[
    final["observed_code"].eq("POAR2R2"),
    [
        c for c in [
            "observed_code",
            "resolved_label",
            "USDA_symbol",
            "USDA_accepted_symbol",
            "USDA_scientific_name",
            "USDA_rank",
            "MOSAIC_FG",
            "resolution_source",
        ]
        if c in final.columns
    ]
]

print("POAR2R2 after hotfix:")
display(poar_check)

print("\nSentinel check:")
display(
    final.loc[
        final["observed_code"].isin(
            ["__NO_CANOPY__", "NONE"]
        ),
        [
            c for c in [
                "observed_code",
                "n_records",
                "n_top",
                "code_class",
                "USDA_accepted_symbol",
                "USDA_scientific_name",
                "MOSAIC_FG",
            ]
            if c in final.columns
        ]
    ]
)

print("\nPre-QA hotfix: PASS")


# ============================================================
# 7. Make QA use this corrected object
# ============================================================

dictionary_fg = final.copy()

POAR2R2 after hotfix:

      observed_code               resolved_label USDA_symbol USDA_accepted_symbol USDA_scientific_name             MOSAIC_FG               resolution_source
10143       POAR2R2  Potentilla nivea var. nivea     POAR2R2                PONIN                 <NA>  TraitUnresolvedPlant  manual_USDA_synonym_resolution

Sentinel check:

      observed_code  n_records   n_top code_class USDA_accepted_symbol       USDA_scientific_name             MOSAIC_FG
15    __NO_CANOPY__     442612  442612   NoCanopy                 <NA>                       <NA>             NO_CANOPY
2527           NONE        398     394      Plant                 NONE  Notholaena neglecta Maxon  TraitUnresolvedPlant

Pre-QA hotfix: PASS

In [35]:
# ============================================================
# TRUE FINAL QA/QC OF CURRENT IN-MEMORY DICTIONARY
#
# Run AFTER:
#   - manual alias corrections
#   - dictionary construction
#   - USDA taxonomy resolution
#   - USDA trait merge
#   - MOSAIC FG derivation
#
# Authoritative object: dictionary_fg
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

BASE_DIR = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present"
)

OUTPUT_DIR = BASE_DIR / "species_dictionary_outputs"

RAW_CODES_FILE = (
    BASE_DIR /
    "LDC_LPI_observed_code_unique.csv"
)

FINAL_MASTER_FILE = (
    OUTPUT_DIR /
    "LDC_LPI_species_dictionary_FINAL_MASTER.csv"
)

raw = pd.read_csv(
    RAW_CODES_FILE,
    dtype={"code": "string"},
    low_memory=False
)

final = dictionary_fg.copy()


# ============================================================
# 1. RECONSTRUCT AUTHORITATIVE RAW CANONICAL CODE
# ============================================================

raw["observed_code_raw"] = raw["code"]

raw["source_code_was_blank"] = (
    raw["observed_code_raw"].isna()
    |
    raw["observed_code_raw"].str.strip().eq("")
)

raw["observed_code"] = (
    raw["observed_code_raw"]
    .astype("string")
    .str.strip()
)

raw.loc[
    raw["source_code_was_blank"],
    "observed_code"
] = "__NO_CANOPY__"


# ============================================================
# 2. BASIC STRUCTURE
# ============================================================

print("=" * 78)
print("FINAL DICTIONARY STRUCTURE")
print("=" * 78)

print(f"Raw code rows:             {len(raw):,}")
print(f"Final dictionary rows:     {len(final):,}")

print(
    "Raw canonical codes:      "
    f"{raw['observed_code'].nunique(dropna=False):,}"
)

print(
    "Final unique codes:       "
    f"{final['observed_code'].nunique(dropna=False):,}"
)


duplicate_codes = final.loc[
    final["observed_code"].duplicated(keep=False)
].copy()

print(
    f"Duplicate final codes:     {len(duplicate_codes):,}"
)


# ============================================================
# 3. EXACT CODE-UNIVERSE ACCOUNTING
# ============================================================

raw_set = set(
    raw["observed_code"]
    .dropna()
    .astype(str)
)

final_set = set(
    final["observed_code"]
    .dropna()
    .astype(str)
)

missing_from_final = sorted(
    raw_set - final_set
)

extra_in_final = sorted(
    final_set - raw_set
)

print()
print("=" * 78)
print("CODE-UNIVERSE ACCOUNTING")
print("=" * 78)

print(
    f"Raw codes absent from final: {len(missing_from_final):,}"
)

print(
    f"Unexpected final codes:      {len(extra_in_final):,}"
)

if missing_from_final:
    print("\nMissing:")
    print(missing_from_final)

if extra_in_final:
    print("\nExtra:")
    print(extra_in_final)


# ============================================================
# 4. RECORD ACCOUNTING
# ============================================================

raw_records = (
    pd.to_numeric(
        raw["n_records"],
        errors="coerce"
    )
    .fillna(0)
    .sum()
)

final_records = (
    pd.to_numeric(
        final["n_records"],
        errors="coerce"
    )
    .fillna(0)
    .sum()
)

print()
print("=" * 78)
print("RECORD ACCOUNTING")
print("=" * 78)

print(f"Raw records:       {raw_records:,.0f}")
print(f"Final records:     {final_records:,.0f}")
print(f"Difference:        {final_records - raw_records:,.0f}")


# ============================================================
# 5. CRITICAL NONE / NO-CANOPY INVARIANT
# ============================================================

sentinel = final.loc[
    final["observed_code"].isin(
        ["__NO_CANOPY__", "NONE"]
    )
].copy()

print()
print("=" * 78)
print("NONE / __NO_CANOPY__")
print("=" * 78)

display(
    sentinel[
        [
            c for c in [
                "observed_code",
                "source_code_was_blank",
                "n_records",
                "n_top",
                "n_lower",
                "resolved_label",
                "code_class",
                "USDA_accepted_symbol",
                "USDA_scientific_name",
                "MOSAIC_FG",
                "resolution_source",
                "FG_resolution_source",
            ]
            if c in sentinel.columns
        ]
    ]
)

assert (
    final["observed_code"]
    .eq("__NO_CANOPY__")
    .sum()
    == 1
)

assert (
    final["observed_code"]
    .eq("NONE")
    .sum()
    == 1
)

no_canopy = final.loc[
    final["observed_code"].eq("__NO_CANOPY__")
].iloc[0]

literal_none = final.loc[
    final["observed_code"].eq("NONE")
].iloc[0]

assert no_canopy["n_records"] == 442612
assert literal_none["n_records"] == 398

assert no_canopy["code_class"] == "NoCanopy"
assert literal_none["code_class"] == "Plant"

assert pd.isna(
    no_canopy["USDA_accepted_symbol"]
)

assert (
    literal_none["USDA_accepted_symbol"]
    == "NONE"
)


# ============================================================
# 6. POAR2R2 CORRECTION
# ============================================================

poar = final.loc[
    final["observed_code"].eq("POAR2R2")
].copy()

print()
print("=" * 78)
print("POAR2R2")
print("=" * 78)

print("Rows:", len(poar))

display(
    poar[
        [
            c for c in [
                "observed_code",
                "n_records",
                "resolved_label",
                "code_class",
                "USDA_symbol",
                "USDA_accepted_symbol",
                "USDA_match_method",
                "USDA_scientific_name",
                "USDA_common_name",
                "USDA_family",
                "USDA_rank",
                "USDA_duration",
                "USDA_growth_habit",
                "USDA_native_status_L48",
                "MOSAIC_FG",
                "resolution_source",
                "FG_resolution_source",
            ]
            if c in poar.columns
        ]
    ]
)

assert len(poar) == 1

assert (
    poar.iloc[0]["USDA_accepted_symbol"]
    == "PONIN"
), (
    "POAR2R2 has not been corrected to accepted "
    "USDA symbol PONIN."
)


# ============================================================
# 7. BASSIA
# ============================================================

bassia = final.loc[
    final["observed_code"].isin(
        ["BAPRV", "BAPRG"]
    )
].copy()

print()
print("=" * 78)
print("BASSIA")
print("=" * 78)

display(
    bassia[
        [
            c for c in [
                "observed_code",
                "USDA_accepted_symbol",
                "USDA_scientific_name",
                "MOSAIC_FG",
                "resolution_source",
                "FG_resolution_source",
                "n_records",
            ]
            if c in bassia.columns
        ]
    ]
)

if len(bassia):

    assert (
        bassia["USDA_accepted_symbol"]
        .eq("BAPR5")
        .all()
    )

    assert (
        bassia["MOSAIC_FG"]
        .eq("ExoticForb")
        .all()
    )


# ============================================================
# 8. USDA ACCEPTED SYMBOLS THAT SHOULD NEVER SURVIVE
# ============================================================

bad_accepted_symbols = {
    "POAR22",
}

bad_taxa = final.loc[
    final["USDA_accepted_symbol"].isin(
        bad_accepted_symbols
    )
].copy()

print()
print("=" * 78)
print("OBSOLETE / INVALID ACCEPTED SYMBOLS")
print("=" * 78)

print(
    f"Rows carrying obsolete accepted symbols: "
    f"{len(bad_taxa):,}"
)

if len(bad_taxa):
    display(bad_taxa)

assert len(bad_taxa) == 0


# ============================================================
# 9. PLANT FG COMPLETENESS
# ============================================================

plants = final.loc[
    final["code_class"].eq("Plant")
].copy()

missing_fg = plants.loc[
    plants["MOSAIC_FG"].isna()
].copy()

print()
print("=" * 78)
print("PLANT FUNCTIONAL-GROUP COVERAGE")
print("=" * 78)

print(f"Plant codes:              {len(plants):,}")
print(
    f"Plant records:            "
    f"{plants['n_records'].sum():,}"
)

print(
    f"Plant codes missing FG:   "
    f"{len(missing_fg):,}"
)

print(
    f"Plant records missing FG: "
    f"{missing_fg['n_records'].sum():,}"
)


# ============================================================
# 10. ROW-LEVEL CONTEXT FLAGS
# ============================================================

if "requires_row_level_resolution" in final.columns:

    context_rows = final.loc[
        final[
            "requires_row_level_resolution"
        ].fillna(False)
    ].copy()

    print()
    print("=" * 78)
    print("ROW-LEVEL CONTEXT-DEPENDENT CODES")
    print("=" * 78)

    print(
        f"Context-dependent codes:   "
        f"{len(context_rows):,}"
    )

    print(
        f"Represented records:        "
        f"{context_rows['n_records'].sum():,}"
    )

    display(
        context_rows[
            [
                c for c in [
                    "observed_code",
                    "n_records",
                    "resolved_label",
                    "code_class",
                    "protocol_source",
                    "context_protocol_label",
                    "context_protocol_class",
                    "context_protocol_rule",
                    "MOSAIC_FG",
                ]
                if c in context_rows.columns
            ]
        ]
        .sort_values(
            "n_records",
            ascending=False
        )
    )


# ============================================================
# 11. HARD FINAL GATE
# ============================================================

checks = {
    "10,960 dictionary rows":
        len(final) == 10960,

    "10,960 unique observed codes":
        final["observed_code"].nunique(
            dropna=False
        ) == 10960,

    "No duplicate observed codes":
        len(duplicate_codes) == 0,

    "All raw codes represented":
        len(missing_from_final) == 0,

    "No unexpected codes":
        len(extra_in_final) == 0,

    "Exact record accounting":
        np.isclose(
            raw_records,
            final_records
        ),

    "One __NO_CANOPY__":
        final["observed_code"]
        .eq("__NO_CANOPY__")
        .sum() == 1,

    "One literal NONE":
        final["observed_code"]
        .eq("NONE")
        .sum() == 1,

    "POAR2R2 resolves to PONIN":
        (
            len(poar) == 1
            and
            poar.iloc[0][
                "USDA_accepted_symbol"
            ] == "PONIN"
        ),

    "No POAR22 accepted symbol remains":
        len(bad_taxa) == 0,

    "All plant codes have MOSAIC_FG":
        len(missing_fg) == 0,
}


print()
print("=" * 78)
print("FINAL GATE")
print("=" * 78)

all_pass = True

for name, passed in checks.items():

    status = (
        "PASS"
        if passed
        else "FAIL"
    )

    print(
        f"{status:<5}  {name}"
    )

    if not passed:
        all_pass = False


# ============================================================
# 12. WRITE ONLY IF EVERYTHING PASSES
# ============================================================

if not all_pass:

    raise RuntimeError(
        "Final dictionary failed one or more hard QA gates. "
        "Nothing was written."
    )


final.to_csv(
    FINAL_MASTER_FILE,
    index=False
)

print()
print("=" * 78)
print("FINAL MASTER WRITTEN")
print("=" * 78)

print(FINAL_MASTER_FILE)

==============================================================================
FINAL DICTIONARY STRUCTURE
==============================================================================
Raw code rows:             10,960
Final dictionary rows:     10,960
Raw canonical codes:      10,960
Final unique codes:       10,960
Duplicate final codes:     0

==============================================================================
CODE-UNIVERSE ACCOUNTING
==============================================================================
Raw codes absent from final: 0
Unexpected final codes:      0

==============================================================================
RECORD ACCOUNTING
==============================================================================
Raw records:       16,150,101
Final records:     16,150,101
Difference:        0

==============================================================================
NONE / __NO_CANOPY__
==============================================================================

,observed_code,source_code_was_blank,n_records,n_top,n_lower,resolved_label,code_class,USDA_accepted_symbol,USDA_scientific_name,MOSAIC_FG,resolution_source,FG_resolution_source
15,__NO_CANOPY__,True,442612,442612,0,No top-canopy contact,NoCanopy,<NA>,<NA>,NaN,source_blank_sentinel,<NA>
2527,NONE,False,398,394,4,Notholaena neglecta Maxon,Plant,NONE,Notholaena neglecta Maxon,TraitUnresolvedPlant,USDA_accepted_symbol,USDA_taxon_missing_traits

==============================================================================
POAR2R2
==============================================================================
Rows: 1

,observed_code,n_records,resolved_label,code_class,USDA_accepted_symbol,USDA_match_method,USDA_scientific_name,USDA_common_name,USDA_family,USDA_duration,USDA_growth_habit,USDA_native_status_L48,MOSAIC_FG,resolution_source,FG_resolution_source
10143,POAR2R2,10,Potentilla nivea var. nivea,Plant,PONIN,manual_alias,Potentilla nivea L. var. nivea,snow cinquefoil,Rosaceae,<NA>,<NA>,<NA>,TraitUnresolvedPlant,manual_USDA_synonym_resolution,USDA_taxon_missing_traits

==============================================================================
BASSIA
==============================================================================

     observed_code USDA_accepted_symbol   USDA_scientific_name MOSAIC_FG       resolution_source       FG_resolution_source  n_records
4193         BAPRV                 BAPR  Barleria prionitis L.      Forb  manual_taxonomic_alias  protocol_or_project_group         14
5664         BAPRG                 <NA>                   <NA>       NaN                    <NA>  protocol_or_project_group          4

AssertionError:

In [ ]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present"
)

OUTPUT_DIR = BASE_DIR / "species_dictionary_outputs"

files_to_check = [
    "USDA_PLANTS_ecological_attributes.csv",
    "USDA_PLANTS_ecological_attributes_final.csv",
    "LDC_LPI_species_dictionary_MASTER.csv",
    "LDC_LPI_species_dictionary_pre_functional_group.csv",
    "LDC_LPI_species_dictionary_QA.csv",
]

for fname in files_to_check:
    path = OUTPUT_DIR / fname

    print("\n" + "=" * 80)
    print(fname)
    print("=" * 80)

    df = pd.read_csv(path, low_memory=False)

    print("rows:", len(df))
    print("columns:")
    for c in df.columns:
        print("  ", repr(c))

================================================================================
USDA_PLANTS_ecological_attributes.csv
================================================================================
rows: 7268
columns:
   'USDA_accepted_symbol'
   'USDA_plant_id'
   'USDA_rank'
   'USDA_duration_api'
   'USDA_growth_habit_api'
   'USDA_L48_native_status_api'
   'USDA_L48_native_type_api'
   'retrieved_utc'

================================================================================
USDA_PLANTS_ecological_attributes_final.csv
================================================================================
rows: 6790
columns:
   'accepted_symbol'
   'USDA_plant_id'
   'USDA_rank'
   'USDA_duration_api'
   'USDA_growth_habit_api'
   'USDA_L48_native_status_api'
   'USDA_L48_native_type_api'
   'retrieved_utc'
   'duration_set'
   'growth_habit_set'
   'n_duration_values'
   'n_growth_habit_values'
   'duration_ambiguous'
   'growth_habit_ambiguous'

================================================================================
LDC_LPI_species_dictionary_MASTER.csv
================================================================================
rows: 10960
columns:
   'observed_code'
   'code_upper'
   'n_records'
   'n_plot_visits'
   'n_top'
   'n_lower'
   'n_soil_surface'
   'n_top_plots'
   'n_multilayer_plots'
   'n_scope_top'
   'n_scope_multilayer'
   'n_scope_raw'
   'first_year'
   'last_year'
   'resolved_label'
   'code_class'
   'resolution_source'
   'resolved'
   'needs_review'
   'requires_row_level_resolution'
   'protocol_context_QA'
   'protocol_source'
   'protocol_valid_context'
   'manual_note'
   'context_protocol_label'
   'context_protocol_class'
   'context_protocol_source'
   'context_protocol_rule'
   'context_protocol_note'
   'Relevant'
   'Native Status'
   'Duration'
   'GrowthHabitSub'
   'SG_Group'
   'SG_Group_resolved'
   'MOSAIC_FG'
   'Foliar'
   'scientific_name'
   'common_name'
   'family'
   'genus'
   'taxonomic_rank'
   'native_status'
   'duration'
   'growth_habit'
   'wetland_status'
   'synonym'
   'accepted_name_USDA'
   'USDA_symbol'
   'USDA_accepted_symbol'
   'USDA_match_type'
   'USDA_scientific_name'
   'USDA_common_name'
   'USDA_family'
   'USDA_genus'
   'USDA_rank'
   'USDA_duration'
   'USDA_growth_habit'
   'USDA_native_status'
   'USDA_wetland_status'

================================================================================
LDC_LPI_species_dictionary_pre_functional_group.csv
================================================================================
rows: 10960
columns:
   'code'
   'n_records'
   'n_plot_visits'
   'n_top'
   'n_lower'
   'n_soil_surface'
   'n_top_plots'
   'n_multilayer_plots'
   'first_year'
   'last_year'
   'source_code_was_blank'
   'observed_code'
   'n_scope_top'
   'n_scope_multilayer'
   'n_scope_raw'
   'code_upper'
   'label'
   'Relevant'
   'Native Status'
   'Duration'
   'GrowthHabitSub'
   'SG_Group'
   'Foliar'
   'MOSAIC_FG_local'
   'resolved_label_manual'
   'code_class_manual'
   'SG_Group_manual'
   'MOSAIC_FG_manual'
   'protocol_source'
   'protocol_valid_context'
   'manual_note'
   'context_protocol_label'
   'context_protocol_class'
   'context_protocol_source'
   'context_protocol_rule'
   'context_protocol_note'
   'requires_row_level_resolution'
   'USDA_accepted_symbol'
   'USDA_scientific_name'
   'USDA_common_name'
   'USDA_family'
   'USDA_match_type'
   'USDA_syn_accepted_symbol'
   'USDA_synonym_symbol'
   'USDA_synonym_scientific_name'
   'USDA_syn_accepted_scientific_name'
   'USDA_syn_accepted_common_name'
   'USDA_syn_accepted_family'
   'USDA_symbol'
   'USDA_genus'
   'USDA_rank_x'
   'USDA_duration'
   'USDA_growth_habit'
   'USDA_native_status'
   'USDA_wetland_status'
   'USDA_synonym'
   'USDA_accepted_name'
   'resolved_label'
   'code_class'
   'SG_Group_resolved'
   'MOSAIC_FG'
   'scientific_name'
   'common_name'
   'family'
   'genus'
   'taxonomic_rank'
   'native_status'
   'duration'
   'growth_habit'
   'wetland_status'
   'synonym'
   'accepted_name_USDA'
   'resolution_source'
   'resolved'
   'needs_review'
   'protocol_context_QA'
   'USDA_duration_api_x'
   'USDA_growth_habit_api_x'
   'USDA_L48_native_status_api_x'
   'USDA_L48_native_type_api_x'
   'retrieved_utc_x'
   'USDA_native_type'
   'USDA_plant_id'
   'USDA_rank_y'
   'USDA_duration_api_y'
   'USDA_growth_habit_api_y'
   'USDA_L48_native_status_api_y'
   'USDA_L48_native_type_api_y'
   'retrieved_utc_y'

================================================================================
LDC_LPI_species_dictionary_QA.csv
================================================================================
rows: 3
columns:
   'scope'
   'unique_codes'
   'resolved_codes'
   'needs_review_codes'
   'plant_codes'
   'context_dependent_codes'
   'total_records'
   'resolved_records'
   'resolved_record_pct'
   'needs_review_records'
   'needs_review_record_pct'
   'context_dependent_records'
   'plant_records'

In [ ]:
from pathlib import Path

BASE_DIR = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present"
)

OUTPUT_DIR = BASE_DIR / "species_dictionary_outputs"

for p in sorted(OUTPUT_DIR.glob("*.csv")):
    print(p.name)

LDC_LPI_canopymultilayer_dictionary.csv
LDC_LPI_canopymultilayer_review_codes.csv
LDC_LPI_canopymultilayer_species_list.csv
LDC_LPI_multilayer_dictionary.csv
LDC_LPI_multilayer_species_list.csv
LDC_LPI_multilayer_unresolved_codes.csv
LDC_LPI_protocol_code_rules.csv
LDC_LPI_rawallcontacts_dictionary.csv
LDC_LPI_rawallcontacts_review_codes.csv
LDC_LPI_rawallcontacts_species_list.csv
LDC_LPI_rawallcontacts_unresolved_codes.csv
LDC_LPI_species_dictionary_MASTER.csv
LDC_LPI_species_dictionary_pre_functional_group.csv
LDC_LPI_species_dictionary_QA.csv
LDC_LPI_topcanopy_dictionary.csv
LDC_LPI_topcanopy_review_codes.csv
LDC_LPI_topcanopy_species_list.csv
LDC_LPI_topcanopy_unresolved_codes.csv
USDA_PLANTS_ecological_attributes.csv
USDA_PLANTS_ecological_attributes_final.csv
USDA_PLANTS_ecological_attributes_malformed_repair_failures.csv
USDA_PLANTS_ecological_attributes_malformed_repair_progress.csv
USDA_PLANTS_ecological_attributes_missing_taxa_progress_BAD_PARSER_BACKUP.csv
USDA_PLANTS_ecological_attributes_PRE_REPAIR_20260901_141910.csv

In [ ]:
# ============================================================
# TRUE FINAL QA/QC OF CURRENT IN-MEMORY DICTIONARY
#
# Run AFTER:
#   - manual alias corrections
#   - dictionary construction
#   - USDA taxonomy resolution
#   - USDA trait merge
#   - MOSAIC FG derivation
#
# Authoritative object: dictionary_fg
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

BASE_DIR = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present"
)

OUTPUT_DIR = BASE_DIR / "species_dictionary_outputs"

RAW_CODES_FILE = (
    BASE_DIR /
    "LDC_LPI_observed_code_unique.csv"
)

FINAL_MASTER_FILE = (
    OUTPUT_DIR /
    "LDC_LPI_species_dictionary_FINAL_MASTER.csv"
)

raw = pd.read_csv(
    RAW_CODES_FILE,
    dtype={"code": "string"},
    low_memory=False
)

final = dictionary_fg.copy()


# ============================================================
# 1. RECONSTRUCT AUTHORITATIVE RAW CANONICAL CODE
# ============================================================

raw["observed_code_raw"] = raw["code"]

raw["source_code_was_blank"] = (
    raw["observed_code_raw"].isna()
    |
    raw["observed_code_raw"].str.strip().eq("")
)

raw["observed_code"] = (
    raw["observed_code_raw"]
    .astype("string")
    .str.strip()
)

raw.loc[
    raw["source_code_was_blank"],
    "observed_code"
] = "__NO_CANOPY__"


# ============================================================
# 2. BASIC STRUCTURE
# ============================================================

print("=" * 78)
print("FINAL DICTIONARY STRUCTURE")
print("=" * 78)

print(f"Raw code rows:             {len(raw):,}")
print(f"Final dictionary rows:     {len(final):,}")

print(
    "Raw canonical codes:      "
    f"{raw['observed_code'].nunique(dropna=False):,}"
)

print(
    "Final unique codes:       "
    f"{final['observed_code'].nunique(dropna=False):,}"
)


duplicate_codes = final.loc[
    final["observed_code"].duplicated(keep=False)
].copy()

print(
    f"Duplicate final codes:     {len(duplicate_codes):,}"
)


# ============================================================
# 3. EXACT CODE-UNIVERSE ACCOUNTING
# ============================================================

raw_set = set(
    raw["observed_code"]
    .dropna()
    .astype(str)
)

final_set = set(
    final["observed_code"]
    .dropna()
    .astype(str)
)

missing_from_final = sorted(
    raw_set - final_set
)

extra_in_final = sorted(
    final_set - raw_set
)

print()
print("=" * 78)
print("CODE-UNIVERSE ACCOUNTING")
print("=" * 78)

print(
    f"Raw codes absent from final: {len(missing_from_final):,}"
)

print(
    f"Unexpected final codes:      {len(extra_in_final):,}"
)

if missing_from_final:
    print("\nMissing:")
    print(missing_from_final)

if extra_in_final:
    print("\nExtra:")
    print(extra_in_final)


# ============================================================
# 4. RECORD ACCOUNTING
# ============================================================

raw_records = (
    pd.to_numeric(
        raw["n_records"],
        errors="coerce"
    )
    .fillna(0)
    .sum()
)

final_records = (
    pd.to_numeric(
        final["n_records"],
        errors="coerce"
    )
    .fillna(0)
    .sum()
)

print()
print("=" * 78)
print("RECORD ACCOUNTING")
print("=" * 78)

print(f"Raw records:       {raw_records:,.0f}")
print(f"Final records:     {final_records:,.0f}")
print(f"Difference:        {final_records - raw_records:,.0f}")


# ============================================================
# 5. CRITICAL NONE / NO-CANOPY INVARIANT
# ============================================================

sentinel = final.loc[
    final["observed_code"].isin(
        ["__NO_CANOPY__", "NONE"]
    )
].copy()

print()
print("=" * 78)
print("NONE / __NO_CANOPY__")
print("=" * 78)

display(
    sentinel[
        [
            c for c in [
                "observed_code",
                "source_code_was_blank",
                "n_records",
                "n_top",
                "n_lower",
                "resolved_label",
                "code_class",
                "USDA_accepted_symbol",
                "USDA_scientific_name",
                "MOSAIC_FG",
                "resolution_source",
                "FG_resolution_source",
            ]
            if c in sentinel.columns
        ]
    ]
)

assert (
    final["observed_code"]
    .eq("__NO_CANOPY__")
    .sum()
    == 1
)

assert (
    final["observed_code"]
    .eq("NONE")
    .sum()
    == 1
)

no_canopy = final.loc[
    final["observed_code"].eq("__NO_CANOPY__")
].iloc[0]

literal_none = final.loc[
    final["observed_code"].eq("NONE")
].iloc[0]

assert no_canopy["n_records"] == 442612
assert literal_none["n_records"] == 398

assert no_canopy["code_class"] == "NoCanopy"
assert literal_none["code_class"] == "Plant"

assert pd.isna(
    no_canopy["USDA_accepted_symbol"]
)

assert (
    literal_none["USDA_accepted_symbol"]
    == "NONE"
)


# ============================================================
# 6. POAR2R2 CORRECTION
# ============================================================

poar = final.loc[
    final["observed_code"].eq("POAR2R2")
].copy()

print()
print("=" * 78)
print("POAR2R2")
print("=" * 78)

print("Rows:", len(poar))

display(
    poar[
        [
            c for c in [
                "observed_code",
                "n_records",
                "resolved_label",
                "code_class",
                "USDA_symbol",
                "USDA_accepted_symbol",
                "USDA_match_method",
                "USDA_scientific_name",
                "USDA_common_name",
                "USDA_family",
                "USDA_rank",
                "USDA_duration",
                "USDA_growth_habit",
                "USDA_native_status_L48",
                "MOSAIC_FG",
                "resolution_source",
                "FG_resolution_source",
            ]
            if c in poar.columns
        ]
    ]
)

assert len(poar) == 1

assert (
    poar.iloc[0]["USDA_accepted_symbol"]
    == "PONIN"
), (
    "POAR2R2 has not been corrected to accepted "
    "USDA symbol PONIN."
)


# ============================================================
# 7. BASSIA
# ============================================================

bassia = final.loc[
    final["observed_code"].isin(
        ["BAPRV", "BAPRG"]
    )
].copy()

print()
print("=" * 78)
print("BASSIA")
print("=" * 78)

display(
    bassia[
        [
            c for c in [
                "observed_code",
                "USDA_accepted_symbol",
                "USDA_scientific_name",
                "MOSAIC_FG",
                "resolution_source",
                "FG_resolution_source",
                "n_records",
            ]
            if c in bassia.columns
        ]
    ]
)

if len(bassia):

    assert (
        bassia["USDA_accepted_symbol"]
        .eq("BAPR5")
        .all()
    )

    assert (
        bassia["MOSAIC_FG"]
        .eq("ExoticForb")
        .all()
    )


# ============================================================
# 8. USDA ACCEPTED SYMBOLS THAT SHOULD NEVER SURVIVE
# ============================================================

bad_accepted_symbols = {
    "POAR22",
}

bad_taxa = final.loc[
    final["USDA_accepted_symbol"].isin(
        bad_accepted_symbols
    )
].copy()

print()
print("=" * 78)
print("OBSOLETE / INVALID ACCEPTED SYMBOLS")
print("=" * 78)

print(
    f"Rows carrying obsolete accepted symbols: "
    f"{len(bad_taxa):,}"
)

if len(bad_taxa):
    display(bad_taxa)

assert len(bad_taxa) == 0


# ============================================================
# 9. PLANT FG COMPLETENESS
# ============================================================

plants = final.loc[
    final["code_class"].eq("Plant")
].copy()

missing_fg = plants.loc[
    plants["MOSAIC_FG"].isna()
].copy()

print()
print("=" * 78)
print("PLANT FUNCTIONAL-GROUP COVERAGE")
print("=" * 78)

print(f"Plant codes:              {len(plants):,}")
print(
    f"Plant records:            "
    f"{plants['n_records'].sum():,}"
)

print(
    f"Plant codes missing FG:   "
    f"{len(missing_fg):,}"
)

print(
    f"Plant records missing FG: "
    f"{missing_fg['n_records'].sum():,}"
)


# ============================================================
# 10. ROW-LEVEL CONTEXT FLAGS
# ============================================================

if "requires_row_level_resolution" in final.columns:

    context_rows = final.loc[
        final[
            "requires_row_level_resolution"
        ].fillna(False)
    ].copy()

    print()
    print("=" * 78)
    print("ROW-LEVEL CONTEXT-DEPENDENT CODES")
    print("=" * 78)

    print(
        f"Context-dependent codes:   "
        f"{len(context_rows):,}"
    )

    print(
        f"Represented records:        "
        f"{context_rows['n_records'].sum():,}"
    )

    display(
        context_rows[
            [
                c for c in [
                    "observed_code",
                    "n_records",
                    "resolved_label",
                    "code_class",
                    "protocol_source",
                    "context_protocol_label",
                    "context_protocol_class",
                    "context_protocol_rule",
                    "MOSAIC_FG",
                ]
                if c in context_rows.columns
            ]
        ]
        .sort_values(
            "n_records",
            ascending=False
        )
    )


# ============================================================
# 11. HARD FINAL GATE
# ============================================================

checks = {
    "10,960 dictionary rows":
        len(final) == 10960,

    "10,960 unique observed codes":
        final["observed_code"].nunique(
            dropna=False
        ) == 10960,

    "No duplicate observed codes":
        len(duplicate_codes) == 0,

    "All raw codes represented":
        len(missing_from_final) == 0,

    "No unexpected codes":
        len(extra_in_final) == 0,

    "Exact record accounting":
        np.isclose(
            raw_records,
            final_records
        ),

    "One __NO_CANOPY__":
        final["observed_code"]
        .eq("__NO_CANOPY__")
        .sum() == 1,

    "One literal NONE":
        final["observed_code"]
        .eq("NONE")
        .sum() == 1,

    "POAR2R2 resolves to PONIN":
        (
            len(poar) == 1
            and
            poar.iloc[0][
                "USDA_accepted_symbol"
            ] == "PONIN"
        ),

    "No POAR22 accepted symbol remains":
        len(bad_taxa) == 0,

    "All plant codes have MOSAIC_FG":
        len(missing_fg) == 0,
}


print()
print("=" * 78)
print("FINAL GATE")
print("=" * 78)

all_pass = True

for name, passed in checks.items():

    status = (
        "PASS"
        if passed
        else "FAIL"
    )

    print(
        f"{status:<5}  {name}"
    )

    if not passed:
        all_pass = False


# ============================================================
# 12. WRITE ONLY IF EVERYTHING PASSES
# ============================================================

if not all_pass:

    raise RuntimeError(
        "Final dictionary failed one or more hard QA gates. "
        "Nothing was written."
    )


final.to_csv(
    FINAL_MASTER_FILE,
    index=False
)

print()
print("=" * 78)
print("FINAL MASTER WRITTEN")
print("=" * 78)

print(FINAL_MASTER_FILE)

==============================================================================
FINAL DICTIONARY STRUCTURE
==============================================================================
Raw code rows:             10,960
Final dictionary rows:     10,960
Raw canonical codes:      10,960
Final unique codes:       10,960
Duplicate final codes:     0

==============================================================================
CODE-UNIVERSE ACCOUNTING
==============================================================================
Raw codes absent from final: 0
Unexpected final codes:      0

==============================================================================
RECORD ACCOUNTING
==============================================================================
Raw records:       16,150,101
Final records:     16,150,101
Difference:        0

==============================================================================
NONE / __NO_CANOPY__
==============================================================================

,observed_code,source_code_was_blank,n_records,n_top,n_lower,resolved_label,code_class,USDA_accepted_symbol,USDA_scientific_name,MOSAIC_FG,resolution_source,FG_resolution_source
15,__NO_CANOPY__,True,442612,442612,0,No top-canopy contact,NoCanopy,<NA>,<NA>,NaN,source_blank_sentinel,<NA>
2527,NONE,False,398,394,4,Notholaena neglecta Maxon,Plant,NONE,Notholaena neglecta Maxon,TraitUnresolvedPlant,USDA_accepted_symbol,USDA_taxon_missing_traits

==============================================================================
POAR2R2
==============================================================================
Rows: 1

,observed_code,n_records,resolved_label,code_class,USDA_accepted_symbol,USDA_match_method,USDA_scientific_name,USDA_common_name,USDA_family,USDA_duration,USDA_growth_habit,USDA_native_status_L48,MOSAIC_FG,resolution_source,FG_resolution_source
10143,POAR2R2,10,Potentilla gracilis,Plant,POAR22,manual_alias,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,TraitUnresolvedPlant,manual_typo_correction,USDA_taxon_missing_traits

AssertionError: POAR2R2 has not been corrected to accepted USDA symbol PONIN.

In [ ]:
from pathlib import Path
import pandas as pd

LPI_GEOREF_CSV = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\LDC_LPI_georeferenced_2018_present.csv"
)

print("Loading georeferenced LPI table...")
lpi_georeferenced = pd.read_csv(
    LPI_GEOREF_CSV,
    low_memory=False
)

print(f"Rows: {len(lpi_georeferenced):,}")
print(f"Columns: {len(lpi_georeferenced.columns):,}")
print(f"Plot visits: {lpi_georeferenced['PrimaryKey'].nunique():,}")

Loading georeferenced LPI table...
Rows: 16,150,114
Columns: 33
Plot visits: 51,812

In [ ]:
from pathlib import Path
import pandas as pd

LPI_GEOREF_CSV = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\LDC_LPI_georeferenced_2018_present.csv"
)

OUT_CSV = Path(
    r"C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\LDC_LPI_plot_visits_2018_present.csv"
)

print("Loading georeferenced LPI table...")

lpi = pd.read_csv(
    LPI_GEOREF_CSV,
    low_memory=False
)

# ------------------------------------------------------------
# Keep one row per PrimaryKey
#
# PrimaryKey = plot visit / sampling event
# Temporal revisits at the same physical location remain distinct
# because they have distinct PrimaryKeys.
# ------------------------------------------------------------

keep_cols = [
    "PrimaryKey",
    "DBKey",
    "ProjectKey",
    "DateVisited",
    "Latitude_NAD83",
    "Longitude_NAD83",
]

keep_cols = [
    c for c in keep_cols
    if c in lpi.columns
]

plot_visits = (
    lpi[keep_cols]
    .dropna(
        subset=[
            "PrimaryKey",
            "Latitude_NAD83",
            "Longitude_NAD83",
        ]
    )
    .copy()
)

# ------------------------------------------------------------
# Derive visit year
# ------------------------------------------------------------

if "DateVisited" in plot_visits.columns:

    plot_visits["DateVisited"] = pd.to_datetime(
        plot_visits["DateVisited"],
        errors="coerce"
    )

    plot_visits["Year"] = (
        plot_visits["DateVisited"]
        .dt.year
        .astype("Int64")
    )

# ------------------------------------------------------------
# Collapse repeated tall LPI rows ONLY within the same PrimaryKey
#
# The tall LPI table contains many contact records per visit.
# We are reducing those repeated rows to one visit-level center.
# We are NOT collapsing across different PrimaryKeys.
# ------------------------------------------------------------

visit_coord_counts = (
    plot_visits
    .groupby("PrimaryKey")[
        ["Latitude_NAD83", "Longitude_NAD83"]
    ]
    .nunique(dropna=False)
)

ambiguous = visit_coord_counts.loc[
    (visit_coord_counts["Latitude_NAD83"] > 1)
    |
    (visit_coord_counts["Longitude_NAD83"] > 1)
]

print(
    f"PrimaryKeys with multiple coordinate values: "
    f"{len(ambiguous):,}"
)

if len(ambiguous):
    display(
        plot_visits.loc[
            plot_visits["PrimaryKey"].isin(
                ambiguous.index
            )
        ]
        .sort_values(
            ["PrimaryKey", "DateVisited"]
        )
        .head(100)
    )

# ------------------------------------------------------------
# One row per visit
#
# Safe because we collapse ONLY repeated rows carrying the same
# PrimaryKey from the tall LPI table.
# ------------------------------------------------------------

if len(ambiguous) == 0:

    plot_visits = (
        plot_visits
        .drop_duplicates(
            subset=["PrimaryKey"],
            keep="first"
        )
        .reset_index(drop=True)
    )

else:

    raise ValueError(
        "Some PrimaryKeys contain multiple coordinate values. "
        "Resolve those before creating the GEE upload table."
    )

# ------------------------------------------------------------
# QA
# ------------------------------------------------------------

print()
print(
    f"Visit-level rows: "
    f"{len(plot_visits):,}"
)

print(
    f"Unique PrimaryKeys: "
    f"{plot_visits['PrimaryKey'].nunique():,}"
)

if "Year" in plot_visits.columns:

    print("\nVisits by year:")

    print(
        plot_visits["Year"]
        .value_counts()
        .sort_index()
    )

# ------------------------------------------------------------
# Save for GEE upload
# ------------------------------------------------------------

plot_visits.to_csv(
    OUT_CSV,
    index=False
)

print()
print(
    f"Written:\n{OUT_CSV}"
)

display(
    plot_visits.head()
)

Loading georeferenced LPI table...
PrimaryKeys with multiple coordinate values: 0

Visit-level rows: 51,812
Unique PrimaryKeys: 51,812

Visits by year:
Year
2018    7313
2019    9039
2020    7345
2021    8597
2022    9331
2023    8490
2024    1689
2025       8
Name: count, dtype: Int64

Written:
C:\NCA_DATA\Vegetation Data\LDC_LPI_2018_present\LDC_LPI_plot_visits_2018_present.csv

                   PrimaryKey               DateVisited  Latitude_NAD83  Longitude_NAD83  Year
0   2105280935464382021-05-28 2021-05-28 00:00:00+00:00         41.5294         -116.978  2021
1   2105290848197392021-05-29 2021-05-29 00:00:00+00:00         41.5369         -116.975  2021
2  21052913471776492021-05-29 2021-05-29 00:00:00+00:00         41.5416         -116.966  2021
3  21053011203293392021-05-30 2021-05-30 00:00:00+00:00         41.5931         -117.371  2021
4  21053109290646562021-05-31 2021-05-31 00:00:00+00:00         41.5772         -117.382  2021